### ISSUE TITLE
Cannot build with MSVC++ 6.0 without PERL_MALLOC

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#60]
Migrated from [rt.perl.org#861](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=861) (status was 'resolved')

Searchable as RT861$

**Comment by p5pRT** [comment]
### From aichner@ecf.teradyne.com


\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Running nmake in
p500557/win32
results in following link error&#8203;:
&nbsp;    link\.exe \-dll \-def&#8203;:perldll\.def \-out&#8203;:\.\.\\perl\.dll @&#8203;C&#8203;:\\TEMP\\nmb00081\.
perldll\.def : error LNK2001&#8203;: unresolved external symbol Perl\_dump\_mstats
perldll\.def : error LNK2001&#8203;: unresolved external symbol Perl\_dump\_mstats
\.\.\\perl\.lib : fatal error LNK1120&#8203;: 2 unresolved externals
LINK : fatal error LNK1141&#8203;: failure during build of exports file
NMAKE : fatal error U1077&#8203;: 'link\.exe' : return code '0x475'
Stop\.

Workaround&#8203;:
To make perl\.dll link under MSVC\+\+ 6\.0 on NT4sp3 win32/Makefile needs
following change&#8203;:

<details><summary>Inline Patch</summary>

```diff
diff -u c:\TEMP\p500557\win32\Makefile.orig c:\TEMP\p500557\win32\Makefile
--- c:\TEMP\p500557\win32\Makefile.orig	Sat Jun 12 20:04:40 1999
+++ c:\TEMP\p500557\win32\Makefile	Sat Jun 12 20:04:40 1999
@@ -105,7 +105,7 @@
 # extensions if you change the default.  Currently, this cannot be enabled
 # if you ask for PERL_OBJECT above.
 #
-#PERL_MALLOC	= define
+PERL_MALLOC	= define
 
 #
 # set the install locations of the compiler include/libraries
```
</details>


<details><summary>Perl Info</summary>

```


Site configuration information for perl 5.00557:

Summary of my perl5 (revision 5.0 version 5 subversion 57) configuration:
  Platform:
    osname=MSWin32, osvers=4.0, archname=MSWin32-x86
    uname=''
    config_args='undef'
    hint=recommended, useposix=true, d_sigaction=undef
    usethreads=undef useperlio=undef d_sfio=undef
    use64bits=undef usemultiplicity=undef
  Compiler:
    cc='cl.exe', optimize='-Od -MD -DNDEBUG', gccversion=
    cppflags='-DWIN32'
    ccflags ='-Od -MD -DNDEBUG -DWIN32 -D_CONSOLE -DNO_STRICT   '
    stdchar='char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=undef, longlongsize=8, d_longdbl=define, longdblsize=10
    alignbytes=8, usemymalloc=y, prototype=define
  Linker and Libraries:
    ld='link', ldflags ='-nologo -nodefaultlib -release -machine:x86'
    libpth=\lib
    libs= oldnames.lib kernel32.lib user32.lib gdi32.lib  winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib  oleaut32.lib netapi32.lib uuid.lib wsock32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib msvcrt.lib
    libc=msvcrt.lib, so=dll, useshrplib=yes, libperl=perl.lib
  Dynamic Linking:
    dlsrc=dl_win32.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags='-dll -nologo -nodefaultlib -release -machine:x86'

Locally applied patches:
    


@INC for perl 5.00557:
    d:\Users\AichnerAd\pl
    c:/perl/5.00557/lib/MSWin32-x86
    c:/perl/5.00557/lib
    c:/perl/site/5.00557/lib/MSWin32-x86
    c:/perl/site/5.00557/lib
    .


Environment for perl 5.00557:
    HOME=d:\Users\AichnerAd
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=c:\perl\5.00557\bin;c:\perl\5.00557\bin\MSWin32-x86;C:\WINNT\system32;C:\WINNT;e:\PROGRA~1\Teradyne\IG-XL\bin;E:\Program Files\Microsoft Visual Studio\Common\Tools\WinNT;E:\Program Files\Microsoft Visual Studio\Common\MSDev98\Bin;E:\Program Files\Microsoft Visual Studio\Common\Tools;E:\Program Files\Microsoft Visual Studio\VC98\bin;E:\Program Files\Microsoft Visual Studio\VB98;e:\cvs;e:\whois;e:\cygnus\cygwin-b20\H-i586-cygwin32\bin;E:\NTRESKIT;e:\enscript;d:\export\home\tmp\texinfo-3.12\makeinfo;d:\sandbox;e:\gstools\gsview;e:\gstools\gs5.10;e:\mks\mksnt;e:\mks\mkssi
    PERL5LIB=d:\Users\AichnerAd\pl
    PERL_BADLANG (unset)
    SHELL (unset)


```
</details>
