### ISSUE TITLE
BBC: Blead breaks DYACOB/Convert-Number-Roman-0.01.tar.gz

### ISSUE THREAD

**Issue by andk** [Perl/perl5#19554]
**Description**

Test diagnostics:

``` text
Use of unassigned code point or non-standalone grapheme for a delimiter is not allowed at ../lib/Convert/Number/Roman.pm line 106, near ""
Use of unassigned code point or non-standalone grapheme for a delimiter is not allowed at ../lib/Convert/Number/Roman.pm line 162, near "=~ "
Compilation failed in require at t/numbers.t line 23.
BEGIN failed--compilation aborted at t/numbers.t line 23.
t/numbers.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 96/96 subtests 
```

Bisect leads to:
``` text
32b87797e986f5d99836e16ea6b9d9ff5a56d3be is the first bad commit
commit 32b87797e986f5d99836e16ea6b9d9ff5a56d3be
Author: Karl Williamson <khw@cpan.org>
Date:   Sat Feb 12 21:47:13 2022 -0700

    toke.c: merge loops, multi-byte delim
```

**Steps to Reproduce**

cpan -i DYACOB/Convert-Number-Roman-0.01.tar.gz

**Expected behavior**

The module should test successfully and be installed

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 35 subversion 10) configuration:
  Commit id: 32b87797e986f5d99836e16ea6b9d9ff5a56d3be
  Platform:
    osname=linux
    osvers=5.16.0-5-amd64
    archname=x86_64-linux
    uname='linux k93msid 5.16.0-5-amd64 #1 smp preempt debian 5.16.14-1 (2022-03-15) x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.9-157-g32b87797e9/da1c -Dmyhostname=k93msid -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Uuseithreads -Uuselongdouble -DEBUGGING=-g'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2 -g'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.2.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.33.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.33'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Mar 22 2022 03:23:29
  @INC:
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.9-157-g32b87797e9/da1c/lib/site_perl/5.35.10/x86_64-linux
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.9-157-g32b87797e9/da1c/lib/site_perl/5.35.10
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.9-157-g32b87797e9/da1c/lib/5.35.10/x86_64-linux
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.9-157-g32b87797e9/da1c/lib/5.35.10

```

**Comment by jkeenan** [comment]
> Test diagnostics:
> 
> ```
> Use of unassigned code point or non-standalone grapheme for a delimiter is not allowed at ../lib/Convert/Number/Roman.pm line 106, near ""
> Use of unassigned code point or non-standalone grapheme for a delimiter is not allowed at ../lib/Convert/Number/Roman.pm line 162, near "=~ "
> Compilation failed in require at t/numbers.t line 23.
> BEGIN failed--compilation aborted at t/numbers.t line 23.
> t/numbers.t .. 
> Dubious, test returned 255 (wstat 65280, 0xff00)
> Failed 96/96 subtests 
> ```
> 
> Bisect leads to:
> 
> ```
> 32b87797e986f5d99836e16ea6b9d9ff5a56d3be is the first bad commit
> commit 32b87797e986f5d99836e16ea6b9d9ff5a56d3be
> Author: Karl Williamson <khw@cpan.org>
> Date:   Sat Feb 12 21:47:13 2022 -0700
> 
>     toke.c: merge loops, multi-byte delim
> ```
> 
> **Steps to Reproduce**
> 
> cpan -i DYACOB/Convert-Number-Roman-0.01.tar.gz
> 
> **Expected behavior**
> 
> The module should test successfully and be installed
> 

```
commit 32b87797e986f5d99836e16ea6b9d9ff5a56d3be
Author:     Karl Williamson <khw@cpan.org>
AuthorDate: Sat Feb 12 21:47:13 2022 -0700
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Sat Mar 19 23:17:51 2022 -0600

    toke.c: merge loops, multi-byte delim
```
@khwilliamson, can you take a look?

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment]
I'm unsure as to the best fix.  This worked only coincidentally in the past, but the use case is valid.  What the code is doing is trying to change one combining mark into another
s/mark1/mark2/
The problem is that those marks try to combine with the slashes, as Unicode says they should.  If you look at it with gvim, the slashes get the marks superimposed on top of them, and are considered one character.

The reason it worked before is that there were two loops doing essentially the same thing, but not quite.  A maze of twisty little passages vs a twisty maze of little passages.  One of the loops treated ASCII delimiters specially.  This commit combined the loops, and in so doing removed that special treatment.

I see two potential ways forward.

1) Restore the special treatment for ASCII delimiters.  That would mean non-ASCII ones would continue to not work.  No one has complained about this

2) Change things so that a delimiter need not be a stand-alone grapheme without following marks (the modern Unicode term for these is 'Extenders')  This was how things worked until a few releases ago.  The requirement would remain that it couldn't be such an extender.  That would mean that something like q'string'extender would parse so that the extender is separate, but wanting to combine with the final apostrophe.

**Comment by hvds** [comment]
> I'm unsure as to the best fix. This worked only coincidentally in the past, but the use case is valid. What the code is doing is trying to change one combining mark into another s/mark1/mark2/ The problem is that those marks try to combine with the slashes, as Unicode says they should. If you look at it with gvim, the slashes get the marks superimposed on top of them, and are considered one character.

You can also see it in metacpan's view source interface: https://metacpan.org/dist/Convert-Number-Roman/source/lib/Convert/Number/Roman.pm

If I correctly understand this, then for me the crux of it is "those marks try to combine with the slashes, as Unicode says they should" (and we're in the scope of `use utf8`). On those grounds, my instinct is that the module code should change to something that expresses mark1 and mark2 in isolation other than by including them literally - I assume there is a way to do that by means of `\N{...}` or the like.

I think the alternative would have to be that we would never treat combining marks as combining in perl source: I think it would be a really bad idea to have them treated exceptionally in specific cases driven by bug reports.

> I see two potential ways forward.
> 
> 1. Restore the special treatment for ASCII delimiters.  That would mean non-ASCII ones would continue to not work.  No one has complained about this
> 
> 2. Change things so that a delimiter need not be a stand-alone grapheme without following marks (the modern Unicode term for these is 'Extenders')  This was how things worked until a few releases ago.  The requirement would remain that it couldn't be such an extender.  That would mean that something like q'string'extender would parse so that the extender is separate, but wanting to combine with the final apostrophe.

It seems wrong to me to restore the special treatment, regardless whether we support non-ASCII delimiters. I have no opinion about option 2 (and not sure I understand it), but if the module's code changes then presumably it doesn't force our hand.

**Comment by rjbs** [comment]
I agree with @hvds .  This code is egregious.  Returning to the old behavior *for a short time* and deprecating this is the largest concession I would suggest.

**Comment by rjbs** [comment]
@khwilliamson Almost two weeks later, my feeling here is that the library is doing something ill-advised, even if it's not totally absurd.  The library should be fixed and we should document this kind of problem in the delta.

Your thoughts?

**Comment by khwilliamson** [comment]
https://github.com/Perl/perl5/pull/19579 changes things back so that this should pass.  I'm thinking it might be a good idea to put this in, as you earlier said, temporarily for 5.36.0.

**Comment by demerphq** [comment]
On Sun, 3 Apr 2022 at 00:40, Karl Williamson ***@***.***>
wrote:

> #19579 <https://github.com/Perl/perl5/pull/19579> changes things back so
> that this should pass. I'm thinking it might be a good idea to put this in,
> as you earlier said, temporarily for 5.36.0.
>
>
> Wouldn't the natural fix for the original module simply be to use an
\x{...} to represent the marks it wants to replace? Then the parser won't
get confused.  It seems to me that you fixed a bug that they were depending
on, and they should change their code.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by khwilliamson** [comment]
On 4/5/22 23:11, Yves Orton wrote:
> On Sun, 3 Apr 2022 at 00:40, Karl Williamson ***@***.***>
> wrote:
> 
>  > #19579 <https://github.com/Perl/perl5/pull/19579> changes things back so
>  > that this should pass. I'm thinking it might be a good idea to put 
> this in,
>  > as you earlier said, temporarily for 5.36.0.
>  >
>  >
>  > Wouldn't the natural fix for the original module simply be to use an
> \x{...} to represent the marks it wants to replace? Then the parser won't
> get confused. It seems to me that you fixed a bug that they were depending
> on, and they should change their code.

Yes it would.

The maintainer hasn't responded to an email from me in a couple weeks 
asking how to contribute; there is no repository for that distribution 
to contribute to.
This would be considered a temporary patch to get 5.36 out the door 
without breaking a distro.

It comes down to how much we care about breaking this module now.  We 
might have to take it over on cpan to fix it.  The patch is an 
alternative for the time being.

**Comment by demerphq** [comment]
On Wed, 6 Apr 2022 at 17:15, Karl Williamson ***@***.***>
wrote:

> On 4/5/22 23:11, Yves Orton wrote:
> > On Sun, 3 Apr 2022 at 00:40, Karl Williamson ***@***.***>
> > wrote:
> >
> > > #19579 <https://github.com/Perl/perl5/pull/19579> changes things back
> so
> > > that this should pass. I'm thinking it might be a good idea to put
> > this in,
> > > as you earlier said, temporarily for 5.36.0.
> > >
> > >
> > > Wouldn't the natural fix for the original module simply be to use an
> > \x{...} to represent the marks it wants to replace? Then the parser won't
> > get confused. It seems to me that you fixed a bug that they were
> depending
> > on, and they should change their code.
>
> Yes it would.
>
> The maintainer hasn't responded to an email from me in a couple weeks
> asking how to contribute; there is no repository for that distribution
> to contribute to.
> This would be considered a temporary patch to get 5.36 out the door
> without breaking a distro.
>
> It comes down to how much we care about breaking this module now. We
> might have to take it over on cpan to fix it. The patch is an
> alternative for the time being.


 FWIW, I definitely dont think this issue should be a blocker for us. I
vote that we keep your patch and not worry about breaking this module. Lets
just file a patch that fixes it and move on.

cheers,
Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by rjbs** [comment]
I agree with Yves.

**Comment by rjbs** [comment]
I have filed https://rt.cpan.org/Ticket/Display.html?id=142295

**Comment by tonycoz** [comment]
If I understand correctly, this is now considered a problem in Convert-Number-Roman, making this closable.

Are there any dissents?

**Comment by jkeenan** [comment]
> If I understand correctly, this is now considered a problem in Convert-Number-Roman, making this closable.
> 
> Are there any dissents?

No dissent.  The author was provided with an analysis of the problem during the last production cycle and has not responded in more than a year.  So +1 to closing.
