### ISSUE TITLE
9fdd7fc479 breaks build using g++ as compiler

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#20108]
A recent commit to blead has broken the build when using `g++` as the C-compiler.

I first noticed this breakage in recent smoke-test reports such as [this one](http://perl.develop-help.com/raw/?id=284029).

Bisecting with this invocation:
```
perl Porting/bisect.pl \
-Dcc=g++ \
--test-build \
--start cf1717027b95225cb27f33b15b84ff798c8bacaf \
--end 40666a761f261de4ec02a7fd4e770a48957df7c7
```
... points to this commit:
```
9fdd7fc4796d89d16dceea42f2af91e4fde296ed is the first bad commit
commit 9fdd7fc4796d89d16dceea42f2af91e4fde296ed
Author: Richard Leach <richardleach@users.noreply.github.com>
Date:   Fri Jul 8 14:52:19 2022 +0000
Commit:     Richard Leach <rich+perl@hyphen-dash-hyphen.info>
CommitDate: Wed Aug 17 11:19:10 2022 +0100

 
    Implement OP_PADSV_STORE - combined sassign/padsv OP

    This commit introduces a new OP to replace simple cases
    of OP_SASSIGN and OP_PADSV.
```
@richardleach, can you take a look?

@neilb, can you keep an eye on this, as it will affect the monthly dev release scheduled for Saturday Aug 20?  Thanks.

**Comment by jkeenan** [comment]
Compilation on FreeBSD-12 using g++ version 10.3.0 ends here:
```
g++ -c -DPERL_CORE -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_FORTIFY_SOURCE=2 -O2 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wwrite-strings peep.c
peep.c: In function 'void Perl_rpeep(OP*)':
peep.c:3897:14: error: jump to case label
 3897 |         case OP_AASSIGN: {
      |              ^~~~~~~~~~
peep.c:3844:17: note:   crosses initialization of 'OP* lval'
 3844 |             OP* lval = cBINOPx(o)->op_last;
      |                 ^~~~
peep.c:3843:17: note:   crosses initialization of 'OP* rhs'
 3843 |             OP* rhs = cBINOPx(o)->op_first;
      |                 ^~~
peep.c:4004:14: error: jump to case label
 4004 |         case OP_REF:
      |              ^~~~~~
peep.c:3844:17: note:   crosses initialization of 'OP* lval'
 3844 |             OP* lval = cBINOPx(o)->op_last;
      |                 ^~~~
peep.c:3843:17: note:   crosses initialization of 'OP* rhs'
 3843 |             OP* rhs = cBINOPx(o)->op_first;
      |                 ^~~
peep.c:4005:14: error: jump to case label
 4005 |         case OP_BLESSED:
      |              ^~~~~~~~~~
peep.c:3844:17: note:   crosses initialization of 'OP* lval'
 3844 |             OP* lval = cBINOPx(o)->op_last;
      |                 ^~~~
peep.c:3843:17: note:   crosses initialization of 'OP* rhs'
 3843 |             OP* rhs = cBINOPx(o)->op_first;
      |                 ^~~
peep.c:4013:14: error: jump to case label
 4013 |         case OP_LENGTH:
      |              ^~~~~~~~~
peep.c:3844:17: note:   crosses initialization of 'OP* lval'
 3844 |             OP* lval = cBINOPx(o)->op_last;
      |                 ^~~~
peep.c:3843:17: note:   crosses initialization of 'OP* rhs'
 3843 |             OP* rhs = cBINOPx(o)->op_first;
      |                 ^~~
peep.c:4022:14: error: jump to case label
 4022 |         case OP_POS:
      |              ^~~~~~
peep.c:3844:17: note:   crosses initialization of 'OP* lval'
 3844 |             OP* lval = cBINOPx(o)->op_last;
      |                 ^~~~
peep.c:3843:17: note:   crosses initialization of 'OP* rhs'
 3843 |             OP* rhs = cBINOPx(o)->op_first;
      |                 ^~~
peep.c:4028:14: error: jump to case label
 4028 |         case OP_CUSTOM: {
      |              ^~~~~~~~~
peep.c:3844:17: note:   crosses initialization of 'OP* lval'
 3844 |             OP* lval = cBINOPx(o)->op_last;
      |                 ^~~~
peep.c:3843:17: note:   crosses initialization of 'OP* rhs'
 3843 |             OP* rhs = cBINOPx(o)->op_first;
      |                 ^~~
*** Error code 1

Stop.
make: stopped in /usr/home/jkeenan/gitwork/perl
```

**Comment by jkeenan** [comment]
And, no surprise, clang++ builds are breaking as well.  [Here's](https://perl5.test-smoke.org/report/5021664) one on OpenBSD.

**Comment by jkeenan** [comment]
> A recent commit to blead has broken the build when using `g++` as the C-compiler.
> 
> I first noticed this breakage in recent smoke-test reports such as [this one](http://perl.develop-help.com/raw/?id=284029).
> 
Correction for copy/paste error noted by Bram:
http://perl.develop-help.com/raw/?id=284149

**Comment by jkeenan** [comment]
Repair confirmed with a build on FreeBSD with this invocation:
```
$ sh ./Configure -des -Dusedevel -Duseithreads -Dcc=g++ && make test_harness
```
