### ISSUE TITLE
BBC: Blead Breaks DBIx::Class

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#22511]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.43 running under perl 5.41.3.

-----------------------------------------------------------------

BBC: Blead Breaks DBIx::Class

Please see http://fast-matrix.cpantesters.org/?dist=DBIx::Class%200.082843

---
**Flags**
- category=core
- severity=low
---
**Perl configuration**
```
Site configuration information for perl 5.41.3:

Configured by cpan at Wed Aug 14 17:29:36 EDT 2024.

Summary of my perl5 (revision 5 version 41 subversion 3) configuration:
  Commit id: c2cb8f95a03c311972b110fc1fb6029c46446cad
  Platform:
    osname=linux
    osvers=5.14.0-427.28.1.el9_4.x86_64
    archname=x86_64-linux
    uname='linux cjg-rhel9 5.14.0-427.28.1.el9_4.x86_64 #1 smp preempt_dynamic fri jul 19 14:40:47 edt 2024 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Dprefix=/home/cpan/bin/perl -Dscriptdir=/home/cpan/bin/perl/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.4.1 20231218 (Red Hat 11.4.1-3)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /usr/lib64 /usr/local/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.34'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


---
@INC for perl 5.41.3:
    /home/cpan/bin/perl/lib/site_perl/5.41.3/x86_64-linux
    /home/cpan/bin/perl/lib/site_perl/5.41.3
    /home/cpan/bin/perl/lib/5.41.3/x86_64-linux
    /home/cpan/bin/perl/lib/5.41.3

---
Environment for perl 5.41.3:
    HOME=/home/cpan
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl/bin:/home/cpan/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash
```

**Comment by jkeenan** [comment]
[Example of failure output](http://www.cpantesters.org/cpan/report/fdbe9830-5a8e-11ef-bda5-922fe37de8b6):
```
t/88result_set_column.t ............................. ok

#   Failed test 'Errors from RS components reported right'
#   at t/90ensure_class_loaded.t line 126.
#                   '{UNKNOWN}: Can't find string terminator "'" anywhere before EOF at t/lib/DBICTest/SyntaxErrorComponent3.pm line 6, <> line 1.
# Compilation failed in require at /home/cpan/bin/perl/lib/site_perl/5.41.3/Class/C3/Componentised.pm line 146, <> line 1. at /home/cpan/bin/perl/lib/site_perl/5.41.3/Class/C3/Componentised.pm line 151
# '
#     doesn't match '(?^:syntax\ error\ at\ t\/lib\/DBICTest\/SyntaxErrorComponent3\.pm)'
# Looks like you failed 1 test of 28.
t/90ensure_class_loaded.t ........................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/28 subtests
```
Bisection with this invocation:
```
perl Porting/bisect.pl \
--start=2c387e63aed4fdb32777f74fdbac6ec6a8e6683b \
--end=df0dd34cc72f566dbf32f671128e0744211cae4d \
--module=DBIx::Class
```
... pointed (not surprisingly) to commit ce1383eae4:
```
ce1383eae4cd16b18ff9df6cecb54582e0c689ab is the first bad commit
commit ce1383eae4cd16b18ff9df6cecb54582e0c689ab
Author: Tony Cook <tony@develop-help.com>
Date:   Wed Jun 19 15:33:01 2024 +1000
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Mon Aug 12 10:13:37 2024 +1000

    remove use of ' as a package separator
```
@tonycoz, could you take a look?  Thanks.

**Comment by tonycoz** [comment]
The removal of `'` in names changed the error reported, and the test checks the error message.

**Comment by jkeenan** [comment]
With b59f4307bc, [DBIx-Class 0.082843](http://fast-matrix.cpantesters.org/?dist=DBIx-Class%200.082843;perl=5.41.6;reports=1) once again PASSes on CPANtesters.
```
b59f4307bc0c99283f004c584fcf4e1c33f69da3 is the first bad commit
commit b59f4307bc0c99283f004c584fcf4e1c33f69da3
Author: Tony Cook <tony@develop-help.com>
Date:   Tue Oct 8 15:06:17 2024 +1100
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Mon Nov 11 10:39:40 2024 +1100

    Revert "remove use of ' as a package separator"
    
    This reverts commit ce1383eae4cd16b18ff9df6cecb54582e0c689ab.
```
