### ISSUE TITLE
CowREFCNT macro is returning an incorrect value for hash keys

### ISSUE THREAD

**Issue by atoomic** [Perl/perl5#17745]
As seen from https://github.com/atoomic/B-COW/issues/1

When using `CowREFCNT` on a hash key, it's returning 0 on most systems but as we could notice it on bigendian it's returning the string length.. an not 0.

the macro `CowREFCNT` should not try to read before the pv when `SvLEN=0`
```c
sv.h:1978:#   define CowREFCNT(sv)      (*(U8 *)(SvPVX(sv)+SvLEN(sv)-1))
```

We should add a protection with something like this
```c
#define CowREFCNT(sv)   ((SvLEN(sv)>0) ? (*(U8 *)(SvPVX(sv)+SvLEN(sv)-1)) : 0)
```

**Comment by atoomic** [comment]
this was introduced by db2c6cb33ec067c880a2cb3c4efdb33f7e3e3d0f during the 5.18 dev cycle

**Comment by atoomic** [comment]
The problem with such a patch is that we cannot assign a value using such an alias...
this still needs some work
```
op.c:15168:16: error: expression is not assignable
        CowREFCNT(sv) = 0;
        ~~~~~~~~~~~~~ ^
```

**Comment by atoomic** [comment]
probably something like this
```c
#define CowREFCNT(sv)   (*(U8 *)(SvPVX(sv)+ ( LIKELY((SvLEN(sv)-1) > 0) ? (SvLEN(sv)-1) : 0 ) ) )

#define CowREFCNT(sv)   (*(U8 *)(SvPVX(sv)+MAX(SvLEN(sv)-1,0)))
```

**Comment by atoomic** [comment]
5cfc284 is not fixing the issue on big-endian platforms

**Comment by iabyn** [comment]
On Thu, Apr 23, 2020 at 12:55:05PM -0700, Nicolas R. wrote:
> As seen from https://github.com/atoomic/B-COW/issues/1
> 
> When using `CowREFCNT` on a hash key, it's returning 0 on most systems
> but as we could notice it on bigendian it's returning the string
> length.. an not 0.

It's not clear to me what you mean by "a hash key".

> We should add a protection with something like this
> ```c
> #define CowREFCNT(sv)   ((SvLEN(sv)>0) ? CowREFCNT(sv) : (*(U8 *)(SvPVX(sv)+SvLEN(sv)-1)))

Well if possible we should avoid adding extra overhead to a hot macro.

-- 
Any [programming] language that doesn't occasionally surprise the
novice will pay for it by continually surprising the expert.
   -- Larry Wall

**Comment by tonycoz** [comment]
CowREFCNT() isn't documented, so it's hard to tell what the preconditions for its use are.

The code in core that looks at CowREFCNT() for existing COW SVs all check that either SvLEN() is non-zero or thet SvCUR()-1 < SvLEN(), for example in sv_clear(), sv_uncow(), do_sv_dump().

Given that I don't think this is a bug in the definition of CowREFCNT(), if it's meant to be used outside of core (or even if it isn't) the pre-condition on SvLEN() should probably be documented.
