### ISSUE TITLE
bleadperl v5.15.3-129-g7049214 breaks ZEFRAM/Devel-Declare-0.006007.tar.gz

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#11688]
Migrated from [rt.perl.org#100930](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=100930) (status was 'resolved')

Searchable as RT100930$

**Comment by p5pRT** [comment]
### From @andk

git bisect


---
7049214e3eea022e77794ed9b9d9038f93695ef9 is the first bad commit
commit 7049214e3eea022e77794ed9b9d9038f93695ef9
Author&#8203;: Karl Williamson \<public@&#8203;khwilliamson\.com>

diagnostics


---
\#   Failed test 'use Devel&#8203;::Declare;'                   
\#   at t/00load\.t line 7\.                               
\#     Tried to use 'Devel&#8203;::Declare'\.                    
\#     Error&#8203;:  Can't load '/tmp/tmp\.U6WR6dDKBX/Devel\-Declare\-0\.006007\-NqmsPR/blib/arch/auto/Devel/Declare/Declare\.so' for module Devel&#8203;::Declare&#8203;: /tmp/tmp\.U6WR6dDKBX/Devel\-Declare\-0\.006007\-NqmsPR/blib/arch/auto/Devel/Declare/Declare\.so&#8203;: undefined symbol&#8203;: \_is\_utf8\_\_perl\_idstart at /home/src/perl/repoperls/installed\-perls/perl/v5\.15\.3\-305\-gc59e8fd/2b65/lib/5\.15\.3/x86\_64\-linux\-ld/DynaLoader\.pm line 190\.                                                       
\#  at \(eval 4\) line 2                                   
\# Compilation failed in require at \(eval 4\) line 2\.     
\# BEGIN failed\-\-compilation aborted at \(eval 4\) line 2\. 
\# Looks like you failed 1 test of 1\.                    
t/00load\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.                        
Dubious\, test returned 1 \(wstat 256\, 0x100\)             
Failed 1/1 subtests                                     

perl \-V


---
Summary of my perl5 \(revision 5 version 15 subversion 3\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 7049214e3eea022e77794ed9b9d9038f93695ef9
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.32\-5\-amd64\, archname=x86\_64\-linux\-thread\-multi
&nbsp;    uname='linux k83 2\.6\.32\-5\-amd64 \#1 smp tue jun 14 09&#8203;:42&#8203;:28 utc 2011 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dprefix=/home/src/perl/repoperls/installed\-perls/perl/v5\.15\.3\-129\-g7049214/ba65 \-Dinstallusrbinperl=n \-Uversiononly \-Dusedevel \-des \-Ui\_db \-Duseithreads \-Uuselongdouble \-DDEBUGGING=\-g'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.4\.5'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib/\.\./lib /usr/lib/\.\./lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=/lib/libc\-2\.11\.2\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.11\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib \-fstack\-protector'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES MULTIPLICITY PERLIO\_LAYERS
&nbsp;                        PERL\_DONT\_CREATE\_GVSV PERL\_IMPLICIT\_CONTEXT
&nbsp;                        PERL\_MALLOC\_WRAP PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_ITHREADS
&nbsp;                        USE\_LARGE\_FILES USE\_LOCALE USE\_LOCALE\_COLLATE
&nbsp;                        USE\_LOCALE\_CTYPE USE\_LOCALE\_NUMERIC USE\_PERLIO
&nbsp;                        USE\_PERL\_ATOF USE\_REENTRANT\_API
&nbsp;  Built under linux
&nbsp;  Compiled at Oct  6 2011 09&#8203;:49&#8203;:28
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /home/src/perl/repoperls/installed\-perls/perl/v5\.15\.3\-129\-g7049214/ba65/lib/site\_perl/5\.15\.3/x86\_64\-linux\-thread\-multi
&nbsp;    /home/src/perl/repoperls/installed\-perls/perl/v5\.15\.3\-129\-g7049214/ba65/lib/site\_perl/5\.15\.3
&nbsp;    /home/src/perl/repoperls/installed\-perls/perl/v5\.15\.3\-129\-g7049214/ba65/lib/5\.15\.3/x86\_64\-linux\-thread\-multi
&nbsp;    /home/src/perl/repoperls/installed\-perls/perl/v5\.15\.3\-129\-g7049214/ba65/lib/5\.15\.3
&nbsp;    \.

\-\- 
andreas

**Comment by p5pRT** [comment]
### From @khwilliamson

On 10/07/2011 03&#8203;:06 PM\, \(Andreas J\. Koenig\) \(via RT\) wrote&#8203;:
> \# New Ticket Created by  \(Andreas J\. Koenig\)
> \# Please include the string&#8203;:  \[perl \#100930\]
> \# in the subject line of all future correspondence about this issue\.
> \#\<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=100930>
>
>
> git bisect
> \-\-\-\-\-\-\-\-\-\-
>
> 7049214e3eea022e77794ed9b9d9038f93695ef9 is the first bad commit
> commit 7049214e3eea022e77794ed9b9d9038f93695ef9
> Author&#8203;: Karl Williamson\<public@&#8203;khwilliamson\.com>

This is a build problem\.  Why would just this one module be unable to 
find the new symbol?

>
> diagnostics
> \-\-\-\-\-\-\-\-\-\-\-
>
> \#   Failed test 'use Devel&#8203;::Declare;'
> \#   at t/00load\.t line 7\.
> \#     Tried to use 'Devel&#8203;::Declare'\.
> \#     Error&#8203;:  Can't load '/tmp/tmp\.U6WR6dDKBX/Devel\-Declare\-0\.006007\-NqmsPR/blib/arch/auto/Devel/Declare/Declare\.so' for module Devel&#8203;::Declare&#8203;: /tmp/tmp\.U6WR6dDKBX/Devel\-Declare\-0\.006007\-NqmsPR/blib/arch/auto/Devel/Declare/Declare\.so&#8203;: undefined symbol&#8203;: \_is\_utf8\_\_perl\_idstart at /home/src/perl/repoperls/installed\-perls/perl/v5\.15\.3\-305\-gc59e8fd/2b65/lib/5\.15\.3/x86\_64\-linux\-ld/DynaLoader\.pm line 190\.
> \#  at \(eval 4\) line 2
> \# Compilation failed in require at \(eval 4\) line 2\.
> \# BEGIN failed\-\-compilation aborted at \(eval 4\) line 2\.
> \# Looks like you failed 1 test of 1\.
> t/00load\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.
> Dubious\, test returned 1 \(wstat 256\, 0x100\)
> Failed 1/1 subtests
>
> perl \-V
> \-\-\-\-\-\-\-
>
> Summary of my perl5 \(revision 5 version 15 subversion 3\) configuration&#8203;:
>    Commit id&#8203;: 7049214e3eea022e77794ed9b9d9038f93695ef9
>    Platform&#8203;:
>      osname=linux\, osvers=2\.6\.32\-5\-amd64\, archname=x86\_64\-linux\-thread\-multi
>      uname='linux k83 2\.6\.32\-5\-amd64 \#1 smp tue jun 14 09&#8203;:42&#8203;:28 utc 2011 x86\_64 gnulinux '
>      config\_args='\-Dprefix=/home/src/perl/repoperls/installed\-perls/perl/v5\.15\.3\-129\-g7049214/ba65 \-Dinstallusrbinperl=n \-Uversiononly \-Dusedevel \-des \-Ui\_db \-Duseithreads \-Uuselongdouble \-DDEBUGGING=\-g'
>      hint=recommended\, useposix=true\, d\_sigaction=define
>      useithreads=define\, usemultiplicity=define
>      useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
>      use64bitint=define\, use64bitall=define\, uselongdouble=undef
>      usemymalloc=n\, bincompat5005=undef
>    Compiler&#8203;:
>      cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
>      optimize='\-O2 \-g'\,
>      cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
>      ccversion=''\, gccversion='4\.4\.5'\, gccosandvers=''
>      intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
>      d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
>      ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
>      alignbytes=8\, prototype=define
>    Linker and Libraries&#8203;:
>      ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
>      libpth=/usr/local/lib /lib/\.\./lib /usr/lib/\.\./lib /lib /usr/lib /lib64 /usr/lib64
>      libs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
>      perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
>      libc=/lib/libc\-2\.11\.2\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
>      gnulibc\_version='2\.11\.2'
>    Dynamic Linking&#8203;:
>      dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
>      cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib \-fstack\-protector'
>
>
> Characteristics of this binary \(from libperl\)&#8203;:
>    Compile\-time options&#8203;: HAS\_TIMES MULTIPLICITY PERLIO\_LAYERS
>                          PERL\_DONT\_CREATE\_GVSV PERL\_IMPLICIT\_CONTEXT
>                          PERL\_MALLOC\_WRAP PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
>                          USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_ITHREADS
>                          USE\_LARGE\_FILES USE\_LOCALE USE\_LOCALE\_COLLATE
>                          USE\_LOCALE\_CTYPE USE\_LOCALE\_NUMERIC USE\_PERLIO
>                          USE\_PERL\_ATOF USE\_REENTRANT\_API
>    Built under linux
>    Compiled at Oct  6 2011 09&#8203;:49&#8203;:28
>    @&#8203;INC&#8203;:
>      /home/src/perl/repoperls/installed\-perls/perl/v5\.15\.3\-129\-g7049214/ba65/lib/site\_perl/5\.15\.3/x86\_64\-linux\-thread\-multi
>      /home/src/perl/repoperls/installed\-perls/perl/v5\.15\.3\-129\-g7049214/ba65/lib/site\_perl/5\.15\.3
>      /home/src/perl/repoperls/installed\-perls/perl/v5\.15\.3\-129\-g7049214/ba65/lib/5\.15\.3/x86\_64\-linux\-thread\-multi
>      /home/src/perl/repoperls/installed\-perls/perl/v5\.15\.3\-129\-g7049214/ba65/lib/5\.15\.3
>      \.
>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Fri Oct 07 15&#8203;:05&#8203;:27 2011\, public@&#8203;khwilliamson\.com wrote&#8203;:
> On 10/07/2011 03&#8203;:06 PM\, \(Andreas J\. Koenig\) \(via RT\) wrote&#8203;:
> > \# New Ticket Created by  \(Andreas J\. Koenig\)
> > \# Please include the string&#8203;:  \[perl \#100930\]
> > \# in the subject line of all future correspondence about this issue\.
> > \#\<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=100930>
> >
> >
> > git bisect
> > \-\-\-\-\-\-\-\-\-\-
> >
> > 7049214e3eea022e77794ed9b9d9038f93695ef9 is the first bad commit
> > commit 7049214e3eea022e77794ed9b9d9038f93695ef9
> > Author&#8203;: Karl Williamson\<public@&#8203;khwilliamson\.com>
> 
> This is a build problem\.  Why would just this one module be unable to
> find the new symbol?

Because the macro expands with \_is\_utf8\_\_perl\_idstart\, not
Perl\_\_is\_utf8\_\_perl\_idstart\.

The \_is\_utf8\_\_perl\_idstart form is only available to CPAN modules with
A\. EX is not sufficient\.

**Comment by p5pRT** [comment]
### From @cpansprout

On Fri Oct 07 17&#8203;:57&#8203;:14 2011\, sprout wrote&#8203;:
> On Fri Oct 07 15&#8203;:05&#8203;:27 2011\, public@&#8203;khwilliamson\.com wrote&#8203;:
> > On 10/07/2011 03&#8203;:06 PM\, \(Andreas J\. Koenig\) \(via RT\) wrote&#8203;:
> > > \# New Ticket Created by  \(Andreas J\. Koenig\)
> > > \# Please include the string&#8203;:  \[perl \#100930\]
> > > \# in the subject line of all future correspondence about this issue\.
> > > \#\<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=100930>
> > >
> > >
> > > git bisect
> > > \-\-\-\-\-\-\-\-\-\-
> > >
> > > 7049214e3eea022e77794ed9b9d9038f93695ef9 is the first bad commit
> > > commit 7049214e3eea022e77794ed9b9d9038f93695ef9
> > > Author&#8203;: Karl Williamson\<public@&#8203;khwilliamson\.com>
> > 
> > This is a build problem\.  Why would just this one module be unable to
> > find the new symbol?
> 
> Because the macro expands with \_is\_utf8\_\_perl\_idstart\, not
> Perl\_\_is\_utf8\_\_perl\_idstart\.
> 
> The \_is\_utf8\_\_perl\_idstart form is only available to CPAN modules with
> A\. EX is not sufficient\.

And now I’ve fixed it with commit 4244b02\.

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
