### PR TITLE
Fix g++ build (Add extra scope block for switch case)

### LINKED ISSUE #20108: 9fdd7fc479 breaks build using g++ as compiler
A recent commit to blead has broken the build when using `g++` as the C-compiler.

I first noticed this breakage in recent smoke-test reports such as [this one](http://perl.develop-help.com/raw/?id=284029).

Bisecting with this invocation:
```
perl Porting/bisect.pl \
-Dcc=g++ \
--test-build \
--start cf1717027b95225cb27f33b15b84ff798c8bacaf \
--end 40666a761f261de4ec02a7fd4e770a48957df7c7
```
... points to this commit:
```
9fdd7fc4796d89d16dceea42f2af91e4fde296ed is the first bad commit
commit 9fdd7fc4796d89d16dceea42f2af91e4fde296ed
Author: Richard Leach <richardleach@users.noreply.github.com>
Date:   Fri Jul 8 14:52:19 2022 +0000
Commit:     Richard Leach <rich+perl@hyphen-dash-hyphen.info>
CommitDate: Wed Aug 17 11:19:10 2022 +0100

 
    Implement OP_PADSV_STORE - combined sassign/padsv OP

    This commit introduces a new OP to replace simple cases
    of OP_SASSIGN and OP_PADSV.
```
@richardleach, can you take a look?

@neilb, can you keep an eye on this, as it will affect the monthly dev release scheduled for Saturday Aug 20?  Thanks.

### PR DESCRIPTION
**Pull request by bram-perl**
Code in 9fdd7fc4796d89d16dceea42f2af91e4fde296ed broke the g++ builds,

Basically after the commit the code looked like:

         switch (o->op_type) {
         ...
         case OP_SASSIGN:
             ...
             OP* rhs = cBINOPx(o)->op_first;
             OP* lval = cBINOPx(o)->op_last;
             ...
             break;

         case OP_AASSIGN: {

g++ does not allow this and errors with:

	peep.c:3897:14: error: jump to case label
	 3897 |         case OP_AASSIGN: {
	      |              ^~~~~~~~~~
	peep.c:3844:17: note:   crosses initialization of 'OP* lval'
	 3844 |             OP* lval = cBINOPx(o)->op_last;
	      |                 ^~~~
	peep.c:3843:17: note:   crosses initialization of 'OP* rhs'
	 3843 |             OP* rhs = cBINOPx(o)->op_first;
	      |                 ^~~

This happens because `rhs` and `lval` are not scoped in the case statement
so it could fall through to the next case.

The solution is to scope them which this commit now does by adding a
separate scope for `OP_SASSIGN` (similar to `OP_AASSIGN`).

Fixes #20108

### CODE REVIEW

**Review by leonerd — APPROVED** [review]
LGTM

**Comment by jkeenan** [comment]
```
$ gitcurr
bram/fix-gh-20108-fix-g++-build

$ git describe
v5.37.2-180-gfa3e3c8122

$ uname -mrs
FreeBSD 12.3-RELEASE-p1 amd64

$ g++ --version
g++ (FreeBSD Ports Collection) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Dcc=g++';

...
$ make test_harness
...
Result: PASS
```
LGTM
