### ISSUE TITLE
Unit tests failing on Windows workers

### ISSUE THREAD

**Issue by ddobbelaere** [Perl/perl5#18280]
@khwilliamson I'm not sure if you aware of it already, but the last couple of days tests are failing on all Windows workers, probably because of changes made in [430f723e](https://github.com/Perl/perl5/commit/430f723e6dceffbacbd1d7160d35ee8a2b698448), which changed the flags of `delimcpy_no_escape` from Tpd to ETpd.

The Windows workers choke on this:

```
APItest.obj : error LNK2001: unresolved external symbol __imp_Perl_delimcpy_no_escape
..\..\lib\auto\XS\APItest\APItest.dll : fatal error LNK1120: 1 unresolved externals
```

**Comment by ddobbelaere** [comment]
The issue is no longer present it seems. Probably some dark magic happening in the background (synchronization of some sort?) that I am unaware of :)

**Comment by khwilliamson** [comment]
@tonycoz noticed this failure and fixed it in 5f7a2573adf235745587e5ca142987542502f760

You are free to view this as dark magic, but I myself don't.  :)
