### ISSUE TITLE
BBC: Blead Breaks Want

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#18375]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.42 running under perl 5.33.5.

-----------------------------------------------------------------
[Please describe your issue here]

BBC: Blead Breaks Want

Please see http://matrix.cpantesters.org/?dist=Want

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=low
---
Site configuration information for perl 5.33.5:

Configured by cpan at Wed Dec  2 10:46:57 EST 2020.

Summary of my perl5 (revision 5 version 33 subversion 5) configuration:
  Commit id: 0a0027ab22794b3826f35e6a97e9c42da4a9e72a
  Platform:
    osname=openbsd
    osvers=6.8
    archname=OpenBSD.amd64-openbsd-thread-multi
    uname='openbsd cjg-openbsd6 6.8 generic#1 amd64 '
    config_args='-des -Dprefix=~/bin/perl-blead -Dscriptdir=~/bin/perl-blead/bin -Dusedevel -Duse64bitall -Duseithreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-pthread -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    optimize='-O2'
    cppflags='-pthread -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='OpenBSD Clang 10.0.1 '
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags ='-pthread -Wl,-E  -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib
    libs=-lpthread -lm -lutil -lc
    perllibs=-lpthread -lm -lutil -lc
    libc=/usr/lib/libc.so.96.0
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags='-DPIC -fPIC '
    lddlflags='-shared -fPIC  -L/usr/local/lib -fstack-protector-strong'

---
@INC for perl 5.33.5:
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.5/OpenBSD.amd64-openbsd-thread-multi
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.5
    /home/cpan/bin/perl-blead/lib/5.33.5/OpenBSD.amd64-openbsd-thread-multi
    /home/cpan/bin/perl-blead/lib/5.33.5

---
Environment for perl 5.33.5:
    HOME=/home/cpan
    LANG (unset)
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl-blead/bin:/home/cpan/bin:/home/cpan/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/games
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/bash

**Comment by jkeenan** [comment]
> This is a bug report for perl from "Carlos Guevara" [carlos@carlosguevara.com](mailto:carlos@carlosguevara.com),
> generated with the help of perlbug 1.42 running under perl 5.33.5.
> 
> [Please describe your issue here]
> 
> BBC: Blead Breaks Want
>

We should explore how similar to (different from) https://github.com/Perl/perl5/issues/18321 this is.

**Comment by richardleach** [comment]
https://github.com/Perl/perl5/commit/1d6cadf136bf2c85058a5359fb48b09b3ea9fe6f looks like the probable cause

**Comment by jkeenan** [comment]
Build-time failure:
```
cc -c    -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_FORTIFY_SOURCE=2 -O2 -pipe -fstack-protector -fno-strict-aliasing    -DVERSION=\"0.29\"  -DXS_VERSION=\"0.29\" -DPIC -fPIC "-I/home/jkeenan/testing/blead/lib/perl5/5.33.5/amd64-freebsd-thread-multi/CORE"   Want.c
Want.xs:308:37: error: use of undeclared identifier 'cUNOPo'
            if (find_ancestors_from(cUNOPo->op_first, next, l))
                                    ^
Want.xs:369:14: error: use of undeclared identifier 'cUNOPo'
    OP* pm = cUNOPo->op_first;
             ^
Want.xs:543:52: error: use of undeclared identifier 'cUNOPo'
    if (o && o->op_type == OP_ENTERSUB && (first = cUNOPo->op_first)
                                                   ^
Want.xs:620:30: error: use of undeclared identifier 'cBINOPo'
        I32 lhs = count_list(cBINOPo->op_last,  Nullop  );
                             ^
4 errors generated.
*** Error code 1
```

**Comment by jkeenan** [comment]
> [1d6cadf](https://github.com/Perl/perl5/commit/1d6cadf136bf2c85058a5359fb48b09b3ea9fe6f) looks like the probable cause

Confirmed.
```
1d6cadf136bf2c85058a5359fb48b09b3ea9fe6f is the first bad commit
commit 1d6cadf136bf2c85058a5359fb48b09b3ea9fe6f
Author: Karl Williamson <khw@cpan.org>
Date:   Sat Oct 17 07:04:41 2020 -0600

    op.h: Restrict to core certain internal symbols
    
    so that they aren't accessible to XS code and won't be picked up by
    autodoc

:100644 100644 975071756240e412ebce92aa1a59851489d591c2 b7d762a52931c3ce5812591570d95b4f76ccce84 Mop.h
```
@khwilliamson, can you have a look?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
As a result of https://github.com/Perl/perl5/commit/8b40c6980a4ae3fa364f4921879001f097000652, this module once again installs against blead.

Thank you very much.
Jim Keenan
