### ISSUE TITLE
blead giving valgrind jump depends on uninit

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#24242]
**Description**

../lib/overload.t: Valgrind output:
../lib/overload.t: ==2203205== Conditional jump or move depends on uninitialised value(s)
../lib/overload.t: ==2203205==    at 0x445584: S_tokeq (toke.c:2495)
../lib/overload.t: ==2203205==    by 0x472CFE: Perl_yylex (toke.c:10312)
../lib/overload.t: ==2203205==    by 0x257846: Perl_yyparse (perly.c:382)
../lib/overload.t: ==2203205==    by 0x199FE9: S_parse_body (perl.c:2688)
../lib/overload.t: ==2203205==    by 0x197FED: perl_parse (perl.c:1933)
../lib/overload.t: ==2203205==    by 0x15254D: main (perlmain.c:106)

**Steps to Reproduce**
valgrind ./perl -Ilib lib/overload.pm

**Expected behavior**

**Perl configuration**

```
# perl -V output goes here
```
Summary of my perl5 (revision 5 version 43 subversion 9) configuration:
  Commit id: c75ae9cc164205e1b6d6dbd57bd2c65c8593fe94
  Platform:
    osname=linux
    osvers=6.8.0-101-generic
    archname=x86_64-linux-thread-multi
    uname='linux khw8950 6.8.0-101-generic #101-ubuntu smp preempt_dynamic mon feb 9 10:15:05 utc 2026 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Uversiononly -Dprefix=/home/khw/blead -Dusedevel -Doptimize=-O0 -DDEBUGGING -A'optimize=-g3' -A'optimize=-ggdb3' -A'optimize=-gdwarf-3' -A'optimize=-g3' -Accflags='-Wno-deprecated' -Dman1dir='none' -Dman3dir='none' -Dcc=g++ -Dusecbacktrace -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='g++'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -Wno-deprecated -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g3 -ggdb3 -gdwarf-3 -g3'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -Wno-deprecated -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='13.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.39'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g3 -ggdb3 -gdwarf-3 -g3 -L/usr/local/lib -fstack-protector-strong'

Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Feb 28 2026 09:12:21
  %ENV:
    PERL5OPT="-w"
    PERL_DIFF_TOOL="wgdiff"
    PERL_DUMP_RE_MAX_LEN="10000"
    PERL_POD_PEDANTIC="1"
    PERL_TEST_HARNESS_ASAP="1"
  @INC:
    /home/khw/perl/blead/lib
    /home/khw/perl/blead/t
    /home/khw/blead/lib/perl5/site_perl/5.43.9/x86_64-linux-thread-multi
    /home/khw/blead/lib/perl5/site_perl/5.43.9
    /home/khw/blead/lib/perl5/5.43.9/x86_64-linux-thread-multi
    /home/khw/blead/lib/perl5/5.43.9
    /home/khw/blead/lib/perl5/site_perl/5.43.3
    /home/khw/blead/lib/perl5/site_perl/5.43.2
    /home/khw/blead/lib/perl5/site_perl/5.43.1
    /home/khw/blead/lib/perl5/site_perl/5.43.0
    /home/khw/blead/lib/perl5/site_perl/5.42.0
    /home/khw/blead/lib/perl5/site_perl/5.41.14
    /home/khw/blead/lib/perl5/site_perl/5.41.13
    /home/khw/blead/lib/perl5/site_perl/5.41.12
    /home/khw/blead/lib/perl5/site_perl/5.41.11
    /home/khw/blead/lib/perl5/site_perl/5.41.10
    /home/khw/blead/lib/perl5/site_perl/5.41.9
    /home/khw/blead/lib/perl5/site_perl/5.41.8
    /home/khw/blead/lib/perl5/site_perl/5.41.7
    /home/khw/blead/lib/perl5/site_perl/5.41.6
    /home/khw/blead/lib/perl5/site_perl/5.41.5
    /home/khw/blead/lib/perl5/site_perl/5.41.2
    /home/khw/blead/lib/perl5/site_perl/5.41.1
    /home/khw/blead/lib/perl5/site_perl/5.41.0
    /home/khw/blead/lib/perl5/site_perl/5.40.0
    /home/khw/blead/lib/perl5/site_perl/5.39.11
    /home/khw/blead/lib/perl5/site_perl/5.39.10
    /home/khw/blead/lib/perl5/site_perl/5.39.9
    /home/khw/blead/lib/perl5/site_perl/5.39.8
    /home/khw/blead/lib/perl5/site_perl/5.39.6
    /home/khw/blead/lib/perl5/site_perl/5.39.5
    /home/khw/blead/lib/perl5/site_perl/5.39.4
    /home/khw/blead/lib/perl5/site_perl/5.39.3
    /home/khw/blead/lib/perl5/site_perl/5.39.2
    /home/khw/blead/lib/perl5/site_perl/5.39.1
    /home/khw/blead/lib/perl5/site_perl/5.39.0
    /home/khw/blead/lib/perl5/site_perl/5.38.0
    /home/khw/blead/lib/perl5/site_perl/5.37.12
    /home/khw/blead/lib/perl5/site_perl/5.37.11
    /home/khw/blead/lib/perl5/site_perl/5.37.10
    /home/khw/blead/lib/perl5/site_perl/5.37.9
    /home/khw/blead/lib/perl5/site_perl/5.37.8
    /home/khw/blead/lib/perl5/site_perl/5.37.7
    /home/khw/blead/lib/perl5/site_perl/5.37.6
    /home/khw/blead/lib/perl5/site_perl/5.37.5
    /home/khw/blead/lib/perl5/site_perl/5.37.4
    /home/khw/blead/lib/perl5/site_perl/5.37.3
    /home/khw/blead/lib/perl5/site_perl/5.37.2
    /home/khw/blead/lib/perl5/site_perl/5.37.1
    /home/khw/blead/lib/perl5/site_perl/5.36.0
    /home/khw/blead/lib/perl5/site_perl/5.35.12
    /home/khw/blead/lib/perl5/site_perl/5.35.11
    /home/khw/blead/lib/perl5/site_perl/5.35.10
    /home/khw/blead/lib/perl5/site_perl/5.35.9
    /home/khw/blead/lib/perl5/site_perl/5.35.8
    /home/khw/blead/lib/perl5/site_perl/5.35.7
    /home/khw/blead/lib/perl5/site_perl/5.35.6
    /home/khw/blead/lib/perl5/site_perl/5.35.5
    /home/khw/blead/lib/perl5/site_perl/5.35.4
    /home/khw/blead/lib/perl5/site_perl/5.35.3
    /home/khw/blead/lib/perl5/site_perl/5.35.2
    /home/khw/blead/lib/perl5/site_perl/5.35.1
    /home/khw/blead/lib/perl5/site_perl/5.35.0
    /home/khw/blead/lib/perl5/site_perl/5.34.0
    /home/khw/blead/lib/perl5/site_perl/5.33.9
    /home/khw/blead/lib/perl5/site_perl/5.33.8
    /home/khw/blead/lib/perl5/site_perl/5.33.7
    /home/khw/blead/lib/perl5/site_perl/5.33.6
    /home/khw/blead/lib/perl5/site_perl/5.33.5
    /home/khw/blead/lib/perl5/site_perl/5.33.4
    /home/khw/blead/lib/perl5/site_perl/5.33.3
    /home/khw/blead/lib/perl5/site_perl/5.33.2
    /home/khw/blead/lib/perl5/site_perl/5.33.1
    /home/khw/blead/lib/perl5/site_perl/5.33.0
    /home/khw/blead/lib/perl5/site_perl/5.32.0
    /home/khw/blead/lib/perl5/site_perl/5.31.12
    /home/khw/blead/lib/perl5/site_perl/5.31.11
    /home/khw/blead/lib/perl5/site_perl/5.31.10
    /home/khw/blead/lib/perl5/site_perl/5.31.9
    /home/khw/blead/lib/perl5/site_perl/5.31.8
    /home/khw/blead/lib/perl5/site_perl/5.31.7
    /home/khw/blead/lib/perl5/site_perl/5.31.6
    /home/khw/blead/lib/perl5/site_perl/5.31.5
    /home/khw/blead/lib/perl5/site_perl/5.31.4
    /home/khw/blead/lib/perl5/site_perl/5.31.3
    /home/khw/blead/lib/perl5/site_perl/5.31.2
    /home/khw/blead/lib/perl5/site_perl/5.31.1
    /home/khw/blead/lib/perl5/site_perl/5.31.0
    /home/khw/blead/lib/perl5/site_perl/5.30.0
    /home/khw/blead/lib/perl5/site_perl/5.29.10
    /home/khw/blead/lib/perl5/site_perl/5.29.9
    /home/khw/blead/lib/perl5/site_perl/5.29.8
    /home/khw/blead/lib/perl5/site_perl/5.29.7
    /home/khw/blead/lib/perl5/site_perl/5.29.6
    /home/khw/blead/lib/perl5/site_perl/5.29.5
    /home/khw/blead/lib/perl5/site_perl/5.29.4
    /home/khw/blead/lib/perl5/site_perl/5.29.3
    /home/khw/blead/lib/perl5/site_perl/5.29.2
    /home/khw/blead/lib/perl5/site_perl/5.29.1
    /home/khw/blead/lib/perl5/site_perl/5.29.0
    /home/khw/blead/lib/perl5/site_perl/5.28.0
    /home/khw/blead/lib/perl5/site_perl/5.27.11
    /home/khw/blead/lib/perl5/site_perl/5.27.10
    /home/khw/blead/lib/perl5/site_perl/5.27.9
    /home/khw/blead/lib/perl5/site_perl/5.27.8
    /home/khw/blead/lib/perl5/site_perl/5.27.7
    /home/khw/blead/lib/perl5/site_perl/5.27.6
    /home/khw/blead/lib/perl5/site_perl/5.27.5
    /home/khw/blead/lib/perl5/site_perl/5.27.4
    /home/khw/blead/lib/perl5/site_perl/5.27.3
    /home/khw/blead/lib/perl5/site_perl/5.27.2
    /home/khw/blead/lib/perl5/site_perl/5.27.1
    /home/khw/blead/lib/perl5/site_perl/5.27.0
    /home/khw/blead/lib/perl5/site_perl/5.26.0
    /home/khw/blead/lib/perl5/site_perl/5.25.12
    /home/khw/blead/lib/perl5/site_perl/5.25.11
    /home/khw/blead/lib/perl5/site_perl/5.25.10
    /home/khw/blead/lib/perl5/site_perl/5.25.9
    /home/khw/blead/lib/perl5/site_perl/5.25.8
    /home/khw/blead/lib/perl5/site_perl/5.25.7
    /home/khw/blead/lib/perl5/site_perl/5.25.6
    /home/khw/blead/lib/perl5/site_perl/5.25.5
    /home/khw/blead/lib/perl5/site_perl/5.25.4
    /home/khw/blead/lib/perl5/site_perl/5.25.3
    /home/khw/blead/lib/perl5/site_perl/5.25.2
    /home/khw/blead/lib/perl5/site_perl/5.25.1
    /home/khw/blead/lib/perl5/site_perl/5.24.0
    /home/khw/blead/lib/perl5/site_perl/5.23.10
    /home/khw/blead/lib/perl5/site_perl/5.23.9
    /home/khw/blead/lib/perl5/site_perl/5.23.8
    /home/khw/blead/lib/perl5/site_perl/5.23.7
    /home/khw/blead/lib/perl5/site_perl/5.23.6
    /home/khw/blead/lib/perl5/site_perl/5.23.5
    /home/khw/blead/lib/perl5/site_perl/5.23.4
    /home/khw/blead/lib/perl5/site_perl/5.23.3
    /home/khw/blead/lib/perl5/site_perl/5.23.2
    /home/khw/blead/lib/perl5/site_perl/5.23.1
    /home/khw/blead/lib/perl5/site_perl/5.23.0
    /home/khw/blead/lib/perl5/site_perl/5.22.0
    /home/khw/blead/lib/perl5/site_perl/5.21.12
    /home/khw/blead/lib/perl5/site_perl/5.21.11
    /home/khw/blead/lib/perl5/site_perl/5.21.10
    /home/khw/blead/lib/perl5/site_perl/5.21.9
    /home/khw/blead/lib/perl5/site_perl/5.21.8
    /home/khw/blead/lib/perl5/site_perl/5.21.7
    /home/khw/blead/lib/perl5/site_perl/5.21.6
    /home/khw/blead/lib/perl5/site_perl/5.21.5
    /home/khw/blead/lib/perl5/site_perl/5.21.4
    /home/khw/blead/lib/perl5/site_perl/5.21.3
    /home/khw/blead/lib/perl5/site_perl/5.21.2
    /home/khw/blead/lib/perl5/site_perl/5.21.1
    /home/khw/blead/lib/perl5/site_perl/5.20.0
    /home/khw/blead/lib/perl5/site_perl/5.19.12
    /home/khw/blead/lib/perl5/site_perl/5.19.11
    /home/khw/blead/lib/perl5/site_perl/5.19.10
    /home/khw/blead/lib/perl5/site_perl

**Comment by mauke** [comment]
Reduced (at commit b97dbfa9e19d044):
```
$ valgrind ./perl -c -e "s'foo'bar'"
==46064== Memcheck, a memory error detector
==46064== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==46064== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==46064== Command: ./perl -c -e s'foo'bar'
==46064== 
==46064== Conditional jump or move depends on uninitialised value(s)
==46064==    at 0x37F357: S_tokeq (toke.c:2500)
==46064==    by 0x39A5F1: Perl_yylex (toke.c:10317)
==46064==    by 0x20C7B7: Perl_yyparse (perly.c:382)
==46064==    by 0x18E1FE: S_parse_body (perl.c:2688)
==46064==    by 0x18E1FE: perl_parse (perl.c:1933)
==46064==    by 0x155312: main (perlmain.c:106)
==46064== 
-e syntax OK
...
```

**Comment by mauke** [comment]
The line it complains about is:
```c
    if (SvTYPE(sv) >= SVt_PVIV && SvIVX(sv) == -1) /* <<'heredoc' */
```
(Maybe `IVX` is uninitialized?)

The calling context of `tokeq` is:
```c
        /* m'foo' still needs to be parsed for possible (?{...}) */
        if (SvIVX(PL_linestr) == '\'' && !PL_lex_inpat) {
            SV *sv = newSVsv(PL_linestr);
            sv = tokeq(sv);
```

Bisecting:
```
$ ../perl5/Porting/bisect.pl --start=v5.42.0 --target=perl -j5 --valgrind -c -e "s'foo'bar'"
...
proto.h:3128:1: warning: data definition has no type or storage class
 3128 | Perl_newSVsv_flags_NN(pTHX_ SV * const old, I32 flags)
      | ^~~~~~~~~~~~~~~~~~~~~
proto.h:3128:1: warning: type defaults to ‘int’ in declaration of ‘Perl_newSVsv_flags_NN’ [-Wimplicit-int]
In file included from perl.h:8001:
sv_inline.h:1008:6: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘:’ token
 1008 |  * ex: set ts=8 sts=4 sw=4 et:
      |      ^
make: *** [Makefile:318: opmini.o] Error 1
HEAD is now at 79b32d926e sv.c: Add Perl_newSVsv_flags_NN and static helpers
skipping - could not build perl at ../perl5/Porting/bisect-runner.pl line 1685.
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
79b32d926ef5961b4946ebe761a7058cb235f797
0dfa8ac113680e6acdef0751168ab231b9bf842c
We cannot bisect more!
error: bisect run cannot continue any more
Died at ../perl5/Porting/bisect.pl line 269.
That took 637 seconds.
```

The candidates 79b32d926ef5 and 0dfa8ac11368 are both by @richardleach and relate to `newSVsv_flags`.

**Comment by mauke** [comment]
Further evidence implicating IVX: If I copy the IVX field to `sv` manually before calling `tokeq`, the error disappears.
```c
        /* m'foo' still needs to be parsed for possible (?{...}) */
        if (SvIVX(PL_linestr) == '\'' && !PL_lex_inpat) {
            SV *sv = newSVsv(PL_linestr);
/* + */     SvIV_set(sv, SvIVX(PL_linestr));
            sv = tokeq(sv);
```

**Comment by richardleach** [comment]
Taking a look

**Comment by richardleach** [comment]
Well, that's "fun". Using the minimal reproducer of `./perl -c -e "s'foo'bar'"`, at the point of `SV *sv = newSVsv(PL_linestr);`, `PL_linestr` looks like this:
```
SV = PVIV(0x562346ff0788) at 0x562346fed170
  REFCNT = 1
  FLAGS = (POK,pPOK)
  IV = 39
  PV = 0x562346ff6010 "bar"\0
  CUR = 3
  LEN = 16
```
The parser's expectation is that the IV value is copied by `newSVsv` - even though the SvFLAGS indicate that only the PV value is valid.

My understanding of dualvars is that the IV and PV values can be unrelated as they are above, but the var still has to be `IOK` **and** `POK`, if `PL_linestr` is supposed to be a dualvar at this point, doesn't this mean it doesn't have its flags set correctly?

**Comment by richardleach** [comment]
There just seems to be that one line where `PL_linestr` is copied to a new SV. I'll draft a PR where the SV is copied as-now, with comments, and then the IV slot is manually populated.

**Comment by tonycoz** [comment]
I don't think the problem is copying, but initialisation.

The old newSVpv() did an sv_upgrade() for the new SV, which initialises the the body to zero, while the new code doesn't initialise IV at all.

So I don't think it needs a copy, but just that all fields are initialised.

Stepping through this in 5.42.0:
```
Breakpoint 1, Perl_yylex (my_perl=my_perl@entry=0x555555a922a0) at toke.c:9821
9821                SV *sv = newSVsv(PL_linestr);
(gdb) n
9822                sv = tokeq(sv);
(gdb) call Perl_sv_dump(PL_linestr)
Too few arguments in function call.
(gdb) call Perl_sv_dump(my_perl, PL_linestr)
SV = PVIV(0x555555ac7820) at 0x555555ac35d8
  REFCNT = 1
  FLAGS = (POK,pPOK)
  IV = 39
  PV = 0x555555aceb78 "bar"\0
  CUR = 3
  LEN = 4
(gdb) call Perl_sv_dump(my_perl, sv)
SV = PVIV(0x555555ac7838) at 0x555555ac3608
  REFCNT = 1
  FLAGS = (POK,pPOK)
  IV = 0
  PV = 0x555555a9a7e8 "bar"\0
  CUR = 3
  LEN = 16
(gdb) q
```

and I expect this could be a problem elsewhere.

**Comment by mauke** [comment]
Makes sense, but at least in this case, there is no practical difference between `0` and a copy (which is `'\''`) because `tokeq()` only checks for `SvIVX(sv) == -1`.

**Comment by richardleach** [comment]
I'm looking again. The bug definitely seems to have come in with `Perl_newSVsv_flags_NN`, but I can't see a difference in `PL_linestr` and `sv` from 5.42.0 (other than the LEN difference, which didn't come in with the relevant commits):

```
SV = PVIV(0x55e2eb7ecd40) at 0x55e2eb7e8888
  REFCNT = 1
  FLAGS = (POK,pPOK)
  IV = 39
  PV = 0x55e2eb7f3838 "bar"\0
  CUR = 3
  LEN = 16
```
```
SV = PVIV(0x55e2eb7ecd58) at 0x55e2eb7e88b8
  REFCNT = 1
  FLAGS = (POK,pPOK)
  IV = 0
  PV = 0x55e2eb7f40f8 "bar"\0
  CUR = 3
  LEN = 16
```

**Comment by richardleach** [comment]
Ok. think I see it. `new_XPVIV` does not zero the body struct. `Perl_newSvsv_flags_NN` doesn't initialize values unless the relevant flag is on - the rationale being "_If the flags don't say this value is valid, what are you doing trying to read it_?!"

Will confirm if that's what's happening.

**Comment by richardleach** [comment]
Yes, that's it. Probably true for the PVNV and PVMG structs too.

I can add in some defensive initializations, though it grates to have to do so.

**Comment by tonycoz** [comment]
There are many CPAN modules that directly SvIV_set(), most also set IOK, or set the IV slot only on SVs that already should have it set, but I'm not sure they all do that or if they always initialise the IV slot before using them.

If they rely on the historical zero initialisation, this could break them, or produce spurious warnings if they test with valgrind.

I expect we're getting our zero-initialisations for our uninitialised memory from the default zero-initialisation linux (IIRC) does for newly allocated blocks.

So I think we need the apparently unneeded initialisations.

**Comment by jkeenan** [comment]
> There are many CPAN modules that directly SvIV_set(), most also set IOK, or set the IV slot only on SVs that already should have it set, but I'm not sure they all do that or if they always initialise the IV slot before using them.
> 

@tonycoz could you name some of them (I only found 2 myself) so that we know which distros need testing against any relevant pull request?

**Comment by tonycoz** [comment]
> [@tonycoz](https://github.com/tonycoz) could you name some of them (I only found 2 myself) so that we know which distros need testing against any relevant pull request?

I started from a cpan grep:
```
$ git remote -v
origin  https://github.com/metacpan/metacpan-cpan-extracted.git (fetch)
origin  https://github.com/metacpan/metacpan-cpan-extracted.git (push)
$ git grep SvIV_set HEAD | grep '\.xs:'
HEAD:distros/A/Affix/lib/Affix.xs:                        SvIV_set(TARGET, SvIV(num));
HEAD:distros/A/Alt-Lexical-Var-ButSupportModernPerl/Var.xs:#  define COP_SEQ_RANGE_HIGH_set(sv,val) SvIV_set(sv, val)
HEAD:distros/A/Array-Heap/Heap.xs:        SvIV_set (sv, idx);
HEAD:distros/C/CORBA-omniORB/omnithreads/omnithreads.xs:    SvIV_set(sv, PTR2IV(thread));
HEAD:distros/C/Coro/Event/Event.xs:  SvIV_set (AvARRAY (priv)[CD_HITS], pe->hits);
HEAD:distros/C/Coro/Event/Event.xs:  SvIV_set (AvARRAY (priv)[CD_GOT], type ? ((pe_ioevent *)pe)->got : 0);
HEAD:distros/D/Data-Peek/Peek.xs:       SvIV_set (tv, SvIV (iv));
HEAD:distros/D/Deliantra-Client/Client.xs:    SvIV_set (*sv, SvIVX (*sv) | bits);
HEAD:distros/D/Devel-Debug-DBGp/perl5db.xs:    SvIV_set(PL_DBsingle, x);
HEAD:distros/D/Devel-Declare/Declare.xs:      SvIV_set(sv, 0);
HEAD:distros/E/EV/EV.xs:      SvIV_set (sv_events, revents);
...
```
