### ISSUE TITLE
null ptr deref -> S_pad_findlex (pad.c:1141

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14621]
Migrated from [rt.perl.org#124187](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=124187) (status was 'resolved')

Searchable as RT124187$

**Comment by p5pRT** [comment]
### From @geeknik

Built v5\.21\.11 \(v5\.21\.10\-23\-g21639bf\) with the following command line&#8203;:

\./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-gcc \-Doptimize=\-O2\\ \-g && AFL\_HARDEN=1 make \-j4 test\-prep

Bug found with AFL \(http&#8203;://lcamtuf\.coredump\.cx/afl\)

Valgrind&#8203;:
==14673== Invalid read of size 8
==14673==    at 0x682C6C&#8203;: S\_pad\_findlex \(pad\.c&#8203;:1141\)
==14673==    by 0x6861FA&#8203;: Perl\_pad\_findmy\_pvn \(pad\.c&#8203;:962\)
==14673==    by 0x5F6C64&#8203;: Perl\_yylex \(toke\.c&#8203;:6482\)
==14673==    by 0x65A584&#8203;: Perl\_yyparse \(perly\.c&#8203;:322\)
==14673==    by 0x531574&#8203;: S\_parse\_body \(perl\.c&#8203;:2296\)
==14673==    by 0x5392E2&#8203;: perl\_parse \(perl\.c&#8203;:1626\)
==14673==    by 0x42AC67&#8203;: main \(perlmain\.c&#8203;:114\)
==14673==  Address 0x0 is not stack'd\, malloc'd or \(recently\) free'd
==14673== 
==14673== 
==14673== Process terminating with default action of signal 11 \(SIGSEGV\)
==14673==  Access not within mapped region at address 0x0
==14673==    at 0x682C6C&#8203;: S\_pad\_findlex \(pad\.c&#8203;:1141\)
==14673==    by 0x6861FA&#8203;: Perl\_pad\_findmy\_pvn \(pad\.c&#8203;:962\)
==14673==    by 0x5F6C64&#8203;: Perl\_yylex \(toke\.c&#8203;:6482\)
==14673==    by 0x65A584&#8203;: Perl\_yyparse \(perly\.c&#8203;:322\)
==14673==    by 0x531574&#8203;: S\_parse\_body \(perl\.c&#8203;:2296\)
==14673==    by 0x5392E2&#8203;: perl\_parse \(perl\.c&#8203;:1626\)
==14673==    by 0x42AC67&#8203;: main \(perlmain\.c&#8203;:114\)
==14673==  If you believe this happened as a result of a stack
==14673==  overflow in your program's main thread \(unlikely but
==14673==  possible\)\, you can try to increase the size of the
==14673==  main thread stack using the \-\-main\-stacksize= flag\.
==14673==  The main thread stack size used in this run was 8388608\.
Segmentation fault

GDB&#8203;:
Program received signal SIGSEGV\, Segmentation fault\.
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-registers\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
RAX&#8203;: 0x0 
RBX&#8203;: 0x11eb215 \-\-> 0x21000000 \(''\)
RCX&#8203;: 0x0 
RDX&#8203;: 0x0 
RSI&#8203;: 0x2 
RDI&#8203;: 0x7fffffffdb40 \-\-> 0x9d7526 \(\<Perl\_sv\_catpv\+2918>&#8203;:    add    BYTE PTR \[rax\]\,al\)
RBP&#8203;: 0x11eb215 \-\-> 0x21000000 \(''\)
RSP&#8203;: 0x7fffffffd8a0 \-\-> 0x11cfd10 \-\-> 0x1 
RIP&#8203;: 0x682c6c \(\<S\_pad\_findlex\+76>&#8203;:    mov    rbx\,QWORD PTR \[rax\]\)
R8 : 0xffffffd2 
R9 : 0x1 
R10&#8203;: 0x11ec198 \-\-> 0x620075 \(\<Perl\_yylex\+313365>&#8203;:    add    BYTE PTR \[rax\-0x75\]\,cl\)
R11&#8203;: 0x7ffff6eb3730 \-\-> 0xfffd5830fffd5070 
R12&#8203;: 0x2 
R13&#8203;: 0x0 
R14&#8203;: 0x2 
R15&#8203;: 0x1
EFLAGS&#8203;: 0x10206 \(carry PARITY adjust zero sign trap INTERRUPT direction overflow\)
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-code\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
&nbsp;   0x682c66 \<S\_pad\_findlex\+70>&#8203;:    push   rbp
&nbsp;   0x682c67 \<S\_pad\_findlex\+71>&#8203;:    push   rbx
&nbsp;   0x682c68 \<S\_pad\_findlex\+72>&#8203;:    sub    rsp\,0x78
=> 0x682c6c \<S\_pad\_findlex\+76>&#8203;:    mov    rbx\,QWORD PTR \[rax\]
&nbsp;   0x682c6f \<S\_pad\_findlex\+79>&#8203;:    mov    rsi\,QWORD PTR \[rsp\+0xb8\]
&nbsp;   0x682c77 \<S\_pad\_findlex\+87>&#8203;:    mov    QWORD PTR \[rsp\]\,rdi
&nbsp;   0x682c7b \<S\_pad\_findlex\+91>&#8203;:    mov    DWORD PTR \[rsp\+0x50\]\,edx
&nbsp;   0x682c7f \<S\_pad\_findlex\+95>&#8203;:    mov    QWORD PTR \[rsp\+0x30\]\,rcx
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-stack\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
0000| 0x7fffffffd8a0 \-\-> 0x11cfd10 \-\-> 0x1 
0008| 0x7fffffffd8a8 \-\-> 0x682c42 \(\<S\_pad\_findlex\+34>&#8203;:    mov    rax\,QWORD PTR \[rsp\+0x10\]\)
0016| 0x7fffffffd8b0 \-\-> 0x0 
0024| 0x7fffffffd8b8 \-\-> 0x0 
0032| 0x7fffffffd8c0 \-\-> 0x7fffffffd98c \-\-> 0x11efbde00000000 
0040| 0x7fffffffd8c8 \-\-> 0x4000 \(''\)
0048| 0x7fffffffd8d0 \-\-> 0x6861b2 \(\<Perl\_pad\_findmy\_pvn\+130>&#8203;:    mov    rax\,QWORD PTR \[rsp\+0x10\]\)
0056| 0x7fffffffd8d8 \-\-> 0x0 
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
Legend&#8203;: code\, data\, rodata\, value
Stopped reason&#8203;: SIGSEGV
S\_pad\_findlex \(\) at pad\.c&#8203;:1141
1141        const PADLIST \* const padlist = CvPADLIST\(cv\);
gdb\-peda$ list
1136        int warn\, SV\*\* out\_capture\, PADNAME\*\* out\_name\, int \*out\_flags\)
1137    \{
1138        I32 offset\, new\_offset;
1139        SV \*new\_capture;
1140        SV \*\*new\_capturep;
1141        const PADLIST \* const padlist = CvPADLIST\(cv\);
1142        const bool staleok = \!\!\(flags & padadd\_STALEOK\);
1143    
1144        PERL\_ARGS\_ASSERT\_PAD\_FINDLEX;
1145

Hexdump of the 21\-byte test case&#8203;:
0000000 7171 407b 5b7b 7d7b 2a7d 7573 7b62 5d5d
0000010 7d7d 3d7d 0075                         
0000015

System Info&#8203;: Debian 7\, Kernel 3\.2\.65\-1\+deb7u2 x86\_64\, GCC 4\.9\.2\, libc 2\.13\-38\+deb7u8

**Comment by p5pRT** [comment]
### From @geeknik

[test1-min](https://rt-archive.perl.org/perl5/Ticket/Attachment/1337889/715143/test1-min)

**Comment by p5pRT** [comment]
### From @geeknik

The test case \(perl \-e 'qq\{@&#8203;\{\[\{\}\}\*sub\{\]\]\}\}\}=u'\) also crashes the following&#8203;:

perl 5\, version 18\, subversion 4 \(v5\.18\.4\) built for i386\-freebsd\-thread\-multi\-64int 
perl 5\, version 21\, subversion 7 \(v5\.21\.7 \(v5\.21\.6\-602\-ge9d2bd8\)\) built for x86\_64\-linux

**Comment by p5pRT** [comment]
### From @geeknik

Does not crash perl 5\, version 16\, subversion 3 \(v5\.16\.3\) built for amd64\-freebsd\-thread\-multi\, fails with this error&#8203;:

$ perl \-e 'qq\{@&#8203;\{\[\{\}\}\*sub\{\]\]\}\}\}=u'
syntax error at \-e line 1\, near "\}\}"
syntax error at \-e line 1\, near "\{\]"
Unmatched right curly bracket at \-e line 1\, at end of line
syntax error at \-e line 1\, at EOF
Execution of \-e aborted due to compilation errors\.

**Comment by p5pRT** [comment]
### From @wolfsage

On Thu\, Mar 26\, 2015 at 11&#8203;:45 PM\, Brian Carpenter
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> \# New Ticket Created by  Brian Carpenter
> \# Please include the string&#8203;:  \[perl \#124187\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=124187 >

This started SEGVing between 5\.17\.5 and 5\.17\.6 \(on vanilla \-des
\-Dusedevel builds\)

&nbsp;  /home/mhorsfall/dpppperls/default/perl\-5\.17\.5/bin/perl5\.17\.5
/home/mhorsfall/test1\-min 2>&1
&nbsp;    syntax error at /home/mhorsfall/test1\-min line 1\, near "\}\}"
&nbsp;    syntax error at /home/mhorsfall/test1\-min line 1\, near "\{\]"
&nbsp;    Unmatched right curly bracket at /home/mhorsfall/test1\-min line 1\,
at end of line
&nbsp;    syntax error at /home/mhorsfall/test1\-min line 1\, at EOF
&nbsp;    Execution of /home/mhorsfall/test1\-min aborted due to compilation errors\.
&nbsp;    child exited with value 255
&nbsp;  /home/mhorsfall/dpppperls/default/perl\-5\.17\.6/bin/perl5\.17\.6
/home/mhorsfall/test1\-min 2>&1
&nbsp;    child died with signal 11 \(SEGV\)

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @wolfsage

On Fri\, Mar 27\, 2015 at 7&#8203;:21 AM\, Matthew Horsfall \(alh\)
\<wolfsage@&#8203;gmail\.com> wrote&#8203;:
> This started SEGVing between 5\.17\.5 and 5\.17\.6 \(on vanilla \-des
> \-Dusedevel builds\)
>
>   /home/mhorsfall/dpppperls/default/perl\-5\.17\.5/bin/perl5\.17\.5
> /home/mhorsfall/test1\-min 2>&1
>     syntax error at /home/mhorsfall/test1\-min line 1\, near "\}\}"
>     syntax error at /home/mhorsfall/test1\-min line 1\, near "\{\]"
>     Unmatched right curly bracket at /home/mhorsfall/test1\-min line 1\,
> at end of line
>     syntax error at /home/mhorsfall/test1\-min line 1\, at EOF
>     Execution of /home/mhorsfall/test1\-min aborted due to compilation errors\.
>     child exited with value 255
>   /home/mhorsfall/dpppperls/default/perl\-5\.17\.6/bin/perl5\.17\.6
> /home/mhorsfall/test1\-min 2>&1
>     child died with signal 11 \(SEGV\)

bad \- non\-zero exit from \./perl \-Ilib /home/mhorsfall/test1\-min
9ffcdca1f504cb09088413c074b35af4b7f247e3 is the first bad commit
commit 9ffcdca1f504cb09088413c074b35af4b7f247e3
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Mon Nov 12 23&#8203;:04&#8203;:16 2012 \-0800

&nbsp;    Don’t leak subs containing syntax errors

&nbsp;    I fixed this for BEGIN blocks earlier\, but missed the fact that
&nbsp;    all subs are affected\.

&nbsp;    When called without an o argument \(from newANONATTRSUB\)\, newATTRSUB
&nbsp;    is expected to return a CV with an unowned reference count of which
&nbsp;    the caller will take ownership\.  We cannot have newATTRSUB returning
&nbsp;    a freed CV\, so we have it return null instead\.  But that means
&nbsp;    ck\_anoncode and pm\_runtime have to account for that\.

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
### From @cpansprout

On Fri Mar 27 05&#8203;:06&#8203;:05 2015\, alh wrote&#8203;:
> bad \- non\-zero exit from \./perl \-Ilib /home/mhorsfall/test1\-min
> 9ffcdca1f504cb09088413c074b35af4b7f247e3 is the first bad commit
> commit 9ffcdca1f504cb09088413c074b35af4b7f247e3
> Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
> Date&#8203;:   Mon Nov 12 23&#8203;:04&#8203;:16 2012 \-0800
> 
> Don’t leak subs containing syntax errors

Why are you always blaming me? :\-\)

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @wolfsage

On Fri\, Mar 27\, 2015 at 11&#8203;:43 AM\, Father Chrysostomos via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> On Fri Mar 27 05&#8203;:06&#8203;:05 2015\, alh wrote&#8203;:
>> bad \- non\-zero exit from \./perl \-Ilib /home/mhorsfall/test1\-min
>> 9ffcdca1f504cb09088413c074b35af4b7f247e3 is the first bad commit
>> commit 9ffcdca1f504cb09088413c074b35af4b7f247e3
>> Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
>> Date&#8203;:   Mon Nov 12 23&#8203;:04&#8203;:16 2012 \-0800
>>
>> Don’t leak subs containing syntax errors
>
> Why are you always blaming me? :\-\)

&nbsp;  $ git show 6a8dbfd7
&nbsp;  commit 6a8dbfd7fdd5687ed748747ea8902c967c879870
&nbsp;  Author&#8203;: Nicholas Clark \<nick@&#8203;ccl4\.org>
&nbsp;  Date&#8203;:   Thu Sep 29 22&#8203;:44&#8203;:45 2011 \+0200

&nbsp;      Add Porting/bisect\.pl\, to automate bisecting a perl code test case\.

It's not me\! :\)

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri Mar 27 05&#8203;:06&#8203;:05 2015\, alh wrote&#8203;:
> bad \- non\-zero exit from \./perl \-Ilib /home/mhorsfall/test1\-min
> 9ffcdca1f504cb09088413c074b35af4b7f247e3 is the first bad commit
> commit 9ffcdca1f504cb09088413c074b35af4b7f247e3
> Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
> Date&#8203;:   Mon Nov 12 23&#8203;:04&#8203;:16 2012 \-0800
> 
> Don’t leak subs containing syntax errors

The attached prevents the crash\.

There maybe a deeper issue where PL\_compcv isn't being restored
correctly\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

<details><summary>0001-perl-124187-don-t-call-pad_findlex-on-a-NULL-CV.patch</summary>

```diff
From 2cb2d43c2aa5d6af0af9e32ae223501c7679fd74 Mon Sep 17 00:00:00 2001
From: Tony Cook <tony@develop-help.com>
Date: Wed, 22 Apr 2015 15:01:15 +1000
Subject: [PATCH] [perl #124187] don't call pad_findlex() on a NULL CV

---
 pad.c        |    4 ++++
 t/base/lex.t |    5 +++++
 2 files changed, 9 insertions(+)

diff --git a/pad.c b/pad.c
index 2d33779..984b5c1 100644
--- a/pad.c
+++ b/pad.c
@@ -959,6 +959,10 @@ Perl_pad_findmy_pvn(pTHX_ const char *namepv, STRLEN namelen, U32 flags)
 	Perl_croak(aTHX_ "panic: pad_findmy_pvn illegal flag bits 0x%" UVxf,
 		   (UV)flags);
 
+    /* compilation errors can zero PL_compcv */
+    if (!PL_compcv)
+        return NOT_IN_PAD;
+
     offset = pad_findlex(namepv, namelen, flags,
                 PL_compcv, PL_cop_seqmax, 1, NULL, &out_pn, &out_flags);
     if ((PADOFFSET)offset != NOT_IN_PAD) 
diff --git a/t/base/lex.t b/t/base/lex.t
index 0a07ab7..a34a508 100644
--- a/t/base/lex.t
+++ b/t/base/lex.t
@@ -506,3 +506,8 @@ eval q|s##[}#e|;
  eval q|my($_);0=split|;
  eval q|my $_; @x = split|;
 }
+
+{
+ # Used to crash [perl #124187]
+ eval q|qq{@{[{}}*sub{]]}}}=u|;
+}
-- 
1.7.10.4


```
</details>

**Comment by p5pRT** [comment]
### From @rjbs

On Tue Apr 21 22&#8203;:03&#8203;:33 2015\, tonyc wrote&#8203;:
> The attached prevents the crash\.
> 
> There maybe a deeper issue where PL\_compcv isn't being restored
> correctly\.

Are we \(read&#8203;: you\) comfortable with this patch as the way to sort this out?  Is your concern that this will paper over one symptom but leave a deeper problem still ready to spring\, or is that an unrelated observation?

\-\- 
rjbs

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon Apr 27 15&#8203;:21&#8203;:58 2015\, rjbs wrote&#8203;:
> On Tue Apr 21 22&#8203;:03&#8203;:33 2015\, tonyc wrote&#8203;:
> > The attached prevents the crash\.
> >
> > There maybe a deeper issue where PL\_compcv isn't being restored
> > correctly\.
> 
> Are we \(read&#8203;: you\) comfortable with this patch as the way to sort this
> out?  Is your concern that this will paper over one symptom but leave
> a deeper problem still ready to spring\, or is that an unrelated
> observation?

Yes\, that's my concern\.

I haven't worked with the parser enough to know whether PL\_compcv == NULL
is a normal case\.

Ticket 124385 seems related \- attemptting to do something with a NULL
PL\_compcv\, if that's a normal case then that code will need a similar fix\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon Apr 27 18&#8203;:03&#8203;:33 2015\, tonyc wrote&#8203;:
> On Mon Apr 27 15&#8203;:21&#8203;:58 2015\, rjbs wrote&#8203;:
> > On Tue Apr 21 22&#8203;:03&#8203;:33 2015\, tonyc wrote&#8203;:
> > > The attached prevents the crash\.
> > >
> > > There maybe a deeper issue where PL\_compcv isn't being restored
> > > correctly\.
> > 
> > Are we \(read&#8203;: you\) comfortable with this patch as the way to sort this
> > out?  Is your concern that this will paper over one symptom but leave
> > a deeper problem still ready to spring\, or is that an unrelated
> > observation?
> 
> Yes\, that's my concern\.
> 
> I haven't worked with the parser enough to know whether PL\_compcv == NULL
> is a normal case\.

These also crash in S\_pad\_findlex\(\)\, with different backtraces&#8203;:

qq\{@&#8203;\{\[\{\}\}\*sub\{\]\]\}\}\}=\<$foo>

qq\{@&#8203;\{\[\{\}\}\*sub\{\]\]\}\}\}; foo\(\)

In all three cases\, PP\_compcv == PL\_main\_cv and there's no sensible value to 
replace into PL\_compcv\.

I tried changing the code from 9ffcdca1 to leave PL\_compcv if it's PL\_main\_cv\,
but that resulted in later assertion failures\.

I've pushed my original patch from above to blead\, since no\-one has objected
to it\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, May 04\, 2015 at 11&#8203;:51&#8203;:56PM \-0700\, Tony Cook via RT wrote&#8203;:
> On Mon Apr 27 18&#8203;:03&#8203;:33 2015\, tonyc wrote&#8203;:
> > On Mon Apr 27 15&#8203;:21&#8203;:58 2015\, rjbs wrote&#8203;:
> > > On Tue Apr 21 22&#8203;:03&#8203;:33 2015\, tonyc wrote&#8203;:
> > > > The attached prevents the crash\.
> > > >
> > > > There maybe a deeper issue where PL\_compcv isn't being restored
> > > > correctly\.
> > > 
> > > Are we \(read&#8203;: you\) comfortable with this patch as the way to sort this
> > > out?  Is your concern that this will paper over one symptom but leave
> > > a deeper problem still ready to spring\, or is that an unrelated
> > > observation?
> > 
> > Yes\, that's my concern\.
> > 
> > I haven't worked with the parser enough to know whether PL\_compcv == NULL
> > is a normal case\.
> 
> These also crash in S\_pad\_findlex\(\)\, with different backtraces&#8203;:
> 
> qq\{@&#8203;\{\[\{\}\}\*sub\{\]\]\}\}\}=\<$foo>
> 
> qq\{@&#8203;\{\[\{\}\}\*sub\{\]\]\}\}\}; foo\(\)
> 
> In all three cases\, PP\_compcv == PL\_main\_cv and there's no sensible value to 
> replace into PL\_compcv\.
> 
> I tried changing the code from 9ffcdca1 to leave PL\_compcv if it's PL\_main\_cv\,
> but that resulted in later assertion failures\.
> 
> I've pushed my original patch from above to blead\, since no\-one has objected
> to it\.

I think my description in de0885da32 covers all these&#8203;:

commit de0885da327045eed274d7f8913a58e6de0e0f30
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Tue May 5 10&#8203;:44&#8203;:16 2015 \+0100
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Tue May 5 11&#8203;:23&#8203;:36 2015 \+0100

&nbsp;    null ptr deref in Perl\_cv\_forget\_slab
&nbsp;    
&nbsp;    RT \#124385
&nbsp;    
&nbsp;    Parsing following a syntax error could result in a null ptr dereference\.
&nbsp;    
&nbsp;    This commit contains a band\-aid that returns from Perl\_cv\_forget\_slab\(\) if
&nbsp;    the cv arg is null; but the real issue is much deeper and needs a more
&nbsp;    general fix at some point\.
&nbsp;    
&nbsp;    Basically\, both the lexer and the parser use the save stack\, and after an
&nbsp;    error\, they can get out of sync\.
&nbsp;    
&nbsp;    In particular&#8203;:
&nbsp;    
&nbsp;    1\) when handling a double\-quoted string\, the lexer does an ENTER\, saves
&nbsp;    most of its current state on the save stack\, then uses the literal string
&nbsp;    as the toke source\. When it reaches the end of the string\, it LEAVEs\,
&nbsp;    restores the lexer state and continues with the main source\.
&nbsp;    
&nbsp;    2\) Whenever the parser starts a new block or sub scope\, it remembers the
&nbsp;    current save stack position\, and at end of scope\, pops the save stack back
&nbsp;    to that position\.
&nbsp;    
&nbsp;    In something like
&nbsp;    
&nbsp;        "@&#8203;\{ sub \{\]\}\}  \}\}\}"
&nbsp;    
&nbsp;    the lexer sees a double\-quoted string\, and saves the current lex state\.
&nbsp;    The parser sees the start of a sub\, and saves PL\_compcv etc\. Then a parse
&nbsp;    error occurs\. The parser goes into error recovery\, discarding tokens until
&nbsp;    it can return to a sane state\. The lexer runs out of tokens when toking
&nbsp;    the string\, does a LEAVE\, and switches back to toking the main source\.
&nbsp;    This LEAVE restores both the lexer's and the parser's state; in particular
&nbsp;    the parser gets its old PL\_compcv restored\, even though the parser hasn't
&nbsp;    finished compiling the current sub\. Later\, series of '\}' tokens coming
&nbsp;    through allows the parser to finish the sub\. Since PL\_error\_count > 0\, it
&nbsp;    discards the just\-compiled sub and sets PL\_compcv to null\. Normally the
&nbsp;    LEAVE\_SCOPE done just after this would restore PL\_compcv to its old value
&nbsp;    \(e\.g\. PL\_main\_cv\) but the stack has already been popped\, so PL\_compcv gets
&nbsp;    left null\, and SEGVs occur\.
&nbsp;    
&nbsp;    The two main ways I can think of fixing this in the long term are
&nbsp;    1\) avoid the lexer using the save stack for long\-term state storage;
&nbsp;    in particular\, make S\_sublex\_push\(\) malloc a new parser object rather
&nbsp;    than saving the current lexer state on the save stack\.
&nbsp;    2\) At the end of a sublex\, if PL\_error\_count > 0\, don't try to restore
&nbsp;    state and continue\, instead just croak\.
&nbsp;    
&nbsp;    N\.B\. the test that this commit adds to lex\.t doesn't actually trigger the
&nbsp;    SEGV\, since the bad code is wrapped in an eval which \(for reasons I
&nbsp;    haven't researched\) avoids the SEGV\.


\-\- 
This is a great day for France\!
&nbsp;    \-\- Nixon at Charles De Gaulle's funeral
