### ISSUE TITLE
when(scalar){} -> S_looks_like_bool: Assertion `o' failed.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10287]
Migrated from [rt.perl.org#74114](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=74114) (status was 'resolved')

Searchable as RT74114$

**Comment by p5pRT** [comment]
### From frank.wiegand@gmail.com

This is a bug report for perl from frank\.wiegand@&#8203;gmail\.com\,
generated with the help of perlbug 1\.39 running under perl 5\.12\.0\.




---
&nbsp;  % perl\-5\.10\.1 \-E 'when\(scalar\)\{\}'
&nbsp;  Not enough arguments for scalar at \-e line 1\, near "scalar\)"
&nbsp;  Execution of \-e aborted due to compilation errors\.

&nbsp;  % perl\-5\.12\.0\-RC3 \-E 'when\(scalar\)\{\}'
&nbsp;  perl\-5\.12\.0\-RC3&#8203;: op\.c&#8203;:5272&#8203;: S\_looks\_like\_bool&#8203;: Assertion \`o' failed\.
&nbsp;  Aborted

This regression has been introduced by the following commit \(as git
bisect says\)&#8203;:

5341b2b7ab11bc31f63ac7a675e74106418d0661 is the first bad commit
commit 5341b2b7ab11bc31f63ac7a675e74106418d0661
Author&#8203;: Josh ben Jore \<jjore@&#8203;cpan\.org>
Date&#8203;:   Wed Sep 23 15&#8203;:35&#8203;:14 2009 \-0700

&nbsp;    Fix when\( scalar \.\.\. \) bug

&nbsp;    looks\_like\_bool should look past scalar\(\)\. Prior to this fix\, saying
&nbsp;    scalar\(\) caused the when\(\) argument to be /not/ a boolean even if it
&nbsp;    reasonably was\. Perhaps something like&#8203;: when\( scalar /$re/ \)\. I don't
&nbsp;    know any natural way someone is doing to use when\(scalar \.\.\.\) but it
&nbsp;    certainly seems like it was mistakenly left out\.

:100644 100644 729c25f0aa87bcd25f8606bd70d852c6c67e1967 c3736fac0b76b2e4beaf755d5a628d4d71e129d3 M      op\.c
:040000 040000 afe81091570f36d8e50f3513ec91f3f0f27b55f4 03acff2025d490e42f74d28599f1df3994becef1 M      t


Thanks\, Frank



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl 5\.12\.0&#8203;:

Configured by fw at Sat Apr  3 09&#8203;:18&#8203;:00 CEST 2010\.

Summary of my perl5 \(revision 5 version 12 subversion 0\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.32\-trunk\-amd64\, archname=x86\_64\-linux
&nbsp;    uname='linux hal2 2\.6\.32\-trunk\-amd64 \#1 smp sun jan 10 22&#8203;:40&#8203;:40 utc 2010 x86\_64 gnulinux '
&nbsp;    config\_args='\-de \-Dusedevel \-DDEBUGGING=both \-Doptimize=\-g \-Dcc=ccache gcc \-Dld=gcc \-Dprefix=/opt/perl/perl\-5\.12\.0\-RC3/ \-Dmad'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache gcc'\, ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.4\.3 20100108 \(prerelease\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=/lib/libc\-2\.10\.2\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.10\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    RC3



---
@&#8203;INC for perl 5\.12\.0&#8203;:
&nbsp;    /opt/perl/perl\-5\.12\.0\-RC3/lib/site\_perl/5\.12\.0/x86\_64\-linux
&nbsp;    /opt/perl/perl\-5\.12\.0\-RC3/lib/site\_perl/5\.12\.0
&nbsp;    /opt/perl/perl\-5\.12\.0\-RC3/lib/5\.12\.0/x86\_64\-linux
&nbsp;    /opt/perl/perl\-5\.12\.0\-RC3/lib/5\.12\.0
&nbsp;    \.



---
Environment for perl 5\.12\.0&#8203;:
&nbsp;    HOME=/home/fw
&nbsp;    LANG=de\_DE\.UTF\-8
&nbsp;    LANGUAGE=
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/sbin&#8203;:/usr/sbin&#8203;:/home/fw/bin&#8203;:/home/fw/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/games
&nbsp;    PERL\_AUTOINSTALL=\-\-defaultdeps
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    PERL\_EXTUTILS\_AUTOINSTALL=\-\-defaultdeps
&nbsp;    PERL\_MM\_USE\_DEFAULT=1
&nbsp;    SHELL=/bin/zsh

**Comment by p5pRT** [comment]
### From @rgarcia

On 7 April 2010 13&#8203;:36\, Frank Wiegand \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
>  % perl\-5\.10\.1 \-E 'when\(scalar\)\{\}'
>  Not enough arguments for scalar at \-e line 1\, near "scalar\)"
>  Execution of \-e aborted due to compilation errors\.
>
>  % perl\-5\.12\.0\-RC3 \-E 'when\(scalar\)\{\}'
>  perl\-5\.12\.0\-RC3&#8203;: op\.c&#8203;:5272&#8203;: S\_looks\_like\_bool&#8203;: Assertion \`o' failed\.
>  Aborted

Thanks for the report and the bisect \!

Here's a patch that makes it report a syntax error instead\. I'll apply
to maint 5\.12 when opened\.

<details><summary>Inline Patch</summary>

```diff
diff --git a/op.c b/op.c
index 9c94cc8..76eb16f 100644
--- a/op.c
+++ b/op.c
@@ -5282,14 +5282,11 @@ S_looks_like_bool(pTHX_ const OP *o)
             && looks_like_bool(cLOGOPo->op_first->op_sibling));

        case OP_NULL:
+       case OP_SCALAR:
            return (
                o->op_flags & OPf_KIDS
            && looks_like_bool(cUNOPo->op_first));

-        case OP_SCALAR:
-            return looks_like_bool(cUNOPo->op_first);
-
-
        case OP_ENTERSUB:

        case OP_NOT:    case OP_XOR:
```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @obra

On Fri Apr 09 03&#8203;:25&#8203;:49 2010\, rgs@&#8203;consttype\.org wrote&#8203;:
> On 7 April 2010 13&#8203;:36\, Frank Wiegand \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> >  % perl\-5\.10\.1 \-E 'when\(scalar\)\{\}'
> >  Not enough arguments for scalar at \-e line 1\, near "scalar\)"
> >  Execution of \-e aborted due to compilation errors\.
> >
> >  % perl\-5\.12\.0\-RC3 \-E 'when\(scalar\)\{\}'
> >  perl\-5\.12\.0\-RC3&#8203;: op\.c&#8203;:5272&#8203;: S\_looks\_like\_bool&#8203;: Assertion \`o' failed\.
> >  Aborted
> 
> Thanks for the report and the bisect \!
> 
> Here's a patch that makes it report a syntax error instead\. I'll apply
> to maint 5\.12 when opened\.
> 

rgs \- wanna cherrypick this to maint?

> diff \-\-git a/op\.c b/op\.c
> index 9c94cc8\.\.76eb16f 100644
> \-\-\- a/op\.c
> \+\+\+ b/op\.c
> @&#8203;@&#8203; \-5282\,14 \+5282\,11 @&#8203;@&#8203; S\_looks\_like\_bool\(pTHX\_ const OP \*o\)
>              && looks\_like\_bool\(cLOGOPo\->op\_first\->op\_sibling\)\);
> 
>         case OP\_NULL&#8203;:
> \+       case OP\_SCALAR&#8203;:
>             return \(
>                 o\->op\_flags & OPf\_KIDS
>             && looks\_like\_bool\(cUNOPo\->op\_first\)\);
> 
> \-        case OP\_SCALAR&#8203;:
> \-            return looks\_like\_bool\(cUNOPo\->op\_first\);
> \-
> \-
>         case OP\_ENTERSUB&#8203;:
> 
>         case OP\_NOT&#8203;:    case OP\_XOR&#8203;:
>

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
