### ISSUE TITLE
Bleadperl v5.19.6-86-g9ffd39a breaks CORION/Test-Without-Module-0.17.tar.gz

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13450]
Migrated from [rt.perl.org#120657](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=120657) (status was 'resolved')

Searchable as RT120657$

**Comment by p5pRT** [comment]
### From @andk

git bisect


---
commit 9ffd39ab75dd662df22fcdafbf7f740838acc898
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Wed Nov 13 18&#8203;:10&#8203;:49 2013 \-0800

&nbsp;    Allow PADTMPs’ strings to be swiped

diagnostics


---
http&#8203;://www\.cpantesters\.org/cpan/report/9c53e8d8\-5a1e\-11e3\-8268\-4c069e5baa37

perl \-V


---
Summary of my perl5 \(revision 5 version 19 subversion 7\) configuration&#8203;:             
&nbsp;  Commit id&#8203;: 9ffd39ab75dd662df22fcdafbf7f740838acc898
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.10\-3\-amd64\, archname=x86\_64\-linux\-thread\-multi\-ld
&nbsp;    uname='linux k83 3\.10\-3\-amd64 \#1 smp debian 3\.10\.11\-1 \(2013\-09\-10\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dprefix=/home/sand/src/perl/repoperls/installed\-perls/perl/v5\.19\.6\-86\-g9ffd39a/a2da \-Dmyhostname=k83 \-Dinstallusrbinperl=n \-Uversiononly \-Dusedevel \-des \-Ui\_db \-Duseithreads \-Duselongdouble \-DDEBUGGING=\-g'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.8\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.17'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib \-fstack\-protector'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES MULTIPLICITY PERLIO\_LAYERS
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD
&nbsp;                        PERL\_IMPLICIT\_CONTEXT PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_NEW\_COPY\_ON\_WRITE PERL\_PRESERVE\_IVUV
&nbsp;                        PERL\_USE\_DEVEL USE\_64\_BIT\_ALL USE\_64\_BIT\_INT
&nbsp;                        USE\_ITHREADS USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LONG\_DOUBLE USE\_PERLIO
&nbsp;                        USE\_PERL\_ATOF USE\_REENTRANT\_API
&nbsp;  Built under linux
&nbsp;  Compiled at Dec  2 2013 08&#8203;:32&#8203;:39
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /home/sand/src/perl/repoperls/installed\-perls/perl/v5\.19\.6\-86\-g9ffd39a/a2da/lib/site\_perl/5\.19\.7/x86\_64\-linux\-thread\-multi\-ld
&nbsp;    /home/sand/src/perl/repoperls/installed\-perls/perl/v5\.19\.6\-86\-g9ffd39a/a2da/lib/site\_perl/5\.19\.7
&nbsp;    /home/sand/src/perl/repoperls/installed\-perls/perl/v5\.19\.6\-86\-g9ffd39a/a2da/lib/5\.19\.7/x86\_64\-linux\-thread\-multi\-ld
&nbsp;    /home/sand/src/perl/repoperls/installed\-perls/perl/v5\.19\.6\-86\-g9ffd39a/a2da/lib/5\.19\.7
&nbsp;    \.

\-\- 
andreas

**Comment by p5pRT** [comment]
### From @rurban

#### Created by @rurban


ether came up on irc with this panic&#8203;: http&#8203;://paste\.scsys\.co\.uk/289079
cpanm Test&#8203;::Without&#8203;::Module with latest blead\.

t/03\-block\-require\-module\.t \.\.\.\.\.\.\. ok

\#   Failed test 'unimport'
\#   at t/04\-import\-export\.t line 11\.
\#          got&#8203;: 'panic&#8203;: attempt to copy freed scalar 100a1b7a0 to 1009af7f8
\# at
\# /Users/ether/\.cpanm/work/1388689737\.38632/Test\-Without\-Module\-0\.17/blib/lib/Test/Without/Module\.pm
\# /line 32\.
\# Compilation failed in require at
\# /Users/ether/\.perlbrew/libs/19\.7@&#8203;std/lib/perl5/File/Temp\.pm line 12\.
\# BEGIN failed\-\-compilation aborted at
\# /Users/ether/\.perlbrew/libs/19\.7@&#8203;std/lib/perl5/File/Temp\.pm line 12\.
\# Compilation failed in require at t/04\-import\-export\.t line 10\.
\# '
\#     expected&#8203;: ''
\# Looks like you failed 1 test of 3\.
t/04\-import\-export\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\. 

I copuld reproduce it by using 
&nbsp;  gdb \-\-args perl5\.19\.8d\-nt@&#8203;91fc0422 \-Iblib/arch \-Iblib/lib t/04\-import\-export\.t
but not with \-Mblib&#8203;:

Breakpoint 2\, Perl\_sv\_setsv\_flags \(dstr=0xbc8200\, sstr=0xbefdb8\, flags=1538\)
at sv\.c&#8203;:4069
4069        Perl\_croak\(aTHX\_ "panic&#8203;: attempt to copy freed scalar %p to %p"\,
\(gdb\) bt
\#0  Perl\_sv\_setsv\_flags \(dstr=0xbc8200\, sstr=0xbefdb8\, flags=1538\) at sv\.c&#8203;:4069
\#1  0x000000000058324e in Perl\_pp\_aassign \(\) at pp\_hot\.c&#8203;:1168
\#2  0x00000000005312d3 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2308
\#3  0x0000000000458eba in Perl\_call\_sv \(sv=0xb570a0\, flags=3\) at perl\.c&#8203;:2733
\#4  0x000000000063da7c in Perl\_pp\_require \(\) at pp\_ctl\.c&#8203;:3851
\#5  0x00000000005312d3 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2308
\#6  0x00000000004590ac in Perl\_call\_sv \(sv=0xbef638\, flags=13\) at perl\.c&#8203;:2748
\#7  0x0000000000462c25 in Perl\_call\_list \(oldscope=6\, paramList=0xc43110\) at perl\.c&#8203;:4844
\#8  0x000000000043c65d in S\_process\_special\_blocks \(floor=92\, fullname=0xa15680 "BEGIN"\, gv=0xc43068\, cv=0xbef638\)
&nbsp;    at op\.c&#8203;:7993
\#9  0x000000000043c1cc in Perl\_newATTRSUB\_x \(floor=92\, o=0xa12c98\, proto=0x0\, attrs=0x0\, block=0xa12cd8\, o\_is\_gv=false\)
&nbsp;    at op\.c&#8203;:7955
\#10 0x000000000042dd09 in Perl\_utilize \(aver=1\, floor=92\, version=0xc49408\, idop=0xc49448\, arg=0x0\) at op\.c&#8203;:5365
\#11 0x00000000004c601b in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:398
\#12 0x000000000063aa4b in S\_doeval \(gimme=2\, outside=0x0\, seq=1401\, hh=0x0\) at pp\_ctl\.c&#8203;:3473
\#13 0x0000000000640e43 in Perl\_pp\_require \(\) at pp\_ctl\.c&#8203;:4123
\#14 0x00000000005312d3 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2308
\#15 0x0000000000457c84 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2428
\#16 0x00000000004572b0 in perl\_run \(my\_perl=0x9f1010\) at perl\.c&#8203;:2349
\#17 0x000000000041cf32 in main \(argc=4\, argv=0x7fffffffe648\, env=0x7fffffffe670\) at perlmain\.c&#8203;:112
\(gdb\) p \*sstr
$1 = \{sv\_any = 0xbefdd0\, sv\_refcnt = 0\, sv\_flags = 255\, sv\_u = \{svu\_pv =
0xc6ffe0 "File/Spec/Unix\.pm"\, 
&nbsp;    svu\_iv = 13041632\, svu\_uv = 13041632\, svu\_rv = 0xc6ffe0\, svu\_rx =
0xc6ffe0\, svu\_array = 0xc6ffe0\, 
&nbsp;    svu\_hash = 0xc6ffe0\, svu\_gp = 0xc6ffe0\, svu\_fp = 0xc6ffe0\}\}
\(gdb\) up
\#1  0x000000000058324e in Perl\_pp\_aassign \(\) at pp\_hot\.c&#8203;:1168
1168            sv\_setsv\(sv\, \*relem\);
\(gdb\) p \*\*relem
$5 = \{sv\_any = 0xbefdd0\, sv\_refcnt = 0\, sv\_flags = 255\, sv\_u = \{svu\_pv =
0xc6ffe0 "File/Spec/Unix\.pm"\, 
&nbsp;    svu\_iv = 13041632\, svu\_uv = 13041632\, svu\_rv = 0xc6ffe0\, svu\_rx =
0xc6ffe0\, svu\_array = 0xc6ffe0\, 
&nbsp;    svu\_hash = 0xc6ffe0\, svu\_gp = 0xc6ffe0\, svu\_fp = 0xc6ffe0\}\}

Haven't checked further\. Test&#8203;::Without&#8203;::Module is 
pure\-perl so it's a core refcnt bug\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.19.8:

Configured by rurban at Sun Dec 29 20:47:22 CST 2013.

Summary of my perl5 (revision 5 version 19 subversion 8) configuration:
  Commit id: 91fc0422e3a3e3aa6b0c35bb1d4d18d03fd35f30
  Platform:
    osname=linux, osvers=3.11-2-amd64, archname=x86_64-linux-debug@91fc0422
    uname='linux reini 3.11-2-amd64 #1 smp debian 3.11.10-1 (2013-12-04) x86_64 gnulinux '
    config_args='-de -Dusedevel -Uversiononly -Dinstallman1dir=none -Dinstallman3dir=none -Dinstallsiteman1dir=none -Dinstallsiteman3dir=none -DEBUGGING -Doptimize='-g3' -Uuseithreads -Accflags=''-msse4.2'' -Accflags=''-march=corei7'' -Dcf_email=''rurban@cpanel.net'' -Dperladmin=''rurban@cpanel.net'''
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-msse4.2 -march=corei7 -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-g3',
    cppflags='-msse4.2 -march=corei7 -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.7.3', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.17'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -g3 -L/usr/local/lib -fstack-protector'



@INC for perl 5.19.8:
    /usr/local/lib/perl5/site_perl/5.19.8/x86_64-linux-debug@91fc0422
    /usr/local/lib/perl5/site_perl/5.19.8
    /usr/local/lib/perl5/5.19.8/x86_64-linux-debug@91fc0422
    /usr/local/lib/perl5/5.19.8
    /usr/local/lib/perl5/site_perl/5.19.7
    /usr/local/lib/perl5/site_perl/5.19.6
    /usr/local/lib/perl5/site_perl/5.19.5
    /usr/local/lib/perl5/site_perl/5.19.4
    /usr/local/lib/perl5/site_perl/5.19.3
    /usr/local/lib/perl5/site_perl/5.19.2
    /usr/local/lib/perl5/site_perl/5.18.2
    /usr/local/lib/perl5/site_perl/5.18.1
    /usr/local/lib/perl5/site_perl/5.18.0
    /usr/local/lib/perl5/site_perl/5.17.11
    /usr/local/lib/perl5/site_perl/5.17.10
    /usr/local/lib/perl5/site_perl/5.17.8
    /usr/local/lib/perl5/site_perl/5.17.7
    /usr/local/lib/perl5/site_perl/5.17.6
    /usr/local/lib/perl5/site_perl/5.17.5
    /usr/local/lib/perl5/site_perl/5.17.4
    /usr/local/lib/perl5/site_perl/5.17.3
    /usr/local/lib/perl5/site_perl/5.17.2
    /usr/local/lib/perl5/site_perl/5.17.1
    /usr/local/lib/perl5/site_perl/5.17.0
    /usr/local/lib/perl5/site_perl/5.17
    /usr/local/lib/perl5/site_perl/5.16.3
    /usr/local/lib/perl5/site_perl/5.16.2
    /usr/local/lib/perl5/site_perl/5.16.1
    /usr/local/lib/perl5/site_perl/5.16.0
    /usr/local/lib/perl5/site_perl/5.15.9
    /usr/local/lib/perl5/site_perl/5.15.8
    /usr/local/lib/perl5/site_perl/5.15.7
    /usr/local/lib/perl5/site_perl/5.15.6
    /usr/local/lib/perl5/site_perl/5.15.5
    /usr/local/lib/perl5/site_perl/5.15.4
    /usr/local/lib/perl5/site_perl/5.15.3
    /usr/local/lib/perl5/site_perl/5.15.2
    /usr/local/lib/perl5/site_perl/5.14.4
    /usr/local/lib/perl5/site_perl/5.14.3
    /usr/local/lib/perl5/site_perl/5.14.2
    /usr/local/lib/perl5/site_perl/5.14.1
    /usr/local/lib/perl5/site_perl/5.12.5
    /usr/local/lib/perl5/site_perl/5.12.4
    /usr/local/lib/perl5/site_perl/5.10.1
    /usr/local/lib/perl5/site_perl/5.8.9
    /usr/local/lib/perl5/site_perl/5.8.8
    /usr/local/lib/perl5/site_perl/5.8.7
    /usr/local/lib/perl5/site_perl/5.8.6
    /usr/local/lib/perl5/site_perl/5.8.5
    /usr/local/lib/perl5/site_perl/5.8.4
    /usr/local/lib/perl5/site_perl/5.8.3
    /usr/local/lib/perl5/site_perl/5.8.2
    /usr/local/lib/perl5/site_perl/5.8.1
    /usr/local/lib/perl5/site_perl/5.6.2
    /usr/local/lib/perl5/site_perl
    .


Environment for perl 5.19.8:
    HOME=/home/rurban
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/rurban/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @rurban

More context on the aassign&#8203;:

\(gdb\) p Perl\_op\_dump\(PL\_op\)
1   TYPE = aassign  ===> 2
&nbsp;    TARG = 5
&nbsp;    FLAGS = \(VOID\,KIDS\,STACKED\,SLABBED\)
&nbsp;    \{
3       TYPE = null  ===> \(4\)
&nbsp;          \(was list\)
&nbsp;        FLAGS = \(LIST\,KIDS\,SLABBED\)
&nbsp;        \{
5           TYPE = padrange  ===> 1
&nbsp;            TARG = 1
&nbsp;            FLAGS = \(LIST\,SPECIAL\,SLABBED\)
&nbsp;            PRIVATE = \(COUNT=3\)
&nbsp;        \}
&nbsp;        \{
6           TYPE = rv2av  ===> 3
&nbsp;            TARG = 4
&nbsp;            FLAGS = \(LIST\,KIDS\,SLABBED\)
&nbsp;            PRIVATE = \(STRICT\_REFS\)
&nbsp;            \{
7               TYPE = gv  ===> 6
&nbsp;                FLAGS = \(SCALAR\,SLABBED\)
&nbsp;                GV = main&#8203;::\_
&nbsp;            \}
&nbsp;        \}
&nbsp;    \}

> Breakpoint 2\, Perl\_sv\_setsv\_flags \(dstr=0xbc8200\, sstr=0xbefdb8\,
> flags=1538\)
> at sv\.c&#8203;:4069
> 4069            Perl\_croak\(aTHX\_ "panic&#8203;: attempt to copy freed scalar
> %p to %p"\,
> \(gdb\) bt
> \#0  Perl\_sv\_setsv\_flags \(dstr=0xbc8200\, sstr=0xbefdb8\, flags=1538\) at
> sv\.c&#8203;:4069
> \#1  0x000000000058324e in Perl\_pp\_aassign \(\) at pp\_hot\.c&#8203;:1168
> \#2  0x00000000005312d3 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2308
> \#3  0x0000000000458eba in Perl\_call\_sv \(sv=0xb570a0\, flags=3\) at
> perl\.c&#8203;:2733
> \#4  0x000000000063da7c in Perl\_pp\_require \(\) at pp\_ctl\.c&#8203;:3851
> \#5  0x00000000005312d3 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2308

\-\- 
Reini Urban

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @rurban

I found a cop in PL\_op\->op\_next&#8203;:
Test&#8203;::Without&#8203;::Module\, line 35

which is 
&nbsp;  my $forbidden = get\_forbidden\_list
in the function fake\_module\.

%forbidden is initialized with&#8203;:
&nbsp;  $forbidden\->\{$\_\} = $INC\{ module2file\($\_\) \};
and later the entry was deleted in scrub&#8203;:
&nbsp;  delete $INC\{$key\}

So we get a deleted HEK returned as result\.

**Comment by p5pRT** [comment]
### From @wolfsage

A bisect between 5\.19\.6 and 5\.19\.7 came up with this&#8203;:

panic&#8203;: attempt to copy freed scalar 9f82d78 to 9f74938 at
/home/mhorsfall/Test/Without/Module\.pm line 32\.
Compilation failed in require at lib/File/Temp\.pm line 12\.
BEGIN failed\-\-compilation aborted at lib/File/Temp\.pm line 12\.
Compilation failed in require at /home/mhorsfall/wtf\.pl line 9\.
HEAD is now at 9ffd39a Allow PADTMPsâ strings to be swiped
bad \- non\-zero exit from \./perl \-Ilib /home/mhorsfall/wtf\.pl
9ffd39ab75dd662df22fcdafbf7f740838acc898 is the first bad commit
commit 9ffd39ab75dd662df22fcdafbf7f740838acc898
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Wed Nov 13 18&#8203;:10&#8203;:49 2013 \-0800

&nbsp;    Allow PADTMPsâ strings to be swiped

&nbsp;    While copy\-on\-write does speed things up\, it is not perfect\.  Take
&nbsp;    this snippet for example&#8203;:

&nbsp;    $a = "$b$c";
&nbsp;    $a \.= $d;

&nbsp;    The concatenation operator on the rhs of the first line has its own
&nbsp;    scalar that it reuses every time that operator is called \(its target\)\.
&nbsp;    When the assignment happens\, $a and that target share the same string
&nbsp;    buffer\, which is good\, because we didnât have to copy it\.  But because
&nbsp;    it is shared between two scalars\, the concatenation on the second line
&nbsp;    forces it to be copied\.

&nbsp;    While copy\-on\-write may be fast\, string swiping surpasses it\, because
&nbsp;    it has no later bookkeeping overhead\.  If we allow stealing targetsâ
&nbsp;    strings\, then $a = "$b$c" no longer causes $a to share the same string
&nbsp;    buffer as the target; rather\, $a steals that buffer and leaves the tar\-
&nbsp;    get undefined\.  The result is that neither â$a =â nor â$a \.=
$dâ needs
&nbsp;    to copy any strings\.  Only the "$b$c" will copy strings \(unavoidably\)\.

&nbsp;    This commit only applies that to long strings\, however\.  This is why&#8203;:

&nbsp;    Simply swiping the string from any swipable TARG \(which I tried at
&nbsp;    first\) resulted in a significant slowdown\.  By swiping the string from
&nbsp;    a TARG that is going to be reused \(as opposed to a TEMP about to be
&nbsp;    freed\, which is where swipe was already happening\)\, we force it to
&nbsp;    allocate another string next time\, greatly increasing the number
&nbsp;    of malloc calls\.  malloc overhead exceeds the overhead of copying
&nbsp;    short strings\.

&nbsp;    I tried swiping TARGs for short strings only when the buffer on the
&nbsp;    lhs was not big enough for a copy \(or there wasnât one\)\, but simple
&nbsp;    benchmarks with mktables show that even checking SvLEN\(dstr\) is enough
&nbsp;    to slow things down\, since the speed\-up this provides is minimal where
&nbsp;    short strings are involved\.

&nbsp;    Then I tried checking just the string length\, and saw a consistent
&nbsp;    speed increase\.  So thatâs what this patch uses\.  Programs using short
&nbsp;    strings will not benefit\.  Programs using long strings may see a 1\.5%
&nbsp;    increase in speed\, due to fewer string copies\.

:040000 040000 d901a3242ad3f62ef63cf94f62a4308c18784447
b1d599d89e39cf22e599da36bc5cbee4605c4902 M      ext
:100644 100644 7d38bb22c18a25186322fde78ef2a3e0a62fc7c8
c06e796db38e069880752196070fe923b3f6064a M      pp\_ctl\.c
:100644 100644 b87311030bb677a39b1b2dca73bd576557da626a
4c3fdbb6ceac45e30df2f9c8c1ca850162783cd6 M      sv\.c
bisect run success
That took 2071 seconds

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
### From @wolfsage

Hrm\, missed p5p in this\.\.\.

\-\-\-\-\-\-\-\-\-\- Forwarded message \-\-\-\-\-\-\-\-\-\-
From&#8203;: Matthew Horsfall \(alh\) \<wolfsage@&#8203;gmail\.com>
Date&#8203;: Thu\, Jan 2\, 2014 at 4&#8203;:48 PM
Subject&#8203;: Re&#8203;: \[perl \#120917\] refcnt=0 in aassign relem with
Test&#8203;::Without&#8203;::Module\->unimport
To&#8203;: perlbug\-followup@&#8203;perl\.org


A bisect between 5\.19\.6 and 5\.19\.7 came up with this&#8203;:

panic&#8203;: attempt to copy freed scalar 9f82d78 to 9f74938 at
/home/mhorsfall/Test/Without/Module\.pm line 32\.
Compilation failed in require at lib/File/Temp\.pm line 12\.
BEGIN failed\-\-compilation aborted at lib/File/Temp\.pm line 12\.
Compilation failed in require at /home/mhorsfall/wtf\.pl line 9\.
HEAD is now at 9ffd39a Allow PADTMPsâ€™ strings to be swiped
bad \- non\-zero exit from \./perl \-Ilib /home/mhorsfall/wtf\.pl
9ffd39ab75dd662df22fcdafbf7f740838acc898 is the first bad commit
commit 9ffd39ab75dd662df22fcdafbf7f740838acc898
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Wed Nov 13 18&#8203;:10&#8203;:49 2013 \-0800

&nbsp;    Allow PADTMPsâ€™ strings to be swiped

&nbsp;    While copy\-on\-write does speed things up\, it is not perfect\.  Take
&nbsp;    this snippet for example&#8203;:

&nbsp;    $a = "$b$c";
&nbsp;    $a \.= $d;

&nbsp;    The concatenation operator on the rhs of the first line has its own
&nbsp;    scalar that it reuses every time that operator is called \(its target\)\.
&nbsp;    When the assignment happens\, $a and that target share the same string
&nbsp;    buffer\, which is good\, because we didnâ€™t have to copy it\.  But because
&nbsp;    it is shared between two scalars\, the concatenation on the second line
&nbsp;    forces it to be copied\.

&nbsp;    While copy\-on\-write may be fast\, string swiping surpasses it\, because
&nbsp;    it has no later bookkeeping overhead\.  If we allow stealing targetsâ€™
&nbsp;    strings\, then $a = "$b$c" no longer causes $a to share the same string
&nbsp;    buffer as the target; rather\, $a steals that buffer and leaves the tar\-
&nbsp;    get undefined\.  The result is that neither â€˜$a =â€™ nor â€˜$a \.=
$dâ€™ needs
&nbsp;    to copy any strings\.  Only the "$b$c" will copy strings \(unavoidably\)\.

&nbsp;    This commit only applies that to long strings\, however\.  This is why&#8203;:

&nbsp;    Simply swiping the string from any swipable TARG \(which I tried at
&nbsp;    first\) resulted in a significant slowdown\.  By swiping the string from
&nbsp;    a TARG that is going to be reused \(as opposed to a TEMP about to be
&nbsp;    freed\, which is where swipe was already happening\)\, we force it to
&nbsp;    allocate another string next time\, greatly increasing the number
&nbsp;    of malloc calls\.  malloc overhead exceeds the overhead of copying
&nbsp;    short strings\.

&nbsp;    I tried swiping TARGs for short strings only when the buffer on the
&nbsp;    lhs was not big enough for a copy \(or there wasnâ€™t one\)\, but simple
&nbsp;    benchmarks with mktables show that even checking SvLEN\(dstr\) is enough
&nbsp;    to slow things down\, since the speed\-up this provides is minimal where
&nbsp;    short strings are involved\.

&nbsp;    Then I tried checking just the string length\, and saw a consistent
&nbsp;    speed increase\.  So thatâ€™s what this patch uses\.  Programs using short
&nbsp;    strings will not benefit\.  Programs using long strings may see a 1\.5%
&nbsp;    increase in speed\, due to fewer string copies\.

:040000 040000 d901a3242ad3f62ef63cf94f62a4308c18784447
b1d599d89e39cf22e599da36bc5cbee4605c4902 M      ext
:100644 100644 7d38bb22c18a25186322fde78ef2a3e0a62fc7c8
c06e796db38e069880752196070fe923b3f6064a M      pp\_ctl\.c
:100644 100644 b87311030bb677a39b1b2dca73bd576557da626a
4c3fdbb6ceac45e30df2f9c8c1ca850162783cd6 M      sv\.c
bisect run success
That took 2071 seconds

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
### From @andk

Maybe related to \#120657 ?
\-\- 
andreas

**Comment by p5pRT** [comment]
### From @wolfsage

On Thu Jan 02 21&#8203;:08&#8203;:25 2014\, andreas\.koenig\.7os6VVqR@&#8203;franz\.ak\.mind\.de wrote&#8203;:
> Maybe related to \#120657 ?

Ah\, so we did just miss it somehow\.

Thank you\, I've merged the two tickets\.

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

Fixed in 901ee10\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
