### ISSUE TITLE
class feature: Segfault during syntax check with class field attributes and undefined variable

### ISSUE THREAD

**Issue by kfly8** [Perl/perl5#23839]
Module: class feature

**Description**

Segmentation fault occurs when running syntax check (`perl -wc`) on a script that combines:
1. Experimental class feature with field attributes (`:reader` or `:writer`)
2. An undefined global variable (e.g., `@ARG`)

Expected behavior is a syntax error message, but instead Perl crashes with a segfault.

Note: The segfault only occurs when field attributes like `:reader` or `:writer` are present. Without these attributes, the expected syntax error is properly reported.

**Steps to Reproduce**

Create a file `a.pl` with the following content:

```perl
use strict;
use warnings;
use experimental qw(class);

print @ARG;

class MyClass {
  field $message :param :reader;
}
```

Then run:
perl -wc a.pl

**Expected behavior**

Should display a syntax error:
`Global symbol "@ARG" requires explicit package name at a.pl line 5.`
a.pl had compilation errors.

**Actual behavior**

Segmentation fault occurs instead of the syntax error message.

**Perl configuration**

```
Summary of my perl5 (revision 5 version 42 subversion 0) configuration:
   
  Platform:
    osname=darwin
    osvers=23.5.0
    archname=darwin-2level
    uname='darwin kfly8.local 23.5.0 darwin kernel version 23.5.0: wed may 1 20:14:38 pdt 2024; root:xnu-10063.121.3~5release_arm64_t6020 arm64 '
    config_args='-des -Dprefix=/Users/kfly8/.local/share/mise/installs/perl/5.42.0 -Dscriptdir=/Users/kfly8/.local/share/mise/installs/perl/5.42.0/bin -Dman1dir=none -Dman3dir=none'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -DNO_THREAD_SAFE_QUERYLOCALE -DNO_POSIX_2008_LOCALE -DHAS_BROKEN_LANGINFO_CODESET -fno-strict-aliasing -pipe -fstack-protector-strong'
    optimize='-O3'
    cppflags='-fno-common -DPERL_DARWIN -DNO_THREAD_SAFE_QUERYLOCALE -DNO_POSIX_2008_LOCALE -DHAS_BROKEN_LANGINFO_CODESET -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='Apple LLVM 16.0.0 (clang-1600.0.26.4)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=8
    longdblkind=0
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/lib /Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk/usr/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /usr/local/lib /usr/lib
    libs= 
    perllibs=
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under darwin
  Compiled at Jul  4 2025 18:48:07
  @INC:
    /Users/kfly8/.local/share/mise/installs/perl/5.42.0/lib/site_perl/5.42.0/darwin-2level
    /Users/kfly8/.local/share/mise/installs/perl/5.42.0/lib/site_perl/5.42.0
    /Users/kfly8/.local/share/mise/installs/perl/5.42.0/lib/5.42.0/darwin-2level
    /Users/kfly8/.local/share/mise/installs/perl/5.42.0/lib/5.42.0

```

**Comment by leonerd** [comment]
I'm afraid I'm unable to reproduce this currently.

```
$ git describe
v5.43.3-152-g6268355b50

$ cat > a.pl
use strict;
use warnings;
use experimental qw(class);

print @ARG;

class MyClass {
  field $message :param :reader;
}

$ ./perl -wc a.pl 
Global symbol "@ARG" requires explicit package name (did you forget to declare "my @ARG"?) at a.pl line 5.
a.pl had compilation errors.
```

**Comment by leonerd** [comment]
Ah - it's fixed in blead now but it did appear sometime in 5.42.x:

```
$ perl5.42.0 -wc a.pl 
Segmentation fault         perl5.42.0 -wc a.pl

$ perl5.43.2 -wc a.pl 
Global symbol "@ARG" requires explicit package name (did you forget to declare "my @ARG"?) at a.pl line 5.
a.pl had compilation errors.
```

Perhaps something for @jkeenan to have a go at bisecting down?

**Comment by mauke** [comment]
> Perhaps something for @jkeenan to have a go at bisecting down?

Or I can just do it myself:

```
$ ../perl5/Porting/bisect.pl --start v5.42.0 --expect-fail -e 'use strict; use experimental "class"; eval q{ $x; class C { field $f :reader } }'
…
HEAD is now at 4e22a3d0e5 class.c: gracefully handle reader/writer after 'strict' error
bad - zero exit from ./perl -Ilib -e use strict; use experimental "class"; eval q{ $x; class C { field $f :reader } }
4e22a3d0e5f933b38e3fa1b98c904fe224001b63 is the first bad commit
commit 4e22a3d0e5f933b38e3fa1b98c904fe224001b63
Author: Lukas Mai <lukasmai.403@gmail.com>
Date:   Wed Jul 30 23:09:54 2025 +0200

    class.c: gracefully handle reader/writer after 'strict' error
    
    Fixes #23511.

 MANIFEST          |  1 +
 class.c           |  6 ++++--
 t/class/gh23511.t | 23 +++++++++++++++++++++++
 3 files changed, 28 insertions(+), 2 deletions(-)
 create mode 100644 t/class/gh23511.t
bisect found first bad commit
That took 1663 seconds.
```

In other words, the issue was fixed by commit 4e22a3d0e5f933b38e3fa1b98c904fe224001b63 (unsurprisingly, in retrospect).

**Comment by kfly8** [comment]
Sorry for the duplication. Thanks for the quick action.
