### ISSUE TITLE
ppport.h doesn't work with threaded 5.6.x + PERL_NO_GET_CONTEXT

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7127]
Migrated from [rt.perl.org#27007](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=27007) (status was 'resolved')

Searchable as RT27007$

**Comment by p5pRT** [comment]
### From @steve-m-hay

#### Created by @steve-m-hay

This is a bug report for perl from steve\.hay@&#8203;uk\.radan\.com\,
generated with the help of perlbug 1\.34 running under perl v5\.8\.2\.


\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

If you create an XS module using ppport\.h generated by Perl 5\.8\.2 then 
it doesn't build
under a threaded Perl 5\.6\.x if the XS file says "\#define 
PERL\_NO\_GET\_CONTEXT"\.

To reproduce this\, type the following using Perl 5\.8\.2&#8203;:

&nbsp;    h2xs \-n Foo \-b 5\.6\.0

and then edit the Foo\.xs file to add

&nbsp;    \#define PERL\_NO\_GET\_CONTEXT

as the first line in the file\.

Now try to build that "Foo" module using a threaded Perl 5\.6\.1\.  On my 
WinXP/MSVC system
this produces the following errors&#8203;:

=====
ppport\.h\(633\) : error C2065&#8203;: 'my\_perl' : undeclared identifier
ppport\.h\(633\) : warning C4047&#8203;: 'function' : 'struct interpreter \*' 
differs in levels of indirection from 'int '
ppport\.h\(633\) : warning C4024&#8203;: 'Perl\_scan\_hex' : different types for 
formal and actual parameter 1
ppport\.h\(648\) : warning C4047&#8203;: 'function' : 'struct interpreter \*' 
differs in levels of indirection from 'int '
ppport\.h\(648\) : warning C4024&#8203;: 'Perl\_scan\_oct' : different types for 
formal and actual parameter 1
ppport\.h\(663\) : warning C4047&#8203;: 'function' : 'struct interpreter \*' 
differs in levels of indirection from 'int '
ppport\.h\(663\) : warning C4024&#8203;: 'Perl\_scan\_bin' : different types for 
formal and actual parameter 1
NMAKE : fatal error U1077&#8203;: 'cl' : return code '0x2'
Stop\.
=====

The errors go away if the PERL\_NO\_GET\_CONTEXT define is removed\, but the 
module should
be more efficient with it\, shouldn't it?

The Devel&#8203;::PPPort version in 5\.8\.2 is 2\.009\.  I've also tried version 
2\.011 from
the current maint\-5\.8\, with the same results\.

An earlier version of Devel&#8203;::PPPort \(2\.0002\, distributed with Perl 
5\.8\.0\) worked fine\.

<details><summary>Perl Info</summary>

```

Flags:
    category=library
    severity=medium

Site configuration information for perl v5.8.2:

Configured by steveh at Tue Nov 18 15:11:07 2003.

Summary of my perl5 (revision 5 version 8 subversion 2) configuration:
  Platform:
    osname=MSWin32, osvers=4.0, archname=MSWin32-x86-perlio
    uname=''
    config_args='undef'
    hint=recommended, useposix=true, d_sigaction=undef
    usethreads=undef use5005threads=undef useithreads=undef 
usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=undef usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=y, bincompat5005=undef
  Compiler:
    cc='cl', ccflags ='-nologo -Gf -W3 -MD -DNDEBUG -O1 -DWIN32 
-D_CONSOLE -DNO_STRICT -DHAVE_DES_FCRYPT  -DPERL_DEBUGGING_MSTATS 
-DUSE_PERLIO -DPERL_MSVCRT_READFIX',
    optimize='-MD -DNDEBUG -O1',
    cppflags='-DWIN32'
    ccversion='', gccversion='', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=undef, longlongsize=8, d_longdbl=define, longdblsize=10
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', 
lseeksize=4
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='link', ldflags ='-nologo -nodefaultlib -release  
-libpath:"C:\perl5\lib\CORE"  -machine:x86'
    libpth=C:\PROGRA~1\MICROS~2\VC98\lib
    libs=  oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  
comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  
netapi32.lib uuid.lib wsock32.lib mpr.lib winmm.lib  version.lib 
odbc32.lib odbccp32.lib msvcrt.lib
    perllibs=  oldnames.lib kernel32.lib user32.lib gdi32.lib 
winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib 
oleaut32.lib  netapi32.lib uuid.lib wsock32.lib mpr.lib winmm.lib  
version.lib odbc32.lib odbccp32.lib msvcrt.lib
    libc=msvcrt.lib, so=dll, useshrplib=yes, libperl=perl58.lib
    gnulibc_version='undef'
  Dynamic Linking:
    dlsrc=dl_win32.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags='-dll -nologo -nodefaultlib -release  
-libpath:"C:\perl5\lib\CORE"  -machine:x86'

Locally applied patches:
   


@INC for perl v5.8.2:
    C:/perl5/lib
    C:/perl5/site/lib
    .


Environment for perl v5.8.2:
    HOME (unset)
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    
PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\PROGRA~1\MICROS~2\Common\MSDev98\BIN;C:\PROGRA~1\MICROS~2\VC98\Bin;C:\PROGRA~1\MICROS~2\Common\Tools\WINNT;C:\PROGRA~1\MICROS~2\Common\Tools;U:\scripts\batch;C:\perl5\bin
    PERL5LIB (unset)
    PERL_BADLANG (unset)
    SHELL (unset)




------------------------------------------------
Radan Computational Ltd.

The information contained in this message and any files transmitted with it are confidential and intended for the addressee(s) only.  If you have received this message in error or there are any problems, please notify the sender immediately.  The unauthorized use, disclosure, copying or alteration of this message is strictly forbidden.  Note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of Radan Computational Ltd.  The recipient(s) of this message should check it and any attached files for viruses: Radan Computational will accept no liability for any damage caused by any virus transmitted by this email.


```
</details>

**Comment by p5pRT** [comment]
### From @mhx

On 2004\-02\-23\, at 19&#8203;:02&#8203;:17 \-0000\, Steve Hay \(via RT\) wrote&#8203;:

> If you create an XS module using ppport\.h generated by Perl 5\.8\.2 then 
> it doesn't build
> under a threaded Perl 5\.6\.x if the XS file says "\#define 
> PERL\_NO\_GET\_CONTEXT"\.

I know\. I'm working on getting a new\, fixed version of D&#8203;::PPP out\.
For now\, the easiest way to "fix" the ppport\.h file is to remove
all the grok\_\* functions if you don't need them\.

> The errors go away if the PERL\_NO\_GET\_CONTEXT define is removed\, but the 
> module should
> be more efficient with it\, shouldn't it?

Yes\.

> An earlier version of Devel&#8203;::PPPort \(2\.0002\, distributed with Perl 
> 5\.8\.0\) worked fine\.

Because it didn't have the grok\_\* functions added\.

Marcus

\-\- 
teamwork\, n\.&#8203;:
&nbsp;    Having someone to blame\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @mhx

Fixed with Devel&#8203;::PPPort 3\.00\.

**Comment by p5pRT** [comment]
@mhx - Status changed from 'open' to 'resolved'
