### ISSUE TITLE
d51aa1a build-time failure with clang++ and g++

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#23725]
In this [smoke-testing report](https://perl.develop-help.com/db/5519236) filed by @cjg-cguevara, we observe a build-time (`make`) failure when compiling with `clang++` version 19 on FreeBSD-14.3.

I have reproduced this failure on the FreeBSD machine from which I customarily generate smoke-test reports.  I rarely smoke-test clang++, so the point when this build failure started to occur was not immediately evident to me.

On this machine, the default `clang++` (`/usr/bin/clang++`) is version 18.  Configuring and building as follows:
```
sh ./Configure -des -Dusedevel -Dusethreads -Dcc=clang++ && make test_prep 2>&1
```
... I got plenty of this kind of warning in both `./Configure` and `make test_prep` ...
```
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
```
... but, then again, I've come to expect that with `c++`-equivalent compilers.  What I did *not* expect was for the build to fail here:
```
clang++ -c -DPERL_CORE -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DNO_POSIX_2008_LOCALE -I/usr/local/include -O2 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings pp.c
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
pp.c:1343:18: error: use of undeclared identifier '_Bool'
 1343 |             if (!S_iv_mul_may_overflow(il, ir, &result)) {
      |                  ^
./inline.h:3540:51: note: expanded from macro 'S_iv_mul_may_overflow'
 3540 | #    define S_iv_mul_may_overflow(il, ir, result) ckd_mul(result, il, ir)
      |                                                   ^
/usr/include/stdckdint.h:32:3: note: expanded from macro 'ckd_mul'
   32 |         (_Bool)__builtin_mul_overflow((a), (b), (result))
      |          ^
pp.c:1409:18: error: use of undeclared identifier '_Bool'
 1409 |             if (!S_uv_mul_overflow(alow, blow, &product)) {
      |                  ^
./inline.h:3567:49: note: expanded from macro 'S_uv_mul_overflow'
 3567 | #    define S_uv_mul_overflow(auv, buv, result) ckd_mul(result, auv, buv)
      |                                                 ^
/usr/include/stdckdint.h:32:3: note: expanded from macro 'ckd_mul'
   32 |         (_Bool)__builtin_mul_overflow((a), (b), (result))
      |          ^
pp.c:1874:18: error: use of undeclared identifier '_Bool'
 1874 |             if (!S_iv_sub_may_overflow(il, ir, &result)) {
      |                  ^
./inline.h:3507:51: note: expanded from macro 'S_iv_sub_may_overflow'
 3507 | #    define S_iv_sub_may_overflow(il, ir, result) ckd_sub(result, il, ir)
      |                                                   ^
/usr/include/stdckdint.h:24:3: note: expanded from macro 'ckd_sub'
   24 |         (_Bool)__builtin_sub_overflow((a), (b), (result))
      |          ^
3 errors generated.
*** Error code 1

Stop.
make: stopped in /usr/home/jkeenan/gitwork/perl
```
I got the same build-time failure when using `clang++19` on the same box.  (I have not yet tried `clang++20`.)

I also got a build-time failure when targeting `miniperl`:
```
sh ./Configure -des -Dusedevel -Dusethreads -Dcc=clang++ && make miniperl
...
clang++ -c -DPERL_CORE -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DNO_POSIX_2008_LOCALE -I/usr/local/include -O2 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings pp.c
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
pp.c:1343:18: error: use of undeclared identifier '_Bool'
 1343 |             if (!S_iv_mul_may_overflow(il, ir, &result)) {
      |                  ^
./inline.h:3540:51: note: expanded from macro 'S_iv_mul_may_overflow'
 3540 | #    define S_iv_mul_may_overflow(il, ir, result) ckd_mul(result, il, ir)
      |                                                   ^
/usr/include/stdckdint.h:32:3: note: expanded from macro 'ckd_mul'
   32 |         (_Bool)__builtin_mul_overflow((a), (b), (result))
      |          ^
pp.c:1409:18: error: use of undeclared identifier '_Bool'
 1409 |             if (!S_uv_mul_overflow(alow, blow, &product)) {
      |                  ^
./inline.h:3567:49: note: expanded from macro 'S_uv_mul_overflow'
 3567 | #    define S_uv_mul_overflow(auv, buv, result) ckd_mul(result, auv, buv)
      |                                                 ^
/usr/include/stdckdint.h:32:3: note: expanded from macro 'ckd_mul'
   32 |         (_Bool)__builtin_mul_overflow((a), (b), (result))
      |          ^
pp.c:1874:18: error: use of undeclared identifier '_Bool'
 1874 |             if (!S_iv_sub_may_overflow(il, ir, &result)) {
      |                  ^
./inline.h:3507:51: note: expanded from macro 'S_iv_sub_may_overflow'
 3507 | #    define S_iv_sub_may_overflow(il, ir, result) ckd_sub(result, il, ir)
      |                                                   ^
/usr/include/stdckdint.h:24:3: note: expanded from macro 'ckd_sub'
   24 |         (_Bool)__builtin_sub_overflow((a), (b), (result))
      |          ^
3 errors generated.
*** Error code 1

Stop.
```
I next tried using `g++`.  The latest version available on this machine was 14.  Here I configured with:
```
$ sh ./Configure -des -Dusedevel -Dcc=g++14 && make miniperl

```
`make miniperl` died here:
```
g++14 -c -DPERL_CORE -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DNO_POSIX_2008_LOCALE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_FORTIFY_SOURCE=2 -O2 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wwrite-strings pp.c
In file included from inline.h:3460,
                 from perl.h:8080,
                 from pp.c:28:
pp.c: In function 'OP* Perl_pp_multiply()':
inline.h:3540:51: error: '_Bool' was not declared in this scope
 3540 | #    define S_iv_mul_may_overflow(il, ir, result) ckd_mul(result, il, ir)
      |                                                   ^~~~~~~
pp.c:1343:18: note: in expansion of macro 'S_iv_mul_may_overflow'
 1343 |             if (!S_iv_mul_may_overflow(il, ir, &result)) {
      |                  ^~~~~~~~~~~~~~~~~~~~~
inline.h:3540:51: error: expected ')' before '__builtin_mul_overflow'
 3540 | #    define S_iv_mul_may_overflow(il, ir, result) ckd_mul(result, il, ir)
      |                                                   ^~~~~~~
pp.c:1343:18: note: in expansion of macro 'S_iv_mul_may_overflow'
 1343 |             if (!S_iv_mul_may_overflow(il, ir, &result)) {
      |                  ^~~~~~~~~~~~~~~~~~~~~
pp.c:1346:14: error: expected ')' before 'goto'
 1346 |             }
      |              ^
      |              )
 1347 |             goto generic;
      |             ~~~~
pp.c:1343:16: note: to match this '('
 1343 |             if (!S_iv_mul_may_overflow(il, ir, &result)) {
      |                ^
pp.c:1347:25: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
 1347 |             goto generic;
      |                         ^
pp.c:1339:16: warning: unused variable 'result' [-Wunused-variable]
 1339 |             IV result;
      |                ^~~~~~
inline.h:3567:49: error: '_Bool' was not declared in this scope
 3567 | #    define S_uv_mul_overflow(auv, buv, result) ckd_mul(result, auv, buv)
      |                                                 ^~~~~~~
pp.c:1409:18: note: in expansion of macro 'S_uv_mul_overflow'
 1409 |             if (!S_uv_mul_overflow(alow, blow, &product)) {
      |                  ^~~~~~~~~~~~~~~~~
inline.h:3567:49: error: expected ')' before '__builtin_mul_overflow'
 3567 | #    define S_uv_mul_overflow(auv, buv, result) ckd_mul(result, auv, buv)
      |                                                 ^~~~~~~
pp.c:1409:18: note: in expansion of macro 'S_uv_mul_overflow'
 1409 |             if (!S_uv_mul_overflow(alow, blow, &product)) {
      |                  ^~~~~~~~~~~~~~~~~
pp.c:1419:14: error: expected ')' before '}' token
 1419 |             } /* ahigh && bhigh */
      |              ^
      |              )
 1420 |         } /* SvIOK(svl) */
      |         ~     
pp.c:1409:16: note: to match this '('
 1409 |             if (!S_uv_mul_overflow(alow, blow, &product)) {
      |                ^
pp.c:1420:9: error: expected primary-expression before '}' token
 1420 |         } /* SvIOK(svl) */
      |         ^
pp.c:1382:16: warning: unused variable 'product' [-Wunused-variable]
 1382 |             UV product;
      |                ^~~~~~~
pp.c:1370:3: warning: label 'generic' defined but not used [-Wunused-label]
 1370 |   generic:
      |   ^~~~~~~
pp.c: In function 'OP* Perl_pp_subtract()':
inline.h:3507:51: error: '_Bool' was not declared in this scope
 3507 | #    define S_iv_sub_may_overflow(il, ir, result) ckd_sub(result, il, ir)
      |                                                   ^~~~~~~
pp.c:1874:18: note: in expansion of macro 'S_iv_sub_may_overflow'
 1874 |             if (!S_iv_sub_may_overflow(il, ir, &result)) {
      |                  ^~~~~~~~~~~~~~~~~~~~~
inline.h:3507:51: error: expected ')' before '__builtin_sub_overflow'
 3507 | #    define S_iv_sub_may_overflow(il, ir, result) ckd_sub(result, il, ir)
      |                                                   ^~~~~~~
pp.c:1874:18: note: in expansion of macro 'S_iv_sub_may_overflow'
 1874 |             if (!S_iv_sub_may_overflow(il, ir, &result)) {
      |                  ^~~~~~~~~~~~~~~~~~~~~
pp.c:1877:14: error: expected ')' before 'goto'
 1877 |             }
      |              ^
      |              )
 1878 |             goto generic;
      |             ~~~~
pp.c:1874:16: note: to match this '('
 1874 |             if (!S_iv_sub_may_overflow(il, ir, &result)) {
      |                ^
pp.c:1878:25: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
 1878 |             goto generic;
      |                         ^
pp.c:1870:16: warning: unused variable 'result' [-Wunused-variable]
 1870 |             IV result;
      |                ^~~~~~
pp.c:1894:3: warning: label 'generic' defined but not used [-Wunused-label]
 1894 |   generic:
      |   ^~~~~~~
*** Error code 1

Stop.
```
Finally, I bisected using the following invocation:
```
$ perl Porting/bisect.pl \
--test-build -Dcc=clang++ \
--start c4da28b08d \
--end e96b7226ea
```
Behavior changed at d51aa1a511cb145eb6487dbc3bef0397bd6ea156, committed to blead on Sept 16.
```
d51aa1a511cb145eb6487dbc3bef0397bd6ea156 is the first bad commit
commit d51aa1a511cb145eb6487dbc3bef0397bd6ea156
Author: TAKAI Kousuke <62541129+t-a-k@users.noreply.github.com>
Date:   Fri Aug 29 01:48:30 2025 +0900
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Tue Sep 16 13:55:31 2025 -0600


    Introduce I_STDCKDINT config macro

    This macro is defined in config.h if <stdckdint.h> is available,
    and used in previously commited code
    (0f2b1e648156555a96ed54170e1b385a60010910, GH #23503).
```
@t-a-k, @khwilliamson, can you take a look?  Thanks.

**Comment by jkeenan** [comment]
> Behavior changed at [d51aa1a](https://github.com/Perl/perl5/commit/d51aa1a511cb145eb6487dbc3bef0397bd6ea156), committed to blead on Sept 16.
> 
> ```
> d51aa1a511cb145eb6487dbc3bef0397bd6ea156 is the first bad commit
> commit d51aa1a511cb145eb6487dbc3bef0397bd6ea156
> Author: TAKAI Kousuke <62541129+t-a-k@users.noreply.github.com>
> Date:   Fri Aug 29 01:48:30 2025 +0900
> Commit:     Karl Williamson <khw@cpan.org>
> CommitDate: Tue Sep 16 13:55:31 2025 -0600
> 
> 
>     Introduce I_STDCKDINT config macro
> 
>     This macro is defined in config.h if <stdckdint.h> is available,
>     and used in previously commited code
>     (0f2b1e648156555a96ed54170e1b385a60010910, GH #23503).
> ```
> 
> [@t-a-k](https://github.com/t-a-k), [@khwilliamson](https://github.com/khwilliamson), can you take a look? Thanks.

The code committed in the breaking commit was developed in this pull request:
https://github.com/Perl/perl5/pull/23703

**Comment by Leont** [comment]
It seems like your `stdckdint.h` assumes the C99 type `_Bool` is defined, but it isn't on C++. On my computer (gcc 15.2.1) there's a C++ override header that fixes this, but I guess that wasn't there from the start. This is all most unfortunate.

**Comment by t-a-k** [comment]
@jkeenan Could you please run the same test with `-Ui_stdckdint` added to `./Configure` ?

If that works, I'll submit a PR to tweak `Configure` to avoid defining I_STDCKDINT when `ckd_*` macros fail to compile.

**Comment by jkeenan** [comment]
> [@jkeenan](https://github.com/jkeenan) Could you please run the same test with `-Ui_stdckdint` added to `./Configure` ?
> 
> If that works, I'll submit a PR to tweak `Configure` to avoid defining I_STDCKDINT when `ckd_*` macros fail to compile.

**g++14**
```
$ sh ./Configure -des -Dusedevel -Dcc=g++14 -Ui_stdckdint && make miniperl
$ make minitest
$ make test_harness
```
The above commands completed successfully.

**clang++18** (default `clang` on this machine)
```
$ sh ./Configure -des -Dusedevel -Dusethreads -Dcc=clang++ -Ui_stdckdint && make test_prep 2>&1 | tee $P5P_DIR/make-output/`extract-sha`.freebsd.threaded.clang++18.modified.maketp.output.txt
```
`make`failed, ending like this:

```
...
clang++ -c -DPERL_CORE -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DNO_POSIX_2008_LOCALE -I/usr/local/include -O2 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings pp.c
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
pp.c:1343:18: error: use of undeclared identifier '_Bool'
 1343 |             if (!S_iv_mul_may_overflow(il, ir, &result)) {
      |                  ^
./inline.h:3542:51: note: expanded from macro 'S_iv_mul_may_overflow'
 3542 | #    define S_iv_mul_may_overflow(il, ir, result) ckd_mul(result, il, ir)
      |                                                   ^
/usr/include/stdckdint.h:32:3: note: expanded from macro 'ckd_mul'
   32 |         (_Bool)__builtin_mul_overflow((a), (b), (result))
      |          ^
pp.c:1409:18: error: use of undeclared identifier '_Bool'
 1409 |             if (!S_uv_mul_overflow(alow, blow, &product)) {
      |                  ^
./inline.h:3569:49: note: expanded from macro 'S_uv_mul_overflow'
 3569 | #    define S_uv_mul_overflow(auv, buv, result) ckd_mul(result, auv, buv)
      |                                                 ^
/usr/include/stdckdint.h:32:3: note: expanded from macro 'ckd_mul'
   32 |         (_Bool)__builtin_mul_overflow((a), (b), (result))
      |          ^
pp.c:1874:18: error: use of undeclared identifier '_Bool'
 1874 |             if (!S_iv_sub_may_overflow(il, ir, &result)) {
      |                  ^
./inline.h:3509:51: note: expanded from macro 'S_iv_sub_may_overflow'
 3509 | #    define S_iv_sub_may_overflow(il, ir, result) ckd_sub(result, il, ir)
      |                                                   ^
/usr/include/stdckdint.h:24:3: note: expanded from macro 'ckd_sub'
   24 |         (_Bool)__builtin_sub_overflow((a), (b), (result))
      |          ^
3 errors generated.
*** Error code 1

Stop.
```
The error output was, with the exception of a few line numbers in `inline.h`, identical to that reported previously for this version of `clang++`.

**clang++19**
```
$ sh ./Configure -des -Dusedevel -Dusethreads -Dcc=clang++19 -Ui_stdckdint && make test_prep 2>&1 | \
  tee $P5P_DIR/make-output/`extract-sha`.freebsd.threaded.clang++19.modified.maketp.output.txt
```
`make test_prep` completed successfully (albeit with build-time warnings I've come to expect; won't complain about those here). `make test_harness` PASS

**clang++20**

(First time attempting this version of `clang++`.)
```
$ sh ./Configure -des -Dusedevel -Dusethreads -Dcc=clang++20 -Ui_stdckdint && make test_prep 2>&1 | \
  tee $P5P_DIR/make-output/`extract-sha`.freebsd.threaded.clang++20.modified.maketp.output.txt
```
Same (good) results as from using `clang++19`.

I was not at first surprised by the results with `clang++` version 18.  But when versions 19 and 20 PASSed, I decided to re-run with what on this version of FreeBSD is the default C compiler.  This time, `make` completed (with the expected build-time warnings) and `make test_harness` PASSed.
```
$ sh ./Configure -des -Dusedevel -Dusethreads -Dcc=clang++ -Ui_stdckdint && make test_prep 2>&1 | \
  tee $P5P_DIR/make-output/`extract-sha`.freebsd.threaded.clang++18.modified.maketp.2.output.txt
```
So, @t-a-k I think you should proceed to submit a pull request.  However, I don't know what code changes should go into `./Configure` and what into, say, `hints/freebsd.sh`.

**Comment by t-a-k** [comment]
My apologies, `-Ui_stdckdint` doesn't work as expected.
I've mixed up with other Configure variables that can be overridden with `-U` (such as `-Ud_builtin_add_overflow`) 

I've also submit PR #23739 to fix this. I would appreciate it if you could check.

**Comment by jkeenan** [comment]
> My apologies, `-Ui_stdckdint` doesn't work as expected. I've mixed up with other Configure variables that can be overridden with `-U` (such as `-Ud_builtin_add_overflow`)
> 
> I've also submit PR [#23739](https://github.com/Perl/perl5/pull/23739) to fix this. I would appreciate it if you could check.

https://github.com/Perl/perl5/pull/23739, a possible solution to this Issue, awaits further code review.

**Comment by tonycoz** [comment]
> [#23739](https://github.com/Perl/perl5/pull/23739), a possible solution to this Issue, awaits further code review.

which has been approved and merged.

**Comment by jkeenan** [comment]
> > [#23739](https://github.com/Perl/perl5/pull/23739), a possible solution to this Issue, awaits further code review.
> 
> which has been approved and merged.

I'll build myself and watch smoke-test reports and close  this in a couple of days.

**Comment by jkeenan** [comment]
I have inspected smoke-test reports using clang++ or g++ filed since this commit:
```
commit e6d5a81feda207243c96065db5f456f94671075f
Author:     TAKAI Kousuke <62541129+t-a-k@users.noreply.github.com>
AuthorDate: Fri Sep 19 20:38:59 2025
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Sun Sep 21 08:51:10 2025

    Configure: check usability of <stdckdint.h>, not only its existence
```
... and I have seen no unexpected failures on these runs.  (g++ builds on OpenBSD remain problematic, but that condition previously existed.)  So I'm closing this ticket now.  Thank you very much.
