### ISSUE TITLE
BBC: Bleadperl breaks FANY/MIME-Signature-0.22.tar.gz

### ISSUE THREAD

**Issue by andk** [Perl/perl5#20885]
**Description**

With v5.37.8-201-g8a8491416c tests have started to fail for FANY/MIME-Signature-0.22.tar.gz

Git bisect leads me to:
``` text
commit 8a8491416c79dc8f491c402c013844437c0643eb                                   
Author: Yves Orton <demerphq@gmail.com>
Date:   Sun Sep 25 10:50:00 2022 +0200

    toke.c - invoke __DIE__ handler after compilation errors in eval

```
@demerphq , please take note.

Sample fail report: http://www.cpantesters.org/cpan/report/71ade746-b626-11ed-a88a-dddda0688e59

At the time of this writing, the cpantesters website is not working, so I include the rather voluminous diagnostic output of the failing test here:

``` text
#   Failed test 'Cannot handle ascii to signed-mutt'
#   at t/20-add-disclaimer.t line 38.
# 
#                   'Can't modify non-lvalue subroutine call of &MIME::Disclaimer::__ANON__ in scalar assignment at (eval 57) line 1, at EOF
# '
#     doesn't match '(?^:^Cannot handle )'
# 
```
**NOTE, edited out unnecessary excess test output - @demerphq**

**Steps to Reproduce**

cpan -i FANY/MIME-Signature-0.22.tar.gz
**Expected behavior**

Should build, test, and install

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 37 subversion 9) configuration:
  Commit id: 692cfdb0a41902b1e4fd4d934426ef95c2b4b694
  Platform:
    osname=linux
    osvers=5.15.0-60-generic
    archname=x86_64-linux-thread-multi
    uname='linux k93jammy 5.15.0-60-generic #66-ubuntu smp fri jan 20 14:29:49 utc 2023 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93jammy/v5.37.9/b4f3 -Dmyhostname=k93jammy -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Duseithreads -Uuselongdouble -DEBUGGING=-g'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.35'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Feb 21 2023 03:27:16
  %ENV:
    PERL5LIB="/tmp/loop_over_bdir-2127505-ZkMztx/Sysync-0.35-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Sysync-0.35-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/Simulation-Automate-1.0.1-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Simulation-Automate-1.0.1-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/makepp-1.19-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/makepp-1.19-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/App-nrun-v1.1.2-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/App-nrun-v1.1.2-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/DBIx-Migration-Directories-0.12-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/DBIx-Migration-Directories-0.12-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/Business-Shipping-DataFiles-1.02-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Business-Shipping-DataFiles-1.02-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/Linux-InitFS-0.2-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Linux-InitFS-0.2-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/CORBA-Python-2.66-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/CORBA-Python-2.66-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/Lingua-BioYaTeA-0.11-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Lingua-BioYaTeA-0.11-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/Lingua-YaTeA-0.626-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Lingua-YaTeA-0.626-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/NoZone-1.3-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/NoZone-1.3-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/mmds-1.902-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/mmds-1.902-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/App-oo_modulino_zsh_completion_helper-0.04-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/App-oo_modulino_zsh_completion_helper-0.04-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/triceps-2.1.0-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/triceps-2.1.0-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/Lemonldap-NG-Cli-0.2-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Lemonldap-NG-Cli-0.2-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/Net-OpenVPN-DDNS-0.1-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Net-OpenVPN-DDNS-0.1-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/dta-tokwrap-0.98-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/dta-tokwrap-0.98-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/Debian-Packages-0.03-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Debian-Packages-0.03-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/perl-Hardware-UPS-Perl-0.43-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/perl-Hardware-UPS-Perl-0.43-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/shishi-0.0.1-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/shishi-0.0.1-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/Net-Async-WebService-lxd-0.03-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Net-Async-WebService-lxd-0.03-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/Alien-SNMP-MIBDEV-2.020000-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Alien-SNMP-MIBDEV-2.020000-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/Dpkg-1.21.19-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Dpkg-1.21.19-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/ProjectBuilder-0.14.1-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/ProjectBuilder-0.14.1-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/AllKnowingDNS-1.7-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/AllKnowingDNS-1.7-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/Devel-Required-0.16-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/Devel-Required-0.16-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/CGI-Application-NetNewsIface-0.0204-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/CGI-Application-NetNewsIface-0.0204-0/blib/lib:/tmp/loop_over_bdir-2127505-ZkMztx/downsexta-0/blib/arch:/tmp/loop_over_bdir-2127505-ZkMztx/downsexta-0/blib/lib"
    PERL5OPT=""
    PERL5_CPANPLUS_IS_RUNNING="2127574"
    PERL5_CPAN_IS_RUNNING="2127574"
    PERL_CANARY_STABILITY_NOPROMPT="1"
    PERL_MM_USE_DEFAULT="1"
    PERL_USE_UNSAFE_INC="1"
  @INC:
    /tmp/loop_over_bdir-2127505-ZkMztx/Sysync-0.35-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Sysync-0.35-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/Simulation-Automate-1.0.1-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Simulation-Automate-1.0.1-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/makepp-1.19-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/makepp-1.19-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/App-nrun-v1.1.2-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/App-nrun-v1.1.2-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/DBIx-Migration-Directories-0.12-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/DBIx-Migration-Directories-0.12-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/Business-Shipping-DataFiles-1.02-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Business-Shipping-DataFiles-1.02-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/Linux-InitFS-0.2-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Linux-InitFS-0.2-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/CORBA-Python-2.66-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/CORBA-Python-2.66-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/Lingua-BioYaTeA-0.11-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Lingua-BioYaTeA-0.11-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/Lingua-YaTeA-0.626-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Lingua-YaTeA-0.626-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/NoZone-1.3-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/NoZone-1.3-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/mmds-1.902-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/mmds-1.902-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/App-oo_modulino_zsh_completion_helper-0.04-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/App-oo_modulino_zsh_completion_helper-0.04-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/triceps-2.1.0-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/triceps-2.1.0-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/Lemonldap-NG-Cli-0.2-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Lemonldap-NG-Cli-0.2-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/Net-OpenVPN-DDNS-0.1-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Net-OpenVPN-DDNS-0.1-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/dta-tokwrap-0.98-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/dta-tokwrap-0.98-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/Debian-Packages-0.03-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Debian-Packages-0.03-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/perl-Hardware-UPS-Perl-0.43-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/perl-Hardware-UPS-Perl-0.43-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/shishi-0.0.1-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/shishi-0.0.1-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/Net-Async-WebService-lxd-0.03-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Net-Async-WebService-lxd-0.03-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/Alien-SNMP-MIBDEV-2.020000-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Alien-SNMP-MIBDEV-2.020000-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/Dpkg-1.21.19-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Dpkg-1.21.19-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/ProjectBuilder-0.14.1-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/ProjectBuilder-0.14.1-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/AllKnowingDNS-1.7-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/AllKnowingDNS-1.7-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/Devel-Required-0.16-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/Devel-Required-0.16-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/CGI-Application-NetNewsIface-0.0204-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/CGI-Application-NetNewsIface-0.0204-0/blib/lib
    /tmp/loop_over_bdir-2127505-ZkMztx/downsexta-0/blib/arch
    /tmp/loop_over_bdir-2127505-ZkMztx/downsexta-0/blib/lib
    /home/sand/src/perl/repoperls/installed-perls/host/k93jammy/v5.37.9/b4f3/lib/site_perl/5.37.9/x86_64-linux-thread-multi
    /home/sand/src/perl/repoperls/installed-perls/host/k93jammy/v5.37.9/b4f3/lib/site_perl/5.37.9
    /home/sand/src/perl/repoperls/installed-perls/host/k93jammy/v5.37.9/b4f3/lib/5.37.9/x86_64-linux-thread-multi
    /home/sand/src/perl/repoperls/installed-perls/host/k93jammy/v5.37.9/b4f3/lib/5.37.9
    .

```

**Comment by demerphq** [comment]
Strange this bisects to me. I don't see any examples of what i would expect from that, but i do see a bunch of stuff that definitely isn't me. Regardless I will poke into it. Thanks for the report.

**Comment by demerphq** [comment]
This isnt a bug in MIME::Sigatures, it is a bug in Class::Method::Modifiers. See https://rt.cpan.org/Ticket/Display.html?id=146848

**Comment by demerphq** [comment]
Patches provided to the various parties involved.

**Comment by rjbs** [comment]
Closed, patch sent upstream, not a blocker.
