### ISSUE TITLE
Bleadperl v5.25.6-260-ga65dc09 breaks DCONWAY/IO-Prompt-0.997003.tar.gz

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15722]
Migrated from [rt.perl.org#130126](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130126) (status was 'resolved')

Searchable as RT130126$

**Comment by p5pRT** [comment]
### From @andk

bisect


---
a65dc09f8c2a74df9479cbf2883f5f3778987217 is the first bad commit
commit a65dc09f8c2a74df9479cbf2883f5f3778987217
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Mon Nov 14 22&#8203;:52&#8203;:45 2016 \+0100

&nbsp;    Finish removing POSIX deprecated fcns
&nbsp;    
&nbsp;    Commit 47ed9d9e89922a8e165d6dfc5737772cc5ee7a45 removed various
&nbsp;    deprecated functions\, as scheduled in this release\, but failed to
&nbsp;    include everything that should have gotten removed\.
&nbsp;    
&nbsp;    Spotted by Abigail\.

diagnostics


---
t/00\.load\.t \.\.\.\.\.\.\. 1/1 
\#   Failed test 'use IO&#8203;::Prompt;'
\#   at t/00\.load\.t line 4\.
\#     Tried to use 'IO&#8203;::Prompt'\.
\#     Error&#8203;:  "isprint" is not exported by the POSIX module
\# Can't continue after import errors at /home/sand/src/perl/repoperls/installed\-perls/perl/v5\.25\.6\-260\-ga65dc09/109d/lib/5\.25\.7/x86\_64\-linux\-thread\-multi\-ld/POSIX\.pm line 192\.
\# BEGIN failed\-\-compilation aborted at /tmp/loop\_over\_bdir\-21802\-ZQMYws/IO\-Prompt\-0\.997003\-0/blib/lib/IO/Prompt\.pm line 16\.
\# Compilation failed in require at t/00\.load\.t line 4\.
\# BEGIN failed\-\-compilation aborted at t/00\.load\.t line 4\.
\# Testing IO&#8203;::Prompt 
\# Looks like you failed 1 test of 1\.
t/00\.load\.t \.\.\.\.\.\.\. Dubious\, test returned 1 \(wstat 256\, 0x100\)
Failed 1/1 subtests 

perl \-V


---
Summary of my perl5 \(revision 5 version 25 subversion 7\) configuration&#8203;:
&nbsp;  Derived from&#8203;: a65dc09f8c2a74df9479cbf2883f5f3778987217
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=4\.7\.0\-1\-amd64
&nbsp;    archname=x86\_64\-linux\-thread\-multi\-ld
&nbsp;    uname='linux k83 4\.7\.0\-1\-amd64 \#1 smp debian 4\.7\.8\-1 \(2016\-10\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dprefix=/home/sand/src/perl/repoperls/installed\-perls/perl/v5\.25\.6\-260\-ga65dc09/109d \-Dmyhostname=k83 \-Dinstallusrbinperl=n \-Uversiononly \-Dusedevel \-des \-Ui\_db \-Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm\_compat \-Duseithreads \-Duselongdouble \-DDEBUGGING=\-g'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=define
&nbsp;    usemultiplicity=define
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=define
&nbsp;    usemymalloc=n
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'
&nbsp;    ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;    optimize='\-O2 \-g'
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='6\.2\.0 20160830'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='long double'
&nbsp;    nvsize=16
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=16
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'
&nbsp;    ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/6/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-lgdbm \-ldl \-lm \-lcrypt \-lutil \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.24\.so
&nbsp;    so=so
&nbsp;    useshrplib=false
&nbsp;    libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.24'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-O2 \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;:
&nbsp;    HAS\_TIMES
&nbsp;    MULTIPLICITY
&nbsp;    PERLIO\_LAYERS
&nbsp;    PERL\_COPY\_ON\_WRITE
&nbsp;    PERL\_DONT\_CREATE\_GVSV
&nbsp;    PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD
&nbsp;    PERL\_IMPLICIT\_CONTEXT
&nbsp;    PERL\_MALLOC\_WRAP
&nbsp;    PERL\_OP\_PARENT
&nbsp;    PERL\_PRESERVE\_IVUV
&nbsp;    PERL\_USE\_DEVEL
&nbsp;    USE\_64\_BIT\_ALL
&nbsp;    USE\_64\_BIT\_INT
&nbsp;    USE\_ITHREADS
&nbsp;    USE\_LARGE\_FILES
&nbsp;    USE\_LOCALE
&nbsp;    USE\_LOCALE\_COLLATE
&nbsp;    USE\_LOCALE\_CTYPE
&nbsp;    USE\_LOCALE\_NUMERIC
&nbsp;    USE\_LOCALE\_TIME
&nbsp;    USE\_LONG\_DOUBLE
&nbsp;    USE\_PERLIO
&nbsp;    USE\_PERL\_ATOF
&nbsp;    USE\_REENTRANT\_API
&nbsp;  Locally applied patches&#8203;:
&nbsp;    uncommitted\-changes
&nbsp;  Built under linux
&nbsp;  Compiled at Nov 17 2016 23&#8203;:02&#8203;:07
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /home/sand/src/perl/repoperls/installed\-perls/perl/v5\.25\.6\-260\-ga65dc09/109d/lib/site\_perl/5\.25\.7/x86\_64\-linux\-thread\-multi\-ld
&nbsp;    /home/sand/src/perl/repoperls/installed\-perls/perl/v5\.25\.6\-260\-ga65dc09/109d/lib/site\_perl/5\.25\.7
&nbsp;    /home/sand/src/perl/repoperls/installed\-perls/perl/v5\.25\.6\-260\-ga65dc09/109d/lib/5\.25\.7/x86\_64\-linux\-thread\-multi\-ld
&nbsp;    /home/sand/src/perl/repoperls/installed\-perls/perl/v5\.25\.6\-260\-ga65dc09/109d/lib/5\.25\.7
&nbsp;    \.

\-\- 
andreas

**Comment by p5pRT** [comment]
### From @khwilliamson

I don't know what to do about this\.  The module uses a now removed function\.  And it says in the module description

"STATUS ^

This module is no longer being maintained\.

Use the IO&#8203;::Prompter module instead\."

So the module itself is obsolete\, and has a bunch of tickets in its queue\.  It seems to me that maybe cpan smoking should skip this module

\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @andk

>>>>> On Sat\, 19 Nov 2016 08&#8203;:11&#8203;:36 \-0800\, "Karl Williamson via RT" \<perlbug\-followup@&#8203;perl\.org> said&#8203;:

&nbsp;  > I don't know what to do about this\.  The module uses a now removed function\.  And it says in the module description
&nbsp;  > "STATUS ^

&nbsp;  > This module is no longer being maintained\.

&nbsp;  > Use the IO&#8203;::Prompter module instead\."

&nbsp;  > So the module itself is obsolete\, and has a bunch of tickets in its
&nbsp;  > queue\. It seems to me that maybe cpan smoking should skip this
&nbsp;  > module

\- first of all I'm sorry\, I didn't know about the half\-deprecation; I
&nbsp;  have now removed the module from my smoker\, but this is not a
&nbsp;  guarantee that it won't reappear as a depencency;

\- 31 reverse dependencies indicate that this is very likely&#8203;:
&nbsp;  https://metacpan.org/requires/distribution/IO-Prompt?p=1&size=500&sort=[[2%2C1]]

\- what is the best way to spread the word about the deprecation? Up to
&nbsp;  the v5\.25\.6\-260\-ga65dc09 there was no pressure\, now there is;

\-\- 
andreas

**Comment by p5pRT** [comment]
### From @eserte

Dana Sat\, 19 Nov 2016 09&#8203;:08&#8203;:16 \-0800\, andreas\.koenig\.7os6VVqR@&#8203;franz\.ak\.mind\.de reče&#8203;:
> >>>>> On Sat\, 19 Nov 2016 08&#8203;:11&#8203;:36 \-0800\, "Karl Williamson via RT"
> >>>>> \<perlbug\-followup@&#8203;perl\.org> said&#8203;:
> 
> > I don't know what to do about this\.  The module uses a now removed
> > function\.  And it says in the module description
> > "STATUS ^
> 
> > This module is no longer being maintained\.
> 
> > Use the IO&#8203;::Prompter module instead\."
> 
> > So the module itself is obsolete\, and has a bunch of tickets in its
> > queue\. It seems to me that maybe cpan smoking should skip this
> > module
> 
> \- first of all I'm sorry\, I didn't know about the half\-deprecation; I
>   have now removed the module from my smoker\, but this is not a
>   guarantee that it won't reappear as a depencency;
> 
> \- 31 reverse dependencies indicate that this is very likely&#8203;:
>   https://metacpan.org/requires/distribution/IO-
> Prompt?p=1&size=500&sort=\[\[2%2C1\]\]
> 
> \- what is the best way to spread the word about the deprecation? Up to
>   the v5\.25\.6\-260\-ga65dc09 there was no pressure\, now there is;

A CPAN RT ticket exists now&#8203;:
https://rt.cpan.org/Ticket/Display.html?id=118893

**Comment by p5pRT** [comment]
### From @eserte

Dana Mon\, 21 Nov 2016 22&#8203;:12&#8203;:42 \-0800\, slaven@&#8203;rezic\.de reče&#8203;:
> Dana Sat\, 19 Nov 2016 09&#8203;:08&#8203;:16 \-0800\,
> andreas\.koenig\.7os6VVqR@&#8203;franz\.ak\.mind\.de reče&#8203;:
> > >>>>> On Sat\, 19 Nov 2016 08&#8203;:11&#8203;:36 \-0800\, "Karl Williamson via RT"
> > >>>>> \<perlbug\-followup@&#8203;perl\.org> said&#8203;:
> >
> > > I don't know what to do about this\.  The module uses a now removed
> > > function\.  And it says in the module description
> > > "STATUS ^
> >
> > > This module is no longer being maintained\.
> >
> > > Use the IO&#8203;::Prompter module instead\."
> >
> > > So the module itself is obsolete\, and has a bunch of tickets in its
> > > queue\. It seems to me that maybe cpan smoking should skip this
> > > module
> >
> > \- first of all I'm sorry\, I didn't know about the half\-deprecation; I
> >   have now removed the module from my smoker\, but this is not a
> >   guarantee that it won't reappear as a depencency;
> >
> > \- 31 reverse dependencies indicate that this is very likely&#8203;:
> >   https://metacpan.org/requires/distribution/IO-
> > Prompt?p=1&size=500&sort=\[\[2%2C1\]\]
> >
> > \- what is the best way to spread the word about the deprecation? Up
> > to
> >   the v5\.25\.6\-260\-ga65dc09 there was no pressure\, now there is;
> 
> A CPAN RT ticket exists now&#8203;:
> https://rt.cpan.org/Ticket/Display.html?id=118893

Related&#8203;: POSIX&#8203;::isdigit was also removed\, and causes FAXMODEM/Test\-Collectd\-Plugins\-0\.1008\.tar\.gz to fail\.

**Comment by p5pRT** [comment]
### From @eserte

Dana Thu\, 24 Nov 2016 12&#8203;:12&#8203;:40 \-0800\, slaven@&#8203;rezic\.de reče&#8203;:
> Dana Mon\, 21 Nov 2016 22&#8203;:12&#8203;:42 \-0800\, slaven@&#8203;rezic\.de reče&#8203;:
> > Dana Sat\, 19 Nov 2016 09&#8203;:08&#8203;:16 \-0800\,
> > andreas\.koenig\.7os6VVqR@&#8203;franz\.ak\.mind\.de reče&#8203;:
> > > >>>>> On Sat\, 19 Nov 2016 08&#8203;:11&#8203;:36 \-0800\, "Karl Williamson via RT"
> > > >>>>> \<perlbug\-followup@&#8203;perl\.org> said&#8203;:
> > >
> > > > I don't know what to do about this\.  The module uses a now
> > > > removed
> > > > function\.  And it says in the module description
> > > > "STATUS ^
> > >
> > > > This module is no longer being maintained\.
> > >
> > > > Use the IO&#8203;::Prompter module instead\."
> > >
> > > > So the module itself is obsolete\, and has a bunch of tickets in
> > > > its
> > > > queue\. It seems to me that maybe cpan smoking should skip this
> > > > module
> > >
> > > \- first of all I'm sorry\, I didn't know about the half\-deprecation;
> > > I
> > >   have now removed the module from my smoker\, but this is not a
> > >   guarantee that it won't reappear as a depencency;
> > >
> > > \- 31 reverse dependencies indicate that this is very likely&#8203;:
> > >   https://metacpan.org/requires/distribution/IO-
> > > Prompt?p=1&size=500&sort=\[\[2%2C1\]\]
> > >
> > > \- what is the best way to spread the word about the deprecation? Up
> > > to
> > >   the v5\.25\.6\-260\-ga65dc09 there was no pressure\, now there is;
> >
> > A CPAN RT ticket exists now&#8203;:
> > https://rt.cpan.org/Ticket/Display.html?id=118893
> 
> Related&#8203;: POSIX&#8203;::isdigit was also removed\, and causes FAXMODEM/Test\-
> Collectd\-Plugins\-0\.1008\.tar\.gz to fail\.

A CPAN RT ticket for this one&#8203;:
https://rt.cpan.org/Ticket/Display.html?id=118947

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Nov 24\, 2016 at 12&#8203;:14&#8203;:53PM \-0800\, slaven@&#8203;rezic\.de via RT wrote&#8203;:
> Dana Thu\, 24 Nov 2016 12&#8203;:12&#8203;:40 \-0800\, slaven@&#8203;rezic\.de reče&#8203;:
> > Dana Mon\, 21 Nov 2016 22&#8203;:12&#8203;:42 \-0800\, slaven@&#8203;rezic\.de reče&#8203;:
> > > Dana Sat\, 19 Nov 2016 09&#8203;:08&#8203;:16 \-0800\,
> > > andreas\.koenig\.7os6VVqR@&#8203;franz\.ak\.mind\.de reče&#8203;:
> > > > >>>>> On Sat\, 19 Nov 2016 08&#8203;:11&#8203;:36 \-0800\, "Karl Williamson via RT"
> > > > >>>>> \<perlbug\-followup@&#8203;perl\.org> said&#8203;:
> > > >
> > > > > I don't know what to do about this\.  The module uses a now
> > > > > removed
> > > > > function\.  And it says in the module description
> > > > > "STATUS ^
> > > >
> > > > > This module is no longer being maintained\.
> > > >
> > > > > Use the IO&#8203;::Prompter module instead\."
> > > >
> > > > > So the module itself is obsolete\, and has a bunch of tickets in
> > > > > its
> > > > > queue\. It seems to me that maybe cpan smoking should skip this
> > > > > module
> > > >
> > > > \- first of all I'm sorry\, I didn't know about the half\-deprecation;
> > > > I
> > > >   have now removed the module from my smoker\, but this is not a
> > > >   guarantee that it won't reappear as a depencency;
> > > >
> > > > \- 31 reverse dependencies indicate that this is very likely&#8203;:
> > > >   https://metacpan.org/requires/distribution/IO-
> > > > Prompt?p=1&size=500&sort=\[\[2%2C1\]\]
> > > >
> > > > \- what is the best way to spread the word about the deprecation? Up
> > > > to
> > > >   the v5\.25\.6\-260\-ga65dc09 there was no pressure\, now there is;
> > >
> > > A CPAN RT ticket exists now&#8203;:
> > > https://rt.cpan.org/Ticket/Display.html?id=118893

IO\-Prompt\-0\.997004 has now been released\, which passes under blead\.

> > Related&#8203;: POSIX&#8203;::isdigit was also removed\, and causes FAXMODEM/Test\-
> > Collectd\-Plugins\-0\.1008\.tar\.gz to fail\.
> 
> A CPAN RT ticket for this one&#8203;:
> https://rt.cpan.org/Ticket/Display.html?id=118947

Collectd\-Plugins\-0\.1009 has been released\, which I can't test due to
dependencies \(one requires an executable called 'yapp' which I don't have
installed\)\, but the author's changelog implies that the new release fixes
this issue\.

So I'll close this ticket\.

\-\- 
It's not that I'm afraid to die\, I just don't want to be there when it
happens\.
&nbsp;    \-\- Woody Allen

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
