### ISSUE TITLE
clang++ build-time failure at 2e2065489c

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#19784]
Attempting a threaded build on FreeBSD-12 using clang++ as the C-compiler today at fd4fc0f6fd, I observed the following build-time failure:
```
$ sh ./Configure -des -Dusedevel -Duseithreads -Dcc=clang++ && make test_prep
...
echo @`sh  cflags "optimize='-O2'" opmini.o`  -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
@clang++ -c -DPERL_CORE -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -I/usr/local/include -O2 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
echo @`sh  cflags "optimize='-O2'" perlmini.o`  -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB perlmini.c
@clang++ -c -DPERL_CORE -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -I/usr/local/include -O2 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB perlmini.c
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
perl.c:1613:26: error: assigning to 'char *' from incompatible type 'void *'
        new_environ[i] = CopyD(environ[i], vars + copied, len, char);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./handy.h:2796:24: note: expanded from macro 'CopyD'
#define CopyD(s,d,n,t)  (MEM_WRAP_CHECK_(n,t) perl_assert_ptr(d), perl_assert_ptr(s), memcpy((char*)(d),(const char*)(s), (n) * sizeof(t)))
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make: stopped in /usr/home/jkeenan/gitwork/perl
```
See also this smoke-report:
https://perl5.test-smoke.org/report/5018932

At tag v5.36.0, using clang++ as the compiler, `make` completes successfully (albeit with build-time warnings) and all tests PASS.  So this failure is new in this dev cycle.  Bisection points to the following commit:
```
# first bad commit: [2e2065489c88c6bfe07d822175cfdefdb707db11] probe for setenv in Configure
2e2065489c88c6bfe07d822175cfdefdb707db11 is the first bad commit
commit 2e2065489c88c6bfe07d822175cfdefdb707db11
Author: Tomasz Konojacki <me@xenu.pl>
Date:   Tue Apr 19 16:41:23 2022 +0200
Commit:     Tomasz Konojacki <me@xenu.pl>
CommitDate: Sun May 29 00:54:10 2022 +0200

    probe for setenv in Configure
```
@xenu, can you take a look?

**Comment by khwilliamson** [comment]
This should be fixed by 01aede5a763f5fc828acfda196b14da88f1ab90f

**Comment by jkeenan** [comment]
> 

Confirmed.  Thanks.  Closing ticket.
