### ISSUE TITLE
Assert fail in op.c without other symptoms: 0=\my%u:e=0

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15338]
Migrated from [rt.perl.org#128183](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128183) (status was 'open')

Searchable as RT128183$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in debugging builds of the perl interpreter\. The testcase is the file below\. On normal builds\, this exits with the expected error\. On debug builds\, this returns an assert fail\.

dcollins@&#8203;nightshade64&#8203;:\~$ cat f3i1
0=\\my%u&#8203;:e=0dcollins@&#8203;nightshade64&#8203;:\~$
dcollins@&#8203;nightshade64&#8203;:\~$ od \-c f3i1
0000000   0   =   \\   m   y   %   u   :   e   =   0
0000013
dcollins@&#8203;nightshade64&#8203;:\~$ ls \-l f3i1
\-rw\-r\-\-\-\-\- 1 dcollins afl 11 May 18 17&#8203;:01 f3i1
dcollins@&#8203;nightshade64&#8203;:\~$ \./perl/perl f3i1
Can't modify reference to subroutine entry in list assignment at f3i1 line 1\, at EOF
Execution of f3i1 aborted due to compilation errors\.
dcollins@&#8203;nightshade64&#8203;:\~$ \./perldebug/perl f3i1
perl&#8203;: op\.c&#8203;:2758&#8203;: S\_lvref&#8203;: Assertion \`\(kid\->op\_flags & 3\) \!= 1' failed\.
Aborted


Debugging tool output is below\. A git bisect was performed\. Unfortunately\, this requires attributes\, so a miniperl build is not sufficient to test\. Here is the result&#8203;:

7664512eddd3e297d305684d8075fd977e4ef95c is the first bad commit
commit 7664512eddd3e297d305684d8075fd977e4ef95c
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Tue Sep 30 22&#8203;:20&#8203;:56 2014 \-0700

&nbsp;    Make \\\( ?&#8203;: \) assignment work

&nbsp;    When I first implemented list assignment to lvalue references\, I
&nbsp;    thought I could simply modify the kids of the refgen op \(\\\) in one
&nbsp;    spot\.  But things like ?&#8203;: make it necessary to do this recursively\.
&nbsp;    So all that code for turning thingies into lvrefs has been moved into
&nbsp;    a separate function patterned after op\_lvalue but handling only the
&nbsp;    lvref cases\.

&nbsp;    \(I thought about combining it with op\_lvalue’s switch statement\, but
&nbsp;    that would require ‘if\(type == OP\_LVREF\) goto nomod;’ too many times\,
&nbsp;    which would be harder to maintain\.\)

:100644 100644 2e163602eb33b1df99c98aeee9c803e79004f7db 9e4e8d9db15ae2e214420f67b2e6683c1611cf54 M      op\.c
:040000 040000 8114515a860c7aebba1d4c401f7b2aa52d8abade f65b52fd5e71e1ae0d6c098770ae4d38f7a37208 M      t
bisect run success


\*\*GDB\*\*

dcollins@&#8203;nightshade64&#8203;:\~$ gdb \-\-args \./perldebug/perl f3i1
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \./perldebug/perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl f3i1
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
perl&#8203;: op\.c&#8203;:2758&#8203;: S\_lvref&#8203;: Assertion \`\(kid\->op\_flags & 3\) \!= 1' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cfa8fa in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6cf23a7 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6cf2452 in \_\_assert\_fail \(\)
&nbsp;   from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x000000000042611e in S\_lvref \(o=0xabc4d8\, type=38\) at op\.c&#8203;:2758
\#5  0x0000000000427556 in Perl\_op\_lvalue\_flags \(o=0xabc460\, type=38\, flags=0\)
&nbsp;    at op\.c&#8203;:3123
\#6  0x0000000000432c5a in Perl\_newASSIGNOP \(flags=64\, left=0xabc460\,
&nbsp;    optype=0\, right=0xabc420\) at op\.c&#8203;:6400
\#7  0x00000000004d7161 in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:781
\#8  0x0000000000461482 in S\_parse\_body \(env=0x0\, xsinit=0x41e9e9 \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:2365
\#9  0x000000000045f8c8 in perl\_parse \(my\_perl=0xa9a010\,
&nbsp;    xsinit=0x41e9e9 \<xs\_init>\, argc=2\, argv=0x7fffffffe648\, env=0x0\)
&nbsp;    at perl\.c&#8203;:1681
\#10 0x000000000041e948 in main \(argc=2\, argv=0x7fffffffe648\,
&nbsp;    env=0x7fffffffe660\) at perlmain\.c&#8203;:114
\(gdb\) f 4
\#4  0x000000000042611e in S\_lvref \(o=0xabc4d8\, type=38\) at op\.c&#8203;:2758
2758                assert\(\(kid\->op\_flags & OPf\_WANT\) \!= OPf\_WANT\_VOID\);
\(gdb\) info locals
kid = 0xabc5a8
\_\_PRETTY\_FUNCTION\_\_ = "S\_lvref"
\(gdb\) l
2753                return;
2754            \}
2755            /\* FALLTHROUGH \*/
2756        case OP\_LIST&#8203;:
2757            for \(kid = cLISTOPo\->op\_first; kid; kid = OpSIBLING\(kid\)\) \{
2758                assert\(\(kid\->op\_flags & OPf\_WANT\) \!= OPf\_WANT\_VOID\);
2759                S\_lvref\(aTHX\_ kid\, type\);
2760            \}
2761            return;
2762        case OP\_STUB&#8203;:
\(gdb\) q


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~$ perl/perl  \-V
Summary of my perl5 \(revision 5 version 25 subversion 1\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 9e17953912c0ab4f21dd642345727a44c388a0af
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.5\.0\-2\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 4\.5\.0\-2\-amd64 \#1 smp debian 4\.5\.3\-2 \(2016\-05\-08\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DDEBUG\_LEAKING\_SCALARS \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='6\.1\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-pc\-linux\-gnu/6\.1\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_OP\_PARENT PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 17 2016 20&#8203;:01&#8203;:23
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.1/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @cpansprout

On Wed May 18 16&#8203;:59&#8203;:31 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> Greetings Porters\,
> 
> I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
> 
> \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache
> afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly
> \-Uman1dir \-Uman3dir \-Dusequadmath \-des
> AFL\_HARDEN=1 make && make test
> 
> And then fuzzed the resulting binary using&#8203;:
> 
> AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
> 
> After reducing testcases using \`afl\-tmin\` and performing additional
> minimization by hand\, I have located the following testcase that
> triggers an assert fail in debugging builds of the perl interpreter\.
> The testcase is the file below\. On normal builds\, this exits with the
> expected error\. On debug builds\, this returns an assert fail\.
> 
> dcollins@&#8203;nightshade64&#8203;:\~$ cat f3i1
> 0=\\my%u&#8203;:e=0dcollins@&#8203;nightshade64&#8203;:\~$
> dcollins@&#8203;nightshade64&#8203;:\~$ od \-c f3i1
> 0000000   0   =   \\   m   y   %   u   :   e   =   0
> 0000013
> dcollins@&#8203;nightshade64&#8203;:\~$ ls \-l f3i1
> \-rw\-r\-\-\-\-\- 1 dcollins afl 11 May 18 17&#8203;:01 f3i1
> dcollins@&#8203;nightshade64&#8203;:\~$ \./perl/perl f3i1
> Can't modify reference to subroutine entry in list assignment at f3i1
> line 1\, at EOF
> Execution of f3i1 aborted due to compilation errors\.
> dcollins@&#8203;nightshade64&#8203;:\~$ \./perldebug/perl f3i1
> perl&#8203;: op\.c&#8203;:2758&#8203;: S\_lvref&#8203;: Assertion \`\(kid\->op\_flags & 3\) \!= 1' failed\.
> Aborted

The initial 0= is unnecessary\.  I completely failed to take attributes into account when implementing refaliasing\.

$ \./perl \-Ilib \-e '\\my %x&#8203;:e = 1'
Assertion failed&#8203;: \(\(kid\->op\_flags & OPf\_WANT\) \!= OPf\_WANT\_VOID\)\, function S\_lvref\, file op\.c\, line 2758\.
Abort trap&#8203;: 6

$ \./perl \-Ilib \-e '\\CORE&#8203;::state %x :e = 1'
Assertion failed&#8203;: \(\(kid\->op\_flags & OPf\_WANT\) \!= OPf\_WANT\_VOID\)\, function S\_lvref\, file op\.c\, line 2758\.
Abort trap&#8203;: 6

$ \./perl \-Ilib \-XMfeature=&#8203;:all \-e 'sub MODIFY\_HASH\_ATTRIBUTES\{\} \\our %x&#8203;:e = \\%a; print "ok\\n"'
ok

The last one works\, because the attribute does not modify the op tree with ‘our’\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @dcollinsn

Experts&#8203;: is the following bug related? \(Also uses attributes\, same assert\, but in a different place\.\)

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-W \-e 'tie my$r&#8203;:n'
perl&#8203;: op\.c&#8203;:2799&#8203;: Perl\_op\_lvalue\_flags&#8203;: Assertion \`\(o\->op\_flags & 3\) \!= 1' failed\.
Aborted


Without debug&#8203;:

dcollins@&#8203;nightshade64&#8203;:\~/perl$ \./perl \-Ilib \-W \-e 'tie my$r&#8203;:n'
Can't modify non\-lvalue subroutine call of &attributes&#8203;::import at \-e line 1\.
dcollins@&#8203;nightshade64&#8203;:\~/perl$ \./perl \-MO=Deparse \-Ilib \-e 'tie my$r&#8203;:n'
use attributes \(\);
tie 'attributes'\->import\('main'\, \\$r\, 'n'\)\, my $r;
\-e syntax OK

Bisect

5c906035ffb6b2857a0f941a97ac9e7bb4126275 is the first bad commit
commit 5c906035ffb6b2857a0f941a97ac9e7bb4126275
Author&#8203;: Gerard Goossen \<gerard@&#8203;ggoossen\.net>
Date&#8203;:   Sat Aug 13 18&#8203;:38&#8203;:13 2011 \+0200

&nbsp;    Propagate lvalue context only to children of list ops which are not in void context\.

&nbsp;    Children list ops might be in void context because the list is in scalar
&nbsp;    context\. A test that discarded elements in a list are not assigned lvalue
&nbsp;    context is added\.
&nbsp;    Children of a list op might also be in void context because they are
&nbsp;    special entersub ops for attributes\. This patch makes the
&nbsp;    OPpENTERSUB\_NOMOD flag redundant\.

:100644 100644 775705b55e4c0f69255527942edbf8ae7b4f0bbf c4c0e762493df04c66d924090cde0c87e2bea018 M       op\.c
:040000 040000 8b96ea734cee36175aef04088948ead0744c5b03 a5c0ce3a48597ac07dadb8340649a878dad3877b M       t
bisect run success
