### ISSUE TITLE
Assert fail in S_sublex_done without other symptoms

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15366]
Migrated from [rt.perl.org#128255](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128255) (status was 'resolved')

Searchable as RT128255$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in debug buids of the perl interpreter\. The testcase is the file below\. On normal builds\, this runs normally \(albeit with an expected warning\)\. On debug builds\, this returns an assert fail\.


dcollins@&#8203;nightshade64&#8203;:\~/perl$ \./perl \-Ilib  /usr/local/perl\-afl/out/allcrash/f1i000029
Use of comma\-less variable list is deprecated at /usr/local/perl\-afl/out/allcrash/f1i000029 line 3\.
Final $ should be \\$ or $name at /usr/local/perl\-afl/out/allcrash/f1i000029 line 3\, within string
syntax error at /usr/local/perl\-afl/out/allcrash/f1i000029 line 3\, next char /
Format not terminated at /usr/local/perl\-afl/out/allcrash/f1i000029 line 4\, at end of line
syntax error at /usr/local/perl\-afl/out/allcrash/f1i000029 line 4\, at EOF
Execution of /usr/local/perl\-afl/out/allcrash/f1i000029 aborted due to compilation errors\.

dcollins@&#8203;nightshade64&#8203;:\~/perl$ cd \.\./perldebug/
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib  /usr/local/perl\-afl/out/allcrash/f1i000029
Use of comma\-less variable list is deprecated at /usr/local/perl\-afl/out/allcrash/f1i000029 line 3\.
perl&#8203;: toke\.c&#8203;:2450&#8203;: S\_sublex\_done&#8203;: Assertion \`\(PL\_parser\->lex\_inwhat\) == OP\_SUBST || \(PL\_parser\->lex\_inwhat\) == OP\_TRANS' failed\.
Aborted

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ cat /usr/local/perl\-afl/out/allcrash/f1i000029
format=
@&#8203;
0"$"dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ od \-c /usr/local/perl\-afl/out/allcrash/f1i000029
0000000   f   o   r   m   a   t   =  \\n   @&#8203;  \\n   0   "   $   "
0000016


Debugging tool output is below\. A git bisect was performed and reported the following\.

5aa91856e21c93226d08f19eb69098f224de5fff is the first bad commit
commit 5aa91856e21c93226d08f19eb69098f224de5fff
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Mon Dec 30 21&#8203;:18&#8203;:54 2013 \-0800

&nbsp;    toke\.c&#8203;: Remove redundant check

&nbsp;    \(and turn it into an assertion\.\)

&nbsp;    PL\_lex\_repl can only be set here if we are parsing a substitution
&nbsp;    \(OP\_SUBST\) or transliteration \(OP\_TRANS\)\.  I believe this check
&nbsp;    has been unnecessary since perl 5\.000\, which it was added\.

:100644 100644 ca306f1455ba8f2c02acd3d7eff3e5490706de84 8ac0f31fb4f85c4ab453b52ec75f92900c448292 M       toke\.c
bisect run success



\*\*GDB\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ gdb \-\-args \./miniperl \-Ilib /usr/local/perl\-afl/out/allcrash/f1i000029
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \./miniperl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/miniperl \-Ilib /usr/local/perl\-afl/out/allcrash/f1i000029
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
Use of comma\-less variable list is deprecated at /usr/local/perl\-afl/out/allcrash/f1i000029 line 3\.
miniperl&#8203;: toke\.c&#8203;:2450&#8203;: S\_sublex\_done&#8203;: Assertion \`\(PL\_parser\->lex\_inwhat\) == OP\_SUBST || \(PL\_parser\->lex\_inwhat\) == OP\_TRANS' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cfa8fa in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6cf23a7 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6cf2452 in \_\_assert\_fail \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x000000000047ea40 in S\_sublex\_done \(\) at toke\.c&#8203;:2450
\#5  0x000000000048b6d5 in Perl\_yylex \(\) at toke\.c&#8203;:4728
\#6  0x00000000004ba030 in Perl\_yyparse \(gramtype=258\) at perly\.c&#8203;:332
\#7  0x00000000004475b4 in S\_parse\_body \(env=0x0\, xsinit=0x727694 \<xs\_init>\) at perl\.c&#8203;:2365
\#8  0x0000000000446052 in perl\_parse \(my\_perl=0xa7f010\, xsinit=0x727694 \<xs\_init>\, argc=3\,
&nbsp;    argv=0x7fffffffe5f8\, env=0x0\) at perl\.c&#8203;:1681
\#9  0x00000000007275f3 in main \(argc=3\, argv=0x7fffffffe5f8\, env=0x7fffffffe618\)
&nbsp;    at miniperlmain\.c&#8203;:120
\(gdb\) f 4
\#4  0x000000000047ea40 in S\_sublex\_done \(\) at toke\.c&#8203;:2450
2450            assert \(PL\_lex\_inwhat == OP\_SUBST || PL\_lex\_inwhat == OP\_TRANS\);
\(gdb\) l
2445        \}
2446
2447        /\* Is there a right\-hand side to take care of? \(s//RHS/ or tr//RHS/\) \*/
2448        assert\(PL\_lex\_inwhat \!= OP\_TRANSR\);
2449        if \(PL\_lex\_repl\) \{
2450            assert \(PL\_lex\_inwhat == OP\_SUBST || PL\_lex\_inwhat == OP\_TRANS\);
2451            PL\_linestr = PL\_lex\_repl;
2452            PL\_lex\_inpat = 0;
2453            PL\_bufend = PL\_bufptr = PL\_oldbufptr = PL\_oldoldbufptr = PL\_linestart = SvPVX\(PL\_linestr\);
2454            PL\_bufend \+= SvCUR\(PL\_linestr\);


\*\*VALGRIND\*\*

No reported memory management errors\.


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 25 subversion 2\) configuration&#8203;:
&nbsp;  Commit id&#8203;: c29dfc6a6c45f86648c51f961304254cc3c449b9
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.5\.0\-2\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 4\.5\.0\-2\-amd64 \#1 smp debian 4\.5\.3\-2 \(2016\-05\-08\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache gcc\-6\.1 \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache gcc\-6\.1'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='6\.1\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache gcc\-6\.1'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-pc\-linux\-gnu/6\.1\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_OP\_PARENT PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 26 2016 17&#8203;:57&#8203;:37
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, May 26\, 2016 at 05&#8203;:45&#8203;:05PM \-0700\, Dan Collins wrote&#8203;:
> dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib  /usr/local/perl\-afl/out/allcrash/f1i000029
> Use of comma\-less variable list is deprecated at /usr/local/perl\-afl/out/allcrash/f1i000029 line 3\.
> perl&#8203;: toke\.c&#8203;:2450&#8203;: S\_sublex\_done&#8203;: Assertion \`\(PL\_parser\->lex\_inwhat\) == OP\_SUBST || \(PL\_parser\->lex\_inwhat\) == OP\_TRANS' failed\.
> Aborted
> 
> dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ cat /usr/local/perl\-afl/out/allcrash/f1i000029
> format=
> @&#8203;

Fixed by the below&#8203;:

&nbsp;    commit 59a08c763def19a317f229e4a95b1cdf6db8e12d
&nbsp;    Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
&nbsp;    AuthorDate&#8203;: Fri Jul 8 09&#8203;:48&#8203;:04 2016 \+0100
&nbsp;    Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
&nbsp;    CommitDate&#8203;: Fri Jul 8 09&#8203;:48&#8203;:04 2016 \+0100

&nbsp;    RT \#128255&#8203;: Assert fail in S\_sublex\_done
&nbsp;    
&nbsp;    Some code that handles deprecated behaviour in formats was triggering
&nbsp;    an assertion\. This&#8203;:
&nbsp;    
&nbsp;        format STDOUT =
&nbsp;        @&#8203;
&nbsp;        0"$x"
&nbsp;    
&nbsp;    gave this warning&#8203;:
&nbsp;    
&nbsp;        Use of comma\-less variable list is deprecated
&nbsp;    
&nbsp;    but then gave this panic&#8203;:
&nbsp;    
&nbsp;        toke\.c&#8203;:2457&#8203;: S\_sublex\_done&#8203;: Assertion \`\(PL\_parser\->lex\_inwhat\) ==
&nbsp;         OP\_SUBST || \(PL\_parser\->lex\_inwhat\) == OP\_TRANS' failed\.
&nbsp;    
&nbsp;    This is due to the lexer calling scan\_str\(\)\, then backing off and doing
&nbsp;    the warning and returning a comma\, then on the next token get\, calling
&nbsp;    scan\_str\(\) again\. Because scan\_str\(\) has been called twice\, the
&nbsp;    second time it extracts the string to PL\_sublex\_info\.repl rather than
&nbsp;    PL\_lex\_stuff\, as it does with things like s/foo/bar/ and tr/abc/ABC/\.
&nbsp;    Later an assert that PL\_sublex\_info\.repl is only set for a s/// or tr///
&nbsp;    fails\.
&nbsp;    
&nbsp;    The solution seems to be to check and return a comma \*before\*
&nbsp;    trying to call scan\_str\(\)\.


\-\- 
I before E\. Except when it isn't\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
