### ISSUE TITLE
BBC: v5.43.2 breaks JDDPAUSE/re-engine-GNU-0.027.tar.gz

### ISSUE THREAD

**Issue by andk** [Perl/perl5#23660]
**Description**

With v5.43.1-271-g09a0707dc9 compilation or tests started to fail for JDDPAUSE/re-engine-GNU-0.027.tar.gz

@jddurand, you may be interested

Fail report: https://www.cpantesters.org/cpan/report/6c4a1518-8482-11f0-8725-f794ec59844f

With other perls I encountered that the compilation failed similar to this diagnostics:

``` text
cc -c  -I. -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -g   -DVERSION=\"0.027\" -DXS_VERSION=\"0.027\" -fPIC "-I/home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.43.1-271-g09a0707dc9/af11/lib/5.43.2/x86_64-linux-ld/CORE"  -DNDEBUG -DNEED_newSVpvn_flags GNU.c
In file included from GNU.xs:8:
GNU.xs: In function ‘GNU_exec_set_capture_string’:
config_REGEXP.h:415:29: error: implicit declaration of function ‘Perl_sv_setsv_cow’; did you mean ‘Perl_sv_setsv_mg’? [-Wimplicit-function-declaration]
  415 | #  define sv_setsv_cow(a,b) Perl_sv_setsv_cow(aTHX_ a,b)
      |                             ^~~~~~~~~~~~~~~~~
config_REGEXP.h:233:60: note: in definition of macro ‘REGEXP_SAVED_COPY_SET’
  233 | #  define REGEXP_SAVED_COPY_SET(r, x) ((r))->saved_copy = (x)
      |                                                            ^
GNU.xs:532:34: note: in expansion of macro ‘sv_setsv_cow’
  532 |         REGEXP_SAVED_COPY_SET(r, sv_setsv_cow(REGEXP_SAVED_COPY_GET(r), sv));
      |                                  ^~~~~~~~~~~~
config_REGEXP.h:233:57: error: assignment to ‘SV *’ {aka ‘struct sv *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  233 | #  define REGEXP_SAVED_COPY_SET(r, x) ((r))->saved_copy = (x)
      |                                                         ^
GNU.xs:532:9: note: in expansion of macro ‘REGEXP_SAVED_COPY_SET’
  532 |         REGEXP_SAVED_COPY_SET(r, sv_setsv_cow(REGEXP_SAVED_COPY_GET(r), sv));
      |         ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:366: GNU.o] Error 1

```

Bisect says:
```
  : 09a0707dc9ae215635d8841c65f4fec4d52b7005 is the first bad commit
  : commit 09a0707dc9ae215635d8841c65f4fec4d52b7005
  : Author: Karl Williamson <khw@cpan.org>
  : Date:   Wed Aug 13 08:50:40 2025 -0600
  : 
  :     Hide function prototyes from unauthorized callers
  :     
  :     0351a629e71de127cbfd1b142e9eaa6069deabf5 extended hiding private
  :     functions from callers into the gcc world.
  :     
  :     Some functions are allowed only in extensions; so can not be marked as
  :     hidden; this commit discourages their use however, by hiding their
  :     prototypes to all but the core and extensions.
  :     
  :     It turns out that four functions were being used in modules we ship
  :     with that were marked as extensions-only; so they had to be made
  :     globally accessible.
  : 
  :  embed.fnc      |    8 +-
  :  proto.h        | 1313 ++++++++++++++++++++++++++++++--------------------------
  :  regen/embed.pl |   12 +
  :  3 files changed, 721 insertions(+), 612 deletions(-)

```

XRef to also affected CPAN module Syntax::Keyword::Try: https://github.com/Perl/perl5/issues/23609

**Steps to Reproduce**

`cpan -i  JDDPAUSE/re-engine-GNU-0.027.tar.gz`

**Expected behavior**

compiled and tested OK beofre this commit

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 43 subversion 2) configuration:
  Commit id: 7afd3f158f75d5730469889406f8f98c681d58c1
  Platform:
    osname=linux
    osvers=6.8.0-64-generic
    archname=x86_64-linux-thread-multi-ld
    uname='linux k93jammy 6.8.0-64-generic #67~22.04.1-ubuntu smp preempt_dynamic tue jun 24 15:19:46 utc 2 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93jammy/v5.43.2/322f -Dmyhostname=k93jammy -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Duseithreads -Duselongdouble -DEBUGGING=-g'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=define
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='long double'
    nvsize=16
    Off_t='off_t'
    lseeksize=8
    alignbytes=16
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.35'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_LONG_DOUBLE
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Aug 24 2025 21:41:08
  %ENV:
    PERL5LIB="/tmp/loop_over_bdir-2028519-o2k9uA/AllKnowingDNS-1.7-0/blib/arch:/tmp/loop_over_bdir-2028519-o2k9uA/AllKnowingDNS-1.7-0/blib/lib:/tmp/loop_over_bdir-2028519-o2k9uA/Devel-Required-0.17-0/blib/arch:/tmp/loop_over_bdir-2028519-o2k9uA/Devel-Required-0.17-0/blib/lib:/tmp/loop_over_bdir-2028519-o2k9uA/dta-tokwrap-0.98-0/blib/arch:/tmp/loop_over_bdir-2028519-o2k9uA/dta-tokwrap-0.98-0/blib/lib"
    PERL5OPT=""
    PERL5_CPANPLUS_IS_RUNNING="2028527"
    PERL5_CPAN_IS_RUNNING="2028527"
    PERL_CANARY_STABILITY_NOPROMPT="1"
    PERL_MM_USE_DEFAULT="1"
    PERL_USE_UNSAFE_INC="1"
  @INC:
    /tmp/loop_over_bdir-2028519-o2k9uA/AllKnowingDNS-1.7-0/blib/arch
    /tmp/loop_over_bdir-2028519-o2k9uA/AllKnowingDNS-1.7-0/blib/lib
    /tmp/loop_over_bdir-2028519-o2k9uA/Devel-Required-0.17-0/blib/arch
    /tmp/loop_over_bdir-2028519-o2k9uA/Devel-Required-0.17-0/blib/lib
    /tmp/loop_over_bdir-2028519-o2k9uA/dta-tokwrap-0.98-0/blib/arch
    /tmp/loop_over_bdir-2028519-o2k9uA/dta-tokwrap-0.98-0/blib/lib
    /home/sand/src/perl/repoperls/installed-perls/host/k93jammy/v5.43.2/322f/lib/site_perl/5.43.2/x86_64-linux-thread-multi-ld
    /home/sand/src/perl/repoperls/installed-perls/host/k93jammy/v5.43.2/322f/lib/site_perl/5.43.2
    /home/sand/src/perl/repoperls/installed-perls/host/k93jammy/v5.43.2/322f/lib/5.43.2/x86_64-linux-thread-multi-ld
    /home/sand/src/perl/repoperls/installed-perls/host/k93jammy/v5.43.2/322f/lib/5.43.2
    .
```

**Comment by jkeenan** [comment]
On **FreeBSD-14** (clang18, threaded), I attempted to install this distro against perl at v5.43.2-63-g3c2e356191.  I got 58 build-time warnings and then one error:
```
$ report-build-warnings re-engine-gnu-make-failure-output-20250830.txt 
File:  re-engine-gnu-make-failure-output-20250830.txt

  Wimplicit-function-declaration             1
  Wunused-value                             57

$ make
...
GNU.xs:532:9: error: incompatible integer to pointer conversion assigning to 'SV *' (aka 'struct sv *') from 'int' [-Wint-conversion]
  532 |         REGEXP_SAVED_COPY_SET(r, sv_setsv_cow(REGEXP_SAVED_COPY_GET(r), sv));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./config_REGEXP.h:233:57: note: expanded from macro 'REGEXP_SAVED_COPY_SET'
  233 | #  define REGEXP_SAVED_COPY_SET(r, x) ((r))->saved_copy = (x)
      |                                                         ^ ~~~
58 warnings and 1 error generated.
*** Error code 1
```
Report: https://www.cpantesters.org/cpan/report/5ce2f71a-85b9-11f0-a3d5-c2aa043161e2

On **Debian Linux** (gcc-12, unthreaded), the build completed, albeit with warnings ...
```
cc -c  -I. -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2   -DVERSION=\"0.027\" -DXS_VERSION=\"0.027\" -fPIC "-I/home/jkeenan/testing/blead/lib/perl5/5.43.3/x86_64-linux/CORE"  -DNDEBUG -DNEED_newSVpvn_flags GNU.c
In file included from GNU.xs:8:
GNU.xs: In function ‘GNU_exec_set_capture_string’:
config_REGEXP.h:415:29: warning: implicit declaration of function ‘Perl_sv_setsv_cow’; did you mean ‘Perl_sv_setsv_mg’? [-Wimplicit-function-declaration]
  415 | #  define sv_setsv_cow(a,b) Perl_sv_setsv_cow(aTHX_ a,b)
      |                             ^~~~~~~~~~~~~~~~~
config_REGEXP.h:233:60: note: in definition of macro ‘REGEXP_SAVED_COPY_SET’
  233 | #  define REGEXP_SAVED_COPY_SET(r, x) ((r))->saved_copy = (x)
      |                                                            ^
GNU.xs:532:34: note: in expansion of macro ‘sv_setsv_cow’
  532 |         REGEXP_SAVED_COPY_SET(r, sv_setsv_cow(REGEXP_SAVED_COPY_GET(r), sv));
      |                                  ^~~~~~~~~~~~
config_REGEXP.h:233:57: warning: assignment to ‘SV *’ {aka ‘struct sv *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  233 | #  define REGEXP_SAVED_COPY_SET(r, x) ((r))->saved_copy = (x)
      |                                                         ^
GNU.xs:532:9: note: in expansion of macro ‘REGEXP_SAVED_COPY_SET’
  532 |         REGEXP_SAVED_COPY_SET(r, sv_setsv_cow(REGEXP_SAVED_COPY_GET(r), sv));
      |         ^~~~~~~~~~~~~~~~~~~~~
rm -f blib/arch/auto/re/engine/GNU/GNU.so
cc  -shared -O2 -L/usr/local/lib -fstack-protector-strong  GNU.o  -o blib/arch/auto/re/engine/GNU/GNU.so  \
      \
  
chmod 755 blib/arch/auto/re/engine/GNU/GNU.so
(/usr/bin/make exited with 0)
CPAN::Reporter: make result is 'pass', No errors.
  JDDPAUSE/re-engine-GNU-0.027.tar.gz
  /usr/bin/make -- OK
```
... but:
```
t/re-engine-GNU.t ...... 
Failed 20/60 subtests 
```
Report: https://www.cpantesters.org/cpan/report/e6669398-85b9-11f0-8865-de5d91c9318b
@khwilliamson

**Comment by khwilliamson** [comment]
As in #23609, this module is using this undocumented internal function which it is not authorized to do.   The blamed commit was intended to catch such usages.

This function appears to have been designed solely for the use of the core pattern matching code.

We need to decide:
1.  if this function should be made available to all code.  If so, it should be documented.   
2. If not, does this module need something like this functionality?  If so, what API should be created to furnish that. 
3.  If not,  what to do?

**Comment by Leont** [comment]
> We need to decide:
>
> if this function should be made available to all code. If so, it should be documented.
> If not, does this module need something like this functionality? If so, what API should be created to furnish that.
> If not, what to do?

This sounds like a reasonable piece of functionality to want, I don't know if it's the right interface to make it API or not (opinions welcome). #23625 seems related to that question.

**Comment by Leont** [comment]
@khwilliamson do you happen to have an opinion on this?

I can't help noticing this function takes an SV as its first argument argument that will be returned if not null (and a new one will be created if it is null). It kind of doubles as `sv_setsv_cow` and `sv_newsv_cow`. I think I can see how that's useful in this particular use-case, but is that something we want in general when we make this an API?

**Comment by khwilliamson** [comment]
I think @tonycoz is better at this than I

**Comment by tonycoz** [comment]
The function itself is pretty bad, CoW copying SVs that we wouldn't normally otherwise CoW, though preventing that breaks other things.

**Comment by khwilliamson** [comment]
We can change the visibility to 'C' which means it is considered Core, but has to be nonetheless visible everywhere; and we can add the 'x' flag to indicate its interface can change.  That would get this to not be a release blocker, and wouldn't encourage others to start using it.

In 5.45, we could then more leisurely figure out what to do beyond.

**Comment by leonerd** [comment]
@khwilliamson Sounds reasonable; make it `Cx` now and we'll deal with it later

**Comment by jkeenan** [comment]
@khwiliamson wrote:

> We can change the visibility to 'C' which means it is considered Core, but has to be nonetheless visible everywhere; and we can add the 'x' flag to indicate its interface can change. That would get this to not be a release blocker, and wouldn't encourage others to start using it.
> 
> In 5.45, we could then more leisurely figure out what to do beyond.

@leonerd responded:

> [@khwilliamson](https://github.com/khwilliamson) Sounds reasonable; make it `Cx` now and we'll deal with it later

However, as yet I don't see any pull request implementing this idea.  Consequently, re-engine-GNU is still segfaulting.
```
Test Summary Report
-------------------
t/re-engine-GNU.t    (Wstat: 139 (Signal: SEGV, dumped core) Tests: 40 Failed: 0)
  Non-zero wait status: 139
  Parse errors: Bad plan.  You planned 60 tests but ran 40.
t/thread.t           (Wstat: 139 (Signal: SEGV, dumped core) Tests: 1 Failed: 0)
  Non-zero wait status: 139
  Parse errors: Bad plan.  You planned 76 tests but ran 1.
Files=4, Tests=43,  2 wallclock secs ( 0.02 usr  0.00 sys +  0.19 cusr  0.03 csys =  0.24 CPU)
Result: FAIL
Failed 2/4 test programs. 0/43 subtests failed.
make: *** [Makefile:1097: test_dynamic] Error 255
  JDDPAUSE/re-engine-GNU-0.027.tar.gz
```

**Comment by khwilliamson** [comment]
Sorry.  I forgot to hit SEND.  https://github.com/Perl/perl5/pull/24371

**Comment by jddurand** [comment]
Many thanks to all for the work on this ticket.

**Comment by jkeenan** [comment]
I tested this module against perl-5.43.10 today on both Linux and FreeBSD.  Failed on both platforms.  Example: Linux: https://www.cpantesters.org/cpan/report/3a5fe9dc-3cb1-11f1-bf0d-dbb6afd52ec6
