### ISSUE TITLE
5.10.1: regression regarding bareword in readline()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9826]
Migrated from [rt.perl.org#68458](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=68458) (status was 'resolved')

Searchable as RT68458$

**Comment by p5pRT** [comment]
### From eserte@biokovo-amd64.herceg.de

This is a bug report for perl from eserte@&#8203;biokovo\-amd64\.herceg\.de\,
generated with the help of perlbug 1\.39 running under perl 5\.10\.1\.




---
The following script

\#\!/usr/bin/perl
use strict;
my $file;
open\(FILE\, $file\);
my $fline = readline\(FILE\);
\_\_END\_\_

compiles under 5\.10\.0 but not under 5\.10\.1\-to\-be&#8203;:

$ /usr/perl\-5\.10\.0\-3220\-gf9961a0/bin/perl \-c readline\.pl
Bareword "FILE" not allowed while "strict subs" in use at readline\.pl line 7\.
readline\.pl had compilation errors\.
Exitcode 9

git bisect says that the breakage occurred in
109c3d50375e96ee005ac98a3d457c7da2f5cb08 in the maint\-5\.10 branch\,
respective in 984f9f66477bc722578262ae8520584e44e881af in the blead
branch\.

This breaks at least the CPAN distribution MySQL\-Backup\-0\.04\.

Ah\, a shorter way to reproduce this&#8203;:
/usr/perl\-5\.10\.0\-3220\-gf9961a0/bin/perl \-c \-e 'use strict; readline\(STDIN\)'

\(Later\)

I found another CPAN distribution with the same problem&#8203;: Tie\-Simple\-1\.03

And there's another bareword problem\, found in Games\-Go\-GoPair\-1\.001\.
With the script

&nbsp;    use strict;
&nbsp;    my @&#8203;players;
&nbsp;    sub \_rankCompare \{ \}
&nbsp;    @&#8203;players = sort\(\_rankCompare @&#8203;players\);

one also gets a bareword error&#8203;:

Bareword "\_rankCompare" not allowed while "strict subs" in use at /tmp/sort1\.pl line 18\.

Regards\,
&nbsp;    Slaven



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl 5\.10\.1&#8203;:

Configured by eserte at Tue Aug  4 10&#8203;:38&#8203;:36 CEST 2009\.

Summary of my perl5 \(revision 5 version 10 subversion 1\) configuration&#8203;:
&nbsp;  Commit id&#8203;: f9961a059c818ac71464be22671a6aeb834e3c87
&nbsp;  Platform&#8203;:
&nbsp;    osname=freebsd\, osvers=7\.0\-release\, archname=amd64\-freebsd
&nbsp;    uname='freebsd biokovo\-amd64\.herceg\.de 7\.0\-release freebsd 7\.0\-release \#0&#8203;: sun feb 24 10&#8203;:35&#8203;:36 utc 2008 root@&#8203;driscoll\.cse\.buffalo\.edu&#8203;:usrobjusrsrcsysgeneric amd64 '
&nbsp;    config\_args='\-Dprefix=/usr/perl\-5\.10\.0\-3220\-gf9961a0 \-Dusemymalloc=n \-D cc=ccache cc \-Dgccansipedantic \-de'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache cc'\, ccflags ='\-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'\,
&nbsp;    optimize='\-O'\,
&nbsp;    cppflags='\-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.2\.1 20070719  \[FreeBSD\]'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache cc'\, ldflags ='\-Wl\,\-E  \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/lib /usr/local/lib
&nbsp;    libs=\-lgdbm \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags='\-DPIC \-fPIC'\, lddlflags='\-shared  \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    PERL\_GIT\_UNPUSHED\_COMMITS        /\* do not remove this line \*/
&nbsp;    PERL\_GIT\_UNCOMMITTED\_CHANGES    /\* do not remove this line \*/



---
@&#8203;INC for perl 5\.10\.1&#8203;:
&nbsp;    /usr/perl\-5\.10\.0\-3220\-gf9961a0/lib/5\.10\.1/amd64\-freebsd
&nbsp;    /usr/perl\-5\.10\.0\-3220\-gf9961a0/lib/5\.10\.1
&nbsp;    /usr/perl\-5\.10\.0\-3220\-gf9961a0/lib/site\_perl/5\.10\.1/amd64\-freebsd
&nbsp;    /usr/perl\-5\.10\.0\-3220\-gf9961a0/lib/site\_perl/5\.10\.1
&nbsp;    \.



---
Environment for perl 5\.10\.1&#8203;:
&nbsp;    HOME=/home/e/eserte
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_ALL=de\_DE\.ISO8859\-1
&nbsp;    LC\_CTYPE=de\_DE\.ISO8859\-1
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/gnu/bin&#8203;:/usr/TeX/bin&#8203;:/usr/local/sbin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/local/pilot/bin&#8203;:/home/e/eserte/bin/FreeBSD&#8203;:/home/e/eserte/bin/sh&#8203;:/home/e/eserte/bin&#8203;:/usr/X11R6/bin&#8203;:/usr/X11/bin&#8203;:/usr/X386/bin&#8203;:/usr/games&#8203;:/home/e/eserte/devel
&nbsp;    PERLDOC=\-MPod&#8203;::Perldoc&#8203;::ToTextOverstrike
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    PERL\_HTML\_DISPLAY\_CLASS=HTML&#8203;::Display&#8203;::Mozilla
&nbsp;    SHELL=/bin/tcsh

**Comment by p5pRT** [comment]
### From @obra




On Wed\, Aug 12\, 2009 at 11&#8203;:54&#8203;:58AM \-0700\, eserte@&#8203;biokovo\-amd64\.herceg\.de \(via RT\) wrote&#8203;:
> This is a bug report for perl from eserte@&#8203;biokovo\-amd64\.herceg\.de\,
> generated with the help of perlbug 1\.39 running under perl 5\.10\.1\.
>

Failing tests for this issue were added in commit cb4bdfcf\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @nwc10

On Wed\, Aug 12\, 2009 at 07&#8203;:51&#8203;:25PM \-0400\, jesse wrote&#8203;:
> 
> 
> 
> On Wed\, Aug 12\, 2009 at 11&#8203;:54&#8203;:58AM \-0700\, eserte@&#8203;biokovo\-amd64\.herceg\.de \(via RT\) wrote&#8203;:
> > This is a bug report for perl from eserte@&#8203;biokovo\-amd64\.herceg\.de\,
> > generated with the help of perlbug 1\.39 running under perl 5\.10\.1\.
> >
> 
> Failing tests for this issue were added in commit cb4bdfcf\.

And as they're not likely to get fixed in blead within the next few weeks\,
let alone the next few days\* I marked them as TODO in 972ee0bb

Nicholas Clark

\* Go on list subscribers\, prove me wrong\.

**Comment by p5pRT** [comment]
### From @rgs

2009/8/13 Nicholas Clark \<nick@&#8203;ccl4\.org>&#8203;:
> On Wed\, Aug 12\, 2009 at 07&#8203;:51&#8203;:25PM \-0400\, jesse wrote&#8203;:
>>
>>
>>
>> On Wed\, Aug 12\, 2009 at 11&#8203;:54&#8203;:58AM \-0700\, eserte@&#8203;biokovo\-amd64\.herceg\.de \(via RT\) wrote&#8203;:
>> > This is a bug report for perl from eserte@&#8203;biokovo\-amd64\.herceg\.de\,
>> > generated with the help of perlbug 1\.39 running under perl 5\.10\.1\.
>> >
>>
>> Failing tests for this issue were added in commit cb4bdfcf\.
>
> And as they're not likely to get fixed in blead within the next few weeks\,
> let alone the next few days\* I marked them as TODO in 972ee0bb
>
> Nicholas Clark
>
> \* Go on list subscribers\, prove me wrong\.

Ok\. The following patch should make everyone happy\.\.\.

commit 9a073a1d1a270eb53990cb82ec7af8ae00d667c4
Author&#8203;: Rafael Garcia\-Suarez \<rgarciasuarez@&#8203;gmail\.com>
Date&#8203;:   Sun Aug 23 15&#8203;:28&#8203;:22 2009 \+0200

&nbsp;    Fix parsing of readline\(FH\) \[perl \#68458\]

&nbsp;    This was broken by commit 984f9f66477bc722578262ae8520584e44e881af\,
&nbsp;    which was committed to solve bug \[perl \#53806\]\.

&nbsp;    Basically\, to make everyone happy\, we need only to enforce strictures
&nbsp;    on barewords that follow the specially parsed keywords "print" and
&nbsp;    "exec" \(and similar\) \-\- except when they have been already parsed\.

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'
