### ISSUE TITLE
all XS functions are implicitly :lvalue

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12955]
Migrated from [rt.perl.org#117947](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=117947) (status was 'resolved')

Searchable as RT117947$

**Comment by p5pRT** [comment]
### From @mauke

#### Created by @mauke



The following problem was found by yko \(Yaroslav Korshak\)&#8203;:

% perl \-wle 'use List&#8203;::Util qw\(maxstr\); List&#8203;::Util\->maxstr\($\_ = "hi"\) = 42; print'
42

% \./perl \-v
This is perl 5\, version 17\, subversion 11 \(v5\.17\.11 \(v5\.17\.10\-74\-g4702594\*\)\) built for i686\-linux
\.\.\.

% \./perl \-Ilib \-wle 'use List&#8203;::Util qw\(maxstr\); List&#8203;::Util\->maxstr\($\_ = "hi"\) = 42; print'
42

Apparently starting with version 16 perl thinks that all XS functions return lvalues\.

For comparison\, the expected result \(here with 5\.12\.4\)&#8203;:
$ perl \-wle 'use List&#8203;::Util qw\(maxstr\); print List&#8203;::Util\->maxstr\("hi"\) = 42; print'
Can't modify non\-lvalue subroutine call at \-e line 1\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

This perlbug was built using Perl 5.12.1 - Thu Jun  3 20:09:15 CEST 2010
It is being executed now by  Perl 5.16.3 - Sun Mar 24 20:23:51 CET 2013.

Site configuration information for perl 5.16.3:

Configured by mauke at Sun Mar 24 20:23:51 CET 2013.

Summary of my perl5 (revision 5 version 16 subversion 3) configuration:
   
  Platform:
    osname=linux, osvers=3.5.7-gentoo, archname=i686-linux
    uname='linux nora 3.5.7-gentoo #5 preempt sat jan 26 16:46:10 cet 2013 i686 amd athlon(tm) 64 processor 3200+ authenticamd gnulinux '
    config_args=''
    hint=previous, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -flto',
    cppflags='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    ccversion='', gccversion='4.8.0', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags ='-fstack-protector -L/usr/local/lib -O2 -flto'
    libpth=/usr/local/lib /lib/../lib /usr/lib/../lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.15.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.15'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -flto -L/usr/local/lib -fstack-protector'

Locally applied patches:
    SAVEARGV0 - disable magic open in <ARGV>


@INC for perl 5.16.3:
    /home/mauke/usr/local/lib/perl5/site_perl/5.16.3/i686-linux
    /home/mauke/usr/local/lib/perl5/site_perl/5.16.3
    /home/mauke/usr/local/lib/perl5/5.16.3/i686-linux
    /home/mauke/usr/local/lib/perl5/5.16.3
    /home/mauke/usr/local/lib/perl5/site_perl/5.16.0/i686-linux
    /home/mauke/usr/local/lib/perl5/site_perl/5.16.0
    /home/mauke/usr/local/lib/perl5/site_perl
    .


Environment for perl 5.16.3:
    HOME=/home/mauke
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_COLLATE=POSIX
    LD_LIBRARY_PATH=/home/mauke/usr/local/lib
    LOGDIR (unset)
    PATH=/home/mauke/usr/perlbrew/bin:/home/mauke/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/i686-pc-linux-gnu/gcc-bin/4.6.3:/opt/sun-jdk-1.4.2.13/bin:/opt/sun-jdk-1.4.2.13/jre/bin:/opt/sun-jdk-1.4.2.13/jre/javaws:/opt/dmd/bin:/usr/games/bin
    PERLBREW_BASHRC_VERSION=0.43
    PERLBREW_HOME=/home/mauke/.perlbrew
    PERLBREW_PATH=/home/mauke/usr/perlbrew/bin
    PERLBREW_ROOT=/home/mauke/usr/perlbrew
    PERLBREW_VERSION=0.27
    PERL_BADLANG (unset)
    PERL_UNICODE=SAL
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @rgarcia

On 10 May 2013 17&#8203;:59\, l\.mai@&#8203;web\.de \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> The following problem was found by yko \(Yaroslav Korshak\)&#8203;:
>
> % perl \-wle 'use List&#8203;::Util qw\(maxstr\); List&#8203;::Util\->maxstr\($\_ = "hi"\) = 42; print'
> 42

maxstr is not a method; if you use List&#8203;::Util&#8203;::maxstr\(\) instead\, it
complains as it should&#8203;:

~§ perl \-wle 'use List&#8203;::Util qw\(maxstr\); List&#8203;::Util&#8203;::maxstr\($\_ = "hi"\)
= 42; print'
Can't modify non\-lvalue subroutine call in scalar assignment at \-e
line 1\, near "42;"
Execution of \-e aborted due to compilation errors\.

That said\, we actually seem to have a problem with XS functions called
as methods\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @Leont

On Mon\, May 13\, 2013 at 1&#8203;:28 PM\, Rafael Garcia\-Suarez \<rgs@&#8203;consttype\.org> wrote&#8203;:
> maxstr is not a method; if you use List&#8203;::Util&#8203;::maxstr\(\) instead\, it
> complains as it should&#8203;:
>
> ~§ perl \-wle 'use List&#8203;::Util qw\(maxstr\); List&#8203;::Util&#8203;::maxstr\($\_ = "hi"\)
> = 42; print'
> Can't modify non\-lvalue subroutine call in scalar assignment at \-e
> line 1\, near "42;"
> Execution of \-e aborted due to compilation errors\.
>
> That said\, we actually seem to have a problem with XS functions called
> as methods\.

Yeah\, the keywords there seems to be "compilation errors"\. For methods
we have to detect this at runtime…

Leon

**Comment by p5pRT** [comment]
### From @mauke

I ran bisect\.pl and it ended with&#8203;:

da1dff9483c6c62608e52ee5f466381813d929ff is the first bad commit
commit da1dff9483c6c62608e52ee5f466381813d929ff
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Mon Dec 26 13&#8203;:25&#8203;:31 2011 \-0800

&nbsp;    Fix two \(er\, four\) sub&#8203;:lvalue \{ &$x \} bugs

\.\.\.

**Comment by p5pRT** [comment]
### From @mauke

On 13\.05\.2013 14&#8203;:12\, Leon Timmermans wrote&#8203;:
> On Mon\, May 13\, 2013 at 1&#8203;:28 PM\, Rafael Garcia\-Suarez \<rgs@&#8203;consttype\.org> wrote&#8203;:
>> maxstr is not a method; if you use List&#8203;::Util&#8203;::maxstr\(\) instead\, it
>> complains as it should&#8203;:
>>
>> ~§ perl \-wle 'use List&#8203;::Util qw\(maxstr\); List&#8203;::Util&#8203;::maxstr\($\_ = "hi"\)
>> = 42; print'
>> Can't modify non\-lvalue subroutine call in scalar assignment at \-e
>> line 1\, near "42;"
>> Execution of \-e aborted due to compilation errors\.
>>
>> That said\, we actually seem to have a problem with XS functions called
>> as methods\.
>
> Yeah\, the keywords there seems to be "compilation errors"\. For methods
> we have to detect this at runtime…

Yes\, this is about calls that can't be resolved \(and rejected\) at 
compile time\. It affects all method calls but also this&#8203;:

% perl \-wle 'use List&#8203;::Util qw\(maxstr\); \(\\&maxstr\)\->\($\_ = "hi"\) = 42; print'
42

i\.e\. calls through a reference\.


\-\- 
Lukas Mai \<plokinom@&#8203;gmail\.com>

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon May 13 12&#8203;:18&#8203;:21 2013\, plokinom@&#8203;gmail\.com wrote&#8203;:
> On 13\.05\.2013 14&#8203;:12\, Leon Timmermans wrote&#8203;:
> > On Mon\, May 13\, 2013 at 1&#8203;:28 PM\, Rafael Garcia\-Suarez
> \<rgs@&#8203;consttype\.org> wrote&#8203;:
> >> maxstr is not a method; if you use List&#8203;::Util&#8203;::maxstr\(\) instead\, it
> >> complains as it should&#8203;:
> >>
> >> ~§ perl \-wle 'use List&#8203;::Util qw\(maxstr\); List&#8203;::Util&#8203;::maxstr\($\_ =
> "hi"\)
> >> = 42; print'
> >> Can't modify non\-lvalue subroutine call in scalar assignment at \-e
> >> line 1\, near "42;"
> >> Execution of \-e aborted due to compilation errors\.
> >>
> >> That said\, we actually seem to have a problem with XS functions
> called
> >> as methods\.
> >
> > Yeah\, the keywords there seems to be "compilation errors"\. For
> methods
> > we have to detect this at runtime…
> 
> Yes\, this is about calls that can't be resolved \(and rejected\) at
> compile time\. It affects all method calls but also this&#8203;:
> 
> % perl \-wle 'use List&#8203;::Util qw\(maxstr\); \(\\&maxstr\)\->\($\_ = "hi"\) = 42;
> print'
> 42
> 
> i\.e\. calls through a reference\.

I’ve just fixed this in 4587c5322c964b\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @mauke

On 28\.05\.2013 03&#8203;:03\, Father Chrysostomos via RT wrote&#8203;:
> According to our records\, your request regarding
>    "all XS functions are implicitly :lvalue"
> has been resolved\.
>
> If you have any further questions or concerns\, please respond to this message\.
>

Nice\, thanks for the quick fix\! Will this be in 5\.18\.1?

\-\- 
Lukas Mai \<l\.mai@&#8203;web\.de>

**Comment by p5pRT** [comment]
### From @tsee

On 05/28/2013 07&#8203;:35 AM\, Lukas Mai wrote&#8203;:
> On 28\.05\.2013 03&#8203;:03\, Father Chrysostomos via RT wrote&#8203;:
>> According to our records\, your request regarding
>>    "all XS functions are implicitly :lvalue"
>> has been resolved\.
>>
>> If you have any further questions or concerns\, please respond to this
>> message\.
>>
>
> Nice\, thanks for the quick fix\! Will this be in 5\.18\.1?

IIRC it was in 5\.16\.3\, so not a 5\.18 regression\. It doesn't affect 
portability\. It's not a security concern\.

My reading of the policy is that it won't be in 5\.18\.1\, I am afraid\. I'd 
be open to an exception if there was a good case for it \(but in the end\, 
Rik's the one to decide\)\.

\-\-Steffen

**Comment by p5pRT** [comment]
### From @nwc10

On Wed\, Jun 05\, 2013 at 07&#8203;:47&#8203;:12AM \+0200\, Steffen Mueller wrote&#8203;:
> On 05/28/2013 07&#8203;:35 AM\, Lukas Mai wrote&#8203;:
> > On 28\.05\.2013 03&#8203;:03\, Father Chrysostomos via RT wrote&#8203;:
> >> According to our records\, your request regarding
> >>    "all XS functions are implicitly :lvalue"
> >> has been resolved\.
> >>
> >> If you have any further questions or concerns\, please respond to this
> >> message\.
> >>
> >
> > Nice\, thanks for the quick fix\! Will this be in 5\.18\.1?
> 
> IIRC it was in 5\.16\.3\, so not a 5\.18 regression\. It doesn't affect 
> portability\. It's not a security concern\.
> 
> My reading of the policy is that it won't be in 5\.18\.1\, I am afraid\. I'd 
> be open to an exception if there was a good case for it \(but in the end\, 
> Rik's the one to decide\)\.

But as it's a 5\.16\.x regression \(ie compared with 5\.14\.x\) it should be
backported to 5\.16\.4?

I'm somewhat playing devil's advocate here\. The paragraph in question in
perlpolicy that you are reading is this?

&nbsp;    Patches that fix regressions in perl's behavior relative to previous
&nbsp;    releases are acceptable\.

In which case "release\*s\*" suggests to me that it's fair game to consider
further than 5\.14\.0\. But in the end\, pragmatism needs to win\, and it's
Ricardo's call on what's pragmatic\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @xdg

On Wed\, Jun 5\, 2013 at 10&#8203;:13 AM\, Nicholas Clark \<nick@&#8203;ccl4\.org> wrote&#8203;:
> In which case "release\*s\*" suggests to me that it's fair game to consider
> further than 5\.14\.0\. But in the end\, pragmatism needs to win\, and it's
> Ricardo's call on what's pragmatic\.

FWIW\, I think we should backport it to all relevant maint releases\.

David


\-\-
David Golden \<xdg@&#8203;xdg\.me>
Take back your inbox\! → http&#8203;://www\.bunchmail\.com/
Twitter/IRC&#8203;: @&#8203;xdg

**Comment by p5pRT** [comment]
### From @nwc10

On Wed\, Jun 05\, 2013 at 10&#8203;:25&#8203;:53AM \-0400\, David Golden wrote&#8203;:
> On Wed\, Jun 5\, 2013 at 10&#8203;:13 AM\, Nicholas Clark \<nick@&#8203;ccl4\.org> wrote&#8203;:
> > In which case "release\*s\*" suggests to me that it's fair game to consider
> > further than 5\.14\.0\. But in the end\, pragmatism needs to win\, and it's
> > Ricardo's call on what's pragmatic\.
> 
> FWIW\, I think we should backport it to all relevant maint releases\.

Yes\, I forgot to say\, that this looks like the thing to do\, as it's a
small change\, seemingly self contained\, and fixes a subtle bug which is
going to trip people up\. \(If it isn't already\)

Nicholas Clark

**Comment by p5pRT** [comment]
### From @cpansprout

On Wed Jun 05 07&#8203;:34&#8203;:10 2013\, nicholas wrote&#8203;:
> On Wed\, Jun 05\, 2013 at 10&#8203;:25&#8203;:53AM \-0400\, David Golden wrote&#8203;:
> > On Wed\, Jun 5\, 2013 at 10&#8203;:13 AM\, Nicholas Clark \<nick@&#8203;ccl4\.org>
> wrote&#8203;:
> > > In which case "release\*s\*" suggests to me that it's fair game to
> consider
> > > further than 5\.14\.0\. But in the end\, pragmatism needs to win\, and
> it's
> > > Ricardo's call on what's pragmatic\.
> >
> > FWIW\, I think we should backport it to all relevant maint releases\.
> 
> Yes\, I forgot to say\, that this looks like the thing to do\, as it's a
> small change\, seemingly self contained\, and fixes a subtle bug which
> is
> going to trip people up\. \(If it isn't already\)

I have back\-ported it to maint\-5\.18 as dffdb99 and to maint\-5\.16 as
e5da327237289669\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

On Wed Jun 05 21&#8203;:33&#8203;:49 2013\, sprout wrote&#8203;:
> On Wed Jun 05 07&#8203;:34&#8203;:10 2013\, nicholas wrote&#8203;:
> > On Wed\, Jun 05\, 2013 at 10&#8203;:25&#8203;:53AM \-0400\, David Golden wrote&#8203;:
> > > On Wed\, Jun 5\, 2013 at 10&#8203;:13 AM\, Nicholas Clark \<nick@&#8203;ccl4\.org>
> > wrote&#8203;:
> > > > In which case "release\*s\*" suggests to me that it's fair game to
> > consider
> > > > further than 5\.14\.0\. But in the end\, pragmatism needs to win\, and
> > it's
> > > > Ricardo's call on what's pragmatic\.
> > >
> > > FWIW\, I think we should backport it to all relevant maint releases\.
> > 
> > Yes\, I forgot to say\, that this looks like the thing to do\, as it's a
> > small change\, seemingly self contained\, and fixes a subtle bug which
> > is
> > going to trip people up\. \(If it isn't already\)
> 
> I have back\-ported it to maint\-5\.18 as dffdb99 and to maint\-5\.16 as
> e5da327237289669\.

But I seem unable to get into cherrymaint\.  Is it down\, or has the
address changed?

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @rjbs

\* David Golden \<xdg@&#8203;xdg\.me> \[2013\-06\-05T10&#8203;:25&#8203;:53\]
> FWIW\, I think we should backport it to all relevant maint releases\.

It's already done\, but \+1 for the record\.

\-\- 
rjbs

**Comment by p5pRT** [comment]
### From @rjbs

\* Father Chrysostomos via RT \<perlbug\-followup@&#8203;perl\.org> \[2013\-06\-06T00&#8203;:38&#8203;:35\]
> But I seem unable to get into cherrymaint\.  Is it down\, or has the
> address changed?

We haven't used that in some time\.  We've discussed recommencing\, but for the
most part have used quick list threads or the "blocking 5\.x\.y" tickets instead\.

\-\- 
rjbs

**Comment by p5pRT** [comment]
### From @cpansprout

On Fri Jun 07 07&#8203;:31&#8203;:27 2013\, perl\.p5p@&#8203;rjbs\.manxome\.org wrote&#8203;:
> \* Father Chrysostomos via RT \<perlbug\-followup@&#8203;perl\.org> \[2013\-06\-
> 06T00&#8203;:38&#8203;:35\]
> > But I seem unable to get into cherrymaint\.  Is it down\, or has the
> > address changed?
> 
> We haven't used that in some time\.  We've discussed recommencing\, but
> for the
> most part have used quick list threads or the "blocking 5\.x\.y" tickets
> instead\.

That actually makes this easier\, if you ask me\.  I was going to mark
this in cherrymaint simply as a courtesy\, but now I am saved the bother\.

\-\- 

Father Chrysostomos
