### ISSUE TITLE
Convert::ASN1 breaks with commit 2583ef601d381a8a3e6e9b5f44db42bac0d537ab 

### ISSUE THREAD

**Issue by timlegge** [Perl/perl5#18834]
Commit https://github.com/Perl/perl5/commit/2583ef601d381a8a3e6e9b5f44db42bac0d537ab introduced a change that breaks tests on Convert:ASN1 for code that previously worked on all prior versions with errors:

```
PERL_DL_NONLAZY=1 "/home/cpan/bin/perl-blead/bin/perl5.35.1" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
Can't modify undef operator in scalar assignment at /home/cpan/.cpan/build/Convert-ASN1-0.29-0/blib/lib/Convert/ASN1/_decode.pm line 98, near ");"
BEGIN not safe after errors--compilation aborted at /home/cpan/.cpan/build/Convert-ASN1-0.29-0/blib/lib/Convert/ASN1/_decode.pm line 607.
Compilation failed in require at /home/cpan/.cpan/build/Convert-ASN1-0.29-0/blib/lib/Convert/ASN1.pm line 435.
BEGIN failed--compilation aborted at /home/cpan/.cpan/build/Convert-ASN1-0.29-0/blib/lib/Convert/ASN1.pm line 441.
Compilation failed in require at t/00prim.t line 7.
BEGIN failed--compilation aborted at t/00prim.t line 7.

```

Convert::ASN1
https://github.com/gbarr/perl-Convert-ASN1/blob/9c029e84c2d308c525e2d8e08f1432f670be29c4/lib/Convert/ASN1/_decode.pm#L97

op.c: 
https://github.com/Perl/perl5/blob/0b47b39244b67fe19dc971903ce28a7a637c2a9a/op.c#L4294

I will review the code in Convert::ASN1 I suppose it is possible it was not hitting that in runtime previously in the tests.

**Comment by timlegge** [comment]
I tested and at least one of the tests does hit that line in Convert::ASN1 so it did previously work in runtime

**Comment by jkeenan** [comment]
So what we will now have to determine is whether the benefit derived from this change in blead outweighs the breakage which becomes evident on CPAN and or which might develop on production code out in the wild.

I recommend that @nwc10, @rjbs, @richardleach and @hvds take a look at this.

Thank you very much.
Jim Keenan

**Comment by hvds** [comment]
> I tested and at least one of the tests does hit that line in Convert::ASN1 so it did previously work in runtime

Hi @timlegge, I tried instrumenting `_decode.pm`, and it appeared to me that the line is hit once by `t/09contr.t` with `$seqof` false, but `$var` defined, so at runtime it resolves to `$stash->{$var} = &{$ctr}(@ctrlist)`.

You would have needed to hit the line with `$seqof` false, `$var` undefined, and `ref($stash)` not being SCALAR before you'd have seen the original runtime failure.

If the intention is to call the function but throw the value away in that case, easiest would just be to introduce a throwaway variable for it, eg:
```
        ($seqof ? $seqof->[$idx++] : defined($var) ? $stash->{$var} : ref($stash) eq 'SCALAR' ? $$stash : my $any)
```

**Comment by timlegge** [comment]
Thanks.  That was where I was looking before life got in my way.  I will
review and fix.  From my point of view the issue can be closed.

Tim

**Comment by timlegge** [comment]
Hi @hvds 

I looked at reformatting the code and:

The broken code is essentially equivalent to the more verbose if elsif below

```
        ($seqof
            ? $seqof->[$idx++] # = &{$ctr}(@ctrlist);
                : defined($var)
                    ? $stash->{$var} # = &{$ctr}(@ctrlist);
                        : ref($stash) eq 'SCALAR'
                            ? $$stash # = &{$ctr}(@ctrlist);
                                : undef # = &{$ctr}(@ctrlist)    )
        = &{$ctr}(@ctrlist);

```
The only purpuse for undef here appears to have a else section for that last conditional so replacing with my $any would be fine. or
```
        if ($seqof) {
            $seqof->[$idx++] = &{$ctr}(@ctrlist);
        } elsif ( defined($var) ) {
            $stash->{$var} = &{$ctr}(@ctrlist);
        } elsif ( ref($stash) eq 'SCALAR' ) {
            $$stash = &{$ctr}(@ctrlist);
        }
```
the more verbose above which does not need the $any/undef because the lack of a final else is not required there.

**Comment by hvds** [comment]
[...]
> The only purpuse for undef here appears to have a else section for that last conditional so replacing with my $any would be fine. or
> 
> ```
>         if ($seqof) {
>             $seqof->[$idx++] = &{$ctr}(@ctrlist);
>         } elsif ( defined($var) ) {
>             $stash->{$var} = &{$ctr}(@ctrlist);
>         } elsif ( ref($stash) eq 'SCALAR' ) {
>             $$stash = &{$ctr}(@ctrlist);
>         }
> ```
> 
> the more verbose above which does not need the $any/undef because the lack of a final else is not required there.

Agreed, this version is also fine if you don't need the side-effects of calling `&{$ctr}(@ctrlist)` in the undef case.

> From my point of view the issue can be closed.

I'd prefer to keep it open until the issue has actually been fixed, whether that's by an update to the package or by a change in perl, just to ensure we properly track it to resolution.

And for the record, the change in perl came via #18779.

**Comment by tonycoz** [comment]
The intent of the change was to error at compile time in the cases when we expect to always error at runtime, which isn't the case here.

I expect the only fix would be to do the check in a ck function.

**Comment by timlegge** [comment]
@tonycoz As @hvds mentioned although the line containing the issue was executed, the particular condition was not so it would not error at runtime.  The compile time check is probably appropriate

**Comment by timlegge** [comment]
Convert::ASN1 0.31 was released to fix the issue

**Comment by hvds** [comment]
> Convert::ASN1 0.31 was released to fix the issue

@timlegge Super, thanks for the feedback; I'll close this issue.

For your information, there is further discussion occurring in PR #18848, which you may find of interest.

**Comment by timlegge** [comment]
Thanks.  I did read through it.  Based on the line of code in the module
being over 20 years old I suspect that it is likely in use in other places
so the discussion seems headed in a good direction.

TIm
