### ISSUE TITLE
eval + feature.pm + syntax error = segfault

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10272]
Migrated from [rt.perl.org#73974](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=73974) (status was 'resolved')

Searchable as RT73974$

**Comment by p5pRT** [comment]
### From frank.wiegand@gmail.com

This is a bug report for perl from frank\.wiegand@&#8203;gmail\.com\,
generated with the help of perlbug 1\.39 running under perl 5\.12\.0\.




---
&nbsp;  eval \{ \+ \}

is a syntax error\. But it should not segfault\, as it does if running with
feature\.pm&#8203;:

&nbsp;  % perl\-5\.12\.0\-RC0 \-e 'eval \{ \+ \}'
&nbsp;  syntax error at \-e line 1\, near "\+ \}"
&nbsp;  Execution of \-e aborted due to compilation errors\.

&nbsp;  % perl\-5\.12\.0\-RC0 \-E 'eval \{ \+ \}'
&nbsp;  syntax error at \-e line 1\, near "\+ \}"
&nbsp;  Execution of \-e aborted due to compilation errors\.
&nbsp;  zsh&#8203;: segmentation fault  perl\-5\.12\.0\-RC0 \-E 'eval \{ \+ \}'


git bisect says&#8203;:

32e2a35d72e0f63c2f9a8de6041a24d35271a7ff is the first bad commit
commit 32e2a35d72e0f63c2f9a8de6041a24d35271a7ff
Author&#8203;: Rafael Garcia\-Suarez \<rgs@&#8203;consttype\.org>
Date&#8203;:   Sun Dec 20 11&#8203;:01&#8203;:34 2009 \+0100

&nbsp;    Make eval \{\} compile directly to OP\_ENTERTRY

&nbsp;    This way\, it's correctly caught and blocked by Safe\, separately
&nbsp;    from eval ""\.


Thanks\, Frank



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl 5\.12\.0&#8203;:

Configured by fw at Tue Mar 30 09&#8203;:16&#8203;:48 CEST 2010\.

Summary of my perl5 \(revision 5 version 12 subversion 0\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.32\-trunk\-amd64\, archname=x86\_64\-linux
&nbsp;    uname='linux hal2 2\.6\.32\-trunk\-amd64 \#1 smp sun jan 10 22&#8203;:40&#8203;:40 utc 2010 x86\_64 gnulinux '
&nbsp;    config\_args='\-de \-Dusedevel \-DDEBUGGING=both \-Doptimize=\-g \-Dcc=ccache gcc \-Dld=gcc \-Dprefix=/opt/perl/perl\-5\.12\.0\-RC1/ \-Dmad'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache gcc'\, ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.4\.3 20100108 \(prerelease\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=/lib/libc\-2\.10\.2\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.10\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    RC1



---
@&#8203;INC for perl 5\.12\.0&#8203;:
&nbsp;    /opt/perl/perl\-5\.12\.0\-RC1/lib/site\_perl/5\.12\.0/x86\_64\-linux
&nbsp;    /opt/perl/perl\-5\.12\.0\-RC1/lib/site\_perl/5\.12\.0
&nbsp;    /opt/perl/perl\-5\.12\.0\-RC1/lib/5\.12\.0/x86\_64\-linux
&nbsp;    /opt/perl/perl\-5\.12\.0\-RC1/lib/5\.12\.0
&nbsp;    \.



---
Environment for perl 5\.12\.0&#8203;:
&nbsp;    HOME=/home/fw
&nbsp;    LANG=de\_DE\.UTF\-8
&nbsp;    LANGUAGE=
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/sbin&#8203;:/usr/sbin&#8203;:/home/fw/bin&#8203;:/home/fw/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/games
&nbsp;    PERL\_AUTOINSTALL=\-\-defaultdeps
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    PERL\_EXTUTILS\_AUTOINSTALL=\-\-defaultdeps
&nbsp;    PERL\_MM\_USE\_DEFAULT=1
&nbsp;    SHELL=/bin/zsh

**Comment by p5pRT** [comment]
### From @rgarcia

On 2 April 2010 00&#8203;:03\, Frank Wiegand \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
>  eval \{ \+ \}
>
> is a syntax error\. But it should not segfault\, as it does if running with
> feature\.pm&#8203;:
>
>  % perl\-5\.12\.0\-RC0 \-e 'eval \{ \+ \}'
>  syntax error at \-e line 1\, near "\+ \}"
>  Execution of \-e aborted due to compilation errors\.
>
>  % perl\-5\.12\.0\-RC0 \-E 'eval \{ \+ \}'
>  syntax error at \-e line 1\, near "\+ \}"
>  Execution of \-e aborted due to compilation errors\.
>  zsh&#8203;: segmentation fault  perl\-5\.12\.0\-RC0 \-E 'eval \{ \+ \}'
>
>
> git bisect says&#8203;:
>
> 32e2a35d72e0f63c2f9a8de6041a24d35271a7ff is the first bad commit
> commit 32e2a35d72e0f63c2f9a8de6041a24d35271a7ff
> Author&#8203;: Rafael Garcia\-Suarez \<rgs@&#8203;consttype\.org>
> Date&#8203;:   Sun Dec 20 11&#8203;:01&#8203;:34 2009 \+0100
>
>    Make eval \{\} compile directly to OP\_ENTERTRY
>
>    This way\, it's correctly caught and blocked by Safe\, separately
>    from eval ""\.

Duh\. Hopefully the fix is obvious\. For evals\, op\_targ carry hint
flags\, which are pretty high when you're using feature or another
\(recent\) pragma\. And previously we had to care only about entereval\,
but now we can compile to entertry too\.

Here's the patch :

<details><summary>Inline Patch</summary>

```diff
diff --git a/op.c b/op.c
index 7754923..9c94cc8 100644
--- a/op.c
+++ b/op.c
@@ -562,6 +562,7 @@ Perl_op_clear(pTHX_ OP *o)
            o->op_targ = 0;
            goto retry;
        }
+    case OP_ENTERTRY:
     case OP_ENTEREVAL: /* Was holding hints. */
        o->op_targ = 0;
        break;

Jesse, is that one OK for the next RC ?
```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @obra




On Fri\, Apr 02\, 2010 at 03&#8203;:00&#8203;:04PM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:
> Duh\. Hopefully the fix is obvious\. For evals\, op\_targ carry hint
> flags\, which are pretty high when you're using feature or another
> \(recent\) pragma\. And previously we had to care only about entereval\,
> but now we can compile to entertry too\.
> 
> Here's the patch :
> 
> diff \-\-git a/op\.c b/op\.c
> index 7754923\.\.9c94cc8 100644
> \-\-\- a/op\.c
> \+\+\+ b/op\.c
> @&#8203;@&#8203; \-562\,6 \+562\,7 @&#8203;@&#8203; Perl\_op\_clear\(pTHX\_ OP \*o\)
>             o\->op\_targ = 0;
>             goto retry;
>         \}
> \+    case OP\_ENTERTRY&#8203;:
>      case OP\_ENTEREVAL&#8203;: /\* Was holding hints\. \*/
>         o\->op\_targ = 0;
>         break;
> 
> Jesse\, is that one OK for the next RC ?

100% OK if there's a new test to make sure it doesn't break again\.

\-\-

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
