### ISSUE TITLE
BBC: Blead Breaks Future::AsyncAwait

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#23711]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.43 running under perl 5.43.3.

-----------------------------------------------------------------

BBC: Blead Breaks Future::AsyncAwait

Please see https://fast2-matrix.cpantesters.org/?dist=Future-AsyncAwait-0.70

---
**Flags**
- category=core
- severity=low
---
**Perl configuration**
```
Site configuration information for perl 5.43.3:

Configured by cpan at Mon Sep 15 18:26:44 EDT 2025.

Summary of my perl5 (revision 5 version 43 subversion 3) configuration:
  Commit id: 3e69d0f74f8df4f76ee99f366c53463b2156ab68
  Platform:
    osname=linux
    osvers=6.12.0-55.32.1.el10_0.x86_64
    archname=x86_64-linux
    uname='linux cjg-rhel10 6.12.0-55.32.1.el10_0.x86_64 #1 smp preempt_dynamic tue sep 9 02:57:23 edt 2025 x86_64 gnulinux '
    config_args='-des -Dprefix=/home/cpan/bin/perl -Dscriptdir=/home/cpan/bin/perl/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='14.2.1 20250110 (Red Hat 14.2.1-7)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /usr/lib64 /usr/local/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.39'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


---
@INC for perl 5.43.3:
    /home/cpan/bin/perl/lib/site_perl/5.43.3/x86_64-linux
    /home/cpan/bin/perl/lib/site_perl/5.43.3
    /home/cpan/bin/perl/lib/5.43.3/x86_64-linux
    /home/cpan/bin/perl/lib/5.43.3

---
Environment for perl 5.43.3:
    HOME=/home/cpan
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl/bin:/home/cpan/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash
```

**Comment by leonerd** [comment]
Hrm; I did get *a* local failure to do with XS::Parse::Sublike, but after reïnstalling that, I now get:

```
t/45sub-signatures.t ............ 1/? 
# Failed test 'argcheck failure happens synchronously'
# at t/45sub-signatures.t line 40.
# +---------+----+---------------------------------------------------------+
# | GOT     | OP | CHECK                                                   |
# +---------+----+---------------------------------------------------------+
# | <UNDEF> | =~ | (?^u:^Too few arguments for subroutine 'main::one_arg') |
# +---------+----+---------------------------------------------------------+
(If this table is too small, you can use the TABLE_TERM_SIZE=### env var to set a larger size, detected size is '78')


# Failed test 'argcheck failure happens synchronously'
# at t/45sub-signatures.t line 44.
# +---------+----+---------------------------------------------------------+
# | GOT     | OP | CHECK                                                   |
# +---------+----+---------------------------------------------------------+
# | <UNDEF> | =~ | (?^u:^Too many arguments for subroutine 'main::one_arg' |
# |         |    | )                                                       |
# +---------+----+---------------------------------------------------------+
(If this table is too small, you can use the TABLE_TERM_SIZE=### env var to set a larger size, detected size is '78')
```

which I suspect is all related to my recent OP_MULTIPARAM work.

**Comment by jkeenan** [comment]
Confirming that behavior changed here:
```
3c2e35619165d949260b733cfa20ac3ab14806ef is the first bad commit
commit 3c2e35619165d949260b733cfa20ac3ab14806ef
Author: Paul Evans <leonerd@leonerd.org.uk>
Date:   Tue May 6 17:21:11 2025 +0100

    Create new `OP_MULTIPARAM` to implement subroutine signatures
```
Cf. https://github.com/Perl/perl5/issues/23712

**Comment by leonerd** [comment]
Another simple fix; the code that hoists an `OP_ARGCHECK` to outside the implied `try` block of the function body just needed to additionally look for `OP_MULTIPARAM`.

Inbound to CPAN as Future-AsyncAwait 0.71.

**Comment by jkeenan** [comment]
Confirmed: https://fast2-matrix.cpantesters.org/?dist=Future-AsyncAwait#
