### ISSUE TITLE
70bac31a4f breaks threaded debugging g++/clang++ builds

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#20772]
When building `perl` with arguments like `-Duseithreads -DDEBUGGING -Dcc=g++` (or substitute `clang++` for `g++`), compilation is failing with error output like this (`clang 11.0.1`):
```
$ zcat 0de69e372d.freebsd13.threaded.debugging.clang++.maketp.output.txt.gz | tail -n 15
...
clang++ -c -DPERL_CORE -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DDEBUGGING -I/usr/local/include -O2 -g -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings dump.c
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang++ -c -DPERL_CORE -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DDEBUGGING -I/usr/local/include -O2 -g -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings util.c
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
util.c:248:13: error: cannot jump from this goto statement to its label
            goto out_of_memory;
            ^
util.c:277:12: note: jump bypasses variable initialization
        UV was_where = PTR2UV(where);
           ^
1 error generated.
*** Error code 1

Stop.
```
Or like this (`g++-10).
```
$ zcat 0de69e372d.linux.threaded.debugging.g++.maketp.output.txt.gz | tail -n 15
g++ -c -DPERL_CORE -D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -g -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wwrite-strings regcomp_trie.c
g++ -c -DPERL_CORE -D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -g -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wwrite-strings regexec.c
g++ -c -DPERL_CORE -D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -g -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wwrite-strings dump.c
g++ -c -DPERL_CORE -D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -g -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wwrite-strings util.c
util.c: In function ‘void* Perl_safesysrealloc(void*, size_t)’:
util.c:335:11: error: jump to label ‘out_of_memory’
  335 |           out_of_memory:
      |           ^~~~~~~~~~~~~
util.c:248:18: note:   from here
  248 |             goto out_of_memory;
      |                  ^~~~~~~~~~~~~
util.c:277:12: note:   crosses initialization of ‘UV was_where’
  277 |         UV was_where = PTR2UV(where);
      |            ^~~~~~~~~
make: *** [makefile:260: util.o] Error 1
```
Bisection with this invocation:
```
perl Porting/bisect.pl -Duseithreads -DDEBUGGING -Dcc=clang++ \
--test-build \
--start=v5.36.0 \
--end=0de69e372d
```
... points to this commit today:
```
70bac31a4f4e90f39d9876a34715f0c83d2684dd is the first bad commit
commit 70bac31a4f4e90f39d9876a34715f0c83d2684dd
Author: Paul "LeoNerd" Evans <leonerd@leonerd.org.uk>
Date:   Wed Dec 14 12:35:57 2022 +0000
Commit:     Yves Orton <demerphq@gmail.com>
CommitDate: Tue Feb 7 19:58:06 2023 +0800


    Avoid a use-after-free warning by converting a pointer to a UV for debug print purposes before we call realloc()
 on it

 util.c | 3 ++-
```
Experimentation with different combinations of command-line switches suggests that it is the *combination* of threading and debugging along with g++/clang++ that triggers the failures in `util.c`.
@leonerd, @demerphq, can you take a look?

**Comment by demerphq** [comment]
Patch already queued up as #20770

**Comment by tonycoz** [comment]
> Patch already queued up as #20770

Which has been merged, closing.
