### ISSUE TITLE
"use strict 'subs" changes behavior of 'truncate' when first argument is constant

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#17996]
Consider the following program, `truncate-fold.t`, which is adapted from `t/comp/fold.t` (a program testing constant folding) in the Perl 5 core distribution's test suite.
```
$ cat truncate-fold.t 
#!./perl -w

print "1..1\n";
my $test = 0;

my $n = "for_fold_dot_t$$";
open my $F, ">$n" or die "open: $!";
print $F "bralh blah blah \n";
close $F or die "close $!";
eval "truncate 1 ? $n : 0, 0;";
print "not " unless -z $n;
print "ok ", ++$test, " - truncate(const ? word : ...)\n";
unlink $n;

__END__
```
Let's run it.
```
$ perl truncate-fold.t 
1..1
ok 1 - truncate(const ? word : ...)
```
Uneventful.  Now let's create a second file in which we duplicate the code to a block in which `use strict 'subs';` is in force.
```
$ cat truncate-fold-with-strict.t 
#!./perl -w

print "1..2\n";
my $test = 0;

my $n = "for_fold_dot_t$$";
open my $F, ">$n" or die "open: $!";
print $F "bralh blah blah \n";
close $F or die "close $!";
eval "truncate 1 ? $n : 0, 0;";
print "not " unless -z $n;
print "ok ", ++$test, " - truncate(const ? word : ...)\n";
unlink $n;

{
    use strict 'subs';
    my $o = "for_fold_dot_u$$";
    open my $F, ">$o" or die "open: $!";
    print $F "bralh blah blah \n";
    close $F or die "close $!";
    eval "truncate 1 ? $o : 0, 0;";
    print "not " unless -z $o;
    print "ok ", ++$test, " - truncate(const ? word : ...)\n";
    unlink $o;
}

__END__
```
We run the second program.
```
 perl truncate-fold-with-strict.t 
1..2
ok 1 - truncate(const ? word : ...)
not ok 2 - truncate(const ? word : ...)
```
The behavior of the program changes once we impose `use strict 'subs';`.  The parent file in the core test suite runs without `use strict;`.

Normally, we expect `use strict;` to catch compilation problems, but we don't expect it to affect the behavior of an otherwise well-formed program.

What is happening here?

Thank you very much.
Jim Keenan

**Comment by leonerd** [comment]
> open my $F, ">$n" or die "open: $!";
...
> {
...
>     open my $F, ">$o" or die "open: $!";

slight guess - possible pollution of the $F lexical here?

Can you wrap the first in a guard block too? And/or rename this one to
$G so as not to collide.

**Comment by jkeenan** [comment]
> > open my $F, ">$n" or die "open: $!";
> > ...
> > {
> > ...
> > open my $F, ">$o" or die "open: $!";
> 
> slight guess - possible pollution of the $F lexical here?
> 
> Can you wrap the first in a guard block too? And/or rename this one to
> $G so as not to collide.

Reasonable suggestions, but unfortunately they don't change the result.
```
$ cat truncate-fold-with-strict-extra.t
#!./perl -w

print "1..2\n";
my $test = 0;

{
    my $n = "for_fold_dot_t$$";
    open my $F, ">$n" or die "open: $!";
    print $F "bralh blah blah \n";
    close $F or die "close $!";
    eval "truncate 1 ? $n : 0, 0;";
    print "not " unless -z $n;
    print "ok ", ++$test, " - truncate(const ? word : ...)\n";
    unlink $n;
}

{
    use strict 'subs';
    my $o = "for_fold_dot_u$$";
    open my $G, ">$o" or die "open: $!";
    print $G "bralh blah blah \n";
    close $G or die "close $!";
    eval "truncate 1 ? $o : 0, 0;";
    print "not " unless -z $o;
    print "ok ", ++$test, " - truncate(const ? word : ...)\n";
    unlink $o;
}

__END__

$ perl truncate-fold-with-strict-extra.t
1..2
ok 1 - truncate(const ? word : ...)
not ok 2 - truncate(const ? word : ...)
```
(FWIW, in the parent file in the test suite, the filehandle is a global.)

Thank you very much.
Jim Keenan

**Comment by xenu** [comment]
The eval dies with `Bareword "for_fold_dot_u4157" not allowed while "strict subs" in use at (eval 2) line 1.`. This isn't a well formed program and the error happens because of the ternary operator, not truncate.

For example:
```
[17:49] xenu@carychium-tridentatum:~> perl -Mstrict -E '-x BAREWORD'
[17:49] xenu@carychium-tridentatum:~> perl -Mstrict -E '-x (1 ? BAREWORD : 0)'
Bareword "BAREWORD" not allowed while "strict subs" in use at -e line 1.
Execution of -e aborted due to compilation errors.
```

**Comment by xenu** [comment]
BTW, that used to work on 5.16 and earlier, but only when ternary was being constant folded:

```
[18:12] xenu@carychium-tridentatum:~> perl5.16 -Mstrict -E 'my $zz; -x ($zz ? BAREWORD : 0)'
Bareword "BAREWORD" not allowed while "strict subs" in use at -e line 1.
Execution of -e aborted due to compilation errors.
[18:12] xenu@carychium-tridentatum:~> perl5.16 -Mstrict -E '-x (1 ? BAREWORD : 0)'
[18:12] xenu@carychium-tridentatum:~>
```

**Comment by tonycoz** [comment]
This looks like expected behaviour. @jkeenan can this be closed?
