### ISSUE TITLE
Devel::Coverage does not work with 5.8.0

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6428]
Migrated from [rt.perl.org#21890](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=21890) (status was 'resolved')

Searchable as RT21890$

**Comment by p5pRT** [comment]
### From @jhi

#### Created by jhi@lyta.hut.fi



$ perl \-d&#8203;:Coverage \-e 'sub foo\{\} sub bar\{\} foo'
No DB&#8203;::DB routine defined at /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/site\_perl/5\.8\.0/Devel/Coverage\.pm line 4\.
BEGIN failed\-\-compilation aborted at /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/site\_perl/5\.8\.0/Devel/Coverage\.pm line 4\.
Compilation failed in require\.
BEGIN failed\-\-compilation aborted\.
$ 

Devel&#8203;::Coverage is a freshly installed 0\.2\.  A naughty workaround is
to modify the Coverage\.pm to have a dummy sub DB&#8203;::DB \{\}\, but that
certainly doesn't make one feel clean\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.8.0:

Configured by jhi at Wed Aug  7 21:21:34 EET DST 2002.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
  Platform:
    osname=dec_osf, osvers=4.0d, archname=alpha-dec_osf-thread-multi
    uname='osf1 lyta.hut.fi v4.0 878 alpha '
    config_args='-des -Duseithreads -Doptimize=-g -Dprefix=/u/vieraat/vieraat/jhi/Perl/platform/OSF1'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=define uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-pthread -std -fprm d -ieee -DDEBUGGING -DLANGUAGE_C',
    optimize='-g',
    cppflags='-pthread -std -ieee -DDEBUGGING -DLANGUAGE_C'
    ccversion='V5.6-082', gccversion='', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=8
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='ld', ldflags =''
    libpth=/usr/shlib /usr/ccs/lib /usr/lib/cmplrs/cc /usr/lib /var/shlib
    libs=-ldbm -ldb -lm -lutil -lpthread -lexc
    perllibs=-lm -lutil -lpthread -lexc
    libc=/usr/shlib/libc.so, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='  -Wl,-rpath,/u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/5.8.0/alpha-dec_osf-thread-multi/CORE'
    cccdlflags=' ', lddlflags='-shared -expect_unresolved "*" -msym -std'

Locally applied patches:
    


@INC for perl v5.8.0:
    /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/5.8.0/alpha-dec_osf-thread-multi
    /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/5.8.0
    /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/site_perl/5.8.0/alpha-dec_osf-thread-multi
    /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/site_perl/5.8.0
    /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/site_perl
    .


Environment for perl v5.8.0:
    HOME=/u/vieraat/vieraat/jhi
    LANG=C
    LANGUAGE (unset)
    LC_ALL=fi_FI.ISO8859-1
    LC_CTYPE=fi_FI.ISO8859-1
    LD_LIBRARY_PATH=/tmp/jhi/perl
    LOGDIR (unset)
    PATH=/u/vieraat/vieraat/jhi/Perl/bin:/u/vieraat/vieraat/jhi/Perl/bin:/u/vieraat/vieraat/jhi/.s:/u/vieraat/vieraat/jhi/.b/OSF1:/c/bin:/p/bin:/p/adm/bin:/usr/bin:/usr/sbin:/sbin:/bin:/usr/ccs/bin:/usr/lib:/etc:/lib:/p/X6/bin:/p/X5/bin:/usr/bin/X11:/usr/lbin:/usr/sbin/acct:/usr/tcb/bin:/tcb/bin:/usr/field:/u/vieraat/vieraat/jhi
    PERL_BADLANG (unset)
    SHELL=/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @rjray

Noted\. I'll forward this report to my home address\, so that I can test for 
this\.

Randy
\-\- 


---
Randy J\. Ray     | Men occasionally stumble over the truth\, but most of them
rjray@&#8203;tellme\.com | pick themselves up and hurry off as if nothing had happened\.
\+1 650 930\-9097  |   \-\- Sir Winston Churchill

**Comment by p5pRT** [comment]
### From @jhi

On Tue\, Apr 08\, 2003 at 08&#8203;:06&#8203;:14PM \-0000\, Randy J\. Ray wrote&#8203;:
> Noted\. I'll forward this report to my home address\, so that I can test for 
> this\.

Since \(I assume\) D&#8203;::C worked with 5\.6\.1 and hasn't changed since\, I'd put
the blame on 5\.8\.0\, not D&#8203;::C\.\.\.

\-\- 
Jarkko Hietaniemi \<jhi@&#8203;iki\.fi> http&#8203;://www\.iki\.fi/jhi/ "There is this special
biologist word we use for 'stable'\.  It is 'dead'\." \-\- Jack Cohen

**Comment by p5pRT** [comment]
### From stas@stason.org

Jarkko Hietaniemi wrote&#8203;:
> On Tue\, Apr 08\, 2003 at 08&#8203;:06&#8203;:14PM \-0000\, Randy J\. Ray wrote&#8203;:
> 
>>Noted\. I'll forward this report to my home address\, so that I can test for 
>>this\.
> 
> 
> Since \(I assume\) D&#8203;::C worked with 5\.6\.1 and hasn't changed since\, I'd put
> the blame on 5\.8\.0\, not D&#8203;::C\.\.\.

D&#8203;::C is not the only one to break because of that\. Apache&#8203;::DB \(mod\_perl 1\) has 
the same problem\. As you can see at the bottom of this thread&#8203;:
http&#8203;://www\.gossamer\-threads\.com/archive/mod\_perl\_C1/modperl\_F7/Trouble\_with\_Apache&#8203;::DB\_P45314/
I've "fixed" it in Apache&#8203;::DB with&#8203;:

<details><summary>Inline Patch</summary>

```diff
--- Apache-DB-0.06/DB.pm.old 1999-10-12 07:50:33.000000000 +0800
+++ Apache-DB-0.06/DB.pm 2002-11-29 18:03:47.000000000 +0800
@@ -14,6 +14,7 @@

```
</details>
$Apache::Registry::MarkLine = 0;

sub init \{
\+ \*DB&#8203;::DB = sub \{\} unless DB\->can\("DB"\); \# temp definition for 5\.8\.0\+
&nbsp;   if\(init\_debugger\(\)\) \{
&nbsp;   warn "\[notice\] Apache&#8203;::DB initialized in child $$\\n";
\}

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Stas Bekman            JAm\_pH \-\-\-\-\-\-> Just Another mod\_perl Hacker
http&#8203;://stason\.org/     mod\_perl Guide \-\-\-> http&#8203;://perl\.apache\.org
mailto&#8203;:stas@&#8203;stason\.org http&#8203;://use\.perl\.org http&#8203;://apacheweek\.com
http&#8203;://modperlbook\.org http&#8203;://apache\.org   http&#8203;://ticketmaster\.com

**Comment by p5pRT** [comment]
### From vkonovalov@spb.lucent.com


> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> $ perl \-d&#8203;:Coverage \-e 'sub foo\{\} sub bar\{\} foo'
> No DB&#8203;::DB routine defined at 
> /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/site\_perl/
> 5\.8\.0/Devel/Coverage\.pm line 4\.
> BEGIN failed\-\-compilation aborted at 
> /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/site\_perl/
> 5\.8\.0/Devel/Coverage\.pm line 4\.
> Compilation failed in require\.
> BEGIN failed\-\-compilation aborted\.
> $ 

something very similar was happening on GUI debugger\, ptkdb\, and people
there did a workaround similar to yours in their compatibility patch\. So\, if
you'll download fresh copy of devel&#8203;::ptkdb\, you'll see that note in comments
at the very beginning&#8203;:

\.\.\.\.
\#\#
\#\# Expedient fix for perl 5\.8\.0\.  True DB&#8203;::DB is further down\.
\#\# 
\#\#
sub DB \{\}

\.\.\.\.

So\, this misbehaviour was already noticed before\.\.\.


> 
> Devel&#8203;::Coverage is a freshly installed 0\.2\.  A naughty workaround is
> to modify the Coverage\.pm to have a dummy sub DB&#8203;::DB \{\}\, but that
> certainly doesn't make one feel clean\.
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>     category=core
>     severity=medium
> \-\-\-
> Site configuration information for perl v5\.8\.0&#8203;:
> 
> Configured by jhi at Wed Aug  7 21&#8203;:21&#8203;:34 EET DST 2002\.
> 
> Summary of my perl5 \(revision 5\.0 version 8 subversion 0\) 
> configuration&#8203;:
>   Platform&#8203;:
>     osname=dec\_osf\, osvers=4\.0d\, archname=alpha\-dec\_osf\-thread\-multi
>     uname='osf1 lyta\.hut\.fi v4\.0 878 alpha '
>     config\_args='\-des \-Duseithreads \-Doptimize=\-g 
> \-Dprefix=/u/vieraat/vieraat/jhi/Perl/platform/OSF1'
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     usethreads=define use5005threads=undef useithreads=define 
> usemultiplicity=define
>     useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
>     use64bitint=define use64bitall=define uselongdouble=undef
>     usemymalloc=n\, bincompat5005=undef
>   Compiler&#8203;:
>     cc='cc'\, ccflags ='\-pthread \-std \-fprm d \-ieee 
> \-DDEBUGGING \-DLANGUAGE\_C'\,
>     optimize='\-g'\,
>     cppflags='\-pthread \-std \-ieee \-DDEBUGGING \-DLANGUAGE\_C'
>     ccversion='V5\.6\-082'\, gccversion=''\, gccosandvers=''
>     intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=8
>     ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, 
> Off\_t='off\_t'\, lseeksize=8
>     alignbytes=8\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='ld'\, ldflags =''
>     libpth=/usr/shlib /usr/ccs/lib /usr/lib/cmplrs/cc 
> /usr/lib /var/shlib
>     libs=\-ldbm \-ldb \-lm \-lutil \-lpthread \-lexc
>     perllibs=\-lm \-lutil \-lpthread \-lexc
>     libc=/usr/shlib/libc\.so\, so=so\, useshrplib=true\, 
> libperl=libperl\.so
>     gnulibc\_version=''
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, 
> ccdlflags='  
> \-Wl\,\-rpath\,/u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5
> /5\.8\.0/alpha\-dec\_osf\-thread\-multi/CORE'
>     cccdlflags=' '\, lddlflags='\-shared \-expect\_unresolved "\*" 
> \-msym \-std'
> 
> Locally applied patches&#8203;:
>     
> 
> \-\-\-
> @&#8203;INC for perl v5\.8\.0&#8203;:
>     
> /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/5\.8\.0/alph
> a\-dec\_osf\-thread\-multi
>     /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/5\.8\.0
>     
> /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/site\_perl/
> 5\.8\.0/alpha\-dec\_osf\-thread\-multi
>     
> /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/site\_perl/5\.8\.0
>     /u/vieraat/vieraat/jhi/Perl/platform/OSF1/lib/perl5/site\_perl
>     \.
> 
> \-\-\-
> Environment for perl v5\.8\.0&#8203;:
>     HOME=/u/vieraat/vieraat/jhi
>     LANG=C
>     LANGUAGE \(unset\)
>     LC\_ALL=fi\_FI\.ISO8859\-1
>     LC\_CTYPE=fi\_FI\.ISO8859\-1
>     LD\_LIBRARY\_PATH=/tmp/jhi/perl
>     LOGDIR \(unset\)
>     
> PATH=/u/vieraat/vieraat/jhi/Perl/bin&#8203;:/u/vieraat/vieraat/jhi/Pe
> rl/bin&#8203;:/u/vieraat/vieraat/jhi/\.s&#8203;:/u/vieraat/vieraat/jhi/\.b/OSF
> 1&#8203;:/c/bin&#8203;:/p/bin&#8203;:/p/adm/bin&#8203;:/usr/bin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/bin&#8203;:/usr/
> ccs/bin&#8203;:/usr/lib&#8203;:/etc&#8203;:/lib&#8203;:/p/X6/bin&#8203;:/p/X5/bin&#8203;:/usr/bin/X11&#8203;:/u
> sr/lbin&#8203;:/usr/sbin/acct&#8203;:/usr/tcb/bin&#8203;:/tcb/bin&#8203;:/usr/field&#8203;:/u/vie
> raat/vieraat/jhi
>     PERL\_BADLANG \(unset\)
>     SHELL=/bin/zsh
>

**Comment by p5pRT** [comment]
### From @jhi

It seems that this has actually been already fixed \(by change \#18589\)
\(the breakage was caused by change \#9754\)\.  I'm marking the problem as resolved\.

**Comment by p5pRT** [comment]
@jhi - Status changed from 'new' to 'resolved'
