### ISSUE TITLE
Solaris and "implicit declaration of function ‘isinf’"

### ISSUE THREAD

**Issue by noloader** [Perl/perl5#17544]
**Description**
I'm building Perl 5.30.1 from the release tarball on Solaris 11.3 i86pc.

The build is producing several warnings like:

```
gcc -c -DPERL_CORE -g2 -O2 -m64 -march=native -fPIC -pthread -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -I/usr/gnu/include -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -DPERL_USE_SAFE_PUTENV -O -Wall -Werror=declaration-after-statement -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -fPIC numeric.c
numeric.c: In function ‘S_my_atof_infnan’:
numeric.c:1461:21: warning: implicit declaration of function ‘isinf’ [-Wimplicit-function-declaration]
                     if (Perl_isinf(nv))
                     ^
``` 

According to the Sun man pages:

```
$ man isinf
...

NAME
       isinf - test for infinity

SYNOPSIS
       c99 [ flag... ] file... -lm [ library... ]
       #include <math.h>

       int isinf(real-floating x);

DESCRIPTION
       The  isinf() macro determines whether its argument value is an infinity
       (positive or negative). First, an  argument  represented  in  a  format
       wider  than  its  semantic type is converted to its semantic type. Then
       determination is based on the type of the argument.
```

**Steps to Reproduce**
Build on Solaris 11.3.

I perform 64-bit builds on Solaris according to [64-bit Computing | When to Use 64-bit](https://docs.oracle.com/cd/E18752_01/html/816-5138/features-1.html) in the Developers Guide. For Autotools projects I use `amd64-sun-solaris`. I also add `-m64` to `CFLAGS`, `CXXFLAGS` and `LDFLAGS`.

Be careful of the *"converted to its semantic type..."* in the man page. I _think_ the three choices for `real-floating` are long int, float and double. I've seen missing math prototypes on Solaris because the compiler did not promote as expected and a simple cast was missing.

**Expected behavior**
A clean compile

**Perl configuration**

```
$ PERL5LIB=./lib ./perl -V
Summary of my perl5 (revision 5 version 30 subversion 1) configuration:
   
  Platform:
    osname=solaris
    osvers=2.11
    archname=i86pc-solaris-64
    uname='sunos solaris 5.11 11.3 i86pc i386 i86pc solaris '
    config_args='-des -Dprefix=/usr/local -Dlibdir=/usr/local/lib -Dpkgconfig=/usr/local/lib/pkgconfig -Dcc=gcc -Dcxx=g++ -Acppflags=-I/usr/local/include -DNDEBUG -Accflags=-g2 -O2 -m64 -march=native -fPIC -pthread -Acxxflags=-g2 -O2 -m64 -march=native -fPIC -pthread -Aldflags=-L/usr/local/lib -m64 -Wl,-R,'XXORIGIN/../lib' -Wl,-R,/usr/local/lib -Dextras=Text::Template Test::More'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags ='-g2 -O2 -m64 -march=native -fPIC -pthread -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -I/usr/gnu/include -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -DPERL_USE_SAFE_PUTENV'
    optimize='-O'
    cppflags='-I/usr/local/include -DNDEBUG -g2 -O2 -m64 -march=native -fPIC -pthread -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -I/usr/gnu/include'
    ccversion=''
    gccversion='4.8.2'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -L/usr/local/lib -m64 -Wl,-R,XXORIGIN/../lib -Wl,-R,/usr/local/lib -fstack-protector -L/usr/gnu/lib -m64 '
    libpth=/usr/local/lib /usr/gcc/4.8/lib /usr/gcc/4.8/lib/gcc/i386-pc-solaris2.11/4.8.2/include-fixed /usr/lib /usr/gnu/lib /usr/ccs/lib
    libs=-lpthread -lsocket -lnsl -lgdbm -ldb -ldl -lm -lc
    perllibs=-lpthread -lsocket -lnsl -ldl -lm -lc
    libc=/lib/libc.so
    so=so
    useshrplib=true
    libperl=libperl.so
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='  -R /usr/local/lib/perl5/5.30.1/i86pc-solaris-64/CORE'
    cccdlflags='-fPIC'
    lddlflags=' -shared -m64 -L/usr/local/lib -Wl,-R,XXORIGIN/../lib -Wl,-R,/usr/local/lib -L/usr/gnu/lib -fstack-protector'

Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under solaris
  Compiled at Feb  6 2020 15:14:41
  %ENV:
    PERL5LIB="./lib"
  @INC:
    ./lib
    /usr/local/lib/perl5/site_perl/5.30.1/i86pc-solaris-64
    /usr/local/lib/perl5/site_perl/5.30.1
    /usr/local/lib/perl5/5.30.1/i86pc-solaris-64
    /usr/local/lib/perl5/5.30.1
```

@jkeenan  - I think this is the last of the trivial reports for lesser used platforms. I've got to move on to other tasks.

**Comment by jkeenan** [comment]
> **Description**
> I'm building Perl 5.30.1 from the release tarball on Solaris 11.3 i86pc.
> 
> The build is producing several warnings like:
> 

[snip]

> 
> **Expected behavior**
> A clean compile
> 

I would like to make sure I understand your expectation here.  By "a clean compile", do you mean that `make` (or `make test_prep`) generates no build-time warnings of the kind described in, say, https://github.com/Perl/perl5/issues/17539?

Thank you very much.
Jim Keenan

**Comment by doughera88** [comment]
> numeric.c: In function ‘S_my_atof_infnan’:
> numeric.c:1461:21: warning: implicit declaration of function ‘isinf’ [-Wimplicit-function-declaration]
>                      if (Perl_isinf(nv))
>                      ^

It looks like Solaris isn't providing an appropriate prototype for isinf().  Since it's documented as a "macro" that can take more than one type of input, and not a simple function, I think perl ought to be very cautious about trying to come up with a prototype on its own that would be valid under all possible scenarios.  The warning is correct but harmless, in that the implicit declaration assumes a return type of 'int', which is the correct return value.

I recommend ignoring the warning.

**Comment by doughera88** [comment]
Absent further feedback, I recommend closing this issue.

**Comment by noloader** [comment]
@doughera88,

I'm still seeing most of the bugs previously reported. Do  you actually clear any bugs? Or do you just close them?

It looks like you need to include `<sunmath.h>`. Also see the [Solaris isinf(3M) man page](https://docs.oracle.com/cd/E37069_01/html/E54439/isinf-3m.html#scrolltoc).

I don't know what to do about this blurb that passes on my screen. I don't know how Perl feature tests, so I don't know what file to add `<sunmath.h>` to.

```
Checking to see if you have isinf...
isinfl() NOT found.
```

**Comment by doughera88** [comment]
On Sat, Jul 18, 2020 at 06:58:24PM -0700, Jeffrey Walton wrote:
> @doughera88,
> 
> I'm still seeing most of the bugs previously reported. Do  you actually clear any bugs? Or do you just close them?

Huh?  Without any context, I don't know what this is about.

> It looks like you need to include `<sunmath.h>`. Also see the [Solaris isinf(3M) man page](https://docs.oracle.com/cd/E37069_01/html/E54439/isinf-3m.html#scrolltoc).
> 
> I don't know what to do about this blurb that passes on my screen. I don't know how Perl feature tests, so I don't know what file to add `<sunmath.h>` to.

In the generated config.sh, the variable i_sunmath indicates whether or not to
include <sunmath.h>.  On Solaris, I would expect it to be 'define'.

> ```
> Checking to see if you have isinf...
> isinfl() NOT found.

If you want to include long double support in Perl, you should pass the
-Duselongdouble flag to Configure.  That directs the Solaris hints to look for
-lsunmath.

-- 
    Andy Dougherty		doughera@lafayette.edu

**Comment by doughera88** [comment]
Just following up again.  (On a side note, it's not obvious to me if <sunmath.h> is really necessary or useful here, though I'd guess it's fine.  The original bug report quotes the Solaris 11.3 man page, which does *not* mention <sunmath.h>.  The link you provided more recently is for Solaris Studio 12.4, but since you are compiling with gcc, it's not obvious if the Solaris Studio compiler pages are relevant.  The Oracle Solaris 11.3 (and 11.4) [isinf(3M)](https://docs.oracle.com/cd/E88353_01/html/E37846/isinf-3m.html) man pages do not mention <sunmath.h>.)  Still, perl probably should include <sunmath.h> if it's available, and Configure does indeed test for it.  Which leaves 2 questions:

1.  Is i_sunmath defined in your config.sh?

2.  Does building with the recommended -Duselongdouble flag resolve the isinfl() issue?

**Comment by doughera88** [comment]
Absent any useful feedback, I guess this issue will have to remain stalled.
