### ISSUE TITLE
Bleadperl 8897dca breaks GFUJI/Data-Util-0.58.tar.gz

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10808]
Migrated from [rt.perl.org#78936](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=78936) (status was 'resolved')

Searchable as RT78936$

**Comment by p5pRT** [comment]
### From @andk

Diagnostics&#8203;:

&nbsp;    cc \-c  "\-I\." \-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-Wall \-W \-Wno\-comment \-O2   \-DVERSION=\\"0\.58\\" \-DXS\_VERSION=\\"0\.58\\" \-o DataUtil\.o \-fPIC "\-I/home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE"  \-DUSE\_PPPORT \-DINLINE\_STR\_EQ DataUtil\.c
&nbsp;    DataUtil\.xs&#8203;: In function ‘my\_deref\_av’&#8203;:
&nbsp;    DataUtil\.xs&#8203;:250&#8203;: warning&#8203;: passing argument 2 of ‘Perl\_amagic\_deref\_call’ from incompatible pointer type
&nbsp;    /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE/proto\.h&#8203;:37&#8203;: note&#8203;: expected ‘struct SV \*’ but argument is of type ‘struct PerlInterpreter \*’
&nbsp;    DataUtil\.xs&#8203;:250&#8203;: warning&#8203;: passing argument 3 of ‘Perl\_amagic\_deref\_call’ makes integer from pointer without a cast
&nbsp;    /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE/proto\.h&#8203;:37&#8203;: note&#8203;: expected ‘int’ but argument is of type ‘struct SV \* const’
&nbsp;    DataUtil\.xs&#8203;:250&#8203;: error&#8203;: too many arguments to function ‘Perl\_amagic\_deref\_call’
&nbsp;    DataUtil\.xs&#8203;: In function ‘my\_deref\_hv’&#8203;:
&nbsp;    DataUtil\.xs&#8203;:263&#8203;: warning&#8203;: passing argument 2 of ‘Perl\_amagic\_deref\_call’ from incompatible pointer type
&nbsp;    /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE/proto\.h&#8203;:37&#8203;: note&#8203;: expected ‘struct SV \*’ but argument is of type ‘struct PerlInterpreter \*’
&nbsp;    DataUtil\.xs&#8203;:263&#8203;: warning&#8203;: passing argument 3 of ‘Perl\_amagic\_deref\_call’ makes integer from pointer without a cast
&nbsp;    /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE/proto\.h&#8203;:37&#8203;: note&#8203;: expected ‘int’ but argument is of type ‘struct SV \* const’
&nbsp;    DataUtil\.xs&#8203;:263&#8203;: error&#8203;: too many arguments to function ‘Perl\_amagic\_deref\_call’
&nbsp;    DataUtil\.xs&#8203;: In function ‘my\_deref\_cv’&#8203;:
&nbsp;    DataUtil\.xs&#8203;:276&#8203;: warning&#8203;: passing argument 2 of ‘Perl\_amagic\_deref\_call’ from incompatible pointer type
&nbsp;    /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE/proto\.h&#8203;:37&#8203;: note&#8203;: expected ‘struct SV \*’ but argument is of type ‘struct PerlInterpreter \*’
&nbsp;    DataUtil\.xs&#8203;:276&#8203;: warning&#8203;: passing argument 3 of ‘Perl\_amagic\_deref\_call’ makes integer from pointer without a cast
&nbsp;    /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE/proto\.h&#8203;:37&#8203;: note&#8203;: expected ‘int’ but argument is of type ‘struct SV \* const’
&nbsp;    DataUtil\.xs&#8203;:276&#8203;: error&#8203;: too many arguments to function ‘Perl\_amagic\_deref\_call’
&nbsp;    DataUtil\.xs&#8203;: In function ‘XS\_Data\_\_Util\_invocant’&#8203;:
&nbsp;    DataUtil\.xs&#8203;:814&#8203;: warning&#8203;: cast from pointer to integer of different size
&nbsp;    make\[1\]&#8203;: \*\*\* \[DataUtil\.o\] Error 1
&nbsp;    make\[1\]&#8203;: Leaving directory \`/home/sand/\.cpan/build/Data\-Util\-0\.58\-vtHQVD'
&nbsp;    \(/usr/bin/make exited with 512\)


git bisect&#8203;:

&nbsp;    There are only 'skip'ped commits left to test\.
&nbsp;    The first bad commit could be any of&#8203;:
&nbsp;    25a9ffce153b0e67cfefd260754edeb097da5be7
&nbsp;    8897dcaad14089c32e969309beb16112ec768eaf
&nbsp;    We cannot bisect more\!

perl \-V&#8203;:

&nbsp;    Summary of my perl5 \(revision 5 version 13 subversion 6\) configuration&#8203;:
&nbsp;      Commit id&#8203;: 8897dcaad14089c32e969309beb16112ec768eaf
&nbsp;      Platform&#8203;:
&nbsp;        osname=linux\, osvers=2\.6\.32\-5\-amd64\, archname=x86\_64\-linux\-thread\-multi
&nbsp;        uname='linux k81 2\.6\.32\-5\-amd64 \#1 smp sat oct 30 14&#8203;:18&#8203;:21 utc 2010 x86\_64 gnulinux '
&nbsp;        config\_args='\-Dprefix=/home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-g8897dca \-Dinstallusrbinperl=n \-Uversiononly \-Dusedevel \-des \-Ui\_db \-Duseithreads \-Uuselongdouble'
&nbsp;        hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;        useithreads=define\, usemultiplicity=define
&nbsp;        useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;        use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;        usemymalloc=n\, bincompat5005=undef
&nbsp;      Compiler&#8203;:
&nbsp;        cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;        optimize='\-O2'\,
&nbsp;        cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;        ccversion=''\, gccversion='4\.4\.5'\, gccosandvers=''
&nbsp;        intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;        d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;        ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;        alignbytes=8\, prototype=define
&nbsp;      Linker and Libraries&#8203;:
&nbsp;        ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;        libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;        libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc \-lgdbm\_compat
&nbsp;        perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;        libc=/lib/libc\-2\.11\.2\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;        gnulibc\_version='2\.11\.2'
&nbsp;      Dynamic Linking&#8203;:
&nbsp;        dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;        cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-L/usr/local/lib \-fstack\-protector'


&nbsp;    Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;      Compile\-time options&#8203;: MULTIPLICITY PERL\_DONT\_CREATE\_GVSV
&nbsp;                            PERL\_IMPLICIT\_CONTEXT PERL\_MALLOC\_WRAP PERL\_USE\_DEVEL
&nbsp;                            USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_ITHREADS
&nbsp;                            USE\_LARGE\_FILES USE\_PERLIO USE\_PERL\_ATOF
&nbsp;                            USE\_REENTRANT\_API
&nbsp;      Built under linux
&nbsp;      Compiled at Nov  9 2010 04&#8203;:50&#8203;:53
&nbsp;      @&#8203;INC&#8203;:
&nbsp;        /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-g8897dca/lib/site\_perl/5\.13\.6/x86\_64\-linux\-thread\-multi
&nbsp;        /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-g8897dca/lib/site\_perl/5\.13\.6
&nbsp;        /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi
&nbsp;        /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-g8897dca/lib/5\.13\.6
&nbsp;        \.

\-\- 
andreas

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Nov 08 20&#8203;:28&#8203;:32 2010\, andreas\.koenig\.7os6VVqR@&#8203;franz\.ak\.mind\.de wrote&#8203;:
> Diagnostics&#8203;:
> 
>     cc \-c  "\-I\." \-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe
>    \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE
>    \-D\_FILE\_OFFSET\_BITS=64 \-Wall \-W \-Wno\-comment \-O2
>    \-DVERSION=\\"0\.58\\" \-DXS\_VERSION=\\"0\.58\\" \-o DataUtil\.o \-fPIC "\-
>    I/home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-
>    g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE"  \-DUSE\_PPPORT
>    \-DINLINE\_STR\_EQ DataUtil\.c
>     DataUtil\.xs&#8203;: In function ‘my\_deref\_av’&#8203;:
>     DataUtil\.xs&#8203;:250&#8203;: warning&#8203;: passing argument 2 of
>    ‘Perl\_amagic\_deref\_call’ from incompatible pointer type
>     /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-
>    g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE/proto\.h&#8203;:37&#8203;:
>    note&#8203;: expected ‘struct SV \*’ but argument is of type ‘struct
>    PerlInterpreter \*’
>     DataUtil\.xs&#8203;:250&#8203;: warning&#8203;: passing argument 3 of
>    ‘Perl\_amagic\_deref\_call’ makes integer from pointer without a cast
>     /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-
>    g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE/proto\.h&#8203;:37&#8203;:
>    note&#8203;: expected ‘int’ but argument is of type ‘struct SV \* const’
>     DataUtil\.xs&#8203;:250&#8203;: error&#8203;: too many arguments to function
>    ‘Perl\_amagic\_deref\_call’
>     DataUtil\.xs&#8203;: In function ‘my\_deref\_hv’&#8203;:
>     DataUtil\.xs&#8203;:263&#8203;: warning&#8203;: passing argument 2 of
>    ‘Perl\_amagic\_deref\_call’ from incompatible pointer type
>     /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-
>    g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE/proto\.h&#8203;:37&#8203;:
>    note&#8203;: expected ‘struct SV \*’ but argument is of type ‘struct
>    PerlInterpreter \*’
>     DataUtil\.xs&#8203;:263&#8203;: warning&#8203;: passing argument 3 of
>    ‘Perl\_amagic\_deref\_call’ makes integer from pointer without a cast
>     /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-
>    g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE/proto\.h&#8203;:37&#8203;:
>    note&#8203;: expected ‘int’ but argument is of type ‘struct SV \* const’
>     DataUtil\.xs&#8203;:263&#8203;: error&#8203;: too many arguments to function
>    ‘Perl\_amagic\_deref\_call’
>     DataUtil\.xs&#8203;: In function ‘my\_deref\_cv’&#8203;:
>     DataUtil\.xs&#8203;:276&#8203;: warning&#8203;: passing argument 2 of
>    ‘Perl\_amagic\_deref\_call’ from incompatible pointer type
>     /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-
>    g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE/proto\.h&#8203;:37&#8203;:
>    note&#8203;: expected ‘struct SV \*’ but argument is of type ‘struct
>    PerlInterpreter \*’
>     DataUtil\.xs&#8203;:276&#8203;: warning&#8203;: passing argument 3 of
>    ‘Perl\_amagic\_deref\_call’ makes integer from pointer without a cast
>     /home/src/perl/repoperls/installed\-perls/perl/v5\.13\.6\-365\-
>    g8897dca/lib/5\.13\.6/x86\_64\-linux\-thread\-multi/CORE/proto\.h&#8203;:37&#8203;:
>    note&#8203;: expected ‘int’ but argument is of type ‘struct SV \* const’
>     DataUtil\.xs&#8203;:276&#8203;: error&#8203;: too many arguments to function
>    ‘Perl\_amagic\_deref\_call’
>     DataUtil\.xs&#8203;: In function ‘XS\_Data\_\_Util\_invocant’&#8203;:
>     DataUtil\.xs&#8203;:814&#8203;: warning&#8203;: cast from pointer to integer of
>    different size
>     make\[1\]&#8203;: \*\*\* \[DataUtil\.o\] Error 1
>     make\[1\]&#8203;: Leaving directory \`/home/sand/\.cpan/build/Data\-Util\-0\.58\-
>    vtHQVD'
>     \(/usr/bin/make exited with 512\)
> 
> 
> git bisect&#8203;:
> 
>     There are only 'skip'ped commits left to test\.
>     The first bad commit could be any of&#8203;:
>     25a9ffce153b0e67cfefd260754edeb097da5be7
>     8897dcaad14089c32e969309beb16112ec768eaf
>     We cannot bisect more\!

This appears to have been fixed by e89bfaa62e9e0b\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
