### ISSUE TITLE
Storable does not work on perl 5.8.1

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#11561]
Migrated from [rt.perl.org#96466](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=96466) (status was 'resolved')

Searchable as RT96466$

**Comment by p5pRT** [comment]
### From rkitover@hlagh.dongs


This is a bug report for perl from rkitover@&#8203;hlagh\.dongs\,
generated with the help of perlbug 1\.34 running under perl v5\.8\.1\.




---
On 5\.8\.1\, Storable does not load&#8203;:

Can't load
'/home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/5\.8\.1/i686\-linux\-thread\-multi/auto/Storable/Storable\.so'
for module Storable&#8203;:
/home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/5\.8\.1/i686\-linux\-thread\-multi/auto/Storable/Storable\.so&#8203;:
undefined symbol&#8203;: SvIsCOW at
/home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/5\.8\.1/i686\-linux\-thread\-multi/XSLoader\.pm
line 68\.
 at
 /home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/5\.8\.1/i686\-linux\-thread\-multi/Storable\.pm
 line 72
 Compilation failed in require\.
 BEGIN failed\-\-compilation aborted\.




---


---
Flags&#8203;:
&nbsp;    category=library
&nbsp;    severity=medium


---
Site configuration information for perl v5\.8\.1&#8203;:

Configured by rkitover at Sun Aug  7 06&#8203;:53&#8203;:07 EDT 2011\.

Summary of my perl5 \(revision 5\.0 version 8 subversion 1\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.36\-rc7\, archname=i686\-linux\-thread\-multi
&nbsp;    uname='linux hlagh 2\.6\.36\-rc7 \#1 smp preempt thu oct 7 15&#8203;:09&#8203;:12 edt 2010 i686 gnulinux '
&nbsp;    config\_args='\-de \-Dprefix=/home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1 \-DDEBUGGING=both \-Dusethreads'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.6\.1'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /usr/lib/i386\-linux\-gnu
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc \-lgdbm\_compat
&nbsp;    libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.13'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.1&#8203;:
&nbsp;    /home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/5\.8\.1/i686\-linux\-thread\-multi
&nbsp;    /home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/5\.8\.1
&nbsp;    /home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/site\_perl/5\.8\.1/i686\-linux\-thread\-multi
&nbsp;    /home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/site\_perl/5\.8\.1
&nbsp;    /home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/site\_perl
&nbsp;    \.



---
Environment for perl v5\.8\.1&#8203;:
&nbsp;    HOME=/home/rkitover
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_CTYPE=en\_US\.utf8
&nbsp;    LD\_LIBRARY\_PATH=/home/rkitover/lib&#8203;:/usr/local/lib&#8203;:/lib&#8203;:/usr/lib&#8203;:/home/rkitover/instantclient\_10\_2&#8203;:/usr/lib/oracle/xe/app/oracle/product/10\.2\.0/server/lib&#8203;:/opt/sqlanywhere11/lib32&#8203;:/home/informix/lib&#8203;:/home/informix/lib/esql
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/rkitover/perl5/perlbrew/bin&#8203;:/home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/bin&#8203;:/home/rkitover/bin&#8203;:/home/rkitover/perl5/bin&#8203;:/home/rkitover/instantclient\_10\_2&#8203;:/usr/lib/oracle/xe/app/oracle/product/10\.2\.0/server/bin&#8203;:/usr/local/bin&#8203;:/usr/local/sbin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/bin/X11&#8203;:/usr/games&#8203;:/opt/cxoffice/bin&#8203;:/opt/cxgames/bin&#8203;:/home/rkitover/android\-sdk/tools&#8203;:/home/informix/bin&#8203;:/home/sybase/DBISQL/bin&#8203;:/home/sybase/OCS\-15\_0/bin&#8203;:/home/sybase/ASE\-15\_0/bin&#8203;:/home/sybase/ASE\-15\_0/install&#8203;:/home/db2inst1/sqllib/bin&#8203;:/home/db2inst1/sqllib/adm&#8203;:/home/db2inst1/sqllib/misc&#8203;:/home/db2inst1/sqllib/db2tss/bin
&nbsp;    PERLBREW\_HOME=/home/rkitover/\.perlbrew
&nbsp;    PERLBREW\_PATH=/home/rkitover/perl5/perlbrew/bin&#8203;:/home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/bin
&nbsp;    PERLBREW\_PERL=perl\-5\.8\.1
&nbsp;    PERLBREW\_ROOT=/home/rkitover/perl5/perlbrew
&nbsp;    PERLBREW\_VERSION=0\.27
&nbsp;    PERLDB\_OPTS=NonStop
&nbsp;    PERL\_AUTOINSTALL\_PREFER\_CPAN=1
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    PERL\_CPANM\_OPT=\-\-sudo \-\-notest \-\-mirror http&#8203;://cpan\.cpantesters\.org/
&nbsp;    PERL\_DL\_NONLAZY=1
&nbsp;    PERL\_MM\_OPT=INSTALLMAN1DIR=none INSTALLMAN3DIR=none
&nbsp;    SHELL=zsh

**Comment by p5pRT** [comment]
### From @cpansprout

On Sun Aug 07 11&#8203;:01&#8203;:10 2011\, rkitover@&#8203;hlagh\.dongs wrote&#8203;:
> 
> This is a bug report for perl from rkitover@&#8203;hlagh\.dongs\,
> generated with the help of perlbug 1\.34 running under perl v5\.8\.1\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> On 5\.8\.1\, Storable does not load&#8203;:
> 
> Can't load
> '/home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/5\.8\.1/i686\-linux\-
>    thread\-multi/auto/Storable/Storable\.so'
> for module Storable&#8203;:
> /home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/5\.8\.1/i686\-linux\-
>    thread\-multi/auto/Storable/Storable\.so&#8203;:
> undefined symbol&#8203;: SvIsCOW at
> /home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/5\.8\.1/i686\-linux\-
>    thread\-multi/XSLoader\.pm
> line 68\.
>  at
>  /home/rkitover/perl5/perlbrew/perls/perl\-5\.8\.1/lib/5\.8\.1/i686\-linux\-
>    thread\-multi/Storable\.pm
>  line 72
>  Compilation failed in require\.
>  BEGIN failed\-\-compilation aborted\.

I’ve already fixed this in blead with commit e88d61e9\. I’m copying the
CPAN maintainer\, so he can make a new release\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Sun Aug 07 11&#8203;:19&#8203;:08 2011\, sprout wrote&#8203;:
> On Sun Aug 07 11&#8203;:01&#8203;:10 2011\, rkitover@&#8203;hlagh\.dongs wrote&#8203;:
> > 
> > This is a bug report for perl from rkitover@&#8203;hlagh\.dongs\,
> > generated with the help of perlbug 1\.34 running under perl v5\.8\.1\.
> > 
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > On 5\.8\.1\, Storable does not load&#8203;:
\[snip\]
> 
> I’ve already fixed this in blead with commit e88d61e9\. I’m copying the
> CPAN maintainer\, so he can make a new release\.
> 

The version of Storable associated with Perl 5\.8\.1 was \(per 'corelist \-a
Storable\) 2\.08\.  With Perl 5\.14\.2 we're at Storable 2\.27\.

Has the original problem been addressed?  If so\, then this ticket should
be closable\.

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @cpansprout

On Sat Apr 21 15&#8203;:25&#8203;:20 2012\, jkeenan wrote&#8203;:
> On Sun Aug 07 11&#8203;:19&#8203;:08 2011\, sprout wrote&#8203;:
> > On Sun Aug 07 11&#8203;:01&#8203;:10 2011\, rkitover@&#8203;hlagh\.dongs wrote&#8203;:
> > > 
> > > This is a bug report for perl from rkitover@&#8203;hlagh\.dongs\,
> > > generated with the help of perlbug 1\.34 running under perl v5\.8\.1\.
> > > 
> > > 
> > > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > > On 5\.8\.1\, Storable does not load&#8203;:
> \[snip\]
> > 
> > I’ve already fixed this in blead with commit e88d61e9\. I’m copying the
> > CPAN maintainer\, so he can make a new release\.
> > 
> 
> The version of Storable associated with Perl 5\.8\.1 was \(per 'corelist \-a
> Storable\) 2\.08\.  With Perl 5\.14\.2 we're at Storable 2\.27\.
> 
> Has the original problem been addressed?  If so\, then this ticket should
> be closable\.

This bug is about the dual\-life distribution\, which still contains the
bug as of version 2\.30\.  We just need a new CPAN release of what is in
blead\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

Resolved by the released of Storable 2\.35\.

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
