### ISSUE TITLE
BBC: Blead Breaks Sereal::Encoder

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#22902]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.43 running under perl 5.41.8.

-----------------------------------------------------------------

BBC: Blead Breaks Sereal::Encoder

Please see http://fast-matrix.cpantesters.org/?dist=Sereal::Encoder

---
**Flags**
- category=core
- severity=low
---
**Perl configuration**
```
Site configuration information for perl 5.41.8:

Configured by cpan at Sat Jan 11 02:10:58 EST 2025.

Summary of my perl5 (revision 5 version 41 subversion 8) configuration:
  Commit id: 3a16cb5fb8114b7773a9c488c78684bffd787b62
  Platform:
    osname=linux
    osvers=5.14.0-503.21.1.el9_5.x86_64
    archname=x86_64-linux
    uname='linux cjg-rhel9 5.14.0-503.21.1.el9_5.x86_64 #1 smp preempt_dynamic thu dec 19 09:37:00 est 2024 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Dprefix=/home/cpan/bin/perl -Dscriptdir=/home/cpan/bin/perl/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.5.0 20240719 (Red Hat 11.5.0-2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /usr/lib64 /usr/local/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.34'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


---
@INC for perl 5.41.8:
    /home/cpan/bin/perl/lib/site_perl/5.41.8/x86_64-linux
    /home/cpan/bin/perl/lib/site_perl/5.41.8
    /home/cpan/bin/perl/lib/5.41.8/x86_64-linux
    /home/cpan/bin/perl/lib/5.41.8

---
Environment for perl 5.41.8:
    HOME=/home/cpan
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl/bin:/home/cpan/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash
```

**Comment by sisyphus** [comment]
When I go to http://fast-matrix.cpantesters.org/?dist=Sereal::Encoder (using Google Chrome) I can see no evidence of any perl-5.41.8 failures.

**Comment by jkeenan** [comment]
Sample failure report:
http://www.cpantesters.org/cpan/report/83a0af28-cff2-11ef-8dd2-e423a86df0c5

This is a failure during Sereal::Encoder's build-time:
```
Output from '/usr/bin/make':

cp lib/Sereal/Encoder/Constants.pm blib/lib/Sereal/Encoder/Constants.pm
cp lib/Sereal/Encoder.pm blib/lib/Sereal/Encoder.pm
Running Mkbootstrap for Encoder ()
chmod 644 "Encoder.bs"
"/home/cpan/bin/perl/bin/perl5.41.8" -MExtUtils::Command::MM -e 'cp_nonempty' -- Encoder.bs blib/arch/auto/Sereal/Encoder/Encoder.bs 644
"/home/cpan/bin/perl/bin/perl5.41.8" "/home/cpan/bin/perl/lib/5.41.8/ExtUtils/xsubpp"  -typemap '/home/cpan/bin/perl/lib/5.41.8/ExtUtils/typemap' -typemap '/home/cpan/.cpan/build/Sereal-Encoder-5.004-0/typemap'  Encoder.xs > Encoder.xsc
mv Encoder.xsc Encoder.c
cc -c  -I. -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O3   -DVERSION=\"5.004\" -DXS_VERSION=\"5.004\" -fPIC "-I/home/cpan/bin/perl/lib/5.41.8/x86_64-linux/CORE"  -DNDEBUG -DMINIZ_NO_STDIO -DHAVE_ZSTD -DHAVE_BUILTIN_CTZ Encoder.c
cc -c  -I. -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O3   -DVERSION=\"5.004\" -DXS_VERSION=\"5.004\" -fPIC "-I/home/cpan/bin/perl/lib/5.41.8/x86_64-linux/CORE"  -DNDEBUG -DMINIZ_NO_STDIO -DHAVE_ZSTD -DHAVE_BUILTIN_CTZ srl_encoder.c
srl_encoder.c: In function 'srl_dump_hk':
srl_encoder.c:1571:69: error: macro "Perl_bytes_to_utf8" requires 3 arguments, but only 2 given
 1571 |         char* utf8= (char *)Perl_bytes_to_utf8(aTHX_ (U8 *)str, &len);
      |                                                                     ^
In file included from /home/cpan/bin/perl/lib/5.41.8/x86_64-linux/CORE/regexp.h:21,
                 from /home/cpan/bin/perl/lib/5.41.8/x86_64-linux/CORE/perl.h:4522,
                 from srl_encoder.c:8:
/home/cpan/bin/perl/lib/5.41.8/x86_64-linux/CORE/utf8.h:1333:9: note: macro "Perl_bytes_to_utf8" defined here
 1333 | #define Perl_bytes_to_utf8(mTHX, s, lenp)  Perl_bytes_to_utf8_free_me(aTHX_ s, lenp, NULL)
      |         ^~~~~~~~~~~~~~~~~~
srl_encoder.c:1571:29: error: 'Perl_bytes_to_utf8' undeclared (first use in this function); did you mean 'Perl_bytes_from_utf8'?
 1571 |         char* utf8= (char *)Perl_bytes_to_utf8(aTHX_ (U8 *)str, &len);
      |                             ^~~~~~~~~~~~~~~~~~
      |                             Perl_bytes_from_utf8
srl_encoder.c:1571:29: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:371: srl_encoder.o] Error 1
```
Now bisecting.

**Comment by jkeenan** [comment]
> When I go to http://fast-matrix.cpantesters.org/?dist=Sereal::Encoder (using Google Chrome) I can see no evidence of any perl-5.41.8 failures.

That URL expects a distribution (Some-Distro) rather than a module (Some::Module).  Hence, it should be:
http://fast-matrix.cpantesters.org/?dist=Sereal::Encoder

**Comment by jkeenan** [comment]
Bisection pointed to 992f7686c5 as the first bad commit:
```
992f7686c57ced1028349aed2f8812c2b790564f is the first bad commit
commit 992f7686c57ced1028349aed2f8812c2b790564f
Author: Karl Williamson <khw@cpan.org>
Date:   Wed Dec 4 17:12:11 2024 -0700
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Tue Jan 7 21:25:29 2025 -0700

    Add new function bytes_to_utf8_free_me
    
    This is like bytes_to_utf8, but if the representation of the input
    string is the same in UTF-8 as it is in native format, the allocation of
    new memory is skipped.
    
    This presents optimization possibilities.

 embed.fnc |  6 ++++-
 embed.h   |  3 ++-
 proto.h   |  7 ++++--
 utf8.c    | 79 +++++++++++++++++++++++++++++++++++++++++++++++++--------------
 utf8.h    |  1 +
 5 files changed, 75 insertions(+), 21 deletions(-)
bisect found first bad commit
That took 1299 seconds.
```
@khwilliamson, can you take a look?  Thanks.

**Comment by jkeenan** [comment]
Failure output from FreeBSD-13, where `clang17` is the compiler:
```
Output from '/usr/bin/make':

cp lib/Sereal/Encoder/Constants.pm blib/lib/Sereal/Encoder/Constants.pm
cp lib/Sereal/Encoder.pm blib/lib/Sereal/Encoder.pm
Running Mkbootstrap for Encoder ()
chmod 644 "Encoder.bs"
"/usr/home/jkeenan/testing/blead/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Encoder.bs blib/arch/auto/Sereal/Encoder/Encoder.bs 644
"/usr/home/jkeenan/testing/blead/bin/perl" "/home/jkeenan/testing/blead/lib/perl5/5.41.8/ExtUtils/xsubpp"  -typemap '/home/jkeenan/testing/blead/lib/perl5/5.41.8/ExtUtils/typemap' -typemap '/usr/home/jkeenan/.cpan/build/Sereal-Encoder-5.004-1/typemap'  Encoder.xs > Encoder.xsc
mv Encoder.xsc Encoder.c
cc -c  -I.  -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DNO_POSIX_2008_LOCALE -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -O3 -Wno-compound-token-split-by-macro    -DVERSION=\"5.004\"  -DXS_VERSION=\"5.004\" -DPIC -fPIC "-I/home/jkeenan/testing/blead/lib/perl5/5.41.8/amd64-freebsd-thread-multi/CORE"  -DNDEBUG -DMINIZ_NO_STDIO -DHAVE_ZSTD -DHAVE_BUILTIN_CTZ Encoder.c
cc -c  -I.  -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DNO_POSIX_2008_LOCALE -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -O3 -Wno-compound-token-split-by-macro    -DVERSION=\"5.004\"  -DXS_VERSION=\"5.004\" -DPIC -fPIC "-I/home/jkeenan/testing/blead/lib/perl5/5.41.8/amd64-freebsd-thread-multi/CORE"  -DNDEBUG -DMINIZ_NO_STDIO -DHAVE_ZSTD -DHAVE_BUILTIN_CTZ srl_encoder.c
srl_encoder.c:1571:69: error: too few arguments provided to function-like macro invocation
 1571 |         char* utf8= (char *)Perl_bytes_to_utf8(aTHX_ (U8 *)str, &len);
      |                                                                     ^
/home/jkeenan/testing/blead/lib/perl5/5.41.8/amd64-freebsd-thread-multi/CORE/utf8.h:1333:9: note: macro 'Perl_bytes_to_utf8' defined here
 1333 | #define Perl_bytes_to_utf8(mTHX, s, lenp)  Perl_bytes_to_utf8_free_me(aTHX_ s, lenp, NULL)
      |         ^
srl_encoder.c:1571:29: error: use of undeclared identifier 'Perl_bytes_to_utf8'
 1571 |         char* utf8= (char *)Perl_bytes_to_utf8(aTHX_ (U8 *)str, &len);
      |                             ^
2 errors generated.
*** Error code 1

Stop.
make: stopped in /usr/home/jkeenan/.cpan/build/Sereal-Encoder-5.004-1
```

**Comment by khwilliamson** [comment]
This is a result of an earlier commit 90f4e9b863c9a5490c7417e0fd4ada26c7c20b28.  When I did that I wondered why no one had thought of it before, because it makes life simpler.  This bug is why.  I hadn't thought things through fully, and this is the first instance it has shown up.  It happens when you use one of the affected functions in its long form (that is prefixed by `Perl_` and with `aTHX_`)  on a threaded perl.  The affected functions are ones where they are actually macros that call another macro or function, and they have been written allegedly so that both the short and long  forms work.  

In the meantime there have been quite a few commits that rely on the new mechanism and which I'm loathe to back out.  For example, I used this to almost completely empty `mathoms.c` .  It also allows most stub functions to just be macros, making things more efficient.

My proposal to fix this is to maintain this capability, but a different mechanism must be used.  I'm thinking to extend the syntax of embed.fnc as in the sample lines below, and let the embed regen program generate the appropriate definitions in embed.h.

```
Admp	|U8 *	|bytes_to_utf8	|NN const U8 *s 			\
				|NN STRLEN *lenp			\
				=bytes_to_utf8_free_me(s, lenp, NULL)
Adp	|U8 *	|bytes_to_utf8_free_me					\
				|NN const U8 *s 			\
				|NN STRLEN *lenp			\
				|NULLOK const U8 **free_me
AOdp	|SSize_t|call_argv	|NN const char *sub_name		\
```
The only difference here is is the line that begins with an equal sign (plus the addition of a continuation backslash on the line just above it).  What this would indicate is that the element this line continues is a macro whose definition in this case would be

`#define bytes_to_utf8(s, lenp)  bytes_to_utf8_free_me(s, lenp, NULL)`

The embed.h regen program would generate the appropriate definitions in `embed.h` to handle all cases.

We have a lot of cases now where one macro is derivative of another macro or a function, typically calling it with an extra parameter, often 0.  This would allow their definitions to be moved to embed.fnc, instead of cluttering up various headers, so you wouldn't have to go looking around, and the definition would be more compact and the overall view more clear.

**Comment by tonycoz** [comment]
> We have a lot of cases now where one macro is derivative of another macro or a function, typically calling it with an extra parameter, often 0. This would allow their definitions to be moved to embed.fnc, instead of cluttering up various headers, so you wouldn't have to go looking around, and the definition would be more compact and the overall view more clear.

You could just make them inline functions, which allows the type checking done by the compiler to happen rather than the possible blind casting to a different type that happens in a lot of the new macros.

**Comment by khwilliamson** [comment]
Are my concerns about having too many inline functions wrong, and those days are gone, so that you can have as many inline functions as you want?  If so, then using inlines is a better option

**Comment by tonycoz** [comment]
The only limitation I'm aware of is the data available to the compiler being too large, or extending compilation times.

It might be worth seeing which of our current inline functions aren't being inlined,

For clang you can extract this with `-fsave-optimization-report`, and with a bit of processing we can see which `inline.h` or `sv_inline.h` functions aren't being inlined at least 20% of the time:
```
Perl_cx_poploop  0.0% 0/3
  Perl_dounwind TooCostly pp_ctl.c 1793
  Perl_pp_leaveloop TooCostly pp_ctl.c 2670
  Perl_pp_last TooCostly pp_ctl.c 3007
Perl_cx_popsub  0.0% 0/2
  Perl_dounwind TooCostly pp_ctl.c 1793
  Perl_pp_leavesublv TooCostly pp_ctl.c 2710
Perl_cx_pushsub  0.0% 0/2
  S_regmatch TooCostly regexec.c 6440
  S_regmatch TooCostly regexec.c 6440
Perl_isUTF8_CHAR  0.0% 0/1
  Perl_check_utf8_print TooCostly utf8.c 4669
Perl_is_utf8_string_loclen  0.0% 0/14
  Perl_lex_start TooCostly toke.c 877
  Perl_lex_next_chunk TooCostly toke.c 1468
  Perl_get_and_check_backslash_N_name TooCostly toke.c 2848
  S_scan_formline TooCostly toke.c 12558
  Perl_is_utf8_non_invariant_string TooCostly ./inline.h 1977
  S_newSV_maybe_utf8 TooCostly toke.c 2234
  yyl_just_a_word TooCostly toke.c 7638
  yyl_just_a_word TooCostly toke.c 7638
  S_scan_heredoc TooCostly toke.c 10903
  yyl_leftpointy TooCostly toke.c 6808
  Perl_yylex TooCostly toke.c 9606
  Perl_yylex TooCostly toke.c 9606
  Perl_yylex TooCostly toke.c 9606
  Perl_yylex TooCostly toke.c 9606
Perl_savesvpv  0.0% 0/5
  Perl_magic_set TooCostly mg.c 3016
  Perl_magic_set TooCostly mg.c 3016
  Perl_magic_set TooCostly mg.c 3016
  Perl_magic_set TooCostly mg.c 3016
  Perl_pp_leavewrite TooCostly pp_sys.c 1707
Perl_sv_setpv_freshbuf  20.0% 1/5
  Perl_vnewSVpvf Inlined sv.c 9984
  Perl_moreswitches TooCostly perl.c 3671
  Perl_moreswitches TooCostly perl.c 3671
  Perl_moreswitches TooCostly perl.c 3671
  Perl_moreswitches TooCostly perl.c 3671
S_sv_or_pv_pos_u2b  20.0% 1/5
  Perl_sv_vcatpvfn_flags TooCostly sv.c 12263
  Perl_sv_vcatpvfn_flags TooCostly sv.c 12263
  Perl_sv_vcatpvfn_flags TooCostly sv.c 12263
  Perl_pp_substr TooCostly pp.c 3581
  Perl_pp_substr_left Inlined pp.c 3729
```
(processed with [clang-inline-report.pl](https://gist.github.com/tonycoz/27051a55d276d368ebb21e07965e1bd8))

which has some interesting entries.

**Comment by tonycoz** [comment]
gcc also supports `-fsave-optimization-report` but it uses a very different output format which is subject to change, so I haven't tried building a summarizer.

gcc also has `-fopt-info-*` which with `-fopt-info-inline-optimized-missed` will show which functions are/aren't inlined.

A brief look at the latter (gcc):
- savesvpv() isn't inlined, just as with clang "Perl_pp_leavewrite/301->Perl_savesvpv/233, call is cold and code would grow at least by 19"
- sv_or_pv_pos_u2b() isn't inlined in pp_substr_left(), the only place clang inlined it
- is_utf8_string_loclen() isn't inlined in toke.c just as with clang
