### ISSUE TITLE
Static builds broken since 77d654fb

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13616]
Migrated from [rt.perl.org#121291](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=121291) (status was 'resolved')

Searchable as RT121291$

**Comment by p5pRT** [comment]
### From @bingos

Static builds \(Configure with \-Uusedl\) are broken&#8203;:

cc \-o perl \-fstack\-protector \-L/usr/local/lib  perlmain\.o lib/auto/arybase/arybase\.a lib/auto/attributes/attributes\.a lib/auto/B/B\.a lib/auto/Compress/Raw/Bzip2/Bzip2\.a lib/auto/Compress/Raw/Zlib/Zlib\.a lib/auto/Cwd/Cwd\.a lib/auto/Data/Dumper/Dumper\.a lib/auto/Devel/Peek/Peek\.a lib/auto/Devel/PPPort/PPPort\.a lib/auto/Digest/MD5/MD5\.a lib/auto/Digest/SHA/SHA\.a lib/auto/Encode/Encode\.a lib/auto/Fcntl/Fcntl\.a lib/auto/File/DosGlob/DosGlob\.a lib/auto/File/Glob/Glob\.a lib/auto/Filter/Util/Call/Call\.a lib/auto/GDBM\_File/GDBM\_File\.a lib/auto/Hash/Util/Util\.a lib/auto/Hash/Util/FieldHash/FieldHash\.a lib/auto/I18N/Langinfo/Langinfo\.a lib/auto/IO/IO\.a lib/auto/IPC/SysV/SysV\.a lib/auto/List/Util/Util\.a lib/auto/Math/BigInt/FastCalc/FastCalc\.a lib/auto/MIME/Base64/Base64\.a lib/auto/mro/mro\.a lib/auto/NDBM\_File/NDBM\_File\.a lib/auto/ODBM\_File/ODBM\_File\.a lib/auto/Opcode/Opcode\.a lib/auto/PerlIO/encoding/encoding\.a lib/auto/PerlIO/mmap/mmap\.a lib/auto/PerlIO/scalar/scalar\.a lib/auto/PerlIO/via/via\.a lib/auto/POSIX/POSIX\.a lib/auto/re/re\.a lib/auto/SDBM\_File/SDBM\_File\.a lib/auto/Socket/Socket\.a lib/auto/Storable/Storable\.a lib/auto/Sys/Hostname/Hostname\.a lib/auto/Sys/Syslog/Syslog\.a lib/auto/threads/threads\.a lib/auto/threads/shared/shared\.a lib/auto/Tie/Hash/NamedCapture/NamedCapture\.a lib/auto/Time/HiRes/HiRes\.a lib/auto/Time/Piece/Piece\.a lib/auto/Unicode/Collate/Collate\.a lib/auto/Unicode/Normalize/Normalize\.a lib/auto/Encode/Byte/Byte\.a lib/auto/Encode/CN/CN\.a lib/auto/Encode/EBCDIC/EBCDIC\.a lib/auto/Encode/JP/JP\.a lib/auto/Encode/KR/KR\.a lib/auto/Encode/Symbol/Symbol\.a lib/auto/Encode/TW/TW\.a lib/auto/Encode/Unicode/Unicode\.a libperl\.a \`cat ext\.libs\` \-lnsl \-lgdbm \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc \-lgdbm\_compat 
libperl\.a\(regexec\.o\)&#8203;: In function \`Perl\_\_get\_regclass\_nonbitmap\_data'&#8203;:
regexec\.c&#8203;:\(\.text\+0x1ea0\)&#8203;: multiple definition of \`Perl\_\_get\_regclass\_nonbitmap\_data'
lib/auto/re/re\.a\(re\_exec\.o\)&#8203;:re\_exec\.c&#8203;:\(\.text\+0x39c0\)&#8203;: first defined here
collect2&#8203;: ld returned 1 exit status
make&#8203;: \*\*\* \[perl\] Error 1

git bisection put the offending commit being&#8203;:

http&#8203;://perl5\.git\.perl\.org/perl\.git/commitdiff/77d654fbc7477bd2bbb8741fcbb08e9b541f53e3

Many thanks\,

\-\- 
Chris Williams
aka BinGOs
PGP ID 0x4658671F
http&#8203;://www\.gumbynet\.org\.uk
==========================

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu Feb 20 14&#8203;:18&#8203;:15 2014\, chris@&#8203;bingosnet\.co\.uk wrote&#8203;:
> Static builds \(Configure with \-Uusedl\) are broken&#8203;:

Craig's 3e63bed3c572617faf16446e7b44b5ea0b78e979 fixes the build\, and you appear to have a fix for the Module&#8203;::Load \-Uusedl failures on the way\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @bingos

On Thu\, Feb 20\, 2014 at 02&#8203;:18&#8203;:15PM \-0800\, Kidney Bingos wrote&#8203;:
> \# New Ticket Created by  Kidney Bingos 
> \# Please include the string&#8203;:  \[perl \#121291\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=121291 >
> 
> 
> Static builds \(Configure with \-Uusedl\) are broken&#8203;:
> 
> cc \-o perl \-fstack\-protector \-L/usr/local/lib  perlmain\.o lib/auto/arybase/arybase\.a lib/auto/attributes/attributes\.a lib/auto/B/B\.a lib/auto/Compress/Raw/Bzip2/Bzip2\.a lib/auto/Compress/Raw/Zlib/Zlib\.a lib/auto/Cwd/Cwd\.a lib/auto/Data/Dumper/Dumper\.a lib/auto/Devel/Peek/Peek\.a lib/auto/Devel/PPPort/PPPort\.a lib/auto/Digest/MD5/MD5\.a lib/auto/Digest/SHA/SHA\.a lib/auto/Encode/Encode\.a lib/auto/Fcntl/Fcntl\.a lib/auto/File/DosGlob/DosGlob\.a lib/auto/File/Glob/Glob\.a lib/auto/Filter/Util/Call/Call\.a lib/auto/GDBM\_File/GDBM\_File\.a lib/auto/Hash/Util/Util\.a lib/auto/Hash/Util/FieldHash/FieldHash\.a lib/auto/I18N/Langinfo/Langinfo\.a lib/auto/IO/IO\.a lib/auto/IPC/SysV/SysV\.a lib/auto/List/Util/Util\.a lib/auto/Math/BigInt/FastCalc/FastCalc\.a lib/auto/MIME/Base64/Base64\.a lib/auto/mro/mro\.a lib/auto/NDBM\_File/NDBM\_File\.a lib/auto/ODBM\_File/ODBM\_File\.a lib/auto/Opcode/Opcode\.a lib/auto/PerlIO/encoding/encoding\.a lib/auto/PerlIO/mmap/mmap\.a lib/auto/PerlIO/scalar/scalar\.a lib/auto/PerlIO/
>  via/via\.a lib/auto/POSIX/POSIX\.a lib/auto/re/re\.a lib/auto/SDBM\_File/SDBM\_File\.a lib/auto/Socket/Socket\.a lib/auto/Storable/Storable\.a lib/auto/Sys/Hostname/Hostname\.a lib/auto/Sys/Syslog/Syslog\.a lib/auto/threads/threads\.a lib/auto/threads/shared/shared\.a lib/auto/Tie/Hash/NamedCapture/NamedCapture\.a lib/auto/Time/HiRes/HiRes\.a lib/auto/Time/Piece/Piece\.a lib/auto/Unicode/Collate/Collate\.a lib/auto/Unicode/Normalize/Normalize\.a lib/auto/Encode/Byte/Byte\.a lib/auto/Encode/CN/CN\.a lib/auto/Encode/EBCDIC/EBCDIC\.a lib/auto/Encode/JP/JP\.a lib/auto/Encode/KR/KR\.a lib/auto/Encode/Symbol/Symbol\.a lib/auto/Encode/TW/TW\.a lib/auto/Encode/Unicode/Unicode\.a libperl\.a \`cat ext\.libs\` \-lnsl \-lgdbm \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc \-lgdbm\_compat 
> libperl\.a\(regexec\.o\)&#8203;: In function \`Perl\_\_get\_regclass\_nonbitmap\_data'&#8203;:
> regexec\.c&#8203;:\(\.text\+0x1ea0\)&#8203;: multiple definition of \`Perl\_\_get\_regclass\_nonbitmap\_data'
> lib/auto/re/re\.a\(re\_exec\.o\)&#8203;:re\_exec\.c&#8203;:\(\.text\+0x39c0\)&#8203;: first defined here
> collect2&#8203;: ld returned 1 exit status
> make&#8203;: \*\*\* \[perl\] Error 1
> 
> git bisection put the offending commit being&#8203;:
> 
> http&#8203;://perl5\.git\.perl\.org/perl\.git/commitdiff/77d654fbc7477bd2bbb8741fcbb08e9b541f53e3
> 

And Mr\. Berry has fixed this with commit 3e63bed3

\\o/

\-\- 
Chris Williams
aka BinGOs
PGP ID 0x4658671F
http&#8203;://www\.gumbynet\.org\.uk
==========================

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu Feb 20 15&#8203;:30&#8203;:37 2014\, chris@&#8203;bingosnet\.co\.uk wrote&#8203;:
> And Mr\. Berry has fixed this with commit 3e63bed3

And you've fixed Module&#8203;::Load\, so closing this ticket\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'resolved'
