### ISSUE TITLE
crash (segmentation fault) on undeclared variable in class

### ISSUE THREAD

**Issue by mauke** [Perl/perl5#24616]
**Description**

Instead of diagnosing the `strict` violation (undeclared variable), perl crashes at compile time. This seems to have been introduced in 5.40 because 5.38 still works as expected.

**Steps to Reproduce**
```perl
use strict;
use warnings;
use experimental 'class';
my $r;
class Bug;
field $_y = $r->{foo}{bar};
method g() { $x }
```

```console
$ perl -c crash.pl
Segmentation fault (core dumped)
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00005555556431a4 in Perl_pad_free (po=5) at pad.c:1838
1838        if (sv && sv != &PL_sv_undef && !SvPADMY(sv))
(gdb) bt
#0  0x00005555556431a4 in Perl_pad_free (po=5) at pad.c:1838
#1  0x00005555555acbfe in Perl_op_clear (o=o@entry=0x555555aabba0) at op.c:1416
#2  0x00005555555ab97d in Perl_op_free (o=0x555555aabba0) at op.c:1042
#3  0x00005555555abddc in Perl_op_free (o=<optimized out>) at op.c:932
#4  0x00005555555f31c5 in S_class_cleanup_definition (stash=0x555555aa4228) at class.c:697
#5  Perl_class_seal_stash (stash=0x555555aa4228) at class.c:760
#6  0x000055555577c546 in Perl_leave_scope (base=base@entry=35) at scope.c:1819
#7  0x00005555555b1537 in Perl_block_end (floor=35, seq=<optimized out>) at op.c:4735
#8  0x000055555565da22 in Perl_yyparse (gramtype=gramtype@entry=258) at /home/mauke/Projects/perl5/perly.y:194
#9  0x00005555555db54b in S_parse_body (xsinit=0x5555555a1460 <xs_init>, env=0x0) at perl.c:2705
#10 perl_parse (my_perl=<optimized out>, xsinit=xsinit@entry=0x5555555a1460 <xs_init>, argc=<optimized out>, argv=<optimized out>, env=env@entry=0x0) at perl.c:1941
#11 0x00005555555a12a3 in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at perlmain.c:106
(gdb) p sv
$1 = (SV *) 0x31
```

**Expected behavior**
```console
$ perl -c crash.pl
Global symbol "$x" requires explicit package name (did you forget to declare "my $x"?) at crash.pl line 7.
crash.pl had compilation errors.
```

**Perl configuration**

<details>

```
This is perl 5, version 44, subversion 0 (v5.44.0) built for x86_64-linux-thread-multi
```

</details>

**Comment by jkeenan** [comment]
I attempted to bisect this problem with the following invocation (unthreaded, Linux):
```
$ cat $P5P_DIR/gh-24616-class.pl
use strict;
use warnings;
use experimental 'class';
my $r;
class Bug;
field $_y = $r->{foo}{bar};
method g() { $x }

$ perl Porting/bisect.pl \
--start=v5.38.0 \
--end=v5.40.0 \
--crash \
-- ./perl -Ilib $P5P_DIR/gh-24616-class.pl
```
That pointed to 080297a1c0 as the commit where the program began to crash (as distinct from `die`-ing due to syntax error).
```
080297a1c054c421f95cf78ca4f58a960f1d124f is the first bad commit
commit 080297a1c054c421f95cf78ca4f58a960f1d124f
Author: Tony Cook <tony@develop-help.com>
Date:   Tue Sep 5 16:37:48 2023 +1000
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Fri Sep 15 09:10:37 2023 +1000

    class: don't leak the default initialiser ops if they're forbidden
```
@tonycoz, can you take a look?

**Comment by jkeenan** [comment]
**To complicate this problem ...**

In order to explore this issue, I built a threaded perl on **FreeBSD** at blead (44f4945c88) with my customary switches.
```
$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Duseithreads -Doptimize=-O2 -pipe -fstack-protector-strong -fno-strict-aliasing';
```
```
$ $ cat $P5P_DIR/gh-24616-class.pl
use strict;
use warnings;
use experimental 'class';
my $r;
class Bug;
field $_y = $r->{foo}{bar};
method g() { $x }
```
I then ran the program, first with `./miniperl`, then with `./perl`.
```
$ ./miniperl -Ilib $P5P_DIR/gh-24616-class.pl
Global symbol "$x" requires explicit package name (did you forget to declare "my $x"?) at /home/jkeenan/learn/perl/p5p/gh-24616-class.pl line 7.
Execution of /home/jkeenan/learn/perl/p5p/gh-24616-class.pl aborted due to compilation errors.

$ ./perl -Ilib $P5P_DIR/gh-24616-class.pl
Global symbol "$x" requires explicit package name (did you forget to declare "my $x"?) at /home/jkeenan/learn/perl/p5p/gh-24616-class.pl line 7.
Execution of /home/jkeenan/learn/perl/p5p/gh-24616-class.pl aborted due to compilation errors.
```
I did not get a segfault either way.  Nor did I get a segfault when I configured with a simple unthreaded build.

Is it possible there is an OS-specific aspect to this problem?

**Comment by mauke** [comment]
valgrind reports:
```
==877893== Invalid read of size 8
==877893==    at 0x1F718E: Perl_pad_free (pad.c:1837)
==877893==    by 0x160BFD: Perl_op_clear (op.c:1416)
==877893==    by 0x15F97C: Perl_op_free.part.0 (op.c:1042)
==877893==    by 0x1A71C4: S_class_cleanup_definition (class.c:697)
==877893==    by 0x1A71C4: Perl_class_seal_stash (class.c:760)
==877893==    by 0x330545: Perl_leave_scope (scope.c:1820)
==877893==    by 0x165536: Perl_block_end (op.c:4735)
==877893==    by 0x211A21: Perl_yyparse (perly.y:194)
==877893==    by 0x18F54A: S_parse_body (perl.c:2705)
==877893==    by 0x18F54A: perl_parse (perl.c:1941)
==877893==    by 0x1552A2: main (perlmain.c:106)
==877893==  Address 0x4bd40a0 is 0 bytes after a block of size 32 alloc'd
==877893==    at 0x484D953: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==877893==    by 0x3AEC4C: Perl_safesyscalloc (util.c:503)
==877893==    by 0x1F8326: Perl_pad_new (pad.c:226)
==877893==    by 0x18EFA0: S_parse_body (perl.c:2602)
==877893==    by 0x18EFA0: perl_parse (perl.c:1941)
==877893==    by 0x1552A2: main (perlmain.c:106)
```
