### PR TITLE
Update Safe.pm to use tr/// to trigger loading utf8_heavy.pl.

### LINKED ISSUE #17271: Safe.pm
Safe.pm starting at line 60 talks about swashes.
The code it uses to load swashes hasn't done anything in the last release or so.
The only remaining use of swashes in the core C files has been in tr/// where the lhs and/or rhs have above-255 code points.
That means that if one of these is encountered, utf8_heavy.pl would need to be loaded
It's not clear to me if Safe cares about that and should try to preload it or not.
But if it does care, it needs to use a tr/// to cause it to get loaded instead of the current method, as that has been out-of-date.  As of today, utf8_heavy is gone from core, but Safe is supposed to work in earlier perl versions.  So, if it really does need utf8_heavy to be loaded when that file existed, it needs to use tr/// to force this.

### PR DESCRIPTION
**Pull request by simcop2387**
This would fix #17271 

I've probably not done this PR correctly, not sure if it should be going to a smoke-me branch or anything first either.  I've tested the changed bits of code in 5.6 and they seem to work fine (still working on testing the whole module, my 5.6.2 install is missing some needed modules).

With the change to using tr/// like this there doesn't seem to be any real reason to keep the stuff conditional on earlier than 5.7.3, but I can fix that if I'm missing something there.

### CODE REVIEW

**Comment by simcop2387** [comment]
I've tested this and the change itself works down to 5.16 though there's a change in the warning that still has it fail overall.  Earlier versions seem to fail with some other problems related to IsDigit not working properly, I suspect that they need some work to make Safe.pm here work properly on them regardless.

```
perlbot@simcop2387:~/build/perl5/dist/Safe$ make test
PERL_DL_NONLAZY=1 "/home/perlbot/perl5/custom/5.16.3/bin/perl5.16.3" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/safe1.t .......... ok    
t/safe2.t .......... ok    
t/safe3.t .......... ok   
t/safeload.t ....... 1/3 
#   Failed test 'Can load version.pm in a Safe compartment'
#   at t/safeload.t line 26.
# Unable to create sub named "*Safe::Root0::version::vxs::numify" at /home/perlbot/perl5/custom/5.16.3/lib/site_perl/5.16.3/x86_64-linux/version.pm line 48.
# Compilation failed in require at (eval 9) line 1.
# BEGIN failed--compilation aborted at (eval 9) line 1.
# Looks like you failed 1 test of 3.
t/safeload.t ....... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
t/safenamedcap.t ... ok   
t/safeops.t ........ skipped: PERL_CORE unset
t/saferegexp.t ..... ok   
t/safesecurity.t ... ok   
t/safesort.t ....... ok     
t/safeuniversal.t .. ok   
t/safeutf8.t ....... 1/7 
#   Failed test 'warn should return 1'
#   at t/safeutf8.t line 43.
#          got: undef
#     expected: '1'

#   Failed test 'warning should have been edited'
#   at t/safeutf8.t line 46.
#                   '   (in cleanup) Can't find Unicode property definition "IsDigit" at t/safeutf8.t line 39.
# '
#     doesn't match '(?^:at XXX line)'
# Looks like you failed 2 tests of 7.
t/safeutf8.t ....... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/7 subtests 
t/safewrap.t ....... ok     

Test Summary Report
-------------------
t/safeload.t     (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
t/safeutf8.t     (Wstat: 512 Tests: 7 Failed: 2)
  Failed tests:  4, 7
  Non-zero exit status: 2
Files=12, Tests=100,  1 wallclock secs ( 0.05 usr  0.01 sys +  0.76 cusr  0.13 csys =  0.95 CPU)
Result: FAIL
Failed 2/12 test programs. 3/100 subtests failed.
make: *** [Makefile:842: test_dynamic] Error 255
```

**Comment by simcop2387** [comment]
I also realize that with the removal of swashes in core that this likely is only needed and relevant for the 5.30 maintenance cycle

**Comment by khwilliamson** [comment]
Safe should be downloadable to work on old perls.  So it would be worth doing not just for maint.

**Comment by khwilliamson** [comment]
It was my understanding that you are planning to work on revising this?  Am I correct?

**Comment by coypoop** [comment]
ping :-)
