### ISSUE TITLE
`package NAME VER` syntax does not work with devel version numbers

### ISSUE THREAD

**Issue by leonerd** [Perl/perl5#21499]
It's common practice to put a `_` symbol in a version number to indicate development or trial release. E.g.

```perl
package Work::In::Progress;
our $VERSION = '0.001_001';
```

Such a version number does not work in the `package` of 5.14+:

```perl
package Work::In::Progress 0.001_001;
```
```
Invalid version format (no underscores) at - line 1, near "package Work::In::Progress "
syntax error at - line 1, near "package Work::In::Progress 0.001_001"
Execution of - aborted due to compilation errors.
```

Nor when quoted:

```perl
package Work::In::Progress '0.001_001';
```
```
Invalid version format (non-numeric data) at - line 1, near "package Work::In::Progress "
syntax error at - line 1, near "package Work::In::Progress '0.001_001'"
Execution of - aborted due to compilation errors.
```

The only viable workaround here is to continue to use the pre-5.14 style of direct assignment to the `$VERSION` package variable; which has a few annoying downsides (less automatic scanning, doesn't happen at BEGIN time)

**Comment by iabyn** [comment]
On Wed, Sep 20, 2023 at 04:19:29AM -0700, Paul Evans wrote:
> It's common practice to put a `_` symbol in a version number to indicate
> development or trial release. E.g.
...
> Invalid version format (no underscores) at - line 1, near "package Work::In::Progress "

Given that the code in vutil.c explicitly checks for an underscore and if
so, complains with an error message that includes the text 'no
underscores', this seems to be very intended behaviour.

As to why its intended, I have no idea or opinion.

-- 
Never work with children, animals, or actors.

**Comment by leonerd** [comment]
> Given that the code in vutil.c explicitly checks for an underscore and if so, complains with an error message that includes the text 'no underscores', this seems to be very intended behaviour.

Oh indeed. It's one of those "bugs" that's more a "the intended behaviour doesn't seem useful or correct", rather than "this is implemented wrong".

I feel that supporting this kind of thing would be useful, so it's perhaps more a feature-request than a true bug. Classification is tricky. ;)

**Comment by Grinnz** [comment]
My best guess is it's related to bareword number parsing ignoring underscores thus rendering them not usable by versioning, and versions can only be specified as barewords in this syntax (as well as in "use"). But I don't know whether that's actually a technical limitation here, or it was prohibited "just in case".

**Comment by Leont** [comment]
We have a concept of strict versus loose format, and this wants strict

**Comment by jkeenan** [comment]
My sense from reviewing this ticket is that there's no real bug here, hence the ticket is closable.  @leonerd, perhaps you could open a ticket that is more explicitly a feature request?

**Comment by Leont** [comment]
> My sense from reviewing this ticket is that there's no real bug here, hence the ticket is closable. @leonerd, perhaps you could open a ticket that is more explicitly a feature request?

I would agree.

Development versions is not a concept that is meaningful in the context of modules, it only makes sense in the context of a distribution tarball that's being uploaded to PAUSE.

**Comment by jkeenan** [comment]
> > My sense from reviewing this ticket is that there's no real bug here, hence the ticket is closable. @leonerd, perhaps you could open a ticket that is more explicitly a feature request?
> 
> I would agree.
> 
> Development versions is not a concept that is meaningful in the context of modules, it only makes sense in the context of a distribution tarball that's being uploaded to PAUSE.

In the past month no one has argued in favor of keeping this ticket open.  Hence, closing it now.
