### ISSUE TITLE
wrong line number in syntax error message

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9991]
Migrated from [rt.perl.org#70910](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=70910) (status was 'resolved')

Searchable as RT70910$

**Comment by p5pRT** [comment]
### From frank.wiegand@gmail.com

This is a bug report for perl from frank\.wiegand@&#8203;gmail\.com\,
generated with the help of perlbug 1\.39 running under perl 5\.11\.2\.




---
&nbsp;  $ bleadperl \-e '\+'
&nbsp;  syntax error at \-e line 2\, at EOF
&nbsp;  Execution of \-e aborted due to compilation errors\.

This broke between 5\.11\.0 and 5\.11\.2\, git bisect reports&#8203;:

f0e67a1d29102aa9905aecf2b0f98449697d5af3 is the first bad commit
commit f0e67a1d29102aa9905aecf2b0f98449697d5af3
Author&#8203;: Zefram \<zefram@&#8203;fysh\.org>
Date&#8203;:   Sun Nov 15 14&#8203;:25&#8203;:50 2009 \+0100

&nbsp;    lexer API

&nbsp;    Attached is a patch that adds a public API for the lowest layers of
&nbsp;    lexing\.  This is meant to provide a solid foundation for the parsing that
&nbsp;    Devel&#8203;::Declare and similar modules do\, and it complements the pluggable
&nbsp;    keyword mechanism\.  The API consists of some existing variables combined
&nbsp;    with some new functions\, all marked as experimental \(which making them
&nbsp;    public certainly is\)\.

:100644 100644 22db6a3c9011829aff5176a7bacd4373f9c1d354 b8073eb771a2c615c876970bc1883bd4316cc88c M      MANIFEST
:100644 100644 7522055a288adf11291c654a30726bd618c11f25 f17f7ada0a8c023af12e8aa9b7800f9ccf643df5 M      embed\.fnc
:100644 100644 52e40c6fa2f68c4c009a83d7669522543a9baad1 17bf11a5139254f0a5f6a46473bb136d1c145259 M      embed\.h
:040000 040000 23226494a6184590278d718527f383b69fff2cf3 6ebec696e22c1a6f7b1b4043db5a090006e9f1b1 M      ext
:100644 100644 6000af755912fcd939cbe94d4662c54dd42acd5b 6a44049c4e4262b09ae4c5a0d2fd2d9749f12189 M      global\.sym
:100644 100644 74d8ef2197b15a99ce10a233a2f829c286043022 462dcfdef806826927c7e9c5261e46e57033960c M      parser\.h
:100644 100644 3639bd6ac0f26afd8537e3e9722382c2ba5beea2 3d378917c94e26aa9a550c181fdd824d6aad2e60 M      perlvars\.h
:040000 040000 79cfd550ba3c1ee290da3a30115bcade3d31effb 4de6df320a87c92b6db4c4df6a5b3cbace2d96bb M      pod
:100644 100644 f1ab3d022e76840708a2367ea74a652b299bd6f1 fd2eb36cd42cecae815240f00f301038d0aba9fc M      proto\.h
:100644 100644 b8abbd854f001057679312ed03b534e0853cf490 6793f7b8669efb9df31731d9eff7507d6672c9b6 M      toke\.c


Frank



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl 5\.11\.2&#8203;:

Configured by fw at Sat Nov 28 22&#8203;:03&#8203;:13 CET 2009\.

Summary of my perl5 \(revision 5 version 11 subversion 2\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 17c59fdf7540adaf656e96fe6d48b58dab391dc0
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.30\-2\-amd64\, archname=x86\_64\-linux
&nbsp;    uname='linux hal2 2\.6\.30\-2\-amd64 \#1 smp fri sep 25 22&#8203;:16&#8203;:56 utc 2009 x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Dusedevel \-Doptimize=\-g \-Dcc=ccache gcc \-Dld=gcc'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache gcc'\, ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.3\.4'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=/lib/libc\-2\.10\.1\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.10\.1'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.11\.2&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.11\.2/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.11\.2
&nbsp;    /usr/local/lib/perl5/5\.11\.2/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/5\.11\.2
&nbsp;    \.



---
Environment for perl 5\.11\.2&#8203;:
&nbsp;    HOME=/home/cpan
&nbsp;    LANG=C
&nbsp;    LANGUAGE=
&nbsp;    LC\_ALL=C
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=~/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/local/games&#8203;:/usr/games
&nbsp;    PERL\_AUTOINSTALL=\-\-defaultdeps
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    PERL\_EXTUTILS\_AUTOINSTALL=\-\-defaultdeps
&nbsp;    PERL\_MM\_USE\_DEFAULT=1
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Frank Wiegand wrote&#8203;:
>  $ bleadperl \-e '\+'
>  syntax error at \-e line 2\, at EOF

Bah\, that's another area where I tested a bunch of variations while
developing the patch\, but apparently missed some\.  I'll look into it\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Frank Wiegand wrote&#8203;:
>  $ bleadperl \-e '\+'
>  syntax error at \-e line 2\, at EOF

Fixed by the attached patch\.

\-zefram

**Comment by p5pRT** [comment]
### From zefram@fysh.org

<details><summary>Inline Patch</summary>

```diff
diff --git a/MANIFEST b/MANIFEST
index a85d318..43e9a49 100644
--- a/MANIFEST
+++ b/MANIFEST
@@ -4187,6 +4187,7 @@ t/comp/bproto.t			See if builtins conform to their prototypes
 t/comp/cmdopt.t			See if command optimization works
 t/comp/colon.t			See if colons are parsed correctly
 t/comp/decl.t			See if declarations work
+t/comp/final_line_num.t		See if line numbers are correct at EOF
 t/comp/fold.t			See if constant folding works
 t/comp/hints.aux		Auxillary file for %^H test
 t/comp/hints.t			See if %^H works
diff --git a/t/comp/final_line_num.t b/t/comp/final_line_num.t
new file mode 100644
index 0000000..bb06847
--- /dev/null
+++ b/t/comp/final_line_num.t
@@ -0,0 +1,13 @@
+#!./perl
+
+BEGIN { print "1..1\n"; }
+
+BEGIN { $SIG{__DIE__} = sub {
+	$_[0] =~ /\Asyntax error at [^ ]+ line ([0-9]+), at EOF/ or exit 1;
+	my $error_line_num = $1;
+	print $error_line_num == $last_line_num ? "ok 1\n" : "not ok 1\n";
+	exit 0;
+}; }
+
+# the next line causes a syntax error at end of file, to be caught above
+BEGIN { $last_line_num = __LINE__; } print 1+
diff --git a/toke.c b/toke.c
index d498a34..2ec5f2d 100644
--- a/toke.c
+++ b/toke.c
@@ -4363,7 +4363,8 @@ Perl_yylex(pTHX)
 		    PL_doextract = FALSE;
 		}
 	    }
-	    incline(s);
+	    if (PL_rsfp)
+		incline(s);
 	} while (PL_doextract);
 	PL_oldoldbufptr = PL_oldbufptr = PL_bufptr = PL_linestart = s;
 	PL_bufend = SvPVX(PL_linestr) + SvCUR(PL_linestr);
```
</details>

**Comment by p5pRT** [comment]
@obra - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @obra

Thanks\. Applied as 85613cabfd8d8a9b6b36082819bd6c38e1bb21c7


On Wed\, Dec 09\, 2009 at 10&#8203;:08&#8203;:33PM \+0000\, Zefram wrote&#8203;:
> Frank Wiegand wrote&#8203;:
> >  $ bleadperl \-e '\+'
> >  syntax error at \-e line 2\, at EOF
> 
> Fixed by the attached patch\.
> 
> \-zefram

> diff \-\-git a/MANIFEST b/MANIFEST
> index a85d318\.\.43e9a49 100644
> \-\-\- a/MANIFEST
> \+\+\+ b/MANIFEST
> @&#8203;@&#8203; \-4187\,6 \+4187\,7 @&#8203;@&#8203; t/comp/bproto\.t            See if builtins conform to their prototypes
>  t/comp/cmdopt\.t            See if command optimization works
>  t/comp/colon\.t            See if colons are parsed correctly
>  t/comp/decl\.t            See if declarations work
> \+t/comp/final\_line\_num\.t        See if line numbers are correct at EOF
>  t/comp/fold\.t            See if constant folding works
>  t/comp/hints\.aux        Auxillary file for %^H test
>  t/comp/hints\.t            See if %^H works
> diff \-\-git a/t/comp/final\_line\_num\.t b/t/comp/final\_line\_num\.t
> new file mode 100644
> index 0000000\.\.bb06847
> \-\-\- /dev/null
> \+\+\+ b/t/comp/final\_line\_num\.t
> @&#8203;@&#8203; \-0\,0 \+1\,13 @&#8203;@&#8203;
> \+\#\!\./perl
> \+
> \+BEGIN \{ print "1\.\.1\\n"; \}
> \+
> \+BEGIN \{ $SIG\{\_\_DIE\_\_\} = sub \{
> \+    $\_\[0\] =~ /\\Asyntax error at \[^ \]\+ line \(\[0\-9\]\+\)\, at EOF/ or exit 1;
> \+    my $error\_line\_num = $1;
> \+    print $error\_line\_num == $last\_line\_num ? "ok 1\\n" : "not ok 1\\n";
> \+    exit 0;
> \+\}; \}
> \+
> \+\# the next line causes a syntax error at end of file\, to be caught above
> \+BEGIN \{ $last\_line\_num = \_\_LINE\_\_; \} print 1\+
> diff \-\-git a/toke\.c b/toke\.c
> index d498a34\.\.2ec5f2d 100644
> \-\-\- a/toke\.c
> \+\+\+ b/toke\.c
> @&#8203;@&#8203; \-4363\,7 \+4363\,8 @&#8203;@&#8203; Perl\_yylex\(pTHX\)
>              PL\_doextract = FALSE;
>          \}
>          \}
> \-        incline\(s\);
> \+        if \(PL\_rsfp\)
> \+        incline\(s\);
>      \} while \(PL\_doextract\);
>      PL\_oldoldbufptr = PL\_oldbufptr = PL\_bufptr = PL\_linestart = s;
>      PL\_bufend = SvPVX\(PL\_linestr\) \+ SvCUR\(PL\_linestr\);


\-\-
