### PR TITLE
only croak on undef = ... not on (complex... undef) = ...

### LINKED ISSUE #18834: Convert::ASN1 breaks with commit 2583ef601d381a8a3e6e9b5f44db42bac0d537ab
Commit https://github.com/Perl/perl5/commit/2583ef601d381a8a3e6e9b5f44db42bac0d537ab introduced a change that breaks tests on Convert:ASN1 for code that previously worked on all prior versions with errors:

```
PERL_DL_NONLAZY=1 "/home/cpan/bin/perl-blead/bin/perl5.35.1" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
Can't modify undef operator in scalar assignment at /home/cpan/.cpan/build/Convert-ASN1-0.29-0/blib/lib/Convert/ASN1/_decode.pm line 98, near ");"
BEGIN not safe after errors--compilation aborted at /home/cpan/.cpan/build/Convert-ASN1-0.29-0/blib/lib/Convert/ASN1/_decode.pm line 607.
Compilation failed in require at /home/cpan/.cpan/build/Convert-ASN1-0.29-0/blib/lib/Convert/ASN1.pm line 435.
BEGIN failed--compilation aborted at /home/cpan/.cpan/build/Convert-ASN1-0.29-0/blib/lib/Convert/ASN1.pm line 441.
Compilation failed in require at t/00prim.t line 7.
BEGIN failed--compilation aborted at t/00prim.t line 7.

```

Convert::ASN1
https://github.com/gbarr/perl-Convert-ASN1/blob/9c029e84c2d308c525e2d8e08f1432f670be29c4/lib/Convert/ASN1/_decode.pm#L97

op.c: 
https://github.com/Perl/perl5/blob/0b47b39244b67fe19dc971903ce28a7a637c2a9a/op.c#L4294

I will review the code in Convert::ASN1 I suppose it is possible it was not hitting that in runtime previously in the tests.

### PR DESCRIPTION
**Pull request by tonycoz**
@richardleach I'm not sure whether it was intended to croak on the case below

The previous check would trigger on code like:

  ($x ? $y : undef) = 1;

I also moved the test from t/run/fresh_perl.t to t/run/croak/op and
added a test for the broken case.

fixes #18834

### CODE REVIEW

**Comment by hvds** [comment]
> @richardleach I'm not sure whether it was intended to croak on the case below
> 
> The previous check would trigger on code like:
> 
> ($x ? $y : undef) = 1;

@tonycoz do you believe that authors are deliberately writing that expecting it to be equivalent to `die "Modification of a read-only value attempted" unless $x; $y = 1`?

> I also moved the test from t/run/fresh_perl.t to t/run/croak/op and
> added a test for the broken case.
> 
> fixes #18834

My reading of the author's comments on #18834 is that he acknowledges this as a bug: even though his tests did not exercise the case, his expectation was that the fallthrough case was a valid one, and he expected it to call the function on the RHS and discard the result.

So the change as it stands will show up bugs like this by flagging them as compile-time errors. Even if we end up changing this before 5.36 release, I do not think we should rush to do so much earlier than that release.

**Comment by tonycoz** [comment]
I don't know what the author intended,

But the original change #18785 , and the original bug #18779 only discuss the simple case, and the discussion in #18785 I think implies that we fail at compile-time when the code would have failed at runtime, which this code doesn't.

I don't mind if we choose to keep this behaviour, but to my mind it doesn't quite match the description.

**Comment by richardleach** [comment]
@tonycoz I don't mind which behaviour ends up being used. I hadn't come across complex (or really any) cases of people trying to scalar assign to undef, so wasn't aware that they were a thing.

I do share Hugo's concern regarding the programmer's expectation of:
`($x ? $y : undef) = 1;`

It does seem like a way of throwing the value away, like with list assignment to undef, and the fact that it could die might be surprising/unintentional. If the undef occurs only in rarely used code paths, it causing an application to surprisingly die does seem bad IMHO.

**Comment by Grinnz** [comment]
> @tonycoz I don't mind which behaviour ends up being used. I hadn't come across complex (or really any) cases of people trying to scalar assign to undef, so wasn't aware that they were a thing.
> 
> I do share Hugo's concern regarding the programmer's expectation of:
> `($x ? $y : undef) = 1;`
> 
> It does seem like a way of throwing the value away, like with list assignment to undef, and the fact that it could die might be surprising/unintentional. If the undef occurs only in rarely used code paths, it causing an application to surprisingly die does seem bad IMHO.

This of course would be reasonable to warn about at compile time. But making it an error breaks bugward compatibility of scripts that were running perfectly fine because they never actually hit that case at runtime.

**Comment by richardleach** [comment]
> > I do share Hugo's concern regarding the programmer's expectation of:
> > `($x ? $y : undef) = 1;`
> > It does seem like a way of throwing the value away, like with list assignment to undef, and the fact that it could die might be surprising/unintentional. If the undef occurs only in rarely used code paths, it causing an application to surprisingly die does seem bad IMHO.
> 
> This of course would be reasonable to warn about at compile time. But making it an error breaks bugward compatibility of scripts that were running perfectly fine because they never actually hit that case at runtime.

True. But Tony's version would have the same effect on scripts with `undef = $foo;` in an effectively unreachable code block. (I appreciate that's probably splitting hairs.)

**Comment by Grinnz** [comment]
> True. But Tony's version would have the same effect on scripts with `undef = $foo;` in an effectively unreachable code block. (I appreciate that's probably splitting hairs.)

In my opinion that is an acceptable degree, because it's plain that was never going to work, whereas clearly there has been instances where developers assumed (wrongly) a conditional assignment would simply be ignored.

**Comment by richardleach** [comment]
> But making it an error breaks bugward compatibility of scripts that were running perfectly fine because they never actually hit that case at runtime.

I'm a bit grumpy, since this will keep life easier for people who have fragile code at the expense of people who might be about to write new fragile code. But I appreciate that's the trade off of bugward compatibility.

**Comment by hvds** [comment]
> I don't mind which behaviour ends up being used. I hadn't come across complex (or really any) cases of people trying to scalar assign to undef, so wasn't aware that they were a thing.
> 
> I do share Hugo's concern regarding the programmer's expectation of:
> `($x ? $y : undef) = 1;`
> 
> It does seem like a way of throwing the value away, like with list assignment to undef, and the fact that it could die might be surprising/unintentional. If the undef occurs only in rarely used code paths, it causing an application to surprisingly die does seem bad IMHO.

Maybe the better solution, then, would be to make it a legitimate way of throwing a value away, same as in the list case.

**Comment by richardleach** [comment]
> Maybe the better solution, then, would be to make it a legitimate way of throwing a value away, same as in the list case.

That would definitely add consistency.

**Comment by richardleach** [comment]
> Maybe the better solution, then, would be to make it a legitimate way of throwing a value away, same as in the list case.

@Grinnz / @tonycoz - what are your thoughts on that?
