### ISSUE TITLE
(regression?) v5.17.6+ segfaulting on simple (buggy) code

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12913]
Migrated from [rt.perl.org#117607](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=117607) (status was 'resolved')

Searchable as RT117607$

**Comment by p5pRT** [comment]
### From @garu

This is a bug report for perl from garu@&#8203;cpan\.org\,
generated with the help of perlbug 1\.39 running under perl 5\.17\.10\.




---
Many thanks to David Leadbeater \(dg\) for doing the actual work
of debugging and bisecting the issue\!

$ cat Boom\.pm
BEGIN \{
&nbsp;  $^H |= 0x00000400; \# strict vars
\}
\# Undeclared variable here
sub foo \{ return $anyvar; \}
\# Any CORE&#8203;:: here
sub bar \{ \\&CORE&#8203;::lc \}



$ cat boom\.sh
\#\!/bin/sh
\./miniperl ~/Boom\.pm
\# expected syntax error
\[ $? = 255 \] && exit 0
\# segfault
exit 1



$ \.\./perl\-bisect/Porting/bisect\.pl \-\-target miniperl ~/boom\.sh
\[\.\.\.\]
9ffcdca1f504cb09088413c074b35af4b7f247e3 is the first bad commit
commit 9ffcdca1f504cb09088413c074b35af4b7f247e3
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Mon Nov 12 23&#8203;:04&#8203;:16 2012 \-0800

&nbsp;    Donât leak subs containing syntax errors

&nbsp;    I fixed this for BEGIN blocks earlier\, but missed the fact that
&nbsp;    all subs are affected\.

&nbsp;    When called without an o argument \(from newANONATTRSUB\)\, newATTRSUB
&nbsp;    is expected to return a CV with an unowned reference count of which
&nbsp;    the caller will take ownership\.  We cannot have newATTRSUB returning
&nbsp;    a freed CV\, so we have it return null instead\.  But that means
&nbsp;    ck\_anoncode and pm\_runtime have to account for that\.

:100644 100644 3f71cffc1351b181760b3b22d2bebb5eae5c16d9
b2801c7b5f4807886cc293e3fb567a46202b6e4d M      op\.c
:040000 040000 5cbf8745aa1eaede5906d8da797797603d6f63ef
f29dce933f3a81a17022f3cc80bdcf115d44bb2c M      t
bisect run success
That took 332 seconds



dgl@&#8203;perlqa&#8203;:\~/perl/perl$ git describe 9ffcdca1f504cb09088413c074b35af4b7f247e3
v5\.17\.5\-461\-g9ffcdca



dgl@&#8203;perlqa&#8203;:\~/perl/perl$ gdb \-\-args \./miniperl ~/Boom\.pm
GNU gdb \(Ubuntu/Linaro 7\.4\-2012\.04\-0ubuntu2\.1\) 7\.4\-2012\.04
Copyright \(C\) 2012 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-linux\-gnu"\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://bugs\.launchpad\.net/gdb\-linaro/>\.\.\.
Reading symbols from /home/dgl/perl/perl/miniperl\.\.\.done\.
\(gdb\) r
Starting program&#8203;: /home/dgl/perl/perl/miniperl /home/dgl/Boom\.pm
warning&#8203;: no loadable sections found in added symbol\-file
system\-supplied DSO at 0x7ffff7ffa000

Program received signal SIGSEGV\, Segmentation fault\.
Perl\_mg\_magical \(sv=0x765130\) at mg\.c&#8203;:147
147                 const MGVTBL\* const vtbl = mg\->mg\_virtual;
\(gdb\) bt
\#0  Perl\_mg\_magical \(sv=0x765130\) at mg\.c&#8203;:147
\#1  0x000000000049484d in Perl\_sv\_magicext \(sv=0x765130\, obj=0x74e6d0\, how=93\,
&nbsp;    vtable=0x74bac0\, name=0x0\, namlen=\<optimized out>\) at sv\.c&#8203;:5264
\#2  0x0000000000495a83 in Perl\_sv\_magic \(sv=0x765130\, obj=0x74e6d0\,
how=93\, name=0x0\,
&nbsp;    namlen=\<optimized out>\) at sv\.c&#8203;:5338
\#3  0x00000000004109e7 in Perl\_cv\_set\_call\_checker \(cv=0x765130\,
&nbsp;    ckfun=0x4165d0 \<Perl\_ck\_entersub\_args\_core>\, ckobj=0x765100\) at op\.c&#8203;:10467
\#4  0x0000000000424344 in S\_maybe\_add\_coresub \(stash=\<optimized out>\,
gv=0x7650d0\,
&nbsp;    name=0x76ef96 "lc"\, len=2\) at gv\.c&#8203;:560
\#5  0x000000000042463a in Perl\_gv\_fetchpvn\_flags \(nambeg=0x76ef90 "CORE&#8203;::lc"\,
&nbsp;    full\_len=\<optimized out>\, flags=2\, sv\_type=SVt\_PVCV\) at gv\.c&#8203;:1717
\#6  0x0000000000425d30 in Perl\_gv\_fetchsv \(name=0x764ff8\, flags=2\,
sv\_type=SVt\_PVCV\)
&nbsp;    at gv\.c&#8203;:1380
\#7  0x0000000000410514 in Perl\_ck\_rvconst \(o=0x76f428\) at op\.c&#8203;:8571
\#8  0x0000000000414b50 in Perl\_newUNOP \(type=17\, flags=\<optimized
out>\, first=0x76f468\)
&nbsp;    at op\.c&#8203;:3978
\#9  0x0000000000444dda in Perl\_yyparse \(gramtype=\<optimized out>\) at
perly\.y&#8203;:1399
\#10 0x000000000040c68d in S\_parse\_body \(xsinit=0x422a40 \<xs\_init>\,
env=0x0\) at perl\.c&#8203;:2262
\#11 perl\_parse \(my\_perl=\<optimized out>\, xsinit=0x422a40 \<xs\_init>\,
argc=\<optimized out>\,
&nbsp;    argv=\<optimized out>\, env=0x0\) at perl\.c&#8203;:1620
\#12 0x00000000004058c0 in main \(argc=2\, argv=0x7fffffffe698\, env=0x7fffffffe6b0\)
&nbsp;    at miniperlmain\.c&#8203;:111
\(gdb\) p mg
$1 = \(const MAGIC \*\) 0xff00000000




---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=high


---
Site configuration information for perl 5\.17\.10&#8203;:

Configured by garu at Sun Apr 14 11&#8203;:05&#8203;:41 BST 2013\.

Summary of my perl5 \(revision 5 version 17 subversion 10\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.0\.0\-32\-generic\, archname=x86\_64\-linux
&nbsp;    uname='linux bebop 3\.0\.0\-32\-generic \#50\-ubuntu smp thu feb 28
22&#8203;:32&#8203;:30 utc 2013 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-de
\-Dprefix=/home/garu/perl5/perlbrew/perls/perl\-5\.17\.10 \-Dusedevel
\-Aeval&#8203;:scriptdir=/home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/bin'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-fno\-strict\-aliasing \-pipe \-fstack\-protector
\-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.6\.1'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib
/usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.13'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-L/usr/local/lib
\-fstack\-protector'

Locally applied patches&#8203;:




---
@&#8203;INC for perl 5\.17\.10&#8203;:
&nbsp;    /home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/lib/site\_perl/5\.17\.10/x86\_64\-linux
&nbsp;    /home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/lib/site\_perl/5\.17\.10
&nbsp;    /home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/lib/5\.17\.10/x86\_64\-linux
&nbsp;    /home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/lib/5\.17\.10
&nbsp;    \.



---
Environment for perl 5\.17\.10&#8203;:
&nbsp;    HOME=/home/garu
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE=
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/garu/perl5/perlbrew/bin&#8203;:/home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/bin&#8203;:/usr/local/sbin&#8203;:/usr/local/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/sbin&#8203;:/bin&#8203;:/usr/games
&nbsp;    PERLBREW\_BASHRC\_VERSION=0\.58
&nbsp;    PERLBREW\_HOME=/home/garu/\.perlbrew
&nbsp;    PERLBREW\_MANPATH=/home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/man
&nbsp;    PERLBREW\_PATH=/home/garu/perl5/perlbrew/bin&#8203;:/home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/bin
&nbsp;    PERLBREW\_PERL=perl\-5\.17\.10
&nbsp;    PERLBREW\_ROOT=/home/garu/perl5/perlbrew
&nbsp;    PERLBREW\_VERSION=0\.58
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @garu


This is a bug report for perl from garu@&#8203;cpan\.org\,
generated with the help of perlbug 1\.39 running under perl 5\.17\.10\.




---
Thanks to David Leadbeater \(dg\) for doing the actual work of
tracing and bisecting the issue\!

$ cat Boom\.pm 
BEGIN \{ 
&nbsp;  $^H |= 0x00000400; \# strict vars
\}
\# Undeclared variable here
sub foo \{ return $anyvar; \}
\# Any CORE&#8203;:: here
sub bar \{ \\&CORE&#8203;::lc \}




$ cat boom\.sh 
\#\!/bin/sh
\./miniperl ~/Boom\.pm
\# expected syntax error
\[ $? = 255 \] && exit 0
\# segfault
exit 1




$ \.\./perl\-bisect/Porting/bisect\.pl \-\-target miniperl ~/boom\.sh
\[\.\.\.\]
9ffcdca1f504cb09088413c074b35af4b7f247e3 is the first bad commit
commit 9ffcdca1f504cb09088413c074b35af4b7f247e3
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Mon Nov 12 23&#8203;:04&#8203;:16 2012 \-0800

&nbsp;    Donât leak subs containing syntax errors
&nbsp;    
&nbsp;    I fixed this for BEGIN blocks earlier\, but missed the fact that
&nbsp;    all subs are affected\.
&nbsp;    
&nbsp;    When called without an o argument \(from newANONATTRSUB\)\, newATTRSUB
&nbsp;    is expected to return a CV with an unowned reference count of which
&nbsp;    the caller will take ownership\.  We cannot have newATTRSUB returning
&nbsp;    a freed CV\, so we have it return null instead\.  But that means
&nbsp;    ck\_anoncode and pm\_runtime have to account for that\.

:100644 100644 3f71cffc1351b181760b3b22d2bebb5eae5c16d9 b2801c7b5f4807886cc293e3fb567a46202b6e4d M      op\.c
:040000 040000 5cbf8745aa1eaede5906d8da797797603d6f63ef f29dce933f3a81a17022f3cc80bdcf115d44bb2c M      t
bisect run success
That took 332 seconds




dgl@&#8203;perlqa&#8203;:\~/perl/perl$ git describe 9ffcdca1f504cb09088413c074b35af4b7f247e3
v5\.17\.5\-461\-g9ffcdca




dgl@&#8203;perlqa&#8203;:\~/perl/perl$ gdb \-\-args \./miniperl ~/Boom\.pm 
GNU gdb \(Ubuntu/Linaro 7\.4\-2012\.04\-0ubuntu2\.1\) 7\.4\-2012\.04
Copyright \(C\) 2012 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-linux\-gnu"\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://bugs\.launchpad\.net/gdb\-linaro/>\.\.\.
Reading symbols from /home/dgl/perl/perl/miniperl\.\.\.done\.
\(gdb\) r
Starting program&#8203;: /home/dgl/perl/perl/miniperl /home/dgl/Boom\.pm
warning&#8203;: no loadable sections found in added symbol\-file system\-supplied DSO at 0x7ffff7ffa000

Program received signal SIGSEGV\, Segmentation fault\.
Perl\_mg\_magical \(sv=0x765130\) at mg\.c&#8203;:147
147                 const MGVTBL\* const vtbl = mg\->mg\_virtual;
\(gdb\) bt
\#0  Perl\_mg\_magical \(sv=0x765130\) at mg\.c&#8203;:147
\#1  0x000000000049484d in Perl\_sv\_magicext \(sv=0x765130\, obj=0x74e6d0\, how=93\, 
&nbsp;    vtable=0x74bac0\, name=0x0\, namlen=\<optimized out>\) at sv\.c&#8203;:5264
\#2  0x0000000000495a83 in Perl\_sv\_magic \(sv=0x765130\, obj=0x74e6d0\, how=93\, name=0x0\, 
&nbsp;    namlen=\<optimized out>\) at sv\.c&#8203;:5338
\#3  0x00000000004109e7 in Perl\_cv\_set\_call\_checker \(cv=0x765130\, 
&nbsp;    ckfun=0x4165d0 \<Perl\_ck\_entersub\_args\_core>\, ckobj=0x765100\) at op\.c&#8203;:10467
\#4  0x0000000000424344 in S\_maybe\_add\_coresub \(stash=\<optimized out>\, gv=0x7650d0\, 
&nbsp;    name=0x76ef96 "lc"\, len=2\) at gv\.c&#8203;:560
\#5  0x000000000042463a in Perl\_gv\_fetchpvn\_flags \(nambeg=0x76ef90 "CORE&#8203;::lc"\, 
&nbsp;    full\_len=\<optimized out>\, flags=2\, sv\_type=SVt\_PVCV\) at gv\.c&#8203;:1717
\#6  0x0000000000425d30 in Perl\_gv\_fetchsv \(name=0x764ff8\, flags=2\, sv\_type=SVt\_PVCV\)
&nbsp;    at gv\.c&#8203;:1380
\#7  0x0000000000410514 in Perl\_ck\_rvconst \(o=0x76f428\) at op\.c&#8203;:8571
\#8  0x0000000000414b50 in Perl\_newUNOP \(type=17\, flags=\<optimized out>\, first=0x76f468\)
&nbsp;    at op\.c&#8203;:3978
\#9  0x0000000000444dda in Perl\_yyparse \(gramtype=\<optimized out>\) at perly\.y&#8203;:1399
\#10 0x000000000040c68d in S\_parse\_body \(xsinit=0x422a40 \<xs\_init>\, env=0x0\) at perl\.c&#8203;:2262
\#11 perl\_parse \(my\_perl=\<optimized out>\, xsinit=0x422a40 \<xs\_init>\, argc=\<optimized out>\, 
&nbsp;    argv=\<optimized out>\, env=0x0\) at perl\.c&#8203;:1620
\#12 0x00000000004058c0 in main \(argc=2\, argv=0x7fffffffe698\, env=0x7fffffffe6b0\)
&nbsp;    at miniperlmain\.c&#8203;:111
\(gdb\) p mg
$1 = \(const MAGIC \*\) 0xff00000000




---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=high


---
Site configuration information for perl 5\.17\.10&#8203;:

Configured by garu at Sun Apr 14 11&#8203;:05&#8203;:41 BST 2013\.

Summary of my perl5 \(revision 5 version 17 subversion 10\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.0\.0\-32\-generic\, archname=x86\_64\-linux
&nbsp;    uname='linux bebop 3\.0\.0\-32\-generic \#50\-ubuntu smp thu feb 28 22&#8203;:32&#8203;:30 utc 2013 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-de \-Dprefix=/home/garu/perl5/perlbrew/perls/perl\-5\.17\.10 \-Dusedevel \-Aeval&#8203;:scriptdir=/home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/bin'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.6\.1'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.13'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.17\.10&#8203;:
&nbsp;    /home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/lib/site\_perl/5\.17\.10/x86\_64\-linux
&nbsp;    /home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/lib/site\_perl/5\.17\.10
&nbsp;    /home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/lib/5\.17\.10/x86\_64\-linux
&nbsp;    /home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/lib/5\.17\.10
&nbsp;    \.



---
Environment for perl 5\.17\.10&#8203;:
&nbsp;    HOME=/home/garu
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE=
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/garu/perl5/perlbrew/bin&#8203;:/home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/bin&#8203;:/usr/local/sbin&#8203;:/usr/local/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/sbin&#8203;:/bin&#8203;:/usr/games
&nbsp;    PERLBREW\_BASHRC\_VERSION=0\.58
&nbsp;    PERLBREW\_HOME=/home/garu/\.perlbrew
&nbsp;    PERLBREW\_MANPATH=/home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/man
&nbsp;    PERLBREW\_PATH=/home/garu/perl5/perlbrew/bin&#8203;:/home/garu/perl5/perlbrew/perls/perl\-5\.17\.10/bin
&nbsp;    PERLBREW\_PERL=perl\-5\.17\.10
&nbsp;    PERLBREW\_ROOT=/home/garu/perl5/perlbrew
&nbsp;    PERLBREW\_VERSION=0\.58
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Apr 14\, 2013 at 06&#8203;:19&#8203;:56AM \-0700\, Breno G\. de Oliveira wrote&#8203;:
> $ cat Boom\.pm
> BEGIN \{
>   $^H |= 0x00000400; \# strict vars
> \}
> \# Undeclared variable here
> sub foo \{ return $anyvar; \}
> \# Any CORE&#8203;:: here
> sub bar \{ \\&CORE&#8203;::lc \}

It can be reduced slightly further&#8203;:


&nbsp;    BEGIN \{
&nbsp;      $^H |= 0x00000400; \# strict vars
&nbsp;    \}
&nbsp;    $anyvar;
&nbsp;    &CORE&#8203;::lc;

Looks like it should be 5\.18 blocker\.



\-\- 
The crew of the Enterprise encounter an alien life form which is
surprisingly neither humanoid nor made from pure energy\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#22

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @mauke

On 15\.04\.2013 13&#8203;:06\, Dave Mitchell wrote&#8203;:
> On Sun\, Apr 14\, 2013 at 06&#8203;:19&#8203;:56AM \-0700\, Breno G\. de Oliveira wrote&#8203;:
>> $ cat Boom\.pm
>> BEGIN \{
>>    $^H |= 0x00000400; \# strict vars
>> \}
>> \# Undeclared variable here
>> sub foo \{ return $anyvar; \}
>> \# Any CORE&#8203;:: here
>> sub bar \{ \\&CORE&#8203;::lc \}
>
> It can be reduced slightly further&#8203;:
>
>
>      BEGIN \{
>        $^H |= 0x00000400; \# strict vars
>      \}
>      $anyvar;
>      &CORE&#8203;::lc;
>
> Looks like it should be 5\.18 blocker\.

A debugging perl fails the assert in gv\.c&#8203;:551 \(S\_maybe\_add\_coresub\)&#8203;:
&nbsp;   assert\(GvCV\(gv\) == cv\);

because GvCV\(gv\) == NULL\.


\-\- 
Lukas Mai \<plokinom@&#8203;gmail\.com>

**Comment by p5pRT** [comment]
### From @tonycoz

I bisected this with a debugging perl\, and found&#8203;:

bad \- non\-zero exit from \./perl \-Ilib \-e eval q\[ use strict; $foo; sub \{
\\&CORE&#8203;::lc \} \];
a73ef99b394ac4c717d671b78792af7d844bbee1 is the first bad commit
commit a73ef99b394ac4c717d671b78792af7d844bbee1
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Wed Jun 20 13&#8203;:45&#8203;:43 2012 \-0700

&nbsp;    \[perl \#113712\] Don’t create stubs after errors

&nbsp;    perl5\.002beta3 \(c07a80fdfe\) stopped bodies of subrou\-
&nbsp;    tines from being defined after compilation errors\, as in
&nbsp;    eval "@&#8203;a =~ s///; sub \{ die \}"\.

&nbsp;    But\, instead of making the sub declaration not happen at all\, it ended
&nbsp;    up leaving a stub\.

&nbsp;    For a full sub declaration \(body and all\) to create a stub just
&nbsp;    seems wrong\.

&nbsp;    Likewise\, it would be weird if a stub declaration
&nbsp;    after a compilation error created a stub\, because then
&nbsp;    eval "@&#8203;a =~ s///; sub foo; sub bar \{ \}" would create foo but not bar\.

&nbsp;    Similarly\, a compilation error will cause ‘sub foo \{\}’ no suppress
&nbsp;    ‘used once’ warnings; but a lexing error won’t\.

&nbsp;    This commit fixes all this\, making things consistent&#8203;:  If there is a
&nbsp;    compilation\, parsing or lexing error\, any kind of sub declaration that
&nbsp;    follows is ignored\.

:100644 100644 69bd2a4df8cc2eae325ed03e408b0fcc260be241
5756eeb302b761276050e88da216f754323e67e6 M      op\.c
:040000 040000 ede63525624312bffafa5d226f9af4eb770e950c
d1ae239eaa8cb406eb2146e804434551909fc0cd M      t
bisect run success
That took 1639 seconds

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon Apr 15 04&#8203;:06&#8203;:51 2013\, davem wrote&#8203;:
> On Sun\, Apr 14\, 2013 at 06&#8203;:19&#8203;:56AM \-0700\, Breno G\. de Oliveira wrote&#8203;:
> > $ cat Boom\.pm
> > BEGIN \{
> >   $^H |= 0x00000400; \# strict vars
> > \}
> > \# Undeclared variable here
> > sub foo \{ return $anyvar; \}
> > \# Any CORE&#8203;:: here
> > sub bar \{ \\&CORE&#8203;::lc \}
> 
> It can be reduced slightly further&#8203;:
> 
> 
>     BEGIN \{
>       $^H |= 0x00000400; \# strict vars
>     \}
>     $anyvar;
>     &CORE&#8203;::lc;
> 
> Looks like it should be 5\.18 blocker\.

Even simpler&#8203;:

$foo/; \# some syntax error
\\&CORE&#8203;::lc;

Pushed a fix to smoke\-me/tonyc/core\_lc\_error

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu Apr 25 01&#8203;:29&#8203;:45 2013\, tonyc wrote&#8203;:
> On Mon Apr 15 04&#8203;:06&#8203;:51 2013\, davem wrote&#8203;:
> > On Sun\, Apr 14\, 2013 at 06&#8203;:19&#8203;:56AM \-0700\, Breno G\. de Oliveira wrote&#8203;:
> > > $ cat Boom\.pm
> > > BEGIN \{
> > >   $^H |= 0x00000400; \# strict vars
> > > \}
> > > \# Undeclared variable here
> > > sub foo \{ return $anyvar; \}
> > > \# Any CORE&#8203;:: here
> > > sub bar \{ \\&CORE&#8203;::lc \}
> > 
> > It can be reduced slightly further&#8203;:
> > 
> > 
> >     BEGIN \{
> >       $^H |= 0x00000400; \# strict vars
> >     \}
> >     $anyvar;
> >     &CORE&#8203;::lc;
> > 
> > Looks like it should be 5\.18 blocker\.
> 
> Even simpler&#8203;:
> 
> $foo/; \# some syntax error
> \\&CORE&#8203;::lc;
> 
> Pushed a fix to smoke\-me/tonyc/core\_lc\_error

Fix pushed as a92039c3eeab8e70aea3bee8729202a4b052282c\, closing\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'resolved'
