### ISSUE TITLE
BBC: Blead Breaks Moose

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#23637]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.43 running under perl 5.43.3.

-----------------------------------------------------------------

BBC: Blead Breaks Moose

Please see https://fast2-matrix.cpantesters.org/?dist=Moose-2.4000

---
**Flags**
- category=core
- severity=low
---
**Perl configuration**
```
Site configuration information for perl 5.43.3:

Configured by cpan at Sat Aug 23 16:56:00 EDT 2025.

Summary of my perl5 (revision 5 version 43 subversion 3) configuration:
  Commit id: 945b00874b2f85e42222530e693964968800fd4a
  Platform:
    osname=linux
    osvers=6.12.0-55.28.1.el10_0.x86_64
    archname=x86_64-linux
    uname='linux cjg-rhel10 6.12.0-55.28.1.el10_0.x86_64 #1 smp preempt_dynamic mon aug 11 15:13:30 edt 2025 x86_64 gnulinux '
    config_args='-des -Dprefix=/home/cpan/bin/perl -Dscriptdir=/home/cpan/bin/perl/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='14.2.1 20250110 (Red Hat 14.2.1-7)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /usr/lib64 /usr/local/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.39'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


---
@INC for perl 5.43.3:
    /home/cpan/bin/perl/lib/site_perl/5.43.3/x86_64-linux
    /home/cpan/bin/perl/lib/site_perl/5.43.3
    /home/cpan/bin/perl/lib/5.43.3/x86_64-linux
    /home/cpan/bin/perl/lib/5.43.3

---
Environment for perl 5.43.3:
    HOME=/home/cpan
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl/bin:/home/cpan/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash
```

**Comment by jkeenan** [comment]
@richardleach, I'm bisecting this now, but this is probably from one of your commits today (Aug 23).  If Moose is broken, then many distros will not be reachable via dependency-order CPAN testing.

The failure reports (*e.g.,* https://www.cpantesters.org/cpan/report/c1e2d158-8064-11f0-87e9-84543082b955) have a large number of previously unseen build-time and test-time warnings.

**Comment by jkeenan** [comment]
> 
> The failure reports (_e.g.,_ https://www.cpantesters.org/cpan/report/c1e2d158-8064-11f0-87e9-84543082b955) have a large number of previously unseen build-time and test-time warnings.

Correction:  These are test-time warnings (only, I think).
```
Reference is already weak at /home/cpan/.cpan/build/Moose-2.4000-0/blib/lib/Class/MOP/Method.pm line 139.
```

**Comment by jkeenan** [comment]
My attempt at bisection failed.  Bisecting with this invocation:
```
perl Porting/bisect.pl --start=0dd461623a4ff2e966b89561efd0904cf8239248 --module=Moose
```
... ended with this:
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
79b32d926ef5961b4946ebe761a7058cb235f797
0dfa8ac113680e6acdef0751168ab231b9bf842c
```
Those commits are, respectively:
```
v5.43.2-46-g945b00874b
v5.43.2-39-g0dfa8ac113
```
I am unsure how to proceed and am out of time for Perl today.

**Comment by karenetheridge** [comment]
I had no problem installing Moose once Sub::Quote had been patched to work around an issue that is now fixed in blead but was broken in 5.43.2.

**Comment by jkeenan** [comment]
> I had no problem installing Moose once Sub::Quote had been patched to work around an issue that is now fixed in blead but was broken in 5.43.2.

Yes, I had the same experience.  The problem reported in this ticket occurred after that point.

@richardleach, you've broken the build.  At least part of the problem is that the following commit fails during `make`:
```
commit 79b32d926ef5961b4946ebe761a7058cb235f797 (HEAD)
Author:     Richard Leach <rich+perl@hyphen-dash-hyphen.info>
AuthorDate: Tue Apr 1 21:12:33 2025 +0000
Commit:     Richard Leach <rich+perl@hyphen-dash-hyphen.info>
CommitDate: Sat Aug 23 17:44:29 2025 +0100

    sv.c: Add Perl_newSVsv_flags_NN and static helpers
```
```
echo @`sh  cflags "optimize='-O2'" opmini.o`  -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
@cc -c -DPERL_CORE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c99 -O2 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings -Wno-use-after-free -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
In file included from perl.h:6227,
                 from op.c:163:
proto.h:3128:1: warning: data definition has no type or storage class
 3128 | Perl_newSVsv_flags_NN(pTHX_ SV * const old, I32 flags)
      | ^~~~~~~~~~~~~~~~~~~~~
proto.h:3128:1: warning: type defaults to ‘int’ in declaration of ‘Perl_newSVsv_flags_NN’ [-Wimplicit-int]
In file included from perl.h:8001:
sv_inline.h:1008:6: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘:’ token
 1008 |  * ex: set ts=8 sts=4 sw=4 et:
      |      ^
make: *** [makefile:318: opmini.o] Error 1
```
@tonycoz, can you suggest a way forward?  Thanks.

**Comment by mauke** [comment]
There are two problems with 79b32d926ef5961b4946ebe761a7058cb235f797, breaking the build:

1. A missing `/*` near the end of `sv_inline.h`.
2. A missing `SV *` in `proto.h` (fixed by running `make regen`).

Manually fixing those confirms that it is indeed the "first bad commit": Tons of "Reference is already weak" warnings in the Moose test suite, and ultimately failure as reported above.

**Comment by jkeenan** [comment]
Also experiencing test failures:  DBI.  See:
http://fast2-matrix.cpantesters.org/?dist=DBI;perl=5.43.3;reports=1#sl=7,1

**Comment by richardleach** [comment]
Checking if reverting 0dfa8ac113680e6acdef0751168ab231b9bf842c and 79b32d926ef5961b4946ebe761a7058cb235f797 together results in a successful Moose build.

**Comment by richardleach** [comment]
> Checking if reverting [0dfa8ac](https://github.com/Perl/perl5/commit/0dfa8ac113680e6acdef0751168ab231b9bf842c) and [79b32d9](https://github.com/Perl/perl5/commit/79b32d926ef5961b4946ebe761a7058cb235f797) together results in a successful Moose build.

Seems to. I'll try to do a bit of digging before putting in a revert PR.

**Comment by richardleach** [comment]
Ok, breakage could be due to `SVprv_WEAKREF` and `SVf_IVisUV` SV flags both being `0x80000000`. (This was something I'd realised during preparation of the branch and tried to account for. Possibly I forgot it though when making changes during the review process.)

**Comment by richardleach** [comment]
I'll go through the sites where `SVprv_WEAKREF` and `SVf_IVisUV` are relevant over the next couple of days.

**Comment by richardleach** [comment]
This fixes the tests in DBI & Moose, but doesn't (yet) represent a thorough review.
```
diff --git a/sv.c b/sv.c
index 40bfcc7876..d492c3cde6 100644
--- a/sv.c
+++ b/sv.c
@@ -5008,8 +5008,9 @@ S_newSVsv_flags_NN_PVxx(pTHX_ SV* dsv, SV* ssv, const I32 flags)
 
     /* This is the only place we set dsv's flags, with the exception
        of SVf_IsCOW, which can't be on for S_newSVsv_flags_NN_POK */
+/*and SVf_IVisUV which collides with SVprv_WEAKREF. */
     SvFLAGS(dsv) |= sflags & (
-            SVf_IOK|SVp_IOK|SVf_IVisUV|SVf_NOK|SVp_NOK
+            SVf_IOK|SVp_IOK|SVf_NOK|SVp_NOK
             |SVf_ROK|SVf_POK|SVp_POK|SVf_UTF8|SVppv_STATIC
     );
 
@@ -5019,6 +5020,8 @@ S_newSVsv_flags_NN_PVxx(pTHX_ SV* dsv, SV* ssv, const I32 flags)
 
     switch(sflags & (SVp_IOK|SVp_NOK|SVf_ROK|SVp_POK|SVf_FAKE|SVppv_STATIC)) {
         case SVp_IOK:  /* [ 50% ]*/
+            if (sflags & SVf_IVisUV)
+                SvFLAGS(dsv) |= SVf_IVisUV;
             SvIV_set(dsv, SvIVX(ssv));
             return dsv;
         case SVp_POK|SVp_IOK|SVp_NOK:  /* [ 3% ] */
@@ -5026,6 +5029,8 @@ S_newSVsv_flags_NN_PVxx(pTHX_ SV* dsv, SV* ssv, const I32 flags)
             SvNV_set(dsv, SvNVX(ssv));
             /* FALLTHROUGH */
         case SVp_POK|SVp_IOK:  /* [ 7% ] */
+            if (sflags & SVf_IVisUV)
+                SvFLAGS(dsv) |= SVf_IVisUV;
             SvIV_set(dsv, SvIVX(ssv));
             break;
         case SVp_POK:  /* [ 28% ] */
```
