### ISSUE TITLE
Perl_ck_stringify: Assertion `!((((kid)->op_sibling) ? (_Bool)1 : (_Bool)0))' failed (op.c:11148)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14627]
Migrated from [rt.perl.org#124207](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=124207) (status was 'resolved')

Searchable as RT124207$

**Comment by p5pRT** [comment]
### From @geeknik

Built v5\.21\.11 \(v5\.21\.10\-31\-g008e8e8\) with the following command line&#8203;:

\./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-gcc \-Doptimize=\-O2\\ \-g && AFL\_HARDEN=1 make \-j8 test\-prep

Bug found with AFL \(http&#8203;://lcamtuf\.coredump\.cx/afl\)

Valgrind&#8203;:
==54249== Process terminating with default action of signal 6 \(SIGABRT\)
==54249==    at 0x5B55165&#8203;: raise \(raise\.c&#8203;:64\)
==54249==    by 0x5B583DF&#8203;: abort \(abort\.c&#8203;:92\)
==54249==    by 0x5B4E310&#8203;: \_\_assert\_fail \(assert\.c&#8203;:81\)
==54249==    by 0x4C2B00&#8203;: Perl\_ck\_stringify \(op\.c&#8203;:11148\)
==54249==    by 0x470E8B&#8203;: Perl\_op\_convert\_list \(op\.c&#8203;:4600\)
==54249==    by 0x65FB2A&#8203;: Perl\_yyparse \(perly\.y&#8203;:721\)
==54249==    by 0x532104&#8203;: S\_parse\_body \(perl\.c&#8203;:2296\)
==54249==    by 0x539E72&#8203;: perl\_parse \(perl\.c&#8203;:1626\)
==54249==    by 0x42AC67&#8203;: main \(perlmain\.c&#8203;:114\)

GDB&#8203;:
perl&#8203;: op\.c&#8203;:11148&#8203;: Perl\_ck\_stringify&#8203;: Assertion \`\!\(\(\(\(kid\)\->op\_sibling\) ? \(\_Bool\)1 : \(\_Bool\)0\)\)' failed\.

Program received signal SIGABRT\, Aborted\.
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-registers\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
RAX&#8203;: 0x0 
RBX&#8203;: 0x7fffffffe622 \-\-> 0x736574006c726570 \('perl'\)
RCX&#8203;: 0xffffffffffffffff 
RDX&#8203;: 0x6 
RSI&#8203;: 0xe664 
RDI&#8203;: 0xe664 
RBP&#8203;: 0x7ffff6ea9c67 \-\-> 0x257325732500203a \('&#8203;: '\)
RSP&#8203;: 0x7fffffffdd58 \-\-> 0x7ffff6d933e0 \(\<\*\_\_GI\_abort\+384>&#8203;:    mov    rdx\,QWORD PTR fs&#8203;:0x10\)
RIP&#8203;: 0x7ffff6d90165 \(\<\*\_\_GI\_raise\+53>&#8203;:    cmp    rax\,0xfffffffffffff000\)
R8 : 0x7ffff7fdd700 \(0x00007ffff7fdd700\)
R9 : 0x6f425f28203a2031 \('1 : \(\_Bo'\)
R10&#8203;: 0x8 
R11&#8203;: 0x202 
R12&#8203;: 0xebc0b8 \("\!\(\(\(\(kid\)\->op\_sibling\) ? \(\_Bool\)1 : \(\_Bool\)0\)\)"\)
R13&#8203;: 0xec8db0 \("Perl\_ck\_stringify"\)
R14&#8203;: 0x7ffff6ea9c67 \-\-> 0x257325732500203a \('&#8203;: '\)
R15&#8203;: 0x2b8c
EFLAGS&#8203;: 0x202 \(carry parity adjust zero sign trap INTERRUPT direction overflow\)
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-code\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
&nbsp;   0x7ffff6d9015b \<\*\_\_GI\_raise\+43>&#8203;:    movsxd rdi\,eax
&nbsp;   0x7ffff6d9015e \<\*\_\_GI\_raise\+46>&#8203;:    mov    eax\,0xea
&nbsp;   0x7ffff6d90163 \<\*\_\_GI\_raise\+51>&#8203;:    syscall 
=> 0x7ffff6d90165 \<\*\_\_GI\_raise\+53>&#8203;:    cmp    rax\,0xfffffffffffff000
&nbsp;   0x7ffff6d9016b \<\*\_\_GI\_raise\+59>&#8203;:    ja     0x7ffff6d90182 \<\*\_\_GI\_raise\+82>
&nbsp;   0x7ffff6d9016d \<\*\_\_GI\_raise\+61>&#8203;:    repz ret 
&nbsp;   0x7ffff6d9016f \<\*\_\_GI\_raise\+63>&#8203;:    nop
&nbsp;   0x7ffff6d90170 \<\*\_\_GI\_raise\+64>&#8203;:    test   eax\,eax
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-stack\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
0000| 0x7fffffffdd58 \-\-> 0x7ffff6d933e0 \(\<\*\_\_GI\_abort\+384>&#8203;:    mov    rdx\,QWORD PTR fs&#8203;:0x10\)
0008| 0x7fffffffdd60 \-\-> 0xebc0b8 \("\!\(\(\(\(kid\)\->op\_sibling\) ? \(\_Bool\)1 : \(\_Bool\)0\)\)"\)
0016| 0x7fffffffdd68 \-\-> 0x7ffff6eabc21 \-\-> 0x706c6568007325 \('%s'\)
0024| 0x7fffffffdd70 \-\-> 0x7fffffffdd90 \-\-> 0x3000000018 
0032| 0x7fffffffdd78 \-\-> 0x2b8c 
0040| 0x7fffffffdd80 \-\-> 0x7fffffffde80 \-\-> 0x7fffffffe622 \-\-> 0x736574006c726570 \('perl'\)
0048| 0x7fffffffdd88 \-\-> 0x7ffff6dc41b6 \(\<\_\_fxprintf\+310>&#8203;:    lea    rsp\,\[rbp\-0x20\]\)
0056| 0x7fffffffdd90 \-\-> 0x3000000018 
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
Legend&#8203;: code\, data\, rodata\, value
Stopped reason&#8203;: SIGABRT
0x00007ffff6d90165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
64    \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.

Hexdump of the 16\-byte test case&#8203;:
0000000 7171 407b 307b 7d5d 7b24 7d7d 7b2c 297d
0000010

System Info&#8203;: Debian 7\, Kernel 3\.2\.65\-1\+deb7u2 x86\_64\, GCC 4\.9\.2\, libc 2\.13\-38\+deb7u8

**Comment by p5pRT** [comment]
### From @geeknik

[test24-min](https://rt-archive.perl.org/perl5/Ticket/Attachment/1338278/715394/test24-min)

**Comment by p5pRT** [comment]
### From @geeknik

perl v5\.21\.7 \(v5\.21\.6\-602\-ge9d2bd8\) just fails like this&#8203;: 

syntax error at test24\-min line 1\, near "0\]"
syntax error at test24\-min line 1\, near "$\{\}"
Execution of test24\-min aborted due to compilation errors\.

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun Mar 29 13&#8203;:43&#8203;:30 2015\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> perl v5\.21\.7 \(v5\.21\.6\-602\-ge9d2bd8\) just fails like this&#8203;: 
> 
> syntax error at test24\-min line 1\, near "0\]"
> syntax error at test24\-min line 1\, near "$\{\}"
> Execution of test24\-min aborted due to compilation errors\.

5\.21\.7 assrted for me too\. I bisected with&#8203;:

AFL\_HARDEN=1 perl \.\./bisect\.pl \-\-start=v5\.18\.0  \-DDEBUGGING \-Dcc=afl\-gcc \-Doptimize=\-O2\\ \-g \-\-target=miniperl \-e 'eval q/qq\{@&#8203;\{0\]\}$\{\}\}\,\{\}\)/'

which produced&#8203;:

bad \- non\-zero exit from \./miniperl \-Ilib \-e eval q/qq\{@&#8203;\{0\]\}$\{\}\}\,\{\}\)/
73f4c4fe76492cf68c8a57ccae33a9a3e5a87206 is the first bad commit
commit 73f4c4fe76492cf68c8a57ccae33a9a3e5a87206
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Sun Oct 12 08&#8203;:10&#8203;:41 2014 \-0700

&nbsp;    Optimise "@&#8203;\_" to a single join
&nbsp;    
&nbsp;    instead of stringify\(join\(\.\.\.\)\)\.

:100644 100644 b4176c78c2e28c85545bc01963c0d9453e200a9b 8231b871e400fce359fa074e21d494111f91714f M      embed\.h
:040000 040000 b8386d4e64ab3a616fc0ded5c3377b1eea6dac3e 780fd754644492829b74143eee8be0a53b105fc7 M      lib
:100644 100644 f1cdc0a3d0bc88a93f83b2ec5aab804520ab83c1 1de26aedb5504abe8350ceaf8f2db6e1affa1031 M      op\.c
:100644 100644 142c75e131db5fc370b0a0a14f4e14a952f04bd7 f555e91fbb267e407b2eee443cef08769dc1b711 M      opcode\.h
:100644 100644 88449326f28315a7e47db975738fb7bd1b3a2d21 042316019c80bcc058b1d03569905e132ef7289d M      proto\.h
:040000 040000 d31c2bc09d1c95902de74eaf20cf8e7de829e160 0a0b729f329896c64db99333400d55cd5614ab0d M      regen
:040000 040000 d751917c2702ec4dce32a9bca1b4a7b7cefd4507 4079a6297b0ecc81e8948c662aaf422255b31854 M      t
bisect run success

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Apr 21\, 2015 at 06&#8203;:29&#8203;:13PM \-0700\, Tony Cook via RT wrote&#8203;:
> On Sun Mar 29 13&#8203;:43&#8203;:30 2015\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > perl v5\.21\.7 \(v5\.21\.6\-602\-ge9d2bd8\) just fails like this&#8203;: 
> > 
> > syntax error at test24\-min line 1\, near "0\]"
> > syntax error at test24\-min line 1\, near "$\{\}"
> > Execution of test24\-min aborted due to compilation errors\.
> 
> 5\.21\.7 assrted for me too\. I bisected with&#8203;:
> 
> AFL\_HARDEN=1 perl \.\./bisect\.pl \-\-start=v5\.18\.0  \-DDEBUGGING \-Dcc=afl\-gcc \-Doptimize=\-O2\\ \-g \-\-target=miniperl \-e 'eval q/qq\{@&#8203;\{0\]\}$\{\}\}\,\{\}\)/'
> 
> which produced&#8203;:
> 
> bad \- non\-zero exit from \./miniperl \-Ilib \-e eval q/qq\{@&#8203;\{0\]\}$\{\}\}\,\{\}\)/
> 73f4c4fe76492cf68c8a57ccae33a9a3e5a87206 is the first bad commit
> commit 73f4c4fe76492cf68c8a57ccae33a9a3e5a87206
> Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
> Date&#8203;:   Sun Oct 12 08&#8203;:10&#8203;:41 2014 \-0700
> 
>     Optimise "@&#8203;\_" to a single join
>     
>     instead of stringify\(join\(\.\.\.\)\)\.

Now fixed with 

commit 82269f56dcc21a3e0ef8c48158a731daf5ceda25
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Wed Apr 22 16&#8203;:26&#8203;:40 2015 \+0100
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Wed Apr 22 16&#8203;:26&#8203;:40 2015 \+0100

&nbsp;    RT \#124207&#8203;: assert failure in ck\_stringify\(\)
&nbsp;    
&nbsp;    v5\.21\.4\-416\-g73f4c4f converted \(among other things\) stringify\(join\(\.\.\.\)\)
&nbsp;    into just join\(\.\.\.\)\.  It asserted that the stringify didn't have any extra
&nbsp;    children\, which it won't normally do\, since in something like "@&#8203;a\-" the
&nbsp;    elements of the stringify get bundled up into a single tree of concats
&nbsp;    etc\, and stringify just sees a single top\-level join or concat or
&nbsp;    whatever\. However during error recovery weird stuff can get left on the
&nbsp;    stack\.
&nbsp;    
&nbsp;    So rather than asserting no more kids\, skip the optimisation if there are
&nbsp;    more kids\.


\-\- 
"Procrastination grows to fill the available time"
&nbsp;    \-\- Mitchell's corollary to Parkinson's Law

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this ticket\.

The issue should now be resolved with the release today of Perl v5\.22\, which is available at http&#8203;://www\.perl\.org/get\.html
\-\- 
Karl Williamson for the Perl 5 team

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
