### ISSUE TITLE
BBC: Blead Breaks Data::Alias

### ISSUE THREAD

**Issue by eserte** [Perl/perl5#18668]
Data::Alias was always a difficult module, breaking every now and then under some conditions. However since 5.33.6 there are no more pass reports available (see http://matrix.cpantesters.org/?dist=Data-Alias%201.21 ), and while in the past only a few test scripts were failing (e.g. t/03_copy.t) now almost all test scripts are failing like this:
```
Not enough arguments for Test::More::is at t/03_copy.t line 19, near "co     "
syntax error at t/03_copy.t line 19, near "co     "
Not enough arguments for Test::More::isnt at t/03_copy.t line 21, near "co     "
syntax error at t/03_copy.t line 21, near "co     "
Bareword "mortal" not allowed while "strict subs" in use at t/03_copy.t line 32.
Bareword "mortal" not allowed while "strict subs" in use at t/03_copy.t line 33.
Bareword "nonmortal" not allowed while "strict subs" in use at t/03_copy.t line 36.
Bareword "nonmortal" not allowed while "strict subs" in use at t/03_copy.t line 37.
Execution of t/03_copy.t aborted due to compilation errors.
# Looks like your test exited with 255 before it could output anything.
t/03_copy.t .............. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 14/14 subtests 
Not enough arguments for Test::More::is at t/04_alias_parse.t line 23, near "a     "
syntax error at t/04_alias_parse.t line 23, near "a     "
Not enough arguments for Test::More::is at t/04_alias_parse.t line 27, near "syntax error at t/04_alias_parse.t line 27, near "Not enough arguments for Test::More::is at t/04_alias_parse.t line 30, near "a     "
syntax error at t/04_alias_parse.t line 30, near "a     "
Not enough arguments for Test::More::is at t/04_alias_parse.t line 32, near "a     "
syntax error at t/04_alias_parse.t line 32, near "a     "
syntax error at t/04_alias_parse.t line 33, near "a     "
Not enough arguments for Test::More::is at t/04_alias_parse.t line 34, near "a     "
t/04_alias_parse.t has too many errors.
# Looks like your test exited with 2 before it could output anything.
t/04_alias_parse.t ....... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 23/23 subtests 
... etc ...
```

**Comment by dur-randir** [comment]
It's already broken for one major release and has already been deemed [0] unsalvageable.

[0] https://github.com/Perl/perl5/issues/17072#issuecomment-614192647

**Comment by hvds** [comment]
Following @rjbs' mention on blockers I took a look at this; but my first problem came early, since on a perl built with debugging Data::Alias chokes at compile time trying to use `SvCUR()` as an lvalue:
```
gcc -c   -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g -O6   -DVERSION=\"1.21\" -DXS_VERSION=\"1.21\" -fPIC "-I/opt/scratch/lib/perl5/5.33.9/x86_64-linux/CORE"   Alias.c
Alias.xs: In function 'da_ck_rv2cv':
Alias.xs:2042:22: error: lvalue required as increment operand
     SvCUR(PL_linestr)++;
                      ^~
Alias.xs:2071:23: error: lvalue required as left operand of assignment
     SvCUR(PL_linestr) = len + shift - 1;
                       ^
Alias.xs:2075:23: error: lvalue required as left operand of assignment
     SvCUR(PL_linestr) += shift;
                       ^~
Makefile:336: recipe for target 'Alias.o' failed
make: *** [Alias.o] Error 1
```

I'm not sure how long this has failed; I find it hard to believe that it started in Feb 2006 with commit 08002bbf.

I'll try again with a non-debugging perl, but I thought this was worth noting.

**Comment by hvds** [comment]
I was able to make a somewhat reduced testcase, to run in the directory where Data::Alias has been built:
```
% $PERL -e 'use lib "blib/arch"; use DynaLoader; BEGIN { package Data::Alias { BEGIN { our @ISA = qw{ DynaLoader } } bootstrap Data::Alias 1.21 } } our $x = 42; Data::Alias::copy { $x }'
syntax error at -e line 1, near "D                   "
Execution of -e aborted due to compilation errors.
```
.. but I think I'm unlikely to get far with the XS code itself.

**Comment by sisyphus** [comment]
I just noticed that the error message is sensitive to whitespace in the code:
```
C:\>perl -MData::Alias -wle "$x=42;Data::Alias::copy{$x};"
syntax error at -e line 1, near "D                 "
Execution of -e aborted due to compilation errors.

C:\comp-1020>perl -MData::Alias -wle "$x=42; Data::Alias::copy{$x};"
syntax error at -e line 1, near ""
Execution of -e aborted due to compilation errors.
```
This is a clear indication that it's well and truly beyond my depth.

Perl details:
```
C:\>perl -V:archname
archname='MSWin32-x86-multi-thread';

C:\>perl -MData::Alias -le "print $Data::Alias::VERSION"
1.21

C:\comp-1020>perl -le "print $]"
5.033008
```

**Comment by iabyn** [comment]
Data::Alias-1.25_01 appears to build on blead (threaded debugging), plus the test matrix shows it mostly passing on 5.34.0 and earlier, so I'm closing.
