### ISSUE TITLE
Cygwin builds broken since 37611e66

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14223]
Migrated from [rt.perl.org#123163](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123163) (status was 'resolved')

Searchable as RT123163$

**Comment by p5pRT** [comment]
### From @bingos

Cygwin builds are failing during the static linking of Win32CORE into perlmain

Generating a Unix\-style Makefile
Writing Makefile for Win32CORE
make\[1\]&#8203;: Entering directory '/home/Administrator/repos/perl\.git/ext/Win32CORE'
make\[1\]&#8203;: Leaving directory '/home/Administrator/repos/perl\.git/ext/Win32CORE'
make\[1\]&#8203;: Entering directory '/home/Administrator/repos/perl\.git/ext/Win32CORE'
gcc \-c   \-DPERL\_USE\_SAFE\_PUTENV \-U\_\_STRICT\_ANSI\_\_ \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-D\_FORTIFY\_SOURCE=2 \-DUSEIMPORTLIB \-UUSEIMPORTLIB  \-O3   \-DVERSION=\\"0\.04\\" \-DXS\_VERSION=\\"0\.04\\"  "\-I\.\./\.\."   Win32CORE\.c
rm \-rf \.\./\.\./lib/auto/Win32CORE/Win32CORE\.a
/usr/bin/ar cr \.\./\.\./lib/auto/Win32CORE/Win32CORE\.a Win32CORE\.o && : \.\./\.\./lib/auto/Win32CORE/Win32CORE\.a
chmod 755 \.\./\.\./lib/auto/Win32CORE/Win32CORE\.a
make\[1\]&#8203;: Leaving directory '/home/Administrator/repos/perl\.git/ext/Win32CORE'
gcc \-o perl \-Wl\,\-\-enable\-auto\-import \-Wl\,\-\-export\-all\-symbols \-Wl\,\-\-enable\-auto\-image\-base \-fstack\-protector \-L/usr/local/lib  perlmain\.o \-L\. \-lperl lib/auto/Win32CORE/Win32CORE\.a \`cat ext\.libs\` \-ldl \-lcrypt
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x33\)&#8203;: undefined reference to \`Perl\_newSVnv'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x33\)&#8203;: relocation truncated to fit&#8203;: R\_X86\_64\_PC32 against undefined symbol \`Perl\_newSVnv'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x4b\)&#8203;: undefined reference to \`Perl\_newSVpvn'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x4b\)&#8203;: relocation truncated to fit&#8203;: R\_X86\_64\_PC32 against undefined symbol \`Perl\_newSVpvn'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x5e\)&#8203;: undefined reference to \`Perl\_load\_module'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x5e\)&#8203;: relocation truncated to fit&#8203;: R\_X86\_64\_PC32 against undefined symbol \`Perl\_load\_module'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0xa4\)&#8203;: undefined reference to \`Perl\_block\_gimme'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0xa4\)&#8203;: relocation truncated to fit&#8203;: R\_X86\_64\_PC32 against undefined symbol \`Perl\_block\_gimme'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x96\)&#8203;: undefined reference to \`Perl\_call\_pv'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x96\)&#8203;: relocation truncated to fit&#8203;: R\_X86\_64\_PC32 against undefined symbol \`Perl\_call\_pv'
collect2&#8203;: error&#8203;: ld returned 1 exit status
GNUmakefile&#8203;:371&#8203;: recipe for target 'perl\.exe' failed
make&#8203;: \*\*\* \[perl\.exe\] Error 1

Bisection found the offending commit to be&#8203;:

http&#8203;://perl5\.git\.perl\.org/perl\.git/commitdiff/37611e66dc90407e7e76c2b2d917ff2de6adcd43

And manually running changing the ordering comfirms that the ordering is significant&#8203;:

Administrator@&#8203;WALLOON ~/repos/perl\.git
$ gcc \-o perl \-Wl\,\-\-enable\-auto\-import \-Wl\,\-\-export\-all\-symbols \-Wl\,\-\-enable\-auto\-image\-base \-fstack\-protector \-L/usr/local/lib  perlmain\.o \-L\. \-lperl lib/auto/Win32CORE/Win32CORE\.a \`cat ext\.libs\` \-ldl \-lcrypt
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x33\)&#8203;: undefined reference to \`Perl\_newSVnv'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x33\)&#8203;: relocation truncated to fit&#8203;: R\_X86\_64\_PC32 against undefined symbol \`Perl\_newSVnv'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x4b\)&#8203;: undefined reference to \`Perl\_newSVpvn'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x4b\)&#8203;: relocation truncated to fit&#8203;: R\_X86\_64\_PC32 against undefined symbol \`Perl\_newSVpvn'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x5e\)&#8203;: undefined reference to \`Perl\_load\_module'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x5e\)&#8203;: relocation truncated to fit&#8203;: R\_X86\_64\_PC32 against undefined symbol \`Perl\_load\_module'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0xa4\)&#8203;: undefined reference to \`Perl\_block\_gimme'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0xa4\)&#8203;: relocation truncated to fit&#8203;: R\_X86\_64\_PC32 against undefined symbol \`Perl\_block\_gimme'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x96\)&#8203;: undefined reference to \`Perl\_call\_pv'
lib/auto/Win32CORE/Win32CORE\.a\(Win32CORE\.o\)&#8203;:Win32CORE\.c&#8203;:\(\.text\+0x96\)&#8203;: relocation truncated to fit&#8203;: R\_X86\_64\_PC32 against undefined symbol \`Perl\_call\_pv'
collect2&#8203;: error&#8203;: ld returned 1 exit status

Administrator@&#8203;WALLOON ~/repos/perl\.git
$ gcc \-o perl \-Wl\,\-\-enable\-auto\-import \-Wl\,\-\-export\-all\-symbols \-Wl\,\-\-enable\-auto\-image\-base \-fstack\-protector \-L/usr/local/lib  perlmain\.o \-L\. lib/auto/Win32CORE/Win32CORE\.a \-lperl \`cat ext\.libs\` \-ldl \-lcrypt

Administrator@&#8203;WALLOON ~/repos/perl\.git
$

Many thanks\,

\-\- 
Chris Williams
aka BinGOs
PGP ID 0x4658671F
http&#8203;://www\.gumbynet\.org\.uk
==========================

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun Nov 09 11&#8203;:24&#8203;:19 2014\, chris@&#8203;bingosnet\.co\.uk wrote&#8203;:
> Cygwin builds are failing during the static linking of Win32CORE into
> perlmain

The attached patch fixes cygwin linking for me\.

It will need to be tested on os390 too\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

<details><summary>0001-perl-123163-use-the-original-link-order-unless-on-os.patch</summary>

```diff
From 209b2536e521936bb4bd344ff54655b370cc9ec1 Mon Sep 17 00:00:00 2001
From: Tony Cook <tony@develop-help.com>
Date: Wed, 12 Nov 2014 16:46:48 +1100
Subject: [PATCH] [perl #123163] use the original link order unless on os390

---
 Makefile.SH |   13 +++++++++++++
 1 file changed, 13 insertions(+)

diff --git a/Makefile.SH b/Makefile.SH
index 5f630fa..f3fea9a 100755
--- a/Makefile.SH
+++ b/Makefile.SH
@@ -930,7 +930,20 @@ lib/buildcustomize.pl: $& $(mini_obj) write_buildcustomize.pl
 
 $(PERL_EXE): $& perlmain$(OBJ_EXT) $(LIBPERL) $(static_ext) ext.libs $(PERLEXPORT) write_buildcustomize.pl
 	-@rm -f miniperl.xok
+!NO!SUBS!
+
+        case $osname in
+        os390) $spitshell >>$Makefile <<'!NO!SUBS!'
 	$(SHRPENV) $(CC) -o perl $(CLDFLAGS) $(CCDLFLAGS) perlmain$(OBJ_EXT) $(LLIBPERL) $(static_ext) `cat ext.libs` $(libs)
+!NO!SUBS!
+        ;;
+        *) $spitshell >>$Makefile <<'!NO!SUBS!'
+	$(SHRPENV) $(CC) -o perl $(CLDFLAGS) $(CCDLFLAGS) perlmain$(OBJ_EXT) $(static_ext) $(LLIBPERL) `cat ext.libs` $(libs)
+!NO!SUBS!
+        ;;
+        esac
+
+	$spitshell >>$Makefile <<'!NO!SUBS!'
 
 # Microperl.  This is just a convenience thing if one happens to
 # build also the full Perl and therefore the real big Makefile:
-- 
1.7.10.4


```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Nov 11 21&#8203;:57&#8203;:52 2014\, tonyc wrote&#8203;:
> On Sun Nov 09 11&#8203;:24&#8203;:19 2014\, chris@&#8203;bingosnet\.co\.uk wrote&#8203;:
> > Cygwin builds are failing during the static linking of Win32CORE into
> > perlmain
> 
> The attached patch fixes cygwin linking for me\.

Applied as 6711cb4f90cfacd285b7fabbb5337493678fc628\.

> It will need to be tested on os390 too\.

Discussed this with khw\, and he said it will get tested the next time he rebases\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'resolved'
